-- Lo 001: san pham 0300 den 0414
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-300', '0300', 'Cô gái hoodie đeo tai nghe', 'https://kevindauto.com/products/sp-300.webp', 'nu', 'Đời thường', array['nữ', 'hoodie', 'tai nghe', 'điện thoại', 'đứng']::text[]),
  ('sp-301', '0301', 'Cô gái váy ôm tạo dáng', 'https://kevindauto.com/products/sp-301.webp', 'nu', 'Thời trang', array['nữ', 'váy ôm', 'tạo dáng', 'thời trang']::text[]),
  ('sp-302', '0302', 'Cô gái áo khoác cầm điện thoại', 'https://kevindauto.com/products/sp-302.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'điện thoại', 'streetwear']::text[]),
  ('sp-303', '0303', 'Cô gái đội mũ tạo dáng', 'https://kevindauto.com/products/sp-303.webp', 'nu', 'Thời trang', array['nữ', 'mũ', 'váy ngắn', 'tạo dáng']::text[]),
  ('sp-304', '0304', 'Nữ công sở cầm điện thoại', 'https://kevindauto.com/products/sp-304.webp', 'nu', 'Công sở', array['nữ', 'công sở', 'điện thoại', 'áo khoác']::text[]),
  ('sp-305', '0305', 'Cô gái áo khoác cao cổ', 'https://kevindauto.com/products/sp-305.webp', 'nu', 'Mùa đông', array['nữ', 'áo khoác', 'mùa đông', 'bốt']::text[]),
  ('sp-306', '0306', 'Cô gái phong cách boho', 'https://kevindauto.com/products/sp-306.webp', 'nu', 'Boho', array['nữ', 'boho', 'áo khoác dài', 'thời trang']::text[]),
  ('sp-307', '0307', 'Cô gái váy ngắn chống hông', 'https://kevindauto.com/products/sp-307.webp', 'nu', 'Thời trang', array['nữ', 'váy ngắn', 'chống hông', 'tạo dáng']::text[]),
  ('sp-308', '0308', 'Cô gái sơ mi váy ngắn', 'https://kevindauto.com/products/sp-308.webp', 'nu', 'Công sở', array['nữ', 'sơ mi', 'váy ngắn', 'công sở']::text[]),
  ('sp-309', '0309', 'Quý cô váy dài thanh lịch', 'https://kevindauto.com/products/sp-309.webp', 'nu', 'Thanh lịch', array['nữ', 'váy dài', 'thanh lịch', 'tạo dáng']::text[]),
  ('sp-310', '0310', 'Cô gái streetwear đứng thẳng', 'https://kevindauto.com/products/sp-310.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'áo thun', 'bốt']::text[]),
  ('sp-311', '0311', 'Quý cô gọi điện', 'https://kevindauto.com/products/sp-311.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'váy dài', 'đời thường']::text[]),
  ('sp-312', '0312', 'Quý cô đầm dạ hội', 'https://kevindauto.com/products/sp-312.webp', 'nu', 'Dạ hội', array['nữ', 'đầm dài', 'dạ hội', 'sang trọng']::text[]),
  ('sp-313', '0313', 'Cô gái ngồi đọc sách', 'https://kevindauto.com/products/sp-313.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'đọc sách', 'thư giãn']::text[]),
  ('sp-314', '0314', 'Cô gái ngồi ôm gối', 'https://kevindauto.com/products/sp-314.webp', 'nu', 'Thư giãn', array['nữ', 'ngồi', 'ôm gối', 'thư giãn']::text[]),
  ('sp-315', '0315', 'Cô gái ngồi buộc dây giày', 'https://kevindauto.com/products/sp-315.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'buộc dây giày', 'đời thường']::text[]),
  ('sp-316', '0316', 'Cô gái ngồi thiền', 'https://kevindauto.com/products/sp-316.webp', 'nu', 'Thư giãn', array['nữ', 'ngồi thiền', 'yoga', 'thư giãn']::text[]),
  ('sp-317', '0317', 'Nữ cầu thủ bóng rổ dẫn bóng', 'https://kevindauto.com/products/sp-317.webp', 'thethao', 'Bóng rổ', array['nữ', 'bóng rổ', 'dẫn bóng', 'thể thao']::text[]),
  ('sp-318', '0318', 'Cô gái cúi người tạo dáng', 'https://kevindauto.com/products/sp-318.webp', 'nu', 'Thời trang', array['nữ', 'cúi người', 'tạo dáng', 'thời trang']::text[]),
  ('sp-319', '0319', 'Cô gái dắt chó đi dạo', 'https://kevindauto.com/products/sp-319.webp', 'dongvat', 'Thú cưng', array['nữ', 'chó', 'thú cưng', 'đi dạo']::text[]),
  ('sp-340', '0340', 'Cô gái đội mũ khoanh tay', 'https://kevindauto.com/products/sp-340.webp', 'nu', 'Streetwear', array['nữ', 'mũ', 'khoanh tay', 'streetwear']::text[]),
  ('sp-341', '0341', 'Đôi bạn nữ chụp ảnh', 'https://kevindauto.com/products/sp-341.webp', 'nu', 'Bạn bè', array['nữ', 'bạn bè', 'chụp ảnh', 'tạo dáng']::text[]),
  ('sp-342', '0342', 'Cặp đôi ôm nhau', 'https://kevindauto.com/products/sp-342.webp', 'giadinh', 'Cặp đôi', array['cặp đôi', 'ôm nhau', 'tình nhân', 'nam nữ']::text[]),
  ('sp-343', '0343', 'Cặp đôi trao nụ hôn', 'https://kevindauto.com/products/sp-343.webp', 'giadinh', 'Cặp đôi', array['cặp đôi', 'hôn', 'tình nhân', 'lãng mạn']::text[]),
  ('sp-344', '0344', 'Cặp đôi tựa vai', 'https://kevindauto.com/products/sp-344.webp', 'giadinh', 'Cặp đôi', array['cặp đôi', 'tựa vai', 'tình nhân', 'đời thường']::text[]),
  ('sp-345', '0345', 'Mẹ bế em bé', 'https://kevindauto.com/products/sp-345.webp', 'treem', 'Gia đình', array['mẹ', 'em bé', 'bế con', 'gia đình']::text[]),
  ('sp-346', '0346', 'Cặp đôi hôn nhau dạo phố', 'https://kevindauto.com/products/sp-346.webp', 'giadinh', 'Cặp đôi', array['cặp đôi', 'hôn', 'dạo phố', 'tình nhân']::text[]),
  ('sp-347', '0347', 'Cô gái bên áo phao trưng bày', 'https://kevindauto.com/products/sp-347.webp', 'nu', 'Thời trang', array['nữ', 'áo phao', 'trưng bày', 'thời trang']::text[]),
  ('sp-348', '0348', 'Cô gái váy ngắn tạo dáng', 'https://kevindauto.com/products/sp-348.webp', 'nu', 'Thời trang', array['nữ', 'váy ngắn', 'tạo dáng', 'thời trang']::text[]),
  ('sp-349', '0349', 'Cô gái đội mũ đứng thư giãn', 'https://kevindauto.com/products/sp-349.webp', 'nu', 'Streetwear', array['nữ', 'mũ', 'đứng', 'streetwear']::text[]),
  ('sp-350', '0350', 'Cô gái trượt scooter', 'https://kevindauto.com/products/sp-350.webp', 'thethao', 'Thể thao đường phố', array['nữ', 'scooter', 'trượt', 'thể thao đường phố']::text[]),
  ('sp-351', '0351', 'Cô gái ngồi trên túi du lịch', 'https://kevindauto.com/products/sp-351.webp', 'nu', 'Du lịch', array['nữ', 'ngồi', 'túi du lịch', 'chờ đợi']::text[]),
  ('sp-352', '0352', 'Cô gái áo khoác tung bay', 'https://kevindauto.com/products/sp-352.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'chuyển động', 'streetwear']::text[]),
  ('sp-353', '0353', 'Chàng trai ngồi xổm đeo ba lô', 'https://kevindauto.com/products/sp-353.webp', 'nam', 'Đời thường', array['nam', 'ngồi xổm', 'ba lô', 'đời thường']::text[]),
  ('sp-354', '0354', 'Chàng trai ngồi nghỉ với ba lô', 'https://kevindauto.com/products/sp-354.webp', 'nam', 'Du lịch', array['nam', 'ngồi', 'ba lô', 'du lịch']::text[]),
  ('sp-355', '0355', 'Chàng trai đeo túi đứng chờ', 'https://kevindauto.com/products/sp-355.webp', 'nam', 'Đời thường', array['nam', 'túi đeo', 'đứng chờ', 'đời thường']::text[]),
  ('sp-356', '0356', 'Chàng trai áo khoác bỏ tay túi', 'https://kevindauto.com/products/sp-356.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'bỏ tay túi', 'streetwear']::text[]),
  ('sp-357', '0357', 'Chàng trai đứng xem điện thoại', 'https://kevindauto.com/products/sp-357.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng', 'đời thường']::text[]),
  ('sp-358', '0358', 'Ông mập lái xe', 'https://kevindauto.com/products/sp-358.webp', 'xe', 'Xe máy', array['nữ', 'xe máy', 'lái xe', 'đường phố']::text[]),
  ('sp-362', '0362', 'Nakai Akira ngồi ghế hút thuốc', 'https://kevindauto.com/products/sp-362.webp', 'caotuoi', 'Người cao tuổi', array['cụ bà', 'ngồi ghế', 'thư giãn', 'cao tuổi']::text[]),
  ('sp-363', '0363', 'Chàng trai hoodie to con', 'https://kevindauto.com/products/sp-363.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'quần short', 'streetwear']::text[]),
  ('sp-364', '0364', 'Nam chụp ảnh photographer jacket Korea', 'https://kevindauto.com/products/sp-364.webp', 'nam', 'Đời thường', array['nam', 'áo choàng', 'áo dài', 'đứng']::text[]),
  ('sp-377', '0377', 'Cô gái ngồi ghế ôm gối bãi biển', 'https://kevindauto.com/products/sp-377.webp', 'nu', 'Thư giãn', array['nữ', 'ngồi', 'bắt chéo chân', 'thư giãn']::text[]),
  ('sp-378', '0378', 'Cô gái trẻ ngồi chống tay dưới đất', 'https://kevindauto.com/products/sp-378.webp', 'nu', 'Đời thường', array['nữ', 'ngồi xếp bằng', 'áo thun', 'thư giãn']::text[]),
  ('sp-379', '0379', 'Nữ trượt skateboard mạnh mẽ', 'https://kevindauto.com/products/sp-379.webp', 'thethao', 'Trượt ván', array['nữ', 'trượt ván', 'skateboard', 'thể thao']::text[]),
  ('sp-380', '0380', 'Cô gái sinh viên ba lo Nhật Bản', 'https://kevindauto.com/products/sp-380.webp', 'nu', 'Thời trang', array['nữ', 'váy xếp ly', 'mũ', 'thời trang']::text[]),
  ('sp-381', '0381', 'Nữ văn phòng cà phê túi xách', 'https://kevindauto.com/products/sp-381.webp', 'nu', 'Thanh lịch', array['nữ', 'áo khoác', 'túi xách', 'thanh lịch']::text[]),
  ('sp-382', '0382', 'Sexy girl điện thoại selfie', 'https://kevindauto.com/products/sp-382.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'chụp hình', 'tạo dáng']::text[]),
  ('sp-383', '0383', 'Cô gái áo khoác nó đứng nhìn', 'https://kevindauto.com/products/sp-383.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'đứng', 'streetwear']::text[]),
  ('sp-384', '0384', 'Cô gái ôm mèo đứng nhìn', 'https://kevindauto.com/products/sp-384.webp', 'nu', 'Đời thường', array['nữ', 'suy tư', 'đứng', 'đời thường']::text[]),
  ('sp-385', '0385', 'Cô gái đường phố túi xách', 'https://kevindauto.com/products/sp-385.webp', 'nu', 'Đời thường', array['nữ', 'áo thun', 'điện thoại', 'đứng']::text[]),
  ('sp-386', '0386', 'Cô gái trẻ thể thao chạy bộ', 'https://kevindauto.com/products/sp-386.webp', 'nu', 'Thời trang', array['nữ', 'chống hông', 'quần short', 'năng động']::text[]),
  ('sp-387', '0387', 'Cô gái ngồi dáng nghệ thuật', 'https://kevindauto.com/products/sp-387.webp', 'nu', 'Thời trang', array['nữ', 'ngồi ghế', 'tạo dáng', 'thời trang']::text[]),
  ('sp-388', '0388', 'Nữ anime đứng xoay người', 'https://kevindauto.com/products/sp-388.webp', 'thethao', 'Chạy bộ', array['nữ', 'chạy bộ', 'vận động', 'thể thao']::text[]),
  ('sp-389', '0389', 'Cô gái đứng nghe điện thoại', 'https://kevindauto.com/products/sp-389.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'đứng', 'đời thường']::text[]),
  ('sp-390', '0390', 'Cô gái áo khoác cổ lông đầm ôm', 'https://kevindauto.com/products/sp-390.webp', 'nu', 'Mùa đông', array['nữ', 'áo phao', 'váy ngắn', 'mùa đông']::text[]),
  ('sp-391', '0391', 'Cô gái áo khoác cổ lông đầm ôm', 'https://kevindauto.com/products/sp-391.webp', 'nu', 'Du lịch', array['nữ', 'ba lô', 'cúi người', 'du lịch']::text[]),
  ('sp-392', '0392', 'Anime girl T pose', 'https://kevindauto.com/products/sp-392.webp', 'nu', 'Năng động', array['nữ', 'dang tay', 'giữ thăng bằng', 'năng động']::text[]),
  ('sp-393', '0393', 'Nữ jacket tay ôm má', 'https://kevindauto.com/products/sp-393.webp', 'nu', 'Thanh lịch', array['nữ', 'váy dài', 'suy tư', 'thanh lịch']::text[]),
  ('sp-394', '0394', 'Nữ chiến binh đứng cầm súng', 'https://kevindauto.com/products/sp-394.webp', 'nu', 'Chiến thuật', array['nữ', 'chiến binh', 'súng trường', 'chiến thuật']::text[]),
  ('sp-395', '0395', 'Nữ gangstẻ gậy bóng chày', 'https://kevindauto.com/products/sp-395.webp', 'nu', 'Chiến thuật', array['nữ', 'chiến binh', 'súng phóng', 'hành động']::text[]),
  ('sp-396', '0396', 'Nữ dđầm dạ hội chống hông', 'https://kevindauto.com/products/sp-396.webp', 'nu', 'Dạ hội', array['nữ', 'đầm dạ hội', 'chống hông', 'sang trọng']::text[]),
  ('sp-397', '0397', 'Nữ thun quần tây túi xách mũ nồi', 'https://kevindauto.com/products/sp-397.webp', 'nu', 'Thanh lịch', array['nữ', 'mũ nồi', 'quần dài', 'thanh lịch']::text[]),
  ('sp-398', '0398', 'Nữ đầm dạ hội chống hông', 'https://kevindauto.com/products/sp-398.webp', 'nu', 'Dạ hội', array['nữ', 'đầm dài', 'tạo dáng', 'dạ hội']::text[]),
  ('sp-399', '0399', 'Nữ gymer áo khoác legging', 'https://kevindauto.com/products/sp-399.webp', 'nu', 'Đời thường', array['nữ', 'quần short', 'đứng', 'đời thường']::text[]),
  ('sp-400', '0400', 'Nữ hoodie áo khoác tay đút túi', 'https://kevindauto.com/products/sp-400.webp', 'nam', 'Streetwear', array['nam', 'mũ', 'áo khoác', 'streetwear']::text[]),
  ('sp-401', '0401', 'Nữ nude vươn vai', 'https://kevindauto.com/products/sp-401.webp', 'nu', 'Nghỉ dưỡng', array['nữ', 'bikini', 'vươn vai', 'nghỉ dưỡng']::text[]),
  ('sp-402', '0402', 'Nữ sexy vươn vai', 'https://kevindauto.com/products/sp-402.webp', 'nu', 'Nghỉ dưỡng', array['nữ', 'đồ bơi', 'tạo dáng', 'bãi biển']::text[]),
  ('sp-403', '0403', 'Nữ đầm ngắn áo thun điện thoại', 'https://kevindauto.com/products/sp-403.webp', 'nu', 'Công sở', array['nữ', 'váy bút chì', 'điện thoại', 'công sở']::text[]),
  ('sp-404', '0404', 'Nữ đầm dạ hội', 'https://kevindauto.com/products/sp-404.webp', 'nu', 'Dạ hội', array['nữ', 'đầm dài', 'dạ hội', 'thanh lịch']::text[]),
  ('sp-405', '0405', 'Nữ thời trang fashionista gầm như hổ', 'https://kevindauto.com/products/sp-405.webp', 'nu', 'Lễ hội', array['nữ', 'lễ hội', 'nhảy múa', 'hóa trang']::text[]),
  ('sp-406', '0406', 'Nữ áo thun form dài tay cầm tóc', 'https://kevindauto.com/products/sp-406.webp', 'nu', 'Đời thường', array['nữ', 'váy rộng', 'giơ tay', 'đời thường']::text[]),
  ('sp-407', '0407', 'Nữ trung niên ôm chó to', 'https://kevindauto.com/products/sp-407.webp', 'dongvat', 'Thú cưng', array['nữ', 'chó lớn', 'thú cưng', 'đứng']::text[]),
  ('sp-408', '0408', 'Nữ mùa đông áo dày', 'https://kevindauto.com/products/sp-408.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'bước đi', 'streetwear']::text[]),
  ('sp-409', '0409', 'Nữ bế chó corgi', 'https://kevindauto.com/products/sp-409.webp', 'dongvat', 'Thú cưng', array['nữ', 'mèo', 'ôm thú cưng', 'đời thường']::text[]),
  ('sp-410', '0410', 'Nữ vest cầm hộp quà nón Nodel', 'https://kevindauto.com/products/sp-410.webp', 'duongpho', 'Nghề nghiệp', array['nữ', 'phục vụ', 'khay', 'nghề nghiệp']::text[]),
  ('sp-411', '0411', 'Nữ nghe điện thoại', 'https://kevindauto.com/products/sp-411.webp', 'nu', 'Đời thường', array['nữ', 'váy ngắn', 'đứng', 'đời thường']::text[]),
  ('sp-412', '0412', 'Nữ cầm cà phê tay kéo vali', 'https://kevindauto.com/products/sp-412.webp', 'nu', 'Du lịch', array['nữ', 'vali', 'du lịch', 'điện thoại']::text[]),
  ('sp-413', '0413', 'Nữ sexy phòng xông hơi khăn tắm', 'https://kevindauto.com/products/sp-413.webp', 'nu', 'Thanh lịch', array['nữ', 'ngồi', 'bắt chéo chân', 'thanh lịch']::text[]),
  ('sp-414', '0414', 'Nữ Noel vãy ngắn nón trùm đầu', 'https://kevindauto.com/products/sp-414.webp', 'nu', 'Thời trang', array['nữ', 'váy xòe', 'trẻ trung', 'tạo dáng']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
