-- Lo 002: san pham 0415 den 0542
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-415', '0415', 'Nữ mùa đông vẫy tay', 'https://kevindauto.com/products/sp-415.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'vẫy tay', 'bước đi']::text[]),
  ('sp-416', '0416', 'Nữ mùa đông túi xách', 'https://kevindauto.com/products/sp-416.webp', 'nu', 'Streetwear', array['nữ', 'mũ', 'túi xách', 'streetwear']::text[]),
  ('sp-417', '0417', 'Nữ mùa đông thời trang kỳ lạ', 'https://kevindauto.com/products/sp-417.webp', 'nam', 'Mùa đông', array['nam', 'áo khoác', 'mùa đông', 'đứng']::text[]),
  ('sp-418', '0418', 'Nữ ba lỗ jean rách tay túi sau mông', 'https://kevindauto.com/products/sp-418.webp', 'nu', 'Chiến thuật', array['nữ', 'chiến thuật', 'trang bị', 'hành động']::text[]),
  ('sp-419', '0419', 'Nữ Hàn Jean short tay chống cằm', 'https://kevindauto.com/products/sp-419.webp', 'nu', 'Thời trang', array['nữ', 'váy ngắn', 'tạo dáng', 'thời trang']::text[]),
  ('sp-420', '0420', 'Nữ cosplay Salonmoon Nhật Bản', 'https://kevindauto.com/products/sp-420.webp', 'nu', 'Du lịch', array['nữ', 'mũ', 'máy ảnh', 'du lịch']::text[]),
  ('sp-421', '0421', 'Nữ thời trang sowmi túi chéo', 'https://kevindauto.com/products/sp-421.webp', 'nam', 'Đời thường', array['nam', 'áo rộng', 'khoanh tay', 'đứng']::text[]),
  ('sp-422', '0422', 'Nữ Kimono tay trước bụng cầm túi', 'https://kevindauto.com/products/sp-422.webp', 'caotuoi', 'Du lịch', array['cụ bà', 'vali', 'du lịch', 'cao tuổi']::text[]),
  ('sp-423', '0423', 'Nữ bãi biển cầm kèm nón vành rộng túi xách', 'https://kevindauto.com/products/sp-423.webp', 'nu', 'Nghỉ dưỡng', array['nữ', 'nón rộng vành', 'đồ bơi', 'nghỉ dưỡng']::text[]),
  ('sp-424', '0424', 'Nữ bãi biển cầm kem', 'https://kevindauto.com/products/sp-424.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'giả tưởng', 'giáp']::text[]),
  ('sp-425', '0425', 'Nữ khủng long không nón Dinogirl', 'https://kevindauto.com/products/sp-425.webp', 'dongvat', 'Hóa trang', array['nữ', 'hóa trang', 'đuôi thú', 'chibi']::text[]),
  ('sp-426', '0426', 'Nữ khoác jean cơ bản', 'https://kevindauto.com/products/sp-426.webp', 'nu', 'Thời trang', array['nữ', 'quần short', 'nghiêng người', 'tạo dáng']::text[]),
  ('sp-427', '0427', 'Nữ bikini bao quà Noel', 'https://kevindauto.com/products/sp-427.webp', 'nu', 'Đời thường', array['nữ', 'khăn trùm', 'túi lớn', 'đời thường']::text[]),
  ('sp-428', '0428', 'Nữ vest túi xách kéo vali', 'https://kevindauto.com/products/sp-428.webp', 'nam', 'Công sở', array['nam', 'công sở', 'vali', 'doanh nhân']::text[]),
  ('sp-429', '0429', 'Nữ biker nón bảo hiểm fullface', 'https://kevindauto.com/products/sp-429.webp', 'thethao', 'Vận động', array['nữ', 'mũ bảo hộ', 'cúi người', 'thể thao']::text[]),
  ('sp-430', '0430', 'Nữ váy ngắn bước cười guốc', 'https://kevindauto.com/products/sp-430.webp', 'nu', 'Thanh lịch', array['nữ', 'váy liền', 'bước đi', 'thanh lịch']::text[]),
  ('sp-431', '0431', 'Nữ chống eo mắt kinh túi xách', 'https://kevindauto.com/products/sp-431.webp', 'nu', 'Thời trang', array['nữ', 'váy ngắn', 'túi xách', 'thời trang']::text[]),
  ('sp-432', '0432', 'Nữ biker ngồi xe', 'https://kevindauto.com/products/sp-432.webp', 'thethao', 'Vận động', array['nam', 'ngồi thấp', 'vận động viên', 'thể thao']::text[]),
  ('sp-433', '0433', 'Nữ nude khăn tắm lau tóc', 'https://kevindauto.com/products/sp-433.webp', 'thethao', 'Thể dục', array['nữ', 'vươn vai', 'thể dục', 'khởi động']::text[]),
  ('sp-434', '0434', 'Nữ áo ba lỗ jean túi xách', 'https://kevindauto.com/products/sp-434.webp', 'nu', 'Mua sắm', array['nữ', 'túi xách', 'mua sắm', 'đời thường']::text[]),
  ('sp-435', '0435', 'Nữ Tây túi xách cầm điện thoại', 'https://kevindauto.com/products/sp-435.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'điện thoại', 'streetwear']::text[]),
  ('sp-436', '0436', 'Nữ sửa xe mỏ lết khổng lồ to', 'https://kevindauto.com/products/sp-436.webp', 'duongpho', 'Giao nhận', array['nữ', 'hộp hàng', 'giao nhận', 'nghề nghiệp']::text[]),
  ('sp-437', '0437', 'Nữ chụp hình điện thoại sơ mi váy ngắn', 'https://kevindauto.com/products/sp-437.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'quay phim', 'tạo dáng']::text[]),
  ('sp-438', '0438', 'Nữ chiến binh ngồi tựa cầm súng', 'https://kevindauto.com/products/sp-438.webp', 'nu', 'Sci-fi', array['nữ', 'chiến binh', 'cơ giới', 'khoa học viễn tưởng']::text[]),
  ('sp-439', '0439', 'Nữ mùa đông quấn khen cà phê', 'https://kevindauto.com/products/sp-439.webp', 'treem', 'Mùa đông', array['trẻ em', 'áo choàng', 'khăn', 'mùa đông']::text[]),
  ('sp-440', '0440', 'Nữ thời trang áo khoác dài nhìn xuống', 'https://kevindauto.com/products/sp-440.webp', 'nu', 'Thanh lịch', array['nữ', 'áo măng tô', 'nhìn xuống', 'thanh lịch']::text[]),
  ('sp-441', '0441', 'Nữ hai tay trái tim trên đầu', 'https://kevindauto.com/products/sp-441.webp', 'thethao', 'Thể dục', array['nữ', 'giãn cơ', 'vươn vai', 'thể thao']::text[]),
  ('sp-442', '0442', 'Nữ gymer chống hông sơmi', 'https://kevindauto.com/products/sp-442.webp', 'nu', 'Thanh lịch', array['nữ', 'áo khoác', 'túi nhỏ', 'thanh lịch']::text[]),
  ('sp-443', '0443', 'Nữ bóng rổ cầm chai nước', 'https://kevindauto.com/products/sp-443.webp', 'thethao', 'Bóng', array['nữ', 'cầm bóng', 'vận động viên', 'thể thao']::text[]),
  ('sp-444', '0444', 'Nữ bước đi túi xách đeo vai', 'https://kevindauto.com/products/sp-444.webp', 'nu', 'Đời thường', array['nữ', 'túi vai', 'đứng', 'đời thường']::text[]),
  ('sp-445', '0445', 'Nữ cầm túi du lịch chờ xe', 'https://kevindauto.com/products/sp-445.webp', 'nu', 'Du lịch', array['nữ', 'túi du lịch', 'hành lý', 'đứng']::text[]),
  ('sp-446', '0446', 'Nữ lái xe ô tô', 'https://kevindauto.com/products/sp-446.webp', 'nu', 'Đời thường', array['nữ', 'ngồi ghế', 'điện thoại', 'đời thường']::text[]),
  ('sp-447', '0447', 'Nữ túi đeo khoác jean', 'https://kevindauto.com/products/sp-447.webp', 'nam', 'Nhiếp ảnh', array['nam', 'máy ảnh', 'nhiếp ảnh gia', 'du lịch']::text[]),
  ('sp-448', '0448', 'Nữ khoanh tay túi xách', 'https://kevindauto.com/products/sp-448.webp', 'nu', 'Đời thường', array['nữ', 'khoanh tay', 'tự tin', 'đứng']::text[]),
  ('sp-449', '0449', 'Chunli', 'https://kevindauto.com/products/sp-449.webp', 'thethao', 'Thể hình', array['nữ', 'vận động viên', 'chống hông', 'thể hình']::text[]),
  ('sp-450', '0450', 'Nữ like Macquin', 'https://kevindauto.com/products/sp-450.webp', 'nu', 'Hành động', array['nữ', 'gậy', 'vũ khí', 'hành động']::text[]),
  ('sp-451', '0451', 'Nữ sơ mi công sở cà phê nói chuyện', 'https://kevindauto.com/products/sp-451.webp', 'nu', 'Công sở', array['nữ', 'điện thoại', 'thuyết trình', 'công sở']::text[]),
  ('sp-500', '0500', 'Nam dang tay vui mừng cười lớn', 'https://kevindauto.com/products/sp-500.webp', 'nam', 'Đời thường', array['nam', 'dang tay', 'trò chuyện', 'đứng']::text[]),
  ('sp-501', '0501', 'Nam nón len hai tay đỡ sợ hãi', 'https://kevindauto.com/products/sp-501.webp', 'caotuoi', 'Người cao tuổi', array['cụ ông', 'áo khoác', 'vẫy tay', 'cao tuổi']::text[]),
  ('sp-502', '0502', 'Nam cảnh sát', 'https://kevindauto.com/products/sp-502.webp', 'nam', 'Nghề nghiệp', array['nam', 'an ninh', 'đồng phục', 'khoanh tay']::text[]),
  ('sp-503', '0503', 'Nam bảo vệ', 'https://kevindauto.com/products/sp-503.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'tự tin', 'đứng']::text[]),
  ('sp-504', '0504', 'Nam pha chế râu quắn', 'https://kevindauto.com/products/sp-504.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'chống hông', 'gọi điện']::text[]),
  ('sp-505', '0505', 'Nam nhảy hiphop', 'https://kevindauto.com/products/sp-505.webp', 'nam', 'Đời thường', array['nam', 'chỉnh tay áo', 'đứng', 'thời trang']::text[]),
  ('sp-506', '0506', 'Nam mập gangster hút thuốc', 'https://kevindauto.com/products/sp-506.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng', 'giao tiếp']::text[]),
  ('sp-507', '0507', 'Nam thanh niên ba lo chỉ tay', 'https://kevindauto.com/products/sp-507.webp', 'nam', 'Du lịch', array['nam', 'ba lô', 'dạo phố', 'du lịch']::text[]),
  ('sp-508', '0508', 'Nam quần đùi tay đút túi mặt ngông', 'https://kevindauto.com/products/sp-508.webp', 'nam', 'Đời thường', array['nam', 'áo thun', 'đứng', 'đời thường']::text[]),
  ('sp-509', '0509', 'Nam áo len 2 tay nắm trước bụng', 'https://kevindauto.com/products/sp-509.webp', 'nam', 'Đời thường', array['nam', 'chống hông', 'đứng', 'đời thường']::text[]),
  ('sp-510', '0510', 'Nam túi đeo chéo bước đi', 'https://kevindauto.com/products/sp-510.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'bỏ tay túi', 'streetwear']::text[]),
  ('sp-511', '0511', 'Tom Holand Peter Parker Spiderman', 'https://kevindauto.com/products/sp-511.webp', 'nam', 'Năng động', array['nam', 'trang phục thể thao', 'đứng', 'năng động']::text[]),
  ('sp-512', '0512', 'Nam leo núi', 'https://kevindauto.com/products/sp-512.webp', 'nam', 'Du lịch', array['nam', 'phượt thủ', 'ba lô', 'chỉ đường']::text[]),
  ('sp-513', '0513', 'Nam arab ả rập giàu có shopping', 'https://kevindauto.com/products/sp-513.webp', 'caotuoi', 'Người cao tuổi', array['cụ ông', 'áo dài', 'túi xách', 'cao tuổi']::text[]),
  ('sp-514', '0514', 'Martin Riggs Lethal Weapon cầm súng', 'https://kevindauto.com/products/sp-514.webp', 'nam', 'Nhiếp ảnh', array['nam', 'nhiếp ảnh gia', 'máy ảnh', 'chụp hình']::text[]),
  ('sp-515', '0515', 'Vin Diesel Fast Furious', 'https://kevindauto.com/products/sp-515.webp', 'thethao', 'Thể hình', array['nam', 'vận động viên', 'khoanh tay', 'thể hình']::text[]),
  ('sp-516', '0516', 'Nữ bám tường', 'https://kevindauto.com/products/sp-516.webp', 'thethao', 'Bóng rổ', array['nam', 'bóng rổ', 'bật nhảy', 'ném bóng']::text[]),
  ('sp-517', '0517', 'Nam khoanh tay', 'https://kevindauto.com/products/sp-517.webp', 'nam', 'Đời thường', array['nam', 'áo thun', 'khoanh tay', 'đứng']::text[]),
  ('sp-518', '0518', 'Nam bốc vác', 'https://kevindauto.com/products/sp-518.webp', 'thethao', 'Thể hình', array['nam', 'vận động viên', 'khởi động', 'giơ tay']::text[]),
  ('sp-519', '0519', 'Nam lái xe', 'https://kevindauto.com/products/sp-519.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'cầm ly', 'trò chuyện']::text[]),
  ('sp-520', '0520', 'Nam lái xe', 'https://kevindauto.com/products/sp-520.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thuyết trình', 'giao tiếp']::text[]),
  ('sp-521', '0521', 'Nam trẻ ngồi tay chống đùi', 'https://kevindauto.com/products/sp-521.webp', 'nam', 'Công sở', array['nam', 'vest', 'ngồi ghế', 'công sở']::text[]),
  ('sp-522', '0522', 'Nam đứng chống cằm suy nghĩ', 'https://kevindauto.com/products/sp-522.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'đứng', 'đời thường']::text[]),
  ('sp-523', '0523', 'Nam thời trang nón kinh khoác dài', 'https://kevindauto.com/products/sp-523.webp', 'caotuoi', 'Người cao tuổi', array['cụ ông', 'mũ', 'đứng', 'cao tuổi']::text[]),
  ('sp-524', '0524', 'Nam chụp hình ảnh đứng', 'https://kevindauto.com/products/sp-524.webp', 'duongpho', 'Nghề nghiệp', array['nam', 'thợ kỹ thuật', 'dụng cụ', 'lao động']::text[]),
  ('sp-525', '0525', 'Nam ba lô nón lưới chai tay đút túi', 'https://kevindauto.com/products/sp-525.webp', 'nam', 'Đời thường', array['nam', 'mũ', 'quần short', 'đứng']::text[]),
  ('sp-526', '0526', 'Nam hip hop tay nắm trước bụng nón lưỡi', 'https://kevindauto.com/products/sp-526.webp', 'nam', 'Đời thường', array['nam', 'chắp tay', 'đứng', 'đời thường']::text[]),
  ('sp-527', '0527', 'Nam gọi điện ba lô râu mắt kính quần đùi', 'https://kevindauto.com/products/sp-527.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'gọi điện', 'thư giãn']::text[]),
  ('sp-528', '0528', 'Nam khoanh tay', 'https://kevindauto.com/products/sp-528.webp', 'nam', 'Đời thường', array['nam', 'áo polo', 'khoanh tay', 'đứng']::text[]),
  ('sp-529', '0529', 'Nam chạy scooter', 'https://kevindauto.com/products/sp-529.webp', 'thethao', 'Thể thao đường phố', array['nam', 'scooter', 'trượt', 'thể thao đường phố']::text[]),
  ('sp-530', '0530', 'Nam bi da billard', 'https://kevindauto.com/products/sp-530.webp', 'nam', 'Nghề nghiệp', array['nam', 'gậy chỉ dẫn', 'đứng', 'nghề nghiệp']::text[]),
  ('sp-531', '0531', 'Nam tattoo giang hồ cởi trần', 'https://kevindauto.com/products/sp-531.webp', 'nam', 'Thể hình', array['nam', 'cởi trần', 'đứng', 'thể hình']::text[]),
  ('sp-532', '0532', 'Nam lướt ván', 'https://kevindauto.com/products/sp-532.webp', 'caotuoi', 'Người cao tuổi', array['cụ ông', 'tóc dài', 'khoanh tay', 'cao tuổi']::text[]),
  ('sp-533', '0533', 'Nam trẻ ngồi ghế dựa bãi biển', 'https://kevindauto.com/products/sp-533.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'tựa lưng', 'thư giãn']::text[]),
  ('sp-534', '0534', 'Nam túi chéo dựa tường', 'https://kevindauto.com/products/sp-534.webp', 'thethao', 'Thể dục', array['nam', 'giữ thăng bằng', 'một chân', 'thể dục']::text[]),
  ('sp-535', '0535', 'Nam túi chéo dựa tường mắt kính', 'https://kevindauto.com/products/sp-535.webp', 'thethao', 'Thể dục', array['nam', 'co chân', 'khởi động', 'thể dục']::text[]),
  ('sp-536', '0536', 'Nam túi chéo đứng thẳng', 'https://kevindauto.com/products/sp-536.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'bỏ tay túi', 'streetwear']::text[]),
  ('sp-537', '0537', 'Nam skateboard lướt ván', 'https://kevindauto.com/products/sp-537.webp', 'thethao', 'Trượt ván', array['nam', 'ván trượt', 'skateboard', 'ngồi']::text[]),
  ('sp-538', '0538', 'Nam trẻ bóng rổ basketball', 'https://kevindauto.com/products/sp-538.webp', 'thethao', 'Bóng rổ', array['nam', 'bóng rổ', 'cầm bóng', 'cầu thủ']::text[]),
  ('sp-539', '0539', 'Nam ba lô cầm sách ngồi', 'https://kevindauto.com/products/sp-539.webp', 'nam', 'Du lịch', array['nam', 'ba lô', 'ngồi ghế', 'du lịch']::text[]),
  ('sp-540', '0540', 'Nam gangster cởi trần quần đùi nón', 'https://kevindauto.com/products/sp-540.webp', 'nam', 'Thể hình', array['nam', 'cởi trần', 'uống nước', 'thể hình']::text[]),
  ('sp-541', '0541', 'Nam hip hop tay balo nón lệch', 'https://kevindauto.com/products/sp-541.webp', 'nam', 'Mua sắm', array['nam', 'xách túi', 'mua sắm', 'bước đi']::text[]),
  ('sp-542', '0542', 'Nam vest điện thoại kéo vali', 'https://kevindauto.com/products/sp-542.webp', 'nam', 'Du lịch', array['nam', 'vali', 'điện thoại', 'du lịch']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
