-- Lo 003: san pham 0543 den 0622
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-543', '0543', 'Nam thể hình sexy tay ôm đầu', 'https://kevindauto.com/products/sp-543.webp', 'thethao', 'Thể hình', array['nam', 'chắp tay sau đầu', 'thể hình', 'đứng']::text[]),
  ('sp-544', '0544', 'Nam vest big security', 'https://kevindauto.com/products/sp-544.webp', 'nam', 'Công sở', array['nam', 'quý ông', 'chắp tay', 'công sở']::text[]),
  ('sp-545', '0545', 'Nam chắp tay giống Snoop Dog', 'https://kevindauto.com/products/sp-545.webp', 'thethao', 'Thể hình', array['nam', 'vận động viên', 'chuẩn bị', 'thể hình']::text[]),
  ('sp-546', '0546', 'Nam chống nạng bằng bó tai nan bước đi', 'https://kevindauto.com/products/sp-546.webp', 'caotuoi', 'Đời thường', array['nam', 'chống nạng', 'đứng', 'đời thường']::text[]),
  ('sp-547', '0547', 'Nam đứng vắt chéo chân', 'https://kevindauto.com/products/sp-547.webp', 'thethao', 'Thể dục', array['nam', 'thăng bằng', 'một chân', 'thể dục']::text[]),
  ('sp-548', '0548', 'Nam vest hút thuốc', 'https://kevindauto.com/products/sp-548.webp', 'nam', 'Công sở', array['nam', 'điện thoại', 'quý ông', 'công sở']::text[]),
  ('sp-549', '0549', 'Nam fuck finger hand', 'https://kevindauto.com/products/sp-549.webp', 'thethao', 'Nhảy hiện đại', array['nam', 'nhảy', 'đường phố', 'chuyển động']::text[]),
  ('sp-550', '0550', 'Nam kungfu tung bay', 'https://kevindauto.com/products/sp-550.webp', 'thethao', 'Võ thuật', array['nam', 'võ sĩ', 'võ thuật', 'tung đòn']::text[]),
  ('sp-551', '0551', 'Nam camera phóng viên', 'https://kevindauto.com/products/sp-551.webp', 'nam', 'Quan sát', array['nam', 'kính viễn vọng', 'quan sát', 'chân máy']::text[]),
  ('sp-552', '0552', 'Nam to lớn tay đút túi', 'https://kevindauto.com/products/sp-552.webp', 'nam', 'Đời thường', array['nam', 'dáng đậm', 'đứng', 'đời thường']::text[]),
  ('sp-553', '0553', 'Thợ ngồi hút thuốc', 'https://kevindauto.com/products/sp-553.webp', 'nam', 'Đời thường', array['nam', 'ngồi ghế', 'suy tư', 'đời thường']::text[]),
  ('sp-554', '0554', 'Nam kungfu thủ thế', 'https://kevindauto.com/products/sp-554.webp', 'thethao', 'Thể dục', array['nam', 'nâng gối', 'tập luyện', 'thể dục']::text[]),
  ('sp-555', '0555', 'Nam tạo dáng chỉ tay', 'https://kevindauto.com/products/sp-555.webp', 'nam', 'Nghề nghiệp', array['nam', 'chỉ tay', 'điều phối', 'đứng']::text[]),
  ('sp-556', '0556', 'Nam gangster châu á khoanh tay', 'https://kevindauto.com/products/sp-556.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'quan sát', 'đứng']::text[]),
  ('sp-557', '0557', 'Nam vác gỗ', 'https://kevindauto.com/products/sp-557.webp', 'thethao', 'Thể thao', array['nam', 'vung gậy', 'vận động viên', 'chuyển động']::text[]),
  ('sp-558', '0558', 'Nam cuốc đất - bổ củi', 'https://kevindauto.com/products/sp-558.webp', 'duongpho', 'Lao động', array['nam', 'công nhân', 'cuốc', 'lao động']::text[]),
  ('sp-559', '0559', 'Nam chống xẻng', 'https://kevindauto.com/products/sp-559.webp', 'duongpho', 'Lao động', array['nam', 'công nhân', 'xẻng', 'lao động']::text[]),
  ('sp-560', '0560', 'Thợ công trình chống xẻng', 'https://kevindauto.com/products/sp-560.webp', 'duongpho', 'Xây dựng', array['nam', 'công nhân', 'mũ bảo hộ', 'xây dựng']::text[]),
  ('sp-561', '0561', 'Thợ công trình hút thuốc', 'https://kevindauto.com/products/sp-561.webp', 'nam', 'Đời thường', array['nam', 'chống cằm', 'suy nghĩ', 'đứng']::text[]),
  ('sp-562', '0562', 'Thợ công trình máy cắt tay', 'https://kevindauto.com/products/sp-562.webp', 'duongpho', 'Nghề nghiệp', array['nam', 'thợ sửa chữa', 'quỳ', 'dụng cụ']::text[]),
  ('sp-563', '0563', 'Thợ công trình cầm hộp dụng cụ', 'https://kevindauto.com/products/sp-563.webp', 'duongpho', 'Nghề nghiệp', array['nam', 'công nhân', 'hộp dụng cụ', 'mũ bảo hộ']::text[]),
  ('sp-564', '0564', 'Thợ công trình chỉ huy', 'https://kevindauto.com/products/sp-564.webp', 'duongpho', 'Xây dựng', array['nam', 'giám sát', 'chỉ hướng', 'công trình']::text[]),
  ('sp-565', '0565', 'Thợ công trình đeo tai chống ồn', 'https://kevindauto.com/products/sp-565.webp', 'duongpho', 'Xây dựng', array['nam', 'công nhân', 'mũ bảo hộ', 'đứng']::text[]),
  ('sp-566', '0566', 'Thợ công trình khoanh tay', 'https://kevindauto.com/products/sp-566.webp', 'duongpho', 'Xây dựng', array['nữ', 'công nhân', 'khoanh tay', 'mũ bảo hộ']::text[]),
  ('sp-567', '0567', 'Nam đua xe cầm cup chiến thắng', 'https://kevindauto.com/products/sp-567.webp', 'duongpho', 'Nghề nghiệp', array['nam', 'thợ kỹ thuật', 'báo hiệu', 'dụng cụ']::text[]),
  ('sp-568', '0568', 'Nam ngồi tay dưới cằm', 'https://kevindauto.com/products/sp-568.webp', 'thethao', 'Bóng', array['nam', 'cầu thủ', 'ôm bóng', 'ngồi thấp']::text[]),
  ('sp-569', '0569', 'Nam to con khoanh tay', 'https://kevindauto.com/products/sp-569.webp', 'nam', 'Streetwear', array['nam', 'mũ', 'khoanh tay', 'streetwear']::text[]),
  ('sp-570', '0570', 'Nam to con khoanh tay', 'https://kevindauto.com/products/sp-570.webp', 'thethao', 'Thể hình', array['nam', 'vận động viên', 'áo thun', 'khoanh tay']::text[]),
  ('sp-571', '0571', 'Nam gọi điện vắt chéo chân', 'https://kevindauto.com/products/sp-571.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'bắt chéo chân', 'đời thường']::text[]),
  ('sp-572', '0572', 'Nam nhật bản sung sướng', 'https://kevindauto.com/products/sp-572.webp', 'thethao', 'Thể dục', array['nam', 'nghiêng người', 'thăng bằng', 'thể dục']::text[]),
  ('sp-573', '0573', 'Nam khoác áo trên vai', 'https://kevindauto.com/products/sp-573.webp', 'duongpho', 'Nghề nghiệp', array['nam', 'kỹ thuật', 'đồng phục', 'đứng']::text[]),
  ('sp-574', '0574', 'Nam lái xe ô tô', 'https://kevindauto.com/products/sp-574.webp', 'xe', 'Lái xe', array['nam', 'tài xế', 'vô lăng', 'ngồi']::text[]),
  ('sp-575', '0575', 'Nam lái xe đạp', 'https://kevindauto.com/products/sp-575.webp', 'xe', 'Lái xe', array['nam', 'tài xế', 'điều khiển', 'ngồi']::text[]),
  ('sp-576', '0576', 'Nam lái ô tô áo mùa đông', 'https://kevindauto.com/products/sp-576.webp', 'xe', 'Lái xe', array['nam', 'tài xế', 'xe tải', 'vô lăng']::text[]),
  ('sp-577', '0577', 'Nam gangster chỉ tay', 'https://kevindauto.com/products/sp-577.webp', 'duongpho', 'Nghề nghiệp', array['nam', 'công nhân', 'lớn tuổi', 'khoanh tay']::text[]),
  ('sp-578', '0578', 'Nam sinhv iên laptop tai nghe học tập', 'https://kevindauto.com/products/sp-578.webp', 'nam', 'Công nghệ', array['nam', 'laptop', 'ngồi', 'công nghệ']::text[]),
  ('sp-579', '0579', 'Nam tóc dài nón len khoanh tay', 'https://kevindauto.com/products/sp-579.webp', 'nam', 'Đời thường', array['nam', 'áo thun', 'khoanh tay', 'đứng']::text[]),
  ('sp-580', '0580', 'Nam ôm chó', 'https://kevindauto.com/products/sp-580.webp', 'dongvat', 'Thú cưng', array['nam', 'chó', 'thú cưng', 'vuốt ve']::text[]),
  ('sp-581', '0581', 'Nam đứng thẳng đẹp trai', 'https://kevindauto.com/products/sp-581.webp', 'nam', 'Đời thường', array['nam', 'bỏ tay túi', 'đứng', 'đời thường']::text[]),
  ('sp-582', '0582', 'Nam gọi điện đẹp trai', 'https://kevindauto.com/products/sp-582.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'gọi điện', 'đứng']::text[]),
  ('sp-583', '0583', 'Nam hiphop đứng thẳng', 'https://kevindauto.com/products/sp-583.webp', 'caotuoi', 'Người cao tuổi', array['cụ ông', 'mũ', 'đứng', 'cao tuổi']::text[]),
  ('sp-584', '0584', 'Chú hề', 'https://kevindauto.com/products/sp-584.webp', 'caotuoi', 'Người cao tuổi', array['cụ ông', 'dụng cụ', 'lao động', 'cao tuổi']::text[]),
  ('sp-585', '0585', 'Nam balo laptop bước đi', 'https://kevindauto.com/products/sp-585.webp', 'nam', 'Streetwear', array['nam', 'túi vai', 'đứng', 'streetwear']::text[]),
  ('sp-586', '0586', 'Nam dự triển lãm ba lô', 'https://kevindauto.com/products/sp-586.webp', 'nam', 'Đời thường', array['nam', 'áo thun', 'bỏ tay túi', 'đứng']::text[]),
  ('sp-587', '0587', 'Nam áo khoác tay nắm trước bụng', 'https://kevindauto.com/products/sp-587.webp', 'nam', 'Công sở', array['nam', 'quý ông', 'chắp tay', 'công sở']::text[]),
  ('sp-588', '0588', 'Thợ công trình làm lái xe', 'https://kevindauto.com/products/sp-588.webp', 'xe', 'Lái xe', array['nam', 'tài xế', 'điều khiển', 'máy móc']::text[]),
  ('sp-589', '0589', 'Thợ công trình khoan', 'https://kevindauto.com/products/sp-589.webp', 'nam', 'Nghệ thuật', array['nam', 'nghệ sĩ', 'nhạc cụ', 'biểu diễn']::text[]),
  ('sp-590', '0590', 'Thợ công trình lái xe', 'https://kevindauto.com/products/sp-590.webp', 'nam', 'Công nghệ', array['nam', 'ngồi', 'thiết bị', 'điều khiển']::text[]),
  ('sp-591', '0591', 'Nam lái xe moto 1 tay', 'https://kevindauto.com/products/sp-591.webp', 'nam', 'Đời thường', array['nam', 'chỉ cổ tay', 'đứng', 'đời thường']::text[]),
  ('sp-592', '0592', 'Nam áo thun quần jean', 'https://kevindauto.com/products/sp-592.webp', 'nam', 'Đời thường', array['nam', 'chống hông', 'đứng', 'đời thường']::text[]),
  ('sp-593', '0593', 'Nam râu áo khoác khăn len mùa đông', 'https://kevindauto.com/products/sp-593.webp', 'nam', 'Mùa đông', array['nam', 'khăn quàng', 'áo khoác', 'mùa đông']::text[]),
  ('sp-594', '0594', 'Nam áo khoác bỏ tay túi quần', 'https://kevindauto.com/products/sp-594.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'bỏ tay túi', 'streetwear']::text[]),
  ('sp-595', '0595', 'Nam vest đứng thẳng', 'https://kevindauto.com/products/sp-595.webp', 'nam', 'Công sở', array['nam', 'blazer', 'chắp tay', 'công sở']::text[]),
  ('sp-596', '0596', 'Nam Châu phi kéo vali vest', 'https://kevindauto.com/products/sp-596.webp', 'nam', 'Công sở', array['nam', 'túi công sở', 'áo khoác', 'đứng']::text[]),
  ('sp-597', '0597', 'Nam trung niên vest nghiêm túc', 'https://kevindauto.com/products/sp-597.webp', 'nam', 'Công sở', array['nam', 'ghi lê', 'quý ông', 'đứng']::text[]),
  ('sp-598', '0598', 'Nam trung niên vest cool', 'https://kevindauto.com/products/sp-598.webp', 'nam', 'Công sở', array['nam', 'vest', 'bỏ tay túi', 'công sở']::text[]),
  ('sp-599', '0599', 'Nam vest bước đi', 'https://kevindauto.com/products/sp-599.webp', 'nam', 'Công sở', array['nam', 'vest', 'bước đi', 'công sở']::text[]),
  ('sp-600', '0600', 'Nam khoác áo vest trên mai', 'https://kevindauto.com/products/sp-600.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'đeo', 'túi', 'vai']::text[]),
  ('sp-601', '0601', 'Nam mùa đông áo khoac dài', 'https://kevindauto.com/products/sp-601.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'thể', 'thao']::text[]),
  ('sp-602', '0602', 'Takumi', 'https://kevindauto.com/products/sp-602.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'đứng', 'thư', 'thái']::text[]),
  ('sp-603', '0603', 'Takumi', 'https://kevindauto.com/products/sp-603.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'áo', 'thun', 'nhìn', 'nghiêng']::text[]),
  ('sp-604', '0604', 'Machilin ngờ lốp xe', 'https://kevindauto.com/products/sp-604.webp', 'dongvat', 'Linh vật', array['dongvat', 'linh vật', 'linh', 'vật', 'người', 'lốp', 'xe', 'vẫy', 'tay']::text[]),
  ('sp-605', '0605', 'Nam đội mũ khoanh tay', 'https://kevindauto.com/products/sp-605.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'đội', 'mũ', 'khoanh', 'tay']::text[]),
  ('sp-606', '0606', 'Nam ôm cá mập gây bóng chày hút thuốc', 'https://kevindauto.com/products/sp-606.webp', 'nam', 'Năng động', array['nam', 'năng động', 'chàng', 'trai', 'vác', 'gậy', 'trên', 'vai']::text[]),
  ('sp-607', '0607', 'Nam gangster răng vàng', 'https://kevindauto.com/products/sp-607.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'gọi', 'điện']::text[]),
  ('sp-608', '0608', 'Nam hiphop đứng thẳng', 'https://kevindauto.com/products/sp-608.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'dáng', 'đậm']::text[]),
  ('sp-609', '0609', 'Nam trẻ hiphop', 'https://kevindauto.com/products/sp-609.webp', 'nam', 'Năng động', array['nam', 'năng động', 'chàng', 'trai', 'mặc', 'đồ', 'thể', 'thao']::text[]),
  ('sp-610', '0610', 'Nam ba lô', 'https://kevindauto.com/products/sp-610.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'bỏ', 'tay', 'túi']::text[]),
  ('sp-611', '0611', 'Nam ngồi chống cằm', 'https://kevindauto.com/products/sp-611.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'quần', 'jogger']::text[]),
  ('sp-612', '0612', 'Racer F1 đua xe', 'https://kevindauto.com/products/sp-612.webp', 'nam', 'Du lịch', array['nam', 'du lịch', 'phượt', 'thủ', 'ngồi', 'nghỉ']::text[]),
  ('sp-613', '0613', 'Nam ngồi uống uống cà phê', 'https://kevindauto.com/products/sp-613.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'nhân', 'viên', 'kỹ', 'thuật', 'giơ', 'tay']::text[]),
  ('sp-614', '0614', 'Nam chụp hình đường phố', 'https://kevindauto.com/products/sp-614.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'cầm', 'cốc']::text[]),
  ('sp-615', '0615', 'Nam áo khoác dài', 'https://kevindauto.com/products/sp-615.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'công', 'nhân', 'đội', 'mũ', 'đứng', 'thẳng']::text[]),
  ('sp-616', '0616', 'Nam gangstẻ gậy bóng chày', 'https://kevindauto.com/products/sp-616.webp', 'nam', 'Mùa đông', array['nam', 'mùa đông', 'người', 'đàn', 'ông', 'áo', 'khoác', 'dài']::text[]),
  ('sp-617', '0617', 'Vận động viên cầm gậy', 'https://kevindauto.com/products/sp-617.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'vận', 'động', 'viên', 'cầm', 'gậy']::text[]),
  ('sp-618', '0618', 'Võ sĩ chỉnh trang phục', 'https://kevindauto.com/products/sp-618.webp', 'thethao', 'Võ thuật', array['thethao', 'võ thuật', 'võ', 'sĩ', 'chỉnh', 'trang', 'phục']::text[]),
  ('sp-619', '0619', 'Vận động viên thể hình đứng thẳng', 'https://kevindauto.com/products/sp-619.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'vận', 'động', 'viên', 'thể', 'hình', 'đứng', 'thẳng']::text[]),
  ('sp-620', '0620', 'Quý ông mặc vest ngồi ghế', 'https://kevindauto.com/products/sp-620.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'mặc', 'vest', 'ngồi', 'ghế']::text[]),
  ('sp-621', '0621', 'Người đàn ông ngồi xem điện thoại', 'https://kevindauto.com/products/sp-621.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'xem', 'điện', 'thoại']::text[]),
  ('sp-622', '0622', 'Người đàn ông dáng đậm áo thun', 'https://kevindauto.com/products/sp-622.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'dáng', 'đậm', 'áo', 'thun']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
