-- Lo 004: san pham 0623 den 0704
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-623', '0623', 'Người đàn ông ngồi suy tư', 'https://kevindauto.com/products/sp-623.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'suy', 'tư']::text[]),
  ('sp-624', '0624', 'Chàng trai đội mũ ngồi ghế', 'https://kevindauto.com/products/sp-624.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'đội', 'mũ', 'ngồi', 'ghế']::text[]),
  ('sp-625', '0625', 'Vận động viên cơ bắp chống hông', 'https://kevindauto.com/products/sp-625.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'vận', 'động', 'viên', 'cơ', 'bắp', 'chống', 'hông']::text[]),
  ('sp-626', '0626', 'Chàng trai vươn vai thư giãn', 'https://kevindauto.com/products/sp-626.webp', 'thethao', 'Thể dục', array['thethao', 'thể dục', 'chàng', 'trai', 'vươn', 'vai', 'thư', 'giãn']::text[]),
  ('sp-627', '0627', 'Chàng trai tựa người nghỉ', 'https://kevindauto.com/products/sp-627.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'tựa', 'người', 'nghỉ']::text[]),
  ('sp-628', '0628', 'Chàng trai áo thun đứng tự nhiên', 'https://kevindauto.com/products/sp-628.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'áo', 'thun', 'đứng', 'tự', 'nhiên']::text[]),
  ('sp-629', '0629', 'Võ sĩ tung cú đá', 'https://kevindauto.com/products/sp-629.webp', 'thethao', 'Võ thuật', array['thethao', 'võ thuật', 'võ', 'sĩ', 'tung', 'cú', 'đá']::text[]),
  ('sp-630', '0630', 'Vận động viên khoe cơ tay', 'https://kevindauto.com/products/sp-630.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'vận', 'động', 'viên', 'khoe', 'cơ', 'tay']::text[]),
  ('sp-631', '0631', 'Chiến binh cơ bắp mang giáp', 'https://kevindauto.com/products/sp-631.webp', 'nam', 'Hành động', array['nam', 'hành động', 'chiến', 'binh', 'cơ', 'bắp', 'mang', 'giáp']::text[]),
  ('sp-632', '0632', 'Lực sĩ tạo dáng hai tay', 'https://kevindauto.com/products/sp-632.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'lực', 'sĩ', 'tạo', 'dáng', 'hai', 'tay']::text[]),
  ('sp-633', '0633', 'Thợ cứu hộ cầm dụng cụ', 'https://kevindauto.com/products/sp-633.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'thợ', 'cứu', 'hộ', 'cầm', 'dụng', 'cụ']::text[]),
  ('sp-634', '0634', 'Đặc nhiệm mang hai súng', 'https://kevindauto.com/products/sp-634.webp', 'nam', 'Chiến thuật', array['nam', 'chiến thuật', 'đặc', 'nhiệm', 'mang', 'hai', 'súng']::text[]),
  ('sp-635', '0635', 'Đặc nhiệm ngắm súng ngắn', 'https://kevindauto.com/products/sp-635.webp', 'nam', 'Chiến thuật', array['nam', 'chiến thuật', 'đặc', 'nhiệm', 'ngắm', 'súng', 'ngắn']::text[]),
  ('sp-636', '0636', 'Đặc nhiệm quỳ ngắm bắn', 'https://kevindauto.com/products/sp-636.webp', 'nam', 'Chiến thuật', array['nam', 'chiến thuật', 'đặc', 'nhiệm', 'quỳ', 'ngắm', 'bắn']::text[]),
  ('sp-637', '0637', 'Binh sĩ ngắm súng trường', 'https://kevindauto.com/products/sp-637.webp', 'nam', 'Chiến thuật', array['nam', 'chiến thuật', 'binh', 'sĩ', 'ngắm', 'súng', 'trường']::text[]),
  ('sp-638', '0638', 'Tay đua mô tô ôm cua', 'https://kevindauto.com/products/sp-638.webp', 'xe', 'Mô tô', array['xe', 'mô tô', 'tay', 'đua', 'mô', 'tô', 'ôm', 'cua']::text[]),
  ('sp-639', '0639', 'Tay đua ngồi bên mô tô', 'https://kevindauto.com/products/sp-639.webp', 'xe', 'Mô tô', array['xe', 'mô tô', 'tay', 'đua', 'ngồi', 'bên', 'mô', 'tô']::text[]),
  ('sp-641', '0641', 'Chàng trai đứng nghe điện thoại', 'https://kevindauto.com/products/sp-641.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'đứng', 'nghe', 'điện', 'thoại']::text[]),
  ('sp-642', '0642', 'Nữ chiến binh đeo kiếm', 'https://kevindauto.com/products/sp-642.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'chiến', 'binh', 'đeo', 'kiếm']::text[]),
  ('sp-643', '0643', 'Chàng trai ngồi ghế thư giãn', 'https://kevindauto.com/products/sp-643.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'ngồi', 'ghế', 'thư', 'giãn']::text[]),
  ('sp-644', '0644', 'Anh hùng giả tưởng mang vũ khí', 'https://kevindauto.com/products/sp-644.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'anh', 'hùng', 'giả', 'tưởng', 'mang', 'vũ', 'khí']::text[]),
  ('sp-645', '0645', 'Siêu anh hùng áo choàng', 'https://kevindauto.com/products/sp-645.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'siêu', 'anh', 'hùng', 'áo', 'choàng']::text[]),
  ('sp-646', '0646', 'Quý ông giơ tay thuyết trình', 'https://kevindauto.com/products/sp-646.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'giơ', 'tay', 'thuyết', 'trình']::text[]),
  ('sp-647', '0647', 'Chiến binh tương lai ngồi ghế', 'https://kevindauto.com/products/sp-647.webp', 'nam', 'Sci-fi', array['nam', 'sci-fi', 'chiến', 'binh', 'tương', 'lai', 'ngồi', 'ghế']::text[]),
  ('sp-648', '0648', 'Siêu anh hùng mặc giáp', 'https://kevindauto.com/products/sp-648.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'siêu', 'anh', 'hùng', 'mặc', 'giáp']::text[]),
  ('sp-649', '0649', 'Vận động viên cầm bóng lớn', 'https://kevindauto.com/products/sp-649.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'vận', 'động', 'viên', 'cầm', 'bóng', 'lớn']::text[]),
  ('sp-650', '0650', 'Cầu thủ mặc đồ bảo hộ', 'https://kevindauto.com/products/sp-650.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'cầu', 'thủ', 'mặc', 'đồ', 'bảo', 'hộ']::text[]),
  ('sp-651', '0651', 'Linh vật người lốp xe quay lưng', 'https://kevindauto.com/products/sp-651.webp', 'dongvat', 'Linh vật', array['dongvat', 'linh vật', 'linh', 'vật', 'người', 'lốp', 'xe', 'quay', 'lưng']::text[]),
  ('sp-652', '0652', 'Ninja tung đòn trên không', 'https://kevindauto.com/products/sp-652.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'ninja', 'tung', 'đòn', 'trên', 'không']::text[]),
  ('sp-653', '0653', 'Quý bà giơ tay chào', 'https://kevindauto.com/products/sp-653.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'quý', 'bà', 'giơ', 'tay', 'chào']::text[]),
  ('sp-654', '0654', 'Chiến binh lùn mang giáp', 'https://kevindauto.com/products/sp-654.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'chiến', 'binh', 'lùn', 'mang', 'giáp']::text[]),
  ('sp-655', '0655', 'Võ sĩ giả tưởng tung đòn', 'https://kevindauto.com/products/sp-655.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'võ', 'sĩ', 'giả', 'tưởng', 'tung', 'đòn']::text[]),
  ('sp-656', '0656', 'Chiến binh áo giáp hạng nặng', 'https://kevindauto.com/products/sp-656.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'chiến', 'binh', 'áo', 'giáp', 'hạng', 'nặng']::text[]),
  ('sp-657', '0657', 'Nhân vật chibi đội mũ nhọn', 'https://kevindauto.com/products/sp-657.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhân', 'vật', 'đội', 'mũ', 'nhọn']::text[]),
  ('sp-658', '0658', 'Nhân vật thú chạy bộ', 'https://kevindauto.com/products/sp-658.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhân', 'vật', 'thú', 'chạy', 'bộ']::text[]),
  ('sp-659', '0659', 'Chuột kiếm sĩ đội mũ', 'https://kevindauto.com/products/sp-659.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'chuột', 'kiếm', 'sĩ', 'đội', 'mũ']::text[]),
  ('sp-660', '0660', 'Nhím hoạt hình mang giày', 'https://kevindauto.com/products/sp-660.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhím', 'hoạt', 'hình', 'mang', 'giày']::text[]),
  ('sp-661', '0661', 'Linh vật gấu nhỏ', 'https://kevindauto.com/products/sp-661.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'gấu', 'nhỏ']::text[]),
  ('sp-662', '0662', 'Chiến binh thú tung quyền', 'https://kevindauto.com/products/sp-662.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'chiến', 'binh', 'thú', 'tung', 'quyền']::text[]),
  ('sp-663', '0663', 'Chiến binh thú phòng thủ', 'https://kevindauto.com/products/sp-663.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'chiến', 'binh', 'thú', 'phòng', 'thủ']::text[]),
  ('sp-664', '0664', 'Rồng canh giữ bệ đá', 'https://kevindauto.com/products/sp-664.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'rồng', 'canh', 'giữ', 'bệ', 'đá']::text[]),
  ('sp-665', '0665', 'Tử thần cầm lưỡi hái', 'https://kevindauto.com/products/sp-665.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'tử', 'thần', 'cầm', 'lưỡi', 'hái']::text[]),
  ('sp-666', '0666', 'Võ sĩ tung cú đá cao', 'https://kevindauto.com/products/sp-666.webp', 'thethao', 'Võ thuật', array['thethao', 'võ thuật', 'võ', 'sĩ', 'tung', 'cú', 'đá', 'cao']::text[]),
  ('sp-667', '0667', 'Tay đua cầm mũ bảo hiểm', 'https://kevindauto.com/products/sp-667.webp', 'xe', 'Đua xe', array['xe', 'đua xe', 'tay', 'đua', 'cầm', 'mũ', 'bảo', 'hiểm']::text[]),
  ('sp-668', '0668', 'Tay đua mặc đồ bảo hộ', 'https://kevindauto.com/products/sp-668.webp', 'xe', 'Đua xe', array['xe', 'đua xe', 'tay', 'đua', 'mặc', 'đồ', 'bảo', 'hộ']::text[]),
  ('sp-669', '0669', 'Phi hành gia mặc bộ đồ không gian', 'https://kevindauto.com/products/sp-669.webp', 'nam', 'Sci-fi', array['nam', 'sci-fi', 'phi', 'hành', 'gia', 'mặc', 'bộ', 'đồ', 'không', 'gian']::text[]),
  ('sp-670', '0670', 'Đầu bếp khoanh tay', 'https://kevindauto.com/products/sp-670.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'đầu', 'bếp', 'khoanh', 'tay']::text[]),
  ('sp-671', '0671', 'Phi hành gia chibi', 'https://kevindauto.com/products/sp-671.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'phi', 'hành', 'gia']::text[]),
  ('sp-672', '0672', 'Mèo máy chibi vẫy tay', 'https://kevindauto.com/products/sp-672.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'mèo', 'máy', 'vẫy', 'tay']::text[]),
  ('sp-673', '0673', 'Quý ông mặc áo dài khoanh tay', 'https://kevindauto.com/products/sp-673.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'quý', 'ông', 'mặc', 'áo', 'dài', 'khoanh', 'tay']::text[]),
  ('sp-674', '0674', 'Khỉ chiến binh cầm gậy', 'https://kevindauto.com/products/sp-674.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'khỉ', 'chiến', 'binh', 'cầm', 'gậy']::text[]),
  ('sp-675', '0675', 'Nhân vật chibi đội mũ', 'https://kevindauto.com/products/sp-675.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhân', 'vật', 'đội', 'mũ']::text[]),
  ('sp-676', '0676', 'Robot chiến đấu mang giáp', 'https://kevindauto.com/products/sp-676.webp', 'dongvat', 'Sci-fi', array['dongvat', 'sci-fi', 'robot', 'chiến', 'đấu', 'mang', 'giáp']::text[]),
  ('sp-677', '0677', 'Cá sấu nằm quan sát', 'https://kevindauto.com/products/sp-677.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'cá', 'sấu', 'nằm', 'quan', 'sát']::text[]),
  ('sp-678', '0678', 'Bò nhà đứng ăn cỏ', 'https://kevindauto.com/products/sp-678.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'bò', 'nhà', 'đứng', 'ăn', 'cỏ']::text[]),
  ('sp-679', '0679', 'Thằn lằn bò sát', 'https://kevindauto.com/products/sp-679.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'thằn', 'lằn', 'bò', 'sát']::text[]),
  ('sp-680', '0680', 'Chó Doberman đứng cảnh giác', 'https://kevindauto.com/products/sp-680.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'doberman', 'đứng', 'cảnh', 'giác']::text[]),
  ('sp-681', '0681', 'Chó săn đứng thẳng', 'https://kevindauto.com/products/sp-681.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'săn', 'đứng', 'thẳng']::text[]),
  ('sp-682', '0682', 'Chó bulldog lực lưỡng', 'https://kevindauto.com/products/sp-682.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'bulldog', 'lực', 'lưỡng']::text[]),
  ('sp-683', '0683', 'Chó bulldog nằm nghỉ', 'https://kevindauto.com/products/sp-683.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'bulldog', 'nằm', 'nghỉ']::text[]),
  ('sp-684', '0684', 'Chó chăn cừu đứng cảnh giác', 'https://kevindauto.com/products/sp-684.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'chăn', 'cừu', 'đứng', 'cảnh', 'giác']::text[]),
  ('sp-685', '0685', 'Chó chăn cừu nằm nghỉ', 'https://kevindauto.com/products/sp-685.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'chăn', 'cừu', 'nằm', 'nghỉ']::text[]),
  ('sp-686', '0686', 'Chó Corgi đứng vui vẻ', 'https://kevindauto.com/products/sp-686.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'corgi', 'đứng', 'vui', 'vẻ']::text[]),
  ('sp-687', '0687', 'Chó Pug ngồi', 'https://kevindauto.com/products/sp-687.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'pug', 'ngồi']::text[]),
  ('sp-688', '0688', 'Chó Corgi ngồi', 'https://kevindauto.com/products/sp-688.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'corgi', 'ngồi']::text[]),
  ('sp-689', '0689', 'Chó săn đứng nghiêng', 'https://kevindauto.com/products/sp-689.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'săn', 'đứng', 'nghiêng']::text[]),
  ('sp-690', '0690', 'Lợn rừng cúi đầu', 'https://kevindauto.com/products/sp-690.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'lợn', 'rừng', 'cúi', 'đầu']::text[]),
  ('sp-691', '0691', 'Chó Labrador ngồi', 'https://kevindauto.com/products/sp-691.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'labrador', 'ngồi']::text[]),
  ('sp-692', '0692', 'Chó lông dài nằm nghỉ', 'https://kevindauto.com/products/sp-692.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'lông', 'dài', 'nằm', 'nghỉ']::text[]),
  ('sp-693', '0693', 'Chó nhỏ ngồi trên ghế', 'https://kevindauto.com/products/sp-693.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'nhỏ', 'ngồi', 'trên', 'ghế']::text[]),
  ('sp-695', '0695', 'Chó Doberman đứng thẳng', 'https://kevindauto.com/products/sp-695.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'doberman', 'đứng', 'thẳng']::text[]),
  ('sp-696', '0696', 'Chó Golden ngồi', 'https://kevindauto.com/products/sp-696.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'golden', 'ngồi']::text[]),
  ('sp-697', '0697', 'Chó săn ngồi', 'https://kevindauto.com/products/sp-697.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'săn', 'ngồi']::text[]),
  ('sp-698', '0698', 'Chó cúi đầu đánh hơi', 'https://kevindauto.com/products/sp-698.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'cúi', 'đầu', 'đánh', 'hơi']::text[]),
  ('sp-699', '0699', 'Sói đứng cảnh giác', 'https://kevindauto.com/products/sp-699.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'sói', 'đứng', 'cảnh', 'giác']::text[]),
  ('sp-700', '0700', 'Hải ly nằm nghỉ', 'https://kevindauto.com/products/sp-700.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'hải', 'ly', 'nằm', 'nghỉ']::text[]),
  ('sp-701', '0701', 'Máy bán hàng tự động', 'https://kevindauto.com/products/sp-701.webp', 'phukien', 'Diorama đường phố', array['phukien', 'diorama đường phố', 'máy', 'bán', 'hàng', 'tự', 'động']::text[]),
  ('sp-702', '0702', 'Mô tô cổ điển', 'https://kevindauto.com/products/sp-702.webp', 'xe', 'Mô tô', array['xe', 'mô tô', 'mô', 'tô', 'cổ', 'điển']::text[]),
  ('sp-703', '0703', 'Ghế sofa đơn hiện đại', 'https://kevindauto.com/products/sp-703.webp', 'phukien', 'Nội thất', array['phukien', 'nội thất', 'ghế', 'sofa', 'đơn', 'hiện', 'đại']::text[]),
  ('sp-704', '0704', 'Mô tô địa hình', 'https://kevindauto.com/products/sp-704.webp', 'xe', 'Mô tô', array['xe', 'mô tô', 'mô', 'tô', 'địa', 'hình']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
