-- Lo 005: san pham 0705 den 0786
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-705', '0705', 'Xe đạp thể thao', 'https://kevindauto.com/products/sp-705.webp', 'xe', 'Xe đạp', array['xe', 'xe đạp', 'đạp', 'thể', 'thao']::text[]),
  ('sp-706', '0706', 'Ghế băng công viên', 'https://kevindauto.com/products/sp-706.webp', 'phukien', 'Diorama đường phố', array['phukien', 'diorama đường phố', 'ghế', 'băng', 'công', 'viên']::text[]),
  ('sp-707', '0707', 'Ngựa bập bênh trẻ em', 'https://kevindauto.com/products/sp-707.webp', 'phukien', 'Sân chơi', array['phukien', 'sân chơi', 'ngựa', 'bập', 'bênh', 'trẻ', 'em']::text[]),
  ('sp-708', '0708', 'Ghế văn phòng xoay', 'https://kevindauto.com/products/sp-708.webp', 'phukien', 'Nội thất', array['phukien', 'nội thất', 'ghế', 'văn', 'phòng', 'xoay']::text[]),
  ('sp-709', '0709', 'Ghế xếp nghỉ dưỡng', 'https://kevindauto.com/products/sp-709.webp', 'phukien', 'Nội thất', array['phukien', 'nội thất', 'ghế', 'xếp', 'nghỉ', 'dưỡng']::text[]),
  ('sp-710', '0710', 'Thùng gỗ trang trí', 'https://kevindauto.com/products/sp-710.webp', 'phukien', 'Diorama', array['phukien', 'diorama', 'thùng', 'gỗ', 'trang', 'trí']::text[]),
  ('sp-711', '0711', 'Hộp sọ voi ma mút', 'https://kevindauto.com/products/sp-711.webp', 'phukien', 'Bảo tàng', array['phukien', 'bảo tàng', 'hộp', 'sọ', 'voi', 'ma', 'mút']::text[]),
  ('sp-712', '0712', 'Loa radio xách tay', 'https://kevindauto.com/products/sp-712.webp', 'phukien', 'Đồ dùng', array['phukien', 'đồ dùng', 'loa', 'radio', 'xách', 'tay']::text[]),
  ('sp-713', '0713', 'Thiết bị điều khiển trò chơi', 'https://kevindauto.com/products/sp-713.webp', 'phukien', 'Đồ dùng', array['phukien', 'đồ dùng', 'thiết', 'bị', 'điều', 'khiển', 'trò', 'chơi']::text[]),
  ('sp-714', '0714', 'Áo hoodie treo trưng bày', 'https://kevindauto.com/products/sp-714.webp', 'phukien', 'Cửa hàng', array['phukien', 'cửa hàng', 'áo', 'hoodie', 'treo', 'trưng', 'bày']::text[]),
  ('sp-715', '0715', 'Bếp lửa dã ngoại', 'https://kevindauto.com/products/sp-715.webp', 'phukien', 'Dã ngoại', array['phukien', 'dã ngoại', 'bếp', 'lửa', 'dã', 'ngoại']::text[]),
  ('sp-716', '0716', 'Tượng bán thân nam trẻ', 'https://kevindauto.com/products/sp-716.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'bán', 'thân', 'nam', 'trẻ']::text[]),
  ('sp-717', '0717', 'Tượng bán thân quý ông', 'https://kevindauto.com/products/sp-717.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'bán', 'thân', 'quý', 'ông']::text[]),
  ('sp-718', '0718', 'Tượng bán thân nam tóc xoăn', 'https://kevindauto.com/products/sp-718.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'bán', 'thân', 'nam', 'tóc', 'xoăn']::text[]),
  ('sp-719', '0719', 'Tượng đầu phi công đội mũ', 'https://kevindauto.com/products/sp-719.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'đầu', 'phi', 'công', 'đội', 'mũ']::text[]),
  ('sp-720', '0720', 'Giày thể thao trưng bày', 'https://kevindauto.com/products/sp-720.webp', 'phukien', 'Cửa hàng', array['phukien', 'cửa hàng', 'giày', 'thể', 'thao', 'trưng', 'bày']::text[]),
  ('sp-721', '0721', 'Vịt chibi đội mũ rộng vành', 'https://kevindauto.com/products/sp-721.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'vịt', 'đội', 'mũ', 'rộng', 'vành']::text[]),
  ('sp-722', '0722', 'Tượng đầu nam đầu trọc', 'https://kevindauto.com/products/sp-722.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'đầu', 'nam', 'trọc']::text[]),
  ('sp-723', '0723', 'Khay thực phẩm nướng', 'https://kevindauto.com/products/sp-723.webp', 'phukien', 'Ẩm thực', array['phukien', 'ẩm thực', 'khay', 'thực', 'phẩm', 'nướng']::text[]),
  ('sp-724', '0724', 'Tháp động vật trang trại', 'https://kevindauto.com/products/sp-724.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'tháp', 'động', 'vật', 'trang', 'trại']::text[]),
  ('sp-725', '0725', 'Người đàn ông gọi điện', 'https://kevindauto.com/products/sp-725.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'gọi', 'điện']::text[]),
  ('sp-726', '0726', 'Người đàn ông ngồi xổm', 'https://kevindauto.com/products/sp-726.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'xổm']::text[]),
  ('sp-727', '0727', 'Công nhân nghe điện thoại', 'https://kevindauto.com/products/sp-727.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'công', 'nhân', 'nghe', 'điện', 'thoại']::text[]),
  ('sp-728', '0728', 'Người đàn ông ngồi ghế', 'https://kevindauto.com/products/sp-728.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'ghế']::text[]),
  ('sp-729', '0729', 'Người đàn ông ngồi thẳng', 'https://kevindauto.com/products/sp-729.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'thẳng']::text[]),
  ('sp-730', '0730', 'Người đàn ông đứng chắp tay', 'https://kevindauto.com/products/sp-730.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'đứng', 'chắp', 'tay']::text[]),
  ('sp-731', '0731', 'Công nhân chống hông', 'https://kevindauto.com/products/sp-731.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'công', 'nhân', 'chống', 'hông']::text[]),
  ('sp-732', '0732', 'Công nhân cầm xẻng bên xô', 'https://kevindauto.com/products/sp-732.webp', 'duongpho', 'Lao động', array['duongpho', 'lao động', 'công', 'nhân', 'cầm', 'xẻng', 'bên', 'xô']::text[]),
  ('sp-733', '0733', 'Người đàn ông ngồi bậc thềm', 'https://kevindauto.com/products/sp-733.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'bậc', 'thềm']::text[]),
  ('sp-734', '0734', 'Người đàn ông cúi nhấc bao', 'https://kevindauto.com/products/sp-734.webp', 'duongpho', 'Lao động', array['duongpho', 'lao động', 'người', 'đàn', 'ông', 'cúi', 'nhấc', 'bao']::text[]),
  ('sp-735', '0735', 'Người đàn ông ngồi dưới đất', 'https://kevindauto.com/products/sp-735.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'dưới', 'đất']::text[]),
  ('sp-736', '0736', 'Cụ ông chống gậy ngồi ghế', 'https://kevindauto.com/products/sp-736.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'ông', 'chống', 'gậy', 'ngồi', 'ghế']::text[]),
  ('sp-737', '0737', 'Người đàn ông ngồi duỗi chân', 'https://kevindauto.com/products/sp-737.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'duỗi', 'chân']::text[]),
  ('sp-738', '0738', 'Công nhân đội mũ ngồi xổm', 'https://kevindauto.com/products/sp-738.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'công', 'nhân', 'đội', 'mũ', 'ngồi', 'xổm']::text[]),
  ('sp-739', '0739', 'Thợ sửa xe bên lốp lớn', 'https://kevindauto.com/products/sp-739.webp', 'duongpho', 'Gara', array['duongpho', 'gara', 'thợ', 'sửa', 'xe', 'bên', 'lốp', 'lớn']::text[]),
  ('sp-740', '0740', 'Vận động viên khúc côn cầu quỳ', 'https://kevindauto.com/products/sp-740.webp', 'thethao', 'Khúc côn cầu', array['thethao', 'khúc côn cầu', 'vận', 'động', 'viên', 'khúc', 'côn', 'cầu', 'quỳ']::text[]),
  ('sp-741', '0741', 'Thợ máy ngồi bên bánh xe', 'https://kevindauto.com/products/sp-741.webp', 'duongpho', 'Gara', array['duongpho', 'gara', 'thợ', 'máy', 'ngồi', 'bên', 'bánh', 'xe']::text[]),
  ('sp-742', '0742', 'Công nhân đứng nghỉ', 'https://kevindauto.com/products/sp-742.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'công', 'nhân', 'đứng', 'nghỉ']::text[]),
  ('sp-743', '0743', 'Chiến binh cầm khiên tròn', 'https://kevindauto.com/products/sp-743.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'chiến', 'binh', 'cầm', 'khiên', 'tròn']::text[]),
  ('sp-744', '0744', 'Nhân viên đồng phục chống hông', 'https://kevindauto.com/products/sp-744.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'nhân', 'viên', 'đồng', 'phục', 'chống', 'hông']::text[]),
  ('sp-745', '0745', 'Chàng trai đứng chắp tay', 'https://kevindauto.com/products/sp-745.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'đứng', 'chắp', 'tay']::text[]),
  ('sp-746', '0746', 'Người đàn ông tựa vai gọi điện', 'https://kevindauto.com/products/sp-746.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'tựa', 'vai', 'gọi', 'điện']::text[]),
  ('sp-747', '0747', 'Chiến binh anime tung quyền', 'https://kevindauto.com/products/sp-747.webp', 'nam', 'Anime', array['nam', 'anime', 'chiến', 'binh', 'tung', 'quyền']::text[]),
  ('sp-748', '0748', 'Chiến binh anime tóc dựng', 'https://kevindauto.com/products/sp-748.webp', 'nam', 'Anime', array['nam', 'anime', 'chiến', 'binh', 'tóc', 'dựng']::text[]),
  ('sp-749', '0749', 'Chàng trai ngồi bên ba lô', 'https://kevindauto.com/products/sp-749.webp', 'nam', 'Du lịch', array['nam', 'du lịch', 'chàng', 'trai', 'ngồi', 'bên', 'ba', 'lô']::text[]),
  ('sp-750', '0750', 'Vận động viên quỳ xuất phát', 'https://kevindauto.com/products/sp-750.webp', 'thethao', 'Chạy bộ', array['thethao', 'chạy bộ', 'vận', 'động', 'viên', 'quỳ', 'xuất', 'phát']::text[]),
  ('sp-751', '0751', 'Nhân viên cứu hộ ngồi thấp', 'https://kevindauto.com/products/sp-751.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'nhân', 'viên', 'cứu', 'hộ', 'ngồi', 'thấp']::text[]),
  ('sp-752', '0752', 'Nữ vận động viên nâng gối', 'https://kevindauto.com/products/sp-752.webp', 'thethao', 'Thể dục', array['thethao', 'thể dục', 'nữ', 'vận', 'động', 'viên', 'nâng', 'gối']::text[]),
  ('sp-753', '0753', 'Người đàn ông quỳ gối', 'https://kevindauto.com/products/sp-753.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'quỳ', 'gối']::text[]),
  ('sp-754', '0754', 'Nhân vật chibi mùa đông', 'https://kevindauto.com/products/sp-754.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhân', 'vật', 'mùa', 'đông']::text[]),
  ('sp-757', '0757', 'Chiến binh chibi cầm bia đá', 'https://kevindauto.com/products/sp-757.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'chiến', 'binh', 'chibi', 'cầm', 'bia', 'đá']::text[]),
  ('sp-758', '0758', 'Cây bonsai chậu vuông', 'https://kevindauto.com/products/sp-758.webp', 'phukien', 'Cây cảnh', array['phukien', 'cây cảnh', 'cây', 'bonsai', 'chậu', 'vuông']::text[]),
  ('sp-759', '0759', 'Chiến binh anime cầm kiếm', 'https://kevindauto.com/products/sp-759.webp', 'nam', 'Anime', array['nam', 'anime', 'chiến', 'binh', 'cầm', 'kiếm']::text[]),
  ('sp-760', '0760', 'Chiến binh anime tóc dựng', 'https://kevindauto.com/products/sp-760.webp', 'nam', 'Anime', array['nam', 'anime', 'chiến', 'binh', 'tóc', 'dựng']::text[]),
  ('sp-761', '0761', 'Nữ chiến binh anime tạo dáng', 'https://kevindauto.com/products/sp-761.webp', 'nu', 'Anime', array['nu', 'anime', 'nữ', 'chiến', 'binh', 'tạo', 'dáng']::text[]),
  ('sp-762', '0762', 'Linh vật rừng cầm ô', 'https://kevindauto.com/products/sp-762.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'rừng', 'cầm', 'ô']::text[]),
  ('sp-763', '0763', 'Cô bé anime ôm mặt', 'https://kevindauto.com/products/sp-763.webp', 'treem', 'Anime', array['treem', 'anime', 'cô', 'bé', 'ôm', 'mặt']::text[]),
  ('sp-764', '0764', 'Nữ vận động viên cầu lông', 'https://kevindauto.com/products/sp-764.webp', 'thethao', 'Cầu lông', array['thethao', 'cầu lông', 'nữ', 'vận', 'động', 'viên', 'cầu', 'lông']::text[]),
  ('sp-765', '0765', 'Gấu bông ngồi', 'https://kevindauto.com/products/sp-765.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'gấu', 'bông', 'ngồi']::text[]),
  ('sp-766', '0766', 'Linh vật ếch đứng thẳng', 'https://kevindauto.com/products/sp-766.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'ếch', 'đứng', 'thẳng']::text[]),
  ('sp-767', '0767', 'Cô gái nghiêng người tạo dáng', 'https://kevindauto.com/products/sp-767.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'cô', 'gái', 'nghiêng', 'người', 'tạo', 'dáng']::text[]),
  ('sp-768', '0768', 'Linh vật ếch nhỏ', 'https://kevindauto.com/products/sp-768.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'ếch', 'nhỏ']::text[]),
  ('sp-769', '0769', 'Linh vật ếch chào kiểu quân đội', 'https://kevindauto.com/products/sp-769.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'ếch', 'chào', 'kiểu', 'quân', 'đội']::text[]),
  ('sp-770', '0770', 'Linh vật gấu tròn', 'https://kevindauto.com/products/sp-770.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'gấu', 'tròn']::text[]),
  ('sp-771', '0771', 'Vận động viên chạy nước rút', 'https://kevindauto.com/products/sp-771.webp', 'thethao', 'Chạy bộ', array['thethao', 'chạy bộ', 'vận', 'động', 'viên', 'chạy', 'nước', 'rút']::text[]),
  ('sp-772', '0772', 'Cặp đôi ôm nhau đứng', 'https://kevindauto.com/products/sp-772.webp', 'giadinh', 'Cặp đôi', array['giadinh', 'cặp đôi', 'cặp', 'đôi', 'ôm', 'nhau', 'đứng']::text[]),
  ('sp-773', '0773', 'Chàng trai ngồi nghỉ', 'https://kevindauto.com/products/sp-773.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'ngồi', 'nghỉ']::text[]),
  ('sp-774', '0774', 'Nhân vật anime đeo ba lô', 'https://kevindauto.com/products/sp-774.webp', 'nam', 'Anime', array['nam', 'anime', 'nhân', 'vật', 'đeo', 'ba', 'lô']::text[]),
  ('sp-775', '0775', 'Vận động viên chạy bộ', 'https://kevindauto.com/products/sp-775.webp', 'thethao', 'Chạy bộ', array['thethao', 'chạy bộ', 'vận', 'động', 'viên', 'chạy', 'bộ']::text[]),
  ('sp-776', '0776', 'Người đàn ông dáng đậm chống hông', 'https://kevindauto.com/products/sp-776.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'dáng', 'đậm', 'chống', 'hông']::text[]),
  ('sp-777', '0777', 'Nông dân chibi xách giỏ', 'https://kevindauto.com/products/sp-777.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nông', 'dân', 'xách', 'giỏ']::text[]),
  ('sp-778', '0778', 'Vận động viên quỳ giơ nắm tay', 'https://kevindauto.com/products/sp-778.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'vận', 'động', 'viên', 'quỳ', 'giơ', 'nắm', 'tay']::text[]),
  ('sp-779', '0779', 'Chiến binh anime ngồi tấn', 'https://kevindauto.com/products/sp-779.webp', 'nam', 'Anime', array['nam', 'anime', 'chiến', 'binh', 'ngồi', 'tấn']::text[]),
  ('sp-780', '0780', 'Võ sĩ tung cú đấm', 'https://kevindauto.com/products/sp-780.webp', 'thethao', 'Quyền anh', array['thethao', 'quyền anh', 'võ', 'sĩ', 'tung', 'cú', 'đấm']::text[]),
  ('sp-781', '0781', 'Đô vật sumo vào thế', 'https://kevindauto.com/products/sp-781.webp', 'thethao', 'Sumo', array['thethao', 'sumo', 'đô', 'vật', 'vào', 'thế']::text[]),
  ('sp-782', '0782', 'Chàng trai mặc đồ thể thao', 'https://kevindauto.com/products/sp-782.webp', 'nam', 'Năng động', array['nam', 'năng động', 'chàng', 'trai', 'mặc', 'đồ', 'thể', 'thao']::text[]),
  ('sp-783', '0783', 'Binh sĩ mang trang bị chiến thuật', 'https://kevindauto.com/products/sp-783.webp', 'nam', 'Chiến thuật', array['nam', 'chiến thuật', 'binh', 'sĩ', 'mang', 'trang', 'bị', 'chiến', 'thuật']::text[]),
  ('sp-784', '0784', 'Phi hành gia chibi mang ba lô', 'https://kevindauto.com/products/sp-784.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'phi', 'hành', 'gia', 'mang', 'ba', 'lô']::text[]),
  ('sp-785', '0785', 'Chàng trai áo khoác đứng nghiêng', 'https://kevindauto.com/products/sp-785.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'nghiêng']::text[]),
  ('sp-786', '0786', 'Bác sĩ đeo kính đứng thẳng', 'https://kevindauto.com/products/sp-786.webp', 'nam', 'Nghề nghiệp', array['nam', 'nghề nghiệp', 'bác', 'sĩ', 'đeo', 'kính', 'đứng', 'thẳng']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
