-- Lo 006: san pham 0787 den 0866
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-787', '0787', 'Người đàn ông ngồi khoanh tay', 'https://kevindauto.com/products/sp-787.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'khoanh', 'tay']::text[]),
  ('sp-788', '0788', 'Vận động viên trượt tuyết', 'https://kevindauto.com/products/sp-788.webp', 'thethao', 'Thể thao mùa đông', array['thethao', 'thể thao mùa đông', 'vận', 'động', 'viên', 'trượt', 'tuyết']::text[]),
  ('sp-789', '0789', 'Chàng trai vừa đi vừa uống nước', 'https://kevindauto.com/products/sp-789.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'vừa', 'đi', 'uống', 'nước']::text[]),
  ('sp-790', '0790', 'Vận động viên kéo giãn vai', 'https://kevindauto.com/products/sp-790.webp', 'thethao', 'Thể dục', array['thethao', 'thể dục', 'vận', 'động', 'viên', 'kéo', 'giãn', 'vai']::text[]),
  ('sp-791', '0791', 'Võ sư tung chưởng', 'https://kevindauto.com/products/sp-791.webp', 'thethao', 'Võ thuật', array['thethao', 'võ thuật', 'võ', 'sư', 'tung', 'chưởng']::text[]),
  ('sp-792', '0792', 'Nữ kiếm sĩ giả tưởng', 'https://kevindauto.com/products/sp-792.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'kiếm', 'sĩ', 'giả', 'tưởng']::text[]),
  ('sp-793', '0793', 'Nữ chiến binh áo choàng', 'https://kevindauto.com/products/sp-793.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'chiến', 'binh', 'áo', 'choàng']::text[]),
  ('sp-794', '0794', 'Quý ông cầm điện thoại suy tư', 'https://kevindauto.com/products/sp-794.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'cầm', 'điện', 'thoại', 'suy', 'tư']::text[]),
  ('sp-795', '0795', 'Võ sĩ quyền anh thủ thế', 'https://kevindauto.com/products/sp-795.webp', 'thethao', 'Quyền anh', array['thethao', 'quyền anh', 'võ', 'sĩ', 'quyền', 'anh', 'thủ', 'thế']::text[]),
  ('sp-796', '0796', 'Người đàn ông ngồi ghế chống gậy', 'https://kevindauto.com/products/sp-796.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'người', 'đàn', 'ông', 'ngồi', 'ghế', 'chống', 'gậy']::text[]),
  ('sp-797', '0797', 'Người đàn ông giơ tay trò chuyện', 'https://kevindauto.com/products/sp-797.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'giơ', 'tay', 'trò', 'chuyện']::text[]),
  ('sp-798', '0798', 'Vận động viên khom người khởi động', 'https://kevindauto.com/products/sp-798.webp', 'thethao', 'Thể dục', array['thethao', 'thể dục', 'vận', 'động', 'viên', 'khom', 'người', 'khởi']::text[]),
  ('sp-799', '0799', 'Người đàn ông chỉ tay lên cao', 'https://kevindauto.com/products/sp-799.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'chỉ', 'tay', 'lên', 'cao']::text[]),
  ('sp-800', '0800', 'Bộ nghệ sĩ biểu diễn nhiều tư thế', 'https://kevindauto.com/products/sp-800.webp', 'nam', 'Nghệ thuật', array['nam', 'nghệ thuật', 'bộ', 'nghệ', 'sĩ', 'biểu', 'diễn', 'nhiều', 'tư', 'thế']::text[]),
  ('sp-801', '0801', 'Người đàn ông gọi điện', 'https://kevindauto.com/products/sp-801.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'gọi', 'điện']::text[]),
  ('sp-802', '0802', 'Chàng trai áo khoác đứng thẳng', 'https://kevindauto.com/products/sp-802.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'thẳng']::text[]),
  ('sp-803', '0803', 'Chàng trai áo khoác bỏ tay túi', 'https://kevindauto.com/products/sp-803.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'bỏ', 'tay', 'túi']::text[]),
  ('sp-804', '0804', 'Chàng trai đội mũ ngồi ghế', 'https://kevindauto.com/products/sp-804.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'đội', 'mũ', 'ngồi', 'ghế']::text[]),
  ('sp-805', '0805', 'Chiến binh anime lái xe nhỏ', 'https://kevindauto.com/products/sp-805.webp', 'xe', 'Anime', array['xe', 'anime', 'chiến', 'binh', 'lái', 'nhỏ']::text[]),
  ('sp-806', '0806', 'Chàng trai áo thun bước đi', 'https://kevindauto.com/products/sp-806.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'áo', 'thun', 'bước', 'đi']::text[]),
  ('sp-807', '0807', 'Cổ động viên giơ khăn', 'https://kevindauto.com/products/sp-807.webp', 'thethao', 'Cổ động', array['thethao', 'cổ động', 'cổ', 'động', 'viên', 'giơ', 'khăn']::text[]),
  ('sp-808', '0808', 'Người đàn ông ngồi chắp tay', 'https://kevindauto.com/products/sp-808.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'chắp', 'tay']::text[]),
  ('sp-809', '0809', 'Xe thể thao mui trần cổ điển', 'https://kevindauto.com/products/sp-809.webp', 'xe', 'Ô tô', array['xe', 'ô tô', 'thể', 'thao', 'mui', 'trần', 'cổ', 'điển']::text[]),
  ('sp-810', '0810', 'Siêu xe mui trần hiện đại', 'https://kevindauto.com/products/sp-810.webp', 'xe', 'Ô tô', array['xe', 'ô tô', 'siêu', 'mui', 'trần', 'hiện', 'đại']::text[]),
  ('sp-811', '0811', 'Ghế đẩu cao', 'https://kevindauto.com/products/sp-811.webp', 'phukien', 'Nội thất', array['phukien', 'nội thất', 'ghế', 'đẩu', 'cao']::text[]),
  ('sp-812', '0812', 'Người đàn ông ngồi ghế thấp', 'https://kevindauto.com/products/sp-812.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'ghế', 'thấp']::text[]),
  ('sp-813', '0813', 'Khung gầm xe chi tiết', 'https://kevindauto.com/products/sp-813.webp', 'xe', 'Phụ tùng ô tô', array['xe', 'phụ tùng ô tô', 'khung', 'gầm', 'chi', 'tiết']::text[]),
  ('sp-814', '0814', 'Linh vật đội mũ bảo hiểm', 'https://kevindauto.com/products/sp-814.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'linh', 'vật', 'đội', 'mũ', 'bảo', 'hiểm']::text[]),
  ('sp-815', '0815', 'Lốp ô tô trưng bày', 'https://kevindauto.com/products/sp-815.webp', 'xe', 'Phụ tùng ô tô', array['xe', 'phụ tùng ô tô', 'lốp', 'ô', 'tô', 'trưng', 'bày']::text[]),
  ('sp-816', '0816', 'Can nhiên liệu', 'https://kevindauto.com/products/sp-816.webp', 'phukien', 'Gara', array['phukien', 'gara', 'can', 'nhiên', 'liệu']::text[]),
  ('sp-817', '0817', 'Mèo chibi đeo nơ', 'https://kevindauto.com/products/sp-817.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'mèo', 'đeo', 'nơ']::text[]),
  ('sp-818', '0818', 'Phi hành gia cắm cờ', 'https://kevindauto.com/products/sp-818.webp', 'nam', 'Sci-fi', array['nam', 'sci-fi', 'phi', 'hành', 'gia', 'cắm', 'cờ']::text[]),
  ('sp-819', '0819', 'Mô tô phân khối lớn', 'https://kevindauto.com/products/sp-819.webp', 'xe', 'Mô tô', array['xe', 'mô tô', 'mô', 'tô', 'phân', 'khối', 'lớn']::text[]),
  ('sp-820', '0820', 'Tủ dụng cụ gara', 'https://kevindauto.com/products/sp-820.webp', 'phukien', 'Gara', array['phukien', 'gara', 'tủ', 'dụng', 'cụ']::text[]),
  ('sp-821', '0821', 'Cô gái đứng gọi điện', 'https://kevindauto.com/products/sp-821.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'đứng', 'gọi', 'điện']::text[]),
  ('sp-822', '0822', 'Nữ công sở đứng thẳng', 'https://kevindauto.com/products/sp-822.webp', 'nu', 'Công sở', array['nu', 'công sở', 'nữ', 'công', 'sở', 'đứng', 'thẳng']::text[]),
  ('sp-823', '0823', 'Quý cô áo khoác cầm túi', 'https://kevindauto.com/products/sp-823.webp', 'nu', 'Thanh lịch', array['nu', 'thanh lịch', 'quý', 'cô', 'áo', 'khoác', 'cầm', 'túi']::text[]),
  ('sp-824', '0824', 'Cô gái hoodie đứng thư giãn', 'https://kevindauto.com/products/sp-824.webp', 'nu', 'Streetwear', array['nu', 'streetwear', 'cô', 'gái', 'hoodie', 'đứng', 'thư', 'giãn']::text[]),
  ('sp-825', '0825', 'Nữ chiến binh mặc bodysuit', 'https://kevindauto.com/products/sp-825.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'chiến', 'binh', 'mặc', 'bodysuit']::text[]),
  ('sp-826', '0826', 'Cô gái đeo túi bước đi', 'https://kevindauto.com/products/sp-826.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'đeo', 'túi', 'bước', 'đi']::text[]),
  ('sp-827', '0827', 'Cô gái áo khoác chống hông', 'https://kevindauto.com/products/sp-827.webp', 'nu', 'Streetwear', array['nu', 'streetwear', 'cô', 'gái', 'áo', 'khoác', 'chống', 'hông']::text[]),
  ('sp-828', '0828', 'Cô gái đội mũ đeo túi', 'https://kevindauto.com/products/sp-828.webp', 'nu', 'Streetwear', array['nu', 'streetwear', 'cô', 'gái', 'đội', 'mũ', 'đeo', 'túi']::text[]),
  ('sp-829', '0829', 'Chàng trai đeo túi đứng nghiêng', 'https://kevindauto.com/products/sp-829.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'đeo', 'túi', 'đứng', 'nghiêng']::text[]),
  ('sp-830', '0830', 'Người đàn ông mặc vest ngồi ghế', 'https://kevindauto.com/products/sp-830.webp', 'nam', 'Công sở', array['nam', 'công sở', 'người', 'đàn', 'ông', 'mặc', 'vest', 'ngồi', 'ghế']::text[]),
  ('sp-831', '0831', 'Chàng trai đeo túi chéo', 'https://kevindauto.com/products/sp-831.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'đeo', 'túi', 'chéo']::text[]),
  ('sp-832', '0832', 'Nữ chiến binh ngắm súng trường', 'https://kevindauto.com/products/sp-832.webp', 'nu', 'Chiến thuật', array['nu', 'chiến thuật', 'nữ', 'chiến', 'binh', 'ngắm', 'súng', 'trường']::text[]),
  ('sp-833', '0833', 'Chàng trai ngồi ghế thư giãn', 'https://kevindauto.com/products/sp-833.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'ngồi', 'ghế', 'thư', 'giãn']::text[]),
  ('sp-834', '0834', 'Chàng trai mang túi vai', 'https://kevindauto.com/products/sp-834.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'mang', 'túi', 'vai']::text[]),
  ('sp-835', '0835', 'Chàng trai áo thun đứng thẳng', 'https://kevindauto.com/products/sp-835.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'áo', 'thun', 'đứng', 'thẳng']::text[]),
  ('sp-836', '0836', 'Quý ông áo khoác bỏ tay túi', 'https://kevindauto.com/products/sp-836.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'áo', 'khoác', 'bỏ', 'tay', 'túi']::text[]),
  ('sp-837', '0837', 'Quý ông sơ mi đứng thẳng', 'https://kevindauto.com/products/sp-837.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'sơ', 'mi', 'đứng', 'thẳng']::text[]),
  ('sp-838', '0838', 'Nữ vận động viên chống hông', 'https://kevindauto.com/products/sp-838.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'nữ', 'vận', 'động', 'viên', 'chống', 'hông']::text[]),
  ('sp-839', '0839', 'Robot chiến binh cầm kiếm', 'https://kevindauto.com/products/sp-839.webp', 'dongvat', 'Sci-fi', array['dongvat', 'sci-fi', 'robot', 'chiến', 'binh', 'cầm', 'kiếm']::text[]),
  ('sp-840', '0840', 'Quái thú chiến binh', 'https://kevindauto.com/products/sp-840.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'quái', 'thú', 'chiến', 'binh']::text[]),
  ('sp-841', '0841', 'Nữ chiến binh bodysuit đứng thẳng', 'https://kevindauto.com/products/sp-841.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'chiến', 'binh', 'bodysuit', 'đứng', 'thẳng']::text[]),
  ('sp-842', '0842', 'Pháp sư áo choàng thi triển phép', 'https://kevindauto.com/products/sp-842.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'pháp', 'sư', 'áo', 'choàng', 'thi', 'triển', 'phép']::text[]),
  ('sp-843', '0843', 'Kiếm sĩ áo choàng cầm trường kiếm', 'https://kevindauto.com/products/sp-843.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'kiếm', 'sĩ', 'áo', 'choàng', 'cầm', 'trường']::text[]),
  ('sp-844', '0844', 'Võ sĩ giơ nắm tay', 'https://kevindauto.com/products/sp-844.webp', 'thethao', 'Quyền anh', array['thethao', 'quyền anh', 'võ', 'sĩ', 'giơ', 'nắm', 'tay']::text[]),
  ('sp-845', '0845', 'Chàng trai áo khoác chống hông', 'https://kevindauto.com/products/sp-845.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'chống', 'hông']::text[]),
  ('sp-846', '0846', 'Người đàn ông áo khoác dài', 'https://kevindauto.com/products/sp-846.webp', 'nam', 'Mùa đông', array['nam', 'mùa đông', 'người', 'đàn', 'ông', 'áo', 'khoác', 'dài']::text[]),
  ('sp-847', '0847', 'Võ sĩ quyền anh thủ thế', 'https://kevindauto.com/products/sp-847.webp', 'thethao', 'Quyền anh', array['thethao', 'quyền anh', 'võ', 'sĩ', 'quyền', 'anh', 'thủ', 'thế']::text[]),
  ('sp-848', '0848', 'Vận động viên ôm bóng', 'https://kevindauto.com/products/sp-848.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'vận', 'động', 'viên', 'ôm', 'bóng']::text[]),
  ('sp-849', '0849', 'Người đàn ông lớn tuổi đứng thư giãn', 'https://kevindauto.com/products/sp-849.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'người', 'đàn', 'ông', 'lớn', 'tuổi', 'đứng', 'thư', 'giãn']::text[]),
  ('sp-850', '0850', 'Chàng trai áo sơ mi đứng thẳng', 'https://kevindauto.com/products/sp-850.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'áo', 'sơ', 'mi', 'đứng', 'thẳng']::text[]),
  ('sp-851', '0851', 'Pháp sư trùm đầu cầm trượng', 'https://kevindauto.com/products/sp-851.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'pháp', 'sư', 'trùm', 'đầu', 'cầm', 'trượng']::text[]),
  ('sp-852', '0852', 'Cầu thủ nâng bóng qua đầu', 'https://kevindauto.com/products/sp-852.webp', 'thethao', 'Bóng rổ', array['thethao', 'bóng rổ', 'cầu', 'thủ', 'nâng', 'bóng', 'qua', 'đầu']::text[]),
  ('sp-853', '0853', 'Cầu thủ giữ bóng trước người', 'https://kevindauto.com/products/sp-853.webp', 'thethao', 'Bóng rổ', array['thethao', 'bóng rổ', 'cầu', 'thủ', 'giữ', 'bóng', 'trước', 'người']::text[]),
  ('sp-854', '0854', 'Vận động viên giơ tay ra hiệu', 'https://kevindauto.com/products/sp-854.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'vận', 'động', 'viên', 'giơ', 'tay', 'ra', 'hiệu']::text[]),
  ('sp-855', '0855', 'Chàng trai khoanh tay trước ngực', 'https://kevindauto.com/products/sp-855.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'khoanh', 'tay', 'trước', 'ngực']::text[]),
  ('sp-856', '0856', 'Quý ông giơ điện thoại', 'https://kevindauto.com/products/sp-856.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'giơ', 'điện', 'thoại']::text[]),
  ('sp-857', '0857', 'Ăng ten chảo vệ tinh', 'https://kevindauto.com/products/sp-857.webp', 'phukien', 'Thiết bị', array['phukien', 'thiết bị', 'ăng', 'ten', 'chảo', 'vệ', 'tinh']::text[]),
  ('sp-858', '0858', 'Ống thông gió góc vuông', 'https://kevindauto.com/products/sp-858.webp', 'phukien', 'Công nghiệp', array['phukien', 'công nghiệp', 'ống', 'thông', 'gió', 'góc', 'vuông']::text[]),
  ('sp-859', '0859', 'Mèo đứng bằng hai chân', 'https://kevindauto.com/products/sp-859.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'mèo', 'đứng', 'bằng', 'hai', 'chân']::text[]),
  ('sp-860', '0860', 'Xe thể thao mui trần', 'https://kevindauto.com/products/sp-860.webp', 'xe', 'Ô tô', array['xe', 'ô tô', 'thể', 'thao', 'mui', 'trần']::text[]),
  ('sp-861', '0861', 'Người đàn ông ngồi xổm', 'https://kevindauto.com/products/sp-861.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'xổm']::text[]),
  ('sp-862', '0862', 'Khỉ đứng quan sát', 'https://kevindauto.com/products/sp-862.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'khỉ', 'đứng', 'quan', 'sát']::text[]),
  ('sp-863', '0863', 'Nhạc công mang nhạc cụ', 'https://kevindauto.com/products/sp-863.webp', 'nam', 'Nghệ thuật', array['nam', 'nghệ thuật', 'nhạc', 'công', 'mang', 'cụ']::text[]),
  ('sp-864', '0864', 'Sư tử con nằm rình', 'https://kevindauto.com/products/sp-864.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'sư', 'tử', 'con', 'nằm', 'rình']::text[]),
  ('sp-865', '0865', 'Siêu xe mui trần khí động học', 'https://kevindauto.com/products/sp-865.webp', 'xe', 'Ô tô', array['xe', 'ô tô', 'siêu', 'mui', 'trần', 'khí', 'động', 'học']::text[]),
  ('sp-866', '0866', 'Xe mô tô địa hình', 'https://kevindauto.com/products/sp-866.webp', 'xe', 'Mô tô', array['xe', 'mô tô', 'mô', 'tô', 'địa', 'hình']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
