-- Lo 007: san pham 0867 den 2246
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-867', '0867', 'Cậu bé chibi đội mũ len', 'https://kevindauto.com/products/sp-867.webp', 'treem', 'Chibi', array['treem', 'chibi', 'cậu', 'bé', 'đội', 'mũ', 'len']::text[]),
  ('sp-868', '0868', 'Tượng bán thân quý ông', 'https://kevindauto.com/products/sp-868.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'bán', 'thân', 'quý', 'ông']::text[]),
  ('sp-869', '0869', 'Cô gái giơ tay chào', 'https://kevindauto.com/products/sp-869.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'giơ', 'tay', 'chào']::text[]),
  ('sp-870', '0870', 'Cô gái chào kiểu quân đội', 'https://kevindauto.com/products/sp-870.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'chào', 'kiểu', 'quân', 'đội']::text[]),
  ('sp-871', '0871', 'Nữ công sở khoanh tay', 'https://kevindauto.com/products/sp-871.webp', 'nu', 'Công sở', array['nu', 'công sở', 'nữ', 'công', 'sở', 'khoanh', 'tay']::text[]),
  ('sp-872', '0872', 'Cô gái ngồi tạo dáng nghỉ dưỡng', 'https://kevindauto.com/products/sp-872.webp', 'nu', 'Nghỉ dưỡng', array['nu', 'nghỉ dưỡng', 'cô', 'gái', 'ngồi', 'tạo', 'dáng', 'nghỉ', 'dưỡng']::text[]),
  ('sp-873', '0873', 'Nữ vận động viên giữ bóng', 'https://kevindauto.com/products/sp-873.webp', 'thethao', 'Thể thao', array['thethao', 'thể thao', 'nữ', 'vận', 'động', 'viên', 'giữ', 'bóng']::text[]),
  ('sp-874', '0874', 'Cô gái mặc váy đứng thẳng', 'https://kevindauto.com/products/sp-874.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'cô', 'gái', 'mặc', 'váy', 'đứng', 'thẳng']::text[]),
  ('sp-875', '0875', 'Bạch tuộc hoạt hình', 'https://kevindauto.com/products/sp-875.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'bạch', 'tuộc', 'hoạt', 'hình']::text[]),
  ('sp-876', '0876', 'Cô gái trượt patin', 'https://kevindauto.com/products/sp-876.webp', 'thethao', 'Thể thao đường phố', array['thethao', 'thể thao đường phố', 'cô', 'gái', 'trượt', 'patin']::text[]),
  ('sp-877', '0877', 'Nữ cầu thủ quỳ giữ bóng', 'https://kevindauto.com/products/sp-877.webp', 'thethao', 'Bóng rổ', array['thethao', 'bóng rổ', 'nữ', 'cầu', 'thủ', 'quỳ', 'giữ', 'bóng']::text[]),
  ('sp-878', '0878', 'Nữ vận động viên thể hình', 'https://kevindauto.com/products/sp-878.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'nữ', 'vận', 'động', 'viên', 'thể', 'hình']::text[]),
  ('sp-879', '0879', 'Chàng trai áo khoác đứng thẳng', 'https://kevindauto.com/products/sp-879.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'thẳng']::text[]),
  ('sp-880', '0880', 'Quái vật cơ bắp', 'https://kevindauto.com/products/sp-880.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'quái', 'vật', 'cơ', 'bắp']::text[]),
  ('sp-881', '0881', 'Chàng trai giơ điện thoại quay phim', 'https://kevindauto.com/products/sp-881.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'giơ', 'điện', 'thoại', 'quay', 'phim']::text[]),
  ('sp-882', '0882', 'Người đàn ông đeo túi giơ tay', 'https://kevindauto.com/products/sp-882.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'đeo', 'túi', 'giơ', 'tay']::text[]),
  ('sp-883', '0883', 'Võ sĩ giơ hai găng tay', 'https://kevindauto.com/products/sp-883.webp', 'thethao', 'Quyền anh', array['thethao', 'quyền anh', 'võ', 'sĩ', 'giơ', 'hai', 'găng', 'tay']::text[]),
  ('sp-884', '0884', 'Lực sĩ khoe cơ tay', 'https://kevindauto.com/products/sp-884.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'lực', 'sĩ', 'khoe', 'cơ', 'tay']::text[]),
  ('sp-885', '0885', 'Người đàn ông ngồi xổm thư giãn', 'https://kevindauto.com/products/sp-885.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'ngồi', 'xổm', 'thư', 'giãn']::text[]),
  ('sp-886', '0886', 'Nhiếp ảnh gia đang tác nghiệp', 'https://kevindauto.com/products/sp-886.webp', 'nam', 'Nhiếp ảnh', array['nam', 'nhiếp ảnh', 'nhiếp', 'ảnh', 'gia', 'đang', 'tác', 'nghiệp']::text[]),
  ('sp-887', '0887', 'Chàng trai đứng chắp tay', 'https://kevindauto.com/products/sp-887.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'đứng', 'chắp', 'tay']::text[]),
  ('sp-888', '0888', 'Người đàn ông khoanh tay', 'https://kevindauto.com/products/sp-888.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'người', 'đàn', 'ông', 'khoanh', 'tay']::text[]),
  ('sp-889', '0889', 'Quý ông ngồi ghế', 'https://kevindauto.com/products/sp-889.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'ngồi', 'ghế']::text[]),
  ('sp-890', '0890', 'Chàng trai áo khoác bỏ tay túi', 'https://kevindauto.com/products/sp-890.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'bỏ', 'tay', 'túi']::text[]),
  ('sp-891', '0891', 'Cậu bé áo khoác đứng thẳng', 'https://kevindauto.com/products/sp-891.webp', 'treem', 'Đời thường', array['treem', 'đời thường', 'cậu', 'bé', 'áo', 'khoác', 'đứng', 'thẳng']::text[]),
  ('sp-892', '0892', 'Công nhân cầm cào', 'https://kevindauto.com/products/sp-892.webp', 'duongpho', 'Lao động', array['duongpho', 'lao động', 'công', 'nhân', 'cầm', 'cào']::text[]),
  ('sp-893', '0893', 'Xe van chở hàng', 'https://kevindauto.com/products/sp-893.webp', 'xe', 'Ô tô', array['xe', 'ô tô', 'van', 'chở', 'hàng']::text[]),
  ('sp-894', '0894', 'Mèo mập nằm nghỉ', 'https://kevindauto.com/products/sp-894.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'mèo', 'mập', 'nằm', 'nghỉ']::text[]),
  ('sp-895', '0895', 'Tượng bán thân nam trung niên', 'https://kevindauto.com/products/sp-895.webp', 'phukien', 'Tượng nghệ thuật', array['phukien', 'tượng nghệ thuật', 'tượng', 'bán', 'thân', 'nam', 'trung', 'niên']::text[]),
  ('sp-896', '0896', 'Động cơ ô tô chi tiết', 'https://kevindauto.com/products/sp-896.webp', 'xe', 'Phụ tùng ô tô', array['xe', 'phụ tùng ô tô', 'động', 'cơ', 'ô', 'tô', 'chi', 'tiết']::text[]),
  ('sp-897', '0897', 'Cô bé chibi đeo kính', 'https://kevindauto.com/products/sp-897.webp', 'treem', 'Chibi', array['treem', 'chibi', 'cô', 'bé', 'đeo', 'kính']::text[]),
  ('sp-898', '0898', 'Cô bé chibi tạo dáng chiến đấu', 'https://kevindauto.com/products/sp-898.webp', 'treem', 'Chibi', array['treem', 'chibi', 'cô', 'bé', 'tạo', 'dáng', 'chiến', 'đấu']::text[]),
  ('sp-899', '0899', 'Cậu bé chibi chỉ tay lên đầu', 'https://kevindauto.com/products/sp-899.webp', 'treem', 'Chibi', array['treem', 'chibi', 'cậu', 'bé', 'chỉ', 'tay', 'lên', 'đầu']::text[]),
  ('sp-2200', '2200', 'Tay đua BMX biểu diễn', 'https://kevindauto.com/products/sp-2200.webp', 'thethao', 'Xe đạp BMX', array['thethao', 'xe đạp bmx', 'tay', 'đua', 'bmx', 'biểu', 'diễn']::text[]),
  ('sp-2201', '2201', 'Chàng trai đầu túi giấy giơ tay', 'https://kevindauto.com/products/sp-2201.webp', 'nam', 'Độc đáo', array['nam', 'độc đáo', 'chàng', 'trai', 'đầu', 'túi', 'giấy', 'giơ', 'tay']::text[]),
  ('sp-2202', '2202', 'Rương kho báu chạm khắc', 'https://kevindauto.com/products/sp-2202.webp', 'phukien', 'Fantasy', array['phukien', 'fantasy', 'rương', 'kho', 'báu', 'chạm', 'khắc']::text[]),
  ('sp-2203', '2203', 'Thùng rác đường phố', 'https://kevindauto.com/products/sp-2203.webp', 'phukien', 'Diorama đường phố', array['phukien', 'diorama đường phố', 'thùng', 'rác', 'đường', 'phố']::text[]),
  ('sp-2204', '2204', 'Bình gốm cắm cành hoa', 'https://kevindauto.com/products/sp-2204.webp', 'phukien', 'Nội thất', array['phukien', 'nội thất', 'bình', 'gốm', 'cắm', 'cành', 'hoa']::text[]),
  ('sp-2205', '2205', 'Người phụ nữ ôm giỏ hàng', 'https://kevindauto.com/products/sp-2205.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'người', 'phụ', 'nữ', 'ôm', 'giỏ', 'hàng']::text[]),
  ('sp-2206', '2206', 'Quý cô váy dài cầm túi', 'https://kevindauto.com/products/sp-2206.webp', 'nu', 'Thanh lịch', array['nu', 'thanh lịch', 'quý', 'cô', 'váy', 'dài', 'cầm', 'túi']::text[]),
  ('sp-2207', '2207', 'Người đàn ông xúc dọn đường', 'https://kevindauto.com/products/sp-2207.webp', 'duongpho', 'Lao động', array['duongpho', 'lao động', 'người', 'đàn', 'ông', 'xúc', 'dọn', 'đường']::text[]),
  ('sp-2208', '2208', 'Chậu hoa hướng dương', 'https://kevindauto.com/products/sp-2208.webp', 'phukien', 'Cây cảnh', array['phukien', 'cây cảnh', 'chậu', 'hoa', 'hướng', 'dương']::text[]),
  ('sp-2209', '2209', 'Cụ ông ngồi cầm súng săn', 'https://kevindauto.com/products/sp-2209.webp', 'caotuoi', 'Dã ngoại', array['caotuoi', 'dã ngoại', 'cụ', 'ông', 'ngồi', 'cầm', 'súng', 'săn']::text[]),
  ('sp-2210', '2210', 'Cô gái váy ngắn gọi điện', 'https://kevindauto.com/products/sp-2210.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'cô', 'gái', 'váy', 'ngắn', 'gọi', 'điện']::text[]),
  ('sp-2211', '2211', 'Nữ chiến binh mặc giáp', 'https://kevindauto.com/products/sp-2211.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'chiến', 'binh', 'mặc', 'giáp']::text[]),
  ('sp-2212', '2212', 'Chàng trai dang hai tay', 'https://kevindauto.com/products/sp-2212.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'dang', 'hai', 'tay']::text[]),
  ('sp-2213', '2213', 'Quý ông vest bỏ tay túi', 'https://kevindauto.com/products/sp-2213.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'vest', 'bỏ', 'tay', 'túi']::text[]),
  ('sp-2214', '2214', 'Người đàn ông lớn tuổi đứng thẳng', 'https://kevindauto.com/products/sp-2214.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'người', 'đàn', 'ông', 'lớn', 'tuổi', 'đứng', 'thẳng']::text[]),
  ('sp-2215', '2215', 'Nữ công sở cầm máy tính bảng', 'https://kevindauto.com/products/sp-2215.webp', 'nu', 'Công sở', array['nu', 'công sở', 'nữ', 'công', 'sở', 'cầm', 'máy', 'tính', 'bảng']::text[]),
  ('sp-2216', '2216', 'Tượng đầu sói chạm khắc', 'https://kevindauto.com/products/sp-2216.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'tượng', 'đầu', 'sói', 'chạm', 'khắc']::text[]),
  ('sp-2217', '2217', 'Tượng đầu lâu cơ khí', 'https://kevindauto.com/products/sp-2217.webp', 'phukien', 'Sci-fi', array['phukien', 'sci-fi', 'tượng', 'đầu', 'lâu', 'cơ', 'khí']::text[]),
  ('sp-2218', '2218', 'Nữ kiếm sĩ chống kiếm', 'https://kevindauto.com/products/sp-2218.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'kiếm', 'sĩ', 'chống']::text[]),
  ('sp-2219', '2219', 'Nhiếp ảnh gia quỳ chụp hình', 'https://kevindauto.com/products/sp-2219.webp', 'nam', 'Nhiếp ảnh', array['nam', 'nhiếp ảnh', 'nhiếp', 'ảnh', 'gia', 'quỳ', 'chụp', 'hình']::text[]),
  ('sp-2220', '2220', 'Vị vua già chống gậy', 'https://kevindauto.com/products/sp-2220.webp', 'caotuoi', 'Hoàng gia', array['caotuoi', 'hoàng gia', 'vị', 'vua', 'già', 'chống', 'gậy']::text[]),
  ('sp-2221', '2221', 'Chiến binh lùn mặc giáp', 'https://kevindauto.com/products/sp-2221.webp', 'dongvat', 'Fantasy', array['dongvat', 'fantasy', 'chiến', 'binh', 'lùn', 'mặc', 'giáp']::text[]),
  ('sp-2222', '2222', 'Chiến binh cầm rìu lớn', 'https://kevindauto.com/products/sp-2222.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'chiến', 'binh', 'cầm', 'rìu', 'lớn']::text[]),
  ('sp-2223', '2223', 'Kỵ sĩ cưỡi ngựa', 'https://kevindauto.com/products/sp-2223.webp', 'xe', 'Kỵ binh', array['xe', 'kỵ binh', 'kỵ', 'sĩ', 'cưỡi', 'ngựa']::text[]),
  ('sp-2224', '2224', 'Quý cô váy dài cầm vali', 'https://kevindauto.com/products/sp-2224.webp', 'nu', 'Du lịch', array['nu', 'du lịch', 'quý', 'cô', 'váy', 'dài', 'cầm', 'vali']::text[]),
  ('sp-2225', '2225', 'Chàng trai ngồi bắt chéo chân', 'https://kevindauto.com/products/sp-2225.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'ngồi', 'bắt', 'chéo', 'chân']::text[]),
  ('sp-2226', '2226', 'Chàng trai hoodie xem điện thoại', 'https://kevindauto.com/products/sp-2226.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'hoodie', 'xem', 'điện', 'thoại']::text[]),
  ('sp-2227', '2227', 'Quý ông áo khoác suy tư', 'https://kevindauto.com/products/sp-2227.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'áo', 'khoác', 'suy', 'tư']::text[]),
  ('sp-2228', '2228', 'Cụ ông áo khoác dài', 'https://kevindauto.com/products/sp-2228.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'ông', 'áo', 'khoác', 'dài']::text[]),
  ('sp-2229', '2229', 'Chàng trai áo khoác đứng thẳng', 'https://kevindauto.com/products/sp-2229.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'thẳng']::text[]),
  ('sp-2230', '2230', 'Quý ông công sở chắp tay', 'https://kevindauto.com/products/sp-2230.webp', 'nam', 'Công sở', array['nam', 'công sở', 'quý', 'ông', 'công', 'sở', 'chắp', 'tay']::text[]),
  ('sp-2231', '2231', 'Nhân vật đầu túi giấy đứng nghỉ', 'https://kevindauto.com/products/sp-2231.webp', 'nam', 'Độc đáo', array['nam', 'độc đáo', 'nhân', 'vật', 'đầu', 'túi', 'giấy', 'đứng', 'nghỉ']::text[]),
  ('sp-2232', '2232', 'Nhân vật đầu túi giấy dang tay', 'https://kevindauto.com/products/sp-2232.webp', 'nam', 'Độc đáo', array['nam', 'độc đáo', 'nhân', 'vật', 'đầu', 'túi', 'giấy', 'dang', 'tay']::text[]),
  ('sp-2233', '2233', 'Chàng trai áo khoác chống hông', 'https://kevindauto.com/products/sp-2233.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'chống', 'hông']::text[]),
  ('sp-2234', '2234', 'Quý cô váy ngắn thanh lịch', 'https://kevindauto.com/products/sp-2234.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'quý', 'cô', 'váy', 'ngắn', 'thanh', 'lịch']::text[]),
  ('sp-2235', '2235', 'Cô gái áo thun chống hông', 'https://kevindauto.com/products/sp-2235.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'áo', 'thun', 'chống', 'hông']::text[]),
  ('sp-2236', '2236', 'Cô gái áo khoác cầm túi', 'https://kevindauto.com/products/sp-2236.webp', 'nu', 'Streetwear', array['nu', 'streetwear', 'cô', 'gái', 'áo', 'khoác', 'cầm', 'túi']::text[]),
  ('sp-2237', '2237', 'Nữ chiến binh cầm vũ khí', 'https://kevindauto.com/products/sp-2237.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'chiến', 'binh', 'cầm', 'vũ', 'khí']::text[]),
  ('sp-2238', '2238', 'Quý ông áo choàng dài', 'https://kevindauto.com/products/sp-2238.webp', 'nam', 'Hoàng gia', array['nam', 'hoàng gia', 'quý', 'ông', 'áo', 'choàng', 'dài']::text[]),
  ('sp-2239', '2239', 'Mèo chibi đeo nơ', 'https://kevindauto.com/products/sp-2239.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'mèo', 'đeo', 'nơ']::text[]),
  ('sp-2240', '2240', 'Chàng trai áo khoác đứng tự nhiên', 'https://kevindauto.com/products/sp-2240.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'tự', 'nhiên']::text[]),
  ('sp-2241', '2241', 'Cô gái mua sắm gọi điện', 'https://kevindauto.com/products/sp-2241.webp', 'nu', 'Mua sắm', array['nu', 'mua sắm', 'cô', 'gái', 'mua', 'sắm', 'gọi', 'điện']::text[]),
  ('sp-2242', '2242', 'Chàng trai áo khoác dài', 'https://kevindauto.com/products/sp-2242.webp', 'nam', 'Mùa đông', array['nam', 'mùa đông', 'chàng', 'trai', 'áo', 'khoác', 'dài']::text[]),
  ('sp-2243', '2243', 'Cụ ông ngồi chắp tay', 'https://kevindauto.com/products/sp-2243.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'ông', 'ngồi', 'chắp', 'tay']::text[]),
  ('sp-2244', '2244', 'Mèo mập ngồi thư giãn', 'https://kevindauto.com/products/sp-2244.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'mèo', 'mập', 'ngồi', 'thư', 'giãn']::text[]),
  ('sp-2245', '2245', 'Nữ công nhân xách xô', 'https://kevindauto.com/products/sp-2245.webp', 'duongpho', 'Lao động', array['duongpho', 'lao động', 'nữ', 'công', 'nhân', 'xách', 'xô']::text[]),
  ('sp-2246', '2246', 'Cô gái đội hộp giấy', 'https://kevindauto.com/products/sp-2246.webp', 'nu', 'Độc đáo', array['nu', 'độc đáo', 'cô', 'gái', 'đội', 'hộp', 'giấy']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
