-- Lo 008: san pham 2247 den 2326
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-2247', '2247', 'Cô gái đội hộp đứng thẳng', 'https://kevindauto.com/products/sp-2247.webp', 'nu', 'Độc đáo', array['nu', 'độc đáo', 'cô', 'gái', 'đội', 'hộp', 'đứng', 'thẳng']::text[]),
  ('sp-2248', '2248', 'Chàng trai gãi đầu suy nghĩ', 'https://kevindauto.com/products/sp-2248.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'gãi', 'đầu', 'suy', 'nghĩ']::text[]),
  ('sp-2249', '2249', 'Cô gái xách nhiều túi mua sắm', 'https://kevindauto.com/products/sp-2249.webp', 'nu', 'Mua sắm', array['nu', 'mua sắm', 'cô', 'gái', 'xách', 'nhiều', 'túi', 'mua', 'sắm']::text[]),
  ('sp-2250', '2250', 'Người đàn ông mặc đồ bảo hộ', 'https://kevindauto.com/products/sp-2250.webp', 'duongpho', 'Nghề nghiệp', array['duongpho', 'nghề nghiệp', 'người', 'đàn', 'ông', 'mặc', 'đồ', 'bảo', 'hộ']::text[]),
  ('sp-2251', '2251', 'Nam du khách kéo vali', 'https://kevindauto.com/products/sp-2251.webp', 'nam', 'Du lịch', array['nam', 'du lịch', 'du', 'khách', 'kéo', 'vali']::text[]),
  ('sp-2252', '2252', 'Doanh nhân xách cặp bước đi', 'https://kevindauto.com/products/sp-2252.webp', 'nam', 'Công sở', array['nam', 'công sở', 'doanh', 'nhân', 'xách', 'cặp', 'bước', 'đi']::text[]),
  ('sp-2253', '2253', 'Cụ ông quàng khăn nghe điện thoại', 'https://kevindauto.com/products/sp-2253.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'ông', 'quàng', 'khăn', 'nghe', 'điện', 'thoại']::text[]),
  ('sp-2254', '2254', 'Cô gái váy ngắn đứng nghiêng', 'https://kevindauto.com/products/sp-2254.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'cô', 'gái', 'váy', 'ngắn', 'đứng', 'nghiêng']::text[]),
  ('sp-2255', '2255', 'Quý cô áo khoác tạo dáng', 'https://kevindauto.com/products/sp-2255.webp', 'nu', 'Thanh lịch', array['nu', 'thanh lịch', 'quý', 'cô', 'áo', 'khoác', 'tạo', 'dáng']::text[]),
  ('sp-2256', '2256', 'Cô gái đưa tay qua đầu', 'https://kevindauto.com/products/sp-2256.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'cô', 'gái', 'đưa', 'tay', 'qua', 'đầu']::text[]),
  ('sp-2257', '2257', 'Người đàn ông lớn tuổi gọi điện', 'https://kevindauto.com/products/sp-2257.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'người', 'đàn', 'ông', 'lớn', 'tuổi', 'gọi', 'điện']::text[]),
  ('sp-2258', '2258', 'Doanh nhân mặc vest chống hông', 'https://kevindauto.com/products/sp-2258.webp', 'nam', 'Công sở', array['nam', 'công sở', 'doanh', 'nhân', 'mặc', 'vest', 'chống', 'hông']::text[]),
  ('sp-2259', '2259', 'Chàng trai áo khoác đứng thư giãn', 'https://kevindauto.com/products/sp-2259.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'thư', 'giãn']::text[]),
  ('sp-2260', '2260', 'Quý cô áo choàng cầm túi', 'https://kevindauto.com/products/sp-2260.webp', 'nu', 'Thanh lịch', array['nu', 'thanh lịch', 'quý', 'cô', 'áo', 'choàng', 'cầm', 'túi']::text[]),
  ('sp-2261', '2261', 'Nữ công sở xách túi', 'https://kevindauto.com/products/sp-2261.webp', 'nu', 'Công sở', array['nu', 'công sở', 'nữ', 'công', 'sở', 'xách', 'túi']::text[]),
  ('sp-2262', '2262', 'Quý ông chibi đội mũ cao', 'https://kevindauto.com/products/sp-2262.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'quý', 'ông', 'đội', 'mũ', 'cao']::text[]),
  ('sp-2263', '2263', 'Cậu bé chắp tay phía trước', 'https://kevindauto.com/products/sp-2263.webp', 'treem', 'Đời thường', array['treem', 'đời thường', 'cậu', 'bé', 'chắp', 'tay', 'phía', 'trước']::text[]),
  ('sp-2264', '2264', 'Chàng trai chắp tay đứng thẳng', 'https://kevindauto.com/products/sp-2264.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'chàng', 'trai', 'chắp', 'tay', 'đứng', 'thẳng']::text[]),
  ('sp-2265', '2265', 'Quý cô đầm dạ hội', 'https://kevindauto.com/products/sp-2265.webp', 'nu', 'Dạ hội', array['nu', 'dạ hội', 'quý', 'cô', 'đầm', 'dạ', 'hội']::text[]),
  ('sp-2266', '2266', 'Cụ bà ngồi bên túi mua sắm', 'https://kevindauto.com/products/sp-2266.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'bà', 'ngồi', 'bên', 'túi', 'mua', 'sắm']::text[]),
  ('sp-2267', '2267', 'Quý cô áo choàng xách túi', 'https://kevindauto.com/products/sp-2267.webp', 'nu', 'Mua sắm', array['nu', 'mua sắm', 'quý', 'cô', 'áo', 'choàng', 'xách', 'túi']::text[]),
  ('sp-2268', '2268', 'Cô gái xách hai túi lớn', 'https://kevindauto.com/products/sp-2268.webp', 'nu', 'Mua sắm', array['nu', 'mua sắm', 'cô', 'gái', 'xách', 'hai', 'túi', 'lớn']::text[]),
  ('sp-2269', '2269', 'Cụ ông xách túi hàng', 'https://kevindauto.com/products/sp-2269.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'ông', 'xách', 'túi', 'hàng']::text[]),
  ('sp-2270', '2270', 'Quý cô cầm nhiều túi mua sắm', 'https://kevindauto.com/products/sp-2270.webp', 'nu', 'Mua sắm', array['nu', 'mua sắm', 'quý', 'cô', 'cầm', 'nhiều', 'túi', 'mua', 'sắm']::text[]),
  ('sp-2271', '2271', 'Nhân viên giao hàng mang thùng', 'https://kevindauto.com/products/sp-2271.webp', 'duongpho', 'Giao nhận', array['duongpho', 'giao nhận', 'nhân', 'viên', 'giao', 'hàng', 'mang', 'thùng']::text[]),
  ('sp-2272', '2272', 'Công nhân ôm kiện hàng', 'https://kevindauto.com/products/sp-2272.webp', 'duongpho', 'Giao nhận', array['duongpho', 'giao nhận', 'công', 'nhân', 'ôm', 'kiện', 'hàng']::text[]),
  ('sp-2273', '2273', 'Cô gái mua sắm xem điện thoại', 'https://kevindauto.com/products/sp-2273.webp', 'nu', 'Mua sắm', array['nu', 'mua sắm', 'cô', 'gái', 'mua', 'sắm', 'xem', 'điện', 'thoại']::text[]),
  ('sp-2274', '2274', 'Chó Bull Terrier đứng thẳng', 'https://kevindauto.com/products/sp-2274.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'bull', 'terrier', 'đứng', 'thẳng']::text[]),
  ('sp-2275', '2275', 'Hà mã đứng quan sát', 'https://kevindauto.com/products/sp-2275.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'hà', 'mã', 'đứng', 'quan', 'sát']::text[]),
  ('sp-2276', '2276', 'Robot samurai cầm kiếm', 'https://kevindauto.com/products/sp-2276.webp', 'dongvat', 'Sci-fi', array['dongvat', 'sci-fi', 'robot', 'samurai', 'cầm', 'kiếm']::text[]),
  ('sp-2277', '2277', 'Robot cơ giới hạng nặng', 'https://kevindauto.com/products/sp-2277.webp', 'dongvat', 'Sci-fi', array['dongvat', 'sci-fi', 'robot', 'cơ', 'giới', 'hạng', 'nặng']::text[]),
  ('sp-2278', '2278', 'Nữ vận động viên chống hông', 'https://kevindauto.com/products/sp-2278.webp', 'thethao', 'Thể hình', array['thethao', 'thể hình', 'nữ', 'vận', 'động', 'viên', 'chống', 'hông']::text[]),
  ('sp-2279', '2279', 'Cụ bà chống gậy', 'https://kevindauto.com/products/sp-2279.webp', 'caotuoi', 'Người cao tuổi', array['caotuoi', 'người cao tuổi', 'cụ', 'bà', 'chống', 'gậy']::text[]),
  ('sp-2280', '2280', 'Chó Bull Terrier đứng nghiêng', 'https://kevindauto.com/products/sp-2280.webp', 'dongvat', 'Thú cưng', array['dongvat', 'thú cưng', 'chó', 'bull', 'terrier', 'đứng', 'nghiêng']::text[]),
  ('sp-2281', '2281', 'Nhà thám hiểm mang trang bị', 'https://kevindauto.com/products/sp-2281.webp', 'nam', 'Phiêu lưu', array['nam', 'phiêu lưu', 'nhà', 'thám', 'hiểm', 'mang', 'trang', 'bị']::text[]),
  ('sp-2282', '2282', 'Chiến binh áo choàng giơ tay', 'https://kevindauto.com/products/sp-2282.webp', 'nam', 'Fantasy', array['nam', 'fantasy', 'chiến', 'binh', 'áo', 'choàng', 'giơ', 'tay']::text[]),
  ('sp-2283', '2283', 'Ống chắn đường kim loại', 'https://kevindauto.com/products/sp-2283.webp', 'phukien', 'Diorama đường phố', array['phukien', 'diorama đường phố', 'ống', 'chắn', 'đường', 'kim', 'loại']::text[]),
  ('sp-2284', '2284', 'Nhân vật chibi đeo mặt nạ khí', 'https://kevindauto.com/products/sp-2284.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhân', 'vật', 'đeo', 'mặt', 'nạ', 'khí']::text[]),
  ('sp-2285', '2285', 'Nhà thám hiểm chibi cầm đèn', 'https://kevindauto.com/products/sp-2285.webp', 'dongvat', 'Chibi', array['dongvat', 'chibi', 'nhà', 'thám', 'hiểm', 'cầm', 'đèn']::text[]),
  ('sp-2286', '2286', 'Chàng trai áo khoác đứng nghiêng', 'https://kevindauto.com/products/sp-2286.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'đứng', 'nghiêng']::text[]),
  ('sp-2287', '2287', 'Chàng trai đeo ba lô ngồi ghế', 'https://kevindauto.com/products/sp-2287.webp', 'nam', 'Du lịch', array['nam', 'du lịch', 'chàng', 'trai', 'đeo', 'ba', 'lô', 'ngồi', 'ghế']::text[]),
  ('sp-2288', '2288', 'Cô gái quần short đứng thẳng', 'https://kevindauto.com/products/sp-2288.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'quần', 'short', 'đứng', 'thẳng']::text[]),
  ('sp-2289', '2289', 'Đĩa hải sản trang trí', 'https://kevindauto.com/products/sp-2289.webp', 'phukien', 'Ẩm thực', array['phukien', 'ẩm thực', 'đĩa', 'hải', 'sản', 'trang', 'trí']::text[]),
  ('sp-2290', '2290', 'Cô gái mặc váy dài tay', 'https://kevindauto.com/products/sp-2290.webp', 'nu', 'Thời trang', array['nu', 'thời trang', 'cô', 'gái', 'mặc', 'váy', 'dài', 'tay']::text[]),
  ('sp-2291', '2291', 'Lợn con nằm nghỉ', 'https://kevindauto.com/products/sp-2291.webp', 'dongvat', 'Động vật', array['dongvat', 'động vật', 'lợn', 'con', 'nằm', 'nghỉ']::text[]),
  ('sp-2292', '2292', 'Nữ pháp sư ngồi ngai', 'https://kevindauto.com/products/sp-2292.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'pháp', 'sư', 'ngồi', 'ngai']::text[]),
  ('sp-2293', '2293', 'Nữ kiếm sĩ áo choàng', 'https://kevindauto.com/products/sp-2293.webp', 'nu', 'Fantasy', array['nu', 'fantasy', 'nữ', 'kiếm', 'sĩ', 'áo', 'choàng']::text[]),
  ('sp-2294', '2294', 'Nhân vật trùm đầu bỏ tay túi', 'https://kevindauto.com/products/sp-2294.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'nhân', 'vật', 'trùm', 'đầu', 'bỏ', 'tay', 'túi']::text[]),
  ('sp-2295', '2295', 'Chàng trai áo khoác cầm điện thoại', 'https://kevindauto.com/products/sp-2295.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'áo', 'khoác', 'cầm', 'điện', 'thoại']::text[]),
  ('sp-2296', '2296', 'Chàng trai hoodie đứng thư giãn', 'https://kevindauto.com/products/sp-2296.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chàng', 'trai', 'hoodie', 'đứng', 'thư', 'giãn']::text[]),
  ('sp-2297', '2297', 'Cậu bé áo khoác đứng thẳng', 'https://kevindauto.com/products/sp-2297.webp', 'treem', 'Đời thường', array['treem', 'đời thường', 'cậu', 'bé', 'áo', 'khoác', 'đứng', 'thẳng']::text[]),
  ('sp-2298', '2298', 'Cô gái áo thun chống hông', 'https://kevindauto.com/products/sp-2298.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'áo', 'thun', 'chống', 'hông']::text[]),
  ('sp-2299', '2299', 'Cô gái đội mũ ngồi ghế', 'https://kevindauto.com/products/sp-2299.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'cô', 'gái', 'đội', 'mũ', 'ngồi', 'ghế']::text[]),
  ('sp-2300', '2300', 'Doraemon ngồi suy tư', 'https://kevindauto.com/products/sp-2300.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'doraemon ngồi suy tư', '2300']::text[]),
  ('sp-2301', '2301', 'Doraemon chạy vui nhộn', 'https://kevindauto.com/products/sp-2301.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'doraemon chạy vui nhộn', '2301']::text[]),
  ('sp-2302', '2302', 'Doraemon há miệng ngạc nhiên', 'https://kevindauto.com/products/sp-2302.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'doraemon há miệng ngạc nhiên', '2302']::text[]),
  ('sp-2303', '2303', 'Doraemon đứng tạo dáng', 'https://kevindauto.com/products/sp-2303.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'doraemon đứng tạo dáng', '2303']::text[]),
  ('sp-2304', '2304', 'Nữ chiến binh cánh rồng', 'https://kevindauto.com/products/sp-2304.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nữ chiến binh cánh rồng', '2304']::text[]),
  ('sp-2305', '2305', 'Tôm hùm đỏ trưng bày', 'https://kevindauto.com/products/sp-2305.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'tôm hùm đỏ trưng bày', '2305']::text[]),
  ('sp-2306', '2306', 'Chậu cây bàn tay nghệ thuật', 'https://kevindauto.com/products/sp-2306.webp', 'phukien', 'Phụ kiện Diorama', array['phukien', 'phụ kiện diorama', 'chậu cây bàn tay nghệ thuật', '2306']::text[]),
  ('sp-2307', '2307', 'Nhân vật nam tạo dáng 2307', 'https://kevindauto.com/products/sp-2307.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2307', '2307']::text[]),
  ('sp-2308', '2308', 'Cua biển giương càng', 'https://kevindauto.com/products/sp-2308.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'cua biển giương càng', '2308']::text[]),
  ('sp-2309', '2309', 'Nhân vật nam tạo dáng 2309', 'https://kevindauto.com/products/sp-2309.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2309', '2309']::text[]),
  ('sp-2310', '2310', 'Nhân vật nam tạo dáng 2310', 'https://kevindauto.com/products/sp-2310.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2310', '2310']::text[]),
  ('sp-2311', '2311', 'Nhân vật nam tạo dáng 2311', 'https://kevindauto.com/products/sp-2311.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2311', '2311']::text[]),
  ('sp-2312', '2312', 'Nhân vật nam tạo dáng 2312', 'https://kevindauto.com/products/sp-2312.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2312', '2312']::text[]),
  ('sp-2313', '2313', 'Động vật và nhân vật chibi 2313', 'https://kevindauto.com/products/sp-2313.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'động vật và nhân vật chibi 2313', '2313']::text[]),
  ('sp-2314', '2314', 'Nhân vật nữ tạo dáng 2314', 'https://kevindauto.com/products/sp-2314.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2314', '2314']::text[]),
  ('sp-2315', '2315', 'Nhân vật nữ tạo dáng 2315', 'https://kevindauto.com/products/sp-2315.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2315', '2315']::text[]),
  ('sp-2316', '2316', 'Động vật và nhân vật chibi 2316', 'https://kevindauto.com/products/sp-2316.webp', 'dongvat', 'Động vật & Chibi', array['dongvat', 'động vật & chibi', 'động vật và nhân vật chibi 2316', '2316']::text[]),
  ('sp-2317', '2317', 'Nhân vật nam tạo dáng 2317', 'https://kevindauto.com/products/sp-2317.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2317', '2317']::text[]),
  ('sp-2318', '2318', 'Nhân vật nam tạo dáng 2318', 'https://kevindauto.com/products/sp-2318.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'nhân vật nam tạo dáng 2318', '2318']::text[]),
  ('sp-2319', '2319', 'Nhân vật nữ tạo dáng 2319', 'https://kevindauto.com/products/sp-2319.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2319', '2319']::text[]),
  ('sp-2320', '2320', 'Nhân vật nữ tạo dáng 2320', 'https://kevindauto.com/products/sp-2320.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2320', '2320']::text[]),
  ('sp-2321', '2321', 'Nhân vật nữ tạo dáng 2321', 'https://kevindauto.com/products/sp-2321.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2321', '2321']::text[]),
  ('sp-2322', '2322', 'Nhân vật nữ tạo dáng 2322', 'https://kevindauto.com/products/sp-2322.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2322', '2322']::text[]),
  ('sp-2323', '2323', 'Nhân vật nữ tạo dáng 2323', 'https://kevindauto.com/products/sp-2323.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2323', '2323']::text[]),
  ('sp-2324', '2324', 'Nhân vật nữ tạo dáng 2324', 'https://kevindauto.com/products/sp-2324.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2324', '2324']::text[]),
  ('sp-2325', '2325', 'Nhân vật nữ tạo dáng 2325', 'https://kevindauto.com/products/sp-2325.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2325', '2325']::text[]),
  ('sp-2326', '2326', 'Nhân vật nữ tạo dáng 2326', 'https://kevindauto.com/products/sp-2326.webp', 'nu', 'Đời thường', array['nu', 'đời thường', 'nhân vật nữ tạo dáng 2326', '2326']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
