-- Lo 020: san pham 3313 den 3392
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-3313', '3313', 'Nam chien binh co bap cam dao', 'https://kevindauto.com/products/sp-3313.webp', 'thethao', 'Hanh dong & The thao', array['thethao', 'hanh dong & the thao', 'nam chien binh co bap cam dao', '3313']::text[]),
  ('sp-3314', '3314', 'Nhan vat ao hoodie rong', 'https://kevindauto.com/products/sp-3314.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'nhan vat ao hoodie rong', '3314']::text[]),
  ('sp-3315', '3315', 'Co gai ben cho Shiba', 'https://kevindauto.com/products/sp-3315.webp', 'dongvat', 'Dong vat & Thu cung', array['dongvat', 'dong vat & thu cung', 'co gai ben cho shiba', '3315']::text[]),
  ('sp-3316', '3316', 'Nu sinh dong phuc den', 'https://kevindauto.com/products/sp-3316.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'nu sinh dong phuc den', '3316']::text[]),
  ('sp-3317', '3317', 'Nu sinh dong phuc trang', 'https://kevindauto.com/products/sp-3317.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'nu sinh dong phuc trang', '3317']::text[]),
  ('sp-3318', '3318', 'Co gai ao bong ro form rong', 'https://kevindauto.com/products/sp-3318.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao bong ro form rong', '3318']::text[]),
  ('sp-3319', '3319', 'Co gai vay hong tao dang', 'https://kevindauto.com/products/sp-3319.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai vay hong tao dang', '3319']::text[]),
  ('sp-3320', '3320', 'Co gai toc xoan ao khoac xanh', 'https://kevindauto.com/products/sp-3320.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai toc xoan ao khoac xanh', '3320']::text[]),
  ('sp-3321', '3321', 'Co gai ao so 88 streetwear', 'https://kevindauto.com/products/sp-3321.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao so 88 streetwear', '3321']::text[]),
  ('sp-3322', '3322', 'Co gai dong phuc xanh', 'https://kevindauto.com/products/sp-3322.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai dong phuc xanh', '3322']::text[]),
  ('sp-3323', '3323', 'Co gai ao thun va quan jean', 'https://kevindauto.com/products/sp-3323.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao thun va quan jean', '3323']::text[]),
  ('sp-3324', '3324', 'Co gai tracksuit vang', 'https://kevindauto.com/products/sp-3324.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai tracksuit vang', '3324']::text[]),
  ('sp-3325', '3325', 'Quy co ao den xach tui', 'https://kevindauto.com/products/sp-3325.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'quy co ao den xach tui', '3325']::text[]),
  ('sp-3326', '3326', 'Co gai ao khoac vang doi mu', 'https://kevindauto.com/products/sp-3326.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac vang doi mu', '3326']::text[]),
  ('sp-3327', '3327', 'Co gai dam dai cam tui', 'https://kevindauto.com/products/sp-3327.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai dam dai cam tui', '3327']::text[]),
  ('sp-3328', '3328', 'Co gai streetwear quan ong rong', 'https://kevindauto.com/products/sp-3328.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai streetwear quan ong rong', '3328']::text[]),
  ('sp-3329', '3329', 'Co gai dam vang om dang', 'https://kevindauto.com/products/sp-3329.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai dam vang om dang', '3329']::text[]),
  ('sp-3330', '3330', 'Co gai ao len xam dung thoai mai', 'https://kevindauto.com/products/sp-3330.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'co gai ao len xam dung thoai mai', '3330']::text[]),
  ('sp-3331', '3331', 'Co gai ao do the thao', 'https://kevindauto.com/products/sp-3331.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'co gai ao do the thao', '3331']::text[]),
  ('sp-3332', '3332', 'Co gai hoodie hong dang dung', 'https://kevindauto.com/products/sp-3332.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai hoodie hong dang dung', '3332']::text[]),
  ('sp-3333', '3333', 'Co gai ao khoac be doi non', 'https://kevindauto.com/products/sp-3333.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'co gai ao khoac be doi non', '3333']::text[]),
  ('sp-3334', '3334', 'Co gai ao khoac denim', 'https://kevindauto.com/products/sp-3334.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac denim', '3334']::text[]),
  ('sp-3335', '3335', 'Co gai ao khoac cam', 'https://kevindauto.com/products/sp-3335.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'co gai ao khoac cam', '3335']::text[]),
  ('sp-3336', '3336', 'Co gai hoodie do streetwear', 'https://kevindauto.com/products/sp-3336.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'co gai hoodie do streetwear', '3336']::text[]),
  ('sp-3337', '3337', 'Co gai ao khoac xam doi mu', 'https://kevindauto.com/products/sp-3337.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac xam doi mu', '3337']::text[]),
  ('sp-3338', '3338', 'Co gai ao choang xanh xach tui', 'https://kevindauto.com/products/sp-3338.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao choang xanh xach tui', '3338']::text[]),
  ('sp-3339', '3339', 'Nhan vat phap su ao do', 'https://kevindauto.com/products/sp-3339.webp', 'phukien', 'Fantasy & Phu kien', array['phukien', 'fantasy & phu kien', 'nhan vat phap su ao do', '3339']::text[]),
  ('sp-3340', '3340', 'Kiem si dang chay', 'https://kevindauto.com/products/sp-3340.webp', 'thethao', 'Hanh dong & The thao', array['thethao', 'hanh dong & the thao', 'kiem si dang chay', '3340']::text[]),
  ('sp-3341', '3341', 'Nhan vat phap su ganh do', 'https://kevindauto.com/products/sp-3341.webp', 'phukien', 'Fantasy & Phu kien', array['phukien', 'fantasy & phu kien', 'nhan vat phap su ganh do', '3341']::text[]),
  ('sp-3342', '3342', 'Kiem si hanh dong voi vu khi', 'https://kevindauto.com/products/sp-3342.webp', 'thethao', 'Hanh dong & The thao', array['thethao', 'hanh dong & the thao', 'kiem si hanh dong voi vu khi', '3342']::text[]),
  ('sp-3343', '3343', 'Nhan vat hanh dong cam luoi hai', 'https://kevindauto.com/products/sp-3343.webp', 'thethao', 'Hanh dong & The thao', array['thethao', 'hanh dong & the thao', 'nhan vat hanh dong cam luoi hai', '3343']::text[]),
  ('sp-3344', '3344', 'Chang trai hoodie xam', 'https://kevindauto.com/products/sp-3344.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'chang trai hoodie xam', '3344']::text[]),
  ('sp-3345', '3345', 'Chang trai ao da den xach tui', 'https://kevindauto.com/products/sp-3345.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'chang trai ao da den xach tui', '3345']::text[]),
  ('sp-3346', '3346', 'Chang trai ao khoac do chinh tai nghe', 'https://kevindauto.com/products/sp-3346.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'chang trai ao khoac do chinh tai nghe', '3346']::text[]),
  ('sp-3347', '3347', 'Chang trai ao khoac nau', 'https://kevindauto.com/products/sp-3347.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'chang trai ao khoac nau', '3347']::text[]),
  ('sp-3348', '3348', 'Co gai ao crop top den', 'https://kevindauto.com/products/sp-3348.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao crop top den', '3348']::text[]),
  ('sp-3349', '3349', 'Cu ong day xe keo hang', 'https://kevindauto.com/products/sp-3349.webp', 'caotuoi', 'Nguoi cao tuoi', array['caotuoi', 'nguoi cao tuoi', 'cu ong day xe keo hang', '3349']::text[]),
  ('sp-3350', '3350', 'Me va em be trang phuc hong', 'https://kevindauto.com/products/sp-3350.webp', 'giadinh', 'Gia dinh & Cap doi', array['giadinh', 'gia dinh & cap doi', 'me va em be trang phuc hong', '3350']::text[]),
  ('sp-3351', '3351', 'Quy ong cam du den', 'https://kevindauto.com/products/sp-3351.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'quy ong cam du den', '3351']::text[]),
  ('sp-3352', '3352', 'Co gai ao khoac xanh va khan do', 'https://kevindauto.com/products/sp-3352.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac xanh va khan do', '3352']::text[]),
  ('sp-3353', '3353', 'Co gai ao ke xanh', 'https://kevindauto.com/products/sp-3353.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao ke xanh', '3353']::text[]),
  ('sp-3354', '3354', 'Co gai ao ke khoanh tay', 'https://kevindauto.com/products/sp-3354.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao ke khoanh tay', '3354']::text[]),
  ('sp-3355', '3355', 'Co gai chup anh bang dien thoai', 'https://kevindauto.com/products/sp-3355.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai chup anh bang dien thoai', '3355']::text[]),
  ('sp-3356', '3356', 'Co gai dam den xach tui', 'https://kevindauto.com/products/sp-3356.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai dam den xach tui', '3356']::text[]),
  ('sp-3357', '3357', 'Co gai deo dan guitar', 'https://kevindauto.com/products/sp-3357.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai deo dan guitar', '3357']::text[]),
  ('sp-3358', '3358', 'Co gai ao khoac do doi mu', 'https://kevindauto.com/products/sp-3358.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac do doi mu', '3358']::text[]),
  ('sp-3359', '3359', 'Co gai vay caro xach tui', 'https://kevindauto.com/products/sp-3359.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai vay caro xach tui', '3359']::text[]),
  ('sp-3360', '3360', 'Co gai tao dang ben trong tron', 'https://kevindauto.com/products/sp-3360.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai tao dang ben trong tron', '3360']::text[]),
  ('sp-3361', '3361', 'Co gai ao khoac xanh xach tui', 'https://kevindauto.com/products/sp-3361.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac xanh xach tui', '3361']::text[]),
  ('sp-3362', '3362', 'Co gai quan short doi mu', 'https://kevindauto.com/products/sp-3362.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai quan short doi mu', '3362']::text[]),
  ('sp-3363', '3363', 'Co gai ao khoac den quan jean', 'https://kevindauto.com/products/sp-3363.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac den quan jean', '3363']::text[]),
  ('sp-3364', '3364', 'Co gai ao xanh xach tui', 'https://kevindauto.com/products/sp-3364.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao xanh xach tui', '3364']::text[]),
  ('sp-3365', '3365', 'Co gai ao khoac xanh doi mu', 'https://kevindauto.com/products/sp-3365.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac xanh doi mu', '3365']::text[]),
  ('sp-3366', '3366', 'Co gai dong phuc cam', 'https://kevindauto.com/products/sp-3366.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai dong phuc cam', '3366']::text[]),
  ('sp-3367', '3367', 'Co gai dong phuc trang xanh', 'https://kevindauto.com/products/sp-3367.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai dong phuc trang xanh', '3367']::text[]),
  ('sp-3368', '3368', 'Co gai suit trang xach tui', 'https://kevindauto.com/products/sp-3368.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai suit trang xach tui', '3368']::text[]),
  ('sp-3369', '3369', 'Co gai streetwear do den', 'https://kevindauto.com/products/sp-3369.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai streetwear do den', '3369']::text[]),
  ('sp-3370', '3370', 'Co gai ao hong be gau nho', 'https://kevindauto.com/products/sp-3370.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao hong be gau nho', '3370']::text[]),
  ('sp-3371', '3371', 'Co gai ngoi thu gian', 'https://kevindauto.com/products/sp-3371.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ngoi thu gian', '3371']::text[]),
  ('sp-3372', '3372', 'Co gai ao poncho vang', 'https://kevindauto.com/products/sp-3372.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao poncho vang', '3372']::text[]),
  ('sp-3373', '3373', 'Co gai ao khoac denim', 'https://kevindauto.com/products/sp-3373.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac denim', '3373']::text[]),
  ('sp-3374', '3374', 'Co gai ao khoac xanh la', 'https://kevindauto.com/products/sp-3374.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac xanh la', '3374']::text[]),
  ('sp-3375', '3375', 'Co gai ao hoodie xam', 'https://kevindauto.com/products/sp-3375.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao hoodie xam', '3375']::text[]),
  ('sp-3376', '3376', 'Co gai ao khoac vang', 'https://kevindauto.com/products/sp-3376.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao khoac vang', '3376']::text[]),
  ('sp-3377', '3377', 'Co gai ao thun trang quan jean', 'https://kevindauto.com/products/sp-3377.webp', 'nu', 'Thoi trang nu', array['nu', 'thoi trang nu', 'co gai ao thun trang quan jean', '3377']::text[]),
  ('sp-3378', '3378', 'Nhan vat ao choang long vu', 'https://kevindauto.com/products/sp-3378.webp', 'phukien', 'Fantasy & Phu kien', array['phukien', 'fantasy & phu kien', 'nhan vat ao choang long vu', '3378']::text[]),
  ('sp-3379', '3379', 'Nhan vat jumpsuit xanh', 'https://kevindauto.com/products/sp-3379.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'nhan vat jumpsuit xanh', '3379']::text[]),
  ('sp-3380', '3380', 'Chang trai ao da nghe tai nghe', 'https://kevindauto.com/products/sp-3380.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'chang trai ao da nghe tai nghe', '3380']::text[]),
  ('sp-3381', '3381', 'Quy ong suit trang', 'https://kevindauto.com/products/sp-3381.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'quy ong suit trang', '3381']::text[]),
  ('sp-3382', '3382', 'Quy ong suit den deo kinh', 'https://kevindauto.com/products/sp-3382.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'quy ong suit den deo kinh', '3382']::text[]),
  ('sp-3383', '3383', 'Quy ong suit den ngoi thap', 'https://kevindauto.com/products/sp-3383.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'quy ong suit den ngoi thap', '3383']::text[]),
  ('sp-3384', '3384', 'Nhan vat nam tao dang 3384', 'https://kevindauto.com/products/sp-3384.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'nhan vat nam tao dang 3384', '3384']::text[]),
  ('sp-3385', '3385', 'Co gai denim giang tay', 'https://kevindauto.com/products/sp-3385.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'co gai denim giang tay', '3385']::text[]),
  ('sp-3386', '3386', 'Chang trai streetwear deo kinh', 'https://kevindauto.com/products/sp-3386.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'chang trai streetwear deo kinh', '3386']::text[]),
  ('sp-3387', '3387', 'Chang trai ao da den', 'https://kevindauto.com/products/sp-3387.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'chang trai ao da den', '3387']::text[]),
  ('sp-3388', '3388', 'Nhan vat sieu anh hung ao vang', 'https://kevindauto.com/products/sp-3388.webp', 'phukien', 'Fantasy & Phu kien', array['phukien', 'fantasy & phu kien', 'nhan vat sieu anh hung ao vang', '3388']::text[]),
  ('sp-3389', '3389', 'Chang trai hoodie vang', 'https://kevindauto.com/products/sp-3389.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'chang trai hoodie vang', '3389']::text[]),
  ('sp-3390', '3390', 'Chang trai ao den vui ve', 'https://kevindauto.com/products/sp-3390.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'chang trai ao den vui ve', '3390']::text[]),
  ('sp-3391', '3391', 'Quy ong ao da nau', 'https://kevindauto.com/products/sp-3391.webp', 'nam', 'Thoi trang nam', array['nam', 'thoi trang nam', 'quy ong ao da nau', '3391']::text[]),
  ('sp-3392', '3392', 'Chang trai ao da den hut thuoc', 'https://kevindauto.com/products/sp-3392.webp', 'duongpho', 'Streetwear & Duong pho', array['duongpho', 'streetwear & duong pho', 'chang trai ao da den hut thuoc', '3392']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
