-- Lo 033: san pham 4353 den 4432
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-4353', '4353', 'Chàng trai áo khoác cầm ly', 'https://kevindauto.com/products/sp-4353.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4353']::text[]),
  ('sp-4354', '4354', 'Chàng trai áo khoác da', 'https://kevindauto.com/products/sp-4354.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4354']::text[]),
  ('sp-4355', '4355', 'Shipper ba lô cam', 'https://kevindauto.com/products/sp-4355.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4355']::text[]),
  ('sp-4356', '4356', 'Chàng trai áo choàng trắng', 'https://kevindauto.com/products/sp-4356.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4356']::text[]),
  ('sp-4357', '4357', 'Chàng trai selfie', 'https://kevindauto.com/products/sp-4357.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4357']::text[]),
  ('sp-4358', '4358', 'Cô gái mũ túi dạo phố', 'https://kevindauto.com/products/sp-4358.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4358']::text[]),
  ('sp-4359', '4359', 'Cô gái ván trượt', 'https://kevindauto.com/products/sp-4359.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4359']::text[]),
  ('sp-4360', '4360', 'Chàng trai sơ mi kẻ', 'https://kevindauto.com/products/sp-4360.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4360']::text[]),
  ('sp-4361', '4361', 'Chàng trai ngồi xổm uống nước', 'https://kevindauto.com/products/sp-4361.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4361']::text[]),
  ('sp-4362', '4362', 'Chàng trai áo len cargo', 'https://kevindauto.com/products/sp-4362.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4362']::text[]),
  ('sp-4363', '4363', 'Cô gái ngồi váy', 'https://kevindauto.com/products/sp-4363.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4363']::text[]),
  ('sp-4364', '4364', 'Chàng trai khoanh tay', 'https://kevindauto.com/products/sp-4364.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4364']::text[]),
  ('sp-4365', '4365', 'Chàng trai denim cầm túi', 'https://kevindauto.com/products/sp-4365.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4365']::text[]),
  ('sp-4366', '4366', 'Chàng trai ngồi áo khoác mở', 'https://kevindauto.com/products/sp-4366.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4366']::text[]),
  ('sp-4367', '4367', 'Cô gái phao bơi đỏ', 'https://kevindauto.com/products/sp-4367.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4367']::text[]),
  ('sp-4368', '4368', 'Cụ ông thợ tạp dề', 'https://kevindauto.com/products/sp-4368.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4368']::text[]),
  ('sp-4369', '4369', 'Chàng trai tạp dề', 'https://kevindauto.com/products/sp-4369.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4369']::text[]),
  ('sp-4370', '4370', 'Quý ông cao tuổi cầm gậy', 'https://kevindauto.com/products/sp-4370.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4370']::text[]),
  ('sp-4371', '4371', 'Cô gái phao bơi tươi tắn', 'https://kevindauto.com/products/sp-4371.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4371']::text[]),
  ('sp-4372', '4372', 'Cô gái mũ túi cá tính', 'https://kevindauto.com/products/sp-4372.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4372']::text[]),
  ('sp-4373', '4373', 'Mo hinh nhan vat 4373', 'https://kevindauto.com/products/sp-4373.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4373']::text[]),
  ('sp-4374', '4374', 'Mo hinh nhan vat 4374', 'https://kevindauto.com/products/sp-4374.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4374']::text[]),
  ('sp-4375', '4375', 'Tay đua xe', 'https://kevindauto.com/products/sp-4375.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4375']::text[]),
  ('sp-4376', '4376', 'Mo hinh nhan vat 4376', 'https://kevindauto.com/products/sp-4376.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4376']::text[]),
  ('sp-4377', '4377', 'Mo hinh nhan vat 4377', 'https://kevindauto.com/products/sp-4377.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4377']::text[]),
  ('sp-4378', '4378', 'Xe đạp cổ điển', 'https://kevindauto.com/products/sp-4378.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4378']::text[]),
  ('sp-4379', '4379', 'Hòm thư đỏ', 'https://kevindauto.com/products/sp-4379.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4379']::text[]),
  ('sp-4380', '4380', 'Xe tay ga', 'https://kevindauto.com/products/sp-4380.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4380']::text[]),
  ('sp-4381', '4381', 'Shipper xe đạp', 'https://kevindauto.com/products/sp-4381.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4381']::text[]),
  ('sp-4382', '4382', 'Nữ sinh đạp xe', 'https://kevindauto.com/products/sp-4382.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4382']::text[]),
  ('sp-4383', '4383', 'Cầu thủ bóng đá đỏ ăn mừng', 'https://kevindauto.com/products/sp-4383.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4383']::text[]),
  ('sp-4384', '4384', 'Cô gái đầm đen thanh lịch', 'https://kevindauto.com/products/sp-4384.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4384']::text[]),
  ('sp-4385', '4385', 'Mo hinh nhan vat 4385', 'https://kevindauto.com/products/sp-4385.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4385']::text[]),
  ('sp-4386', '4386', 'Mo hinh nhan vat 4386', 'https://kevindauto.com/products/sp-4386.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4386']::text[]),
  ('sp-4387', '4387', 'Mo hinh nhan vat 4387', 'https://kevindauto.com/products/sp-4387.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4387']::text[]),
  ('sp-4388', '4388', 'Mo hinh nhan vat 4388', 'https://kevindauto.com/products/sp-4388.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4388']::text[]),
  ('sp-4389', '4389', 'Mo hinh nhan vat 4389', 'https://kevindauto.com/products/sp-4389.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4389']::text[]),
  ('sp-4390', '4390', 'Mo hinh nhan vat 4390', 'https://kevindauto.com/products/sp-4390.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4390']::text[]),
  ('sp-4391', '4391', 'Chàng trai áo khoác cargo', 'https://kevindauto.com/products/sp-4391.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4391']::text[]),
  ('sp-4392', '4392', 'Chàng trai sơ mi cầm điện thoại', 'https://kevindauto.com/products/sp-4392.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4392']::text[]),
  ('sp-4393', '4393', 'Cô gái denim khăn quàng', 'https://kevindauto.com/products/sp-4393.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4393']::text[]),
  ('sp-4394', '4394', 'Chàng trai ngồi áo đỏ', 'https://kevindauto.com/products/sp-4394.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4394']::text[]),
  ('sp-4395', '4395', 'Cô gái tóc vàng ngồi', 'https://kevindauto.com/products/sp-4395.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4395']::text[]),
  ('sp-4396', '4396', 'Nam hút thuốc Nhật Bản', 'https://kevindauto.com/products/sp-4396.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4396']::text[]),
  ('sp-4397', '4397', 'Chàng trai áo khoác denim', 'https://kevindauto.com/products/sp-4397.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4397']::text[]),
  ('sp-4398', '4398', 'Chàng trai ngồi thùng gỗ', 'https://kevindauto.com/products/sp-4398.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4398']::text[]),
  ('sp-4399', '4399', 'Chàng trai bụi bặm denim', 'https://kevindauto.com/products/sp-4399.webp', 'nam', 'Nhan vat & Diorama', array['nam', 'nhan vat & diorama', '4399']::text[]),
  ('sp-4400', '4400', 'Chàng trai phượt chụp ảnh', 'https://kevindauto.com/products/sp-4400.webp', 'nam', 'Du lịch', array['nam', 'phượt', 'du lịch', 'ba lô', 'nhiếp ảnh', 'máy ảnh', 'đời thường']::text[]),
  ('sp-4401', '4401', 'Chàng trai áo khoác denim', 'https://kevindauto.com/products/sp-4401.webp', 'nam', 'Streetwear', array['nam', 'denim', 'jean', 'streetwear', 'đời thường', 'dạo phố']::text[]),
  ('sp-4402', '4402', 'Quý ông sơ mi thường ngày', 'https://kevindauto.com/products/sp-4402.webp', 'nam', 'Đời thường', array['nam', 'sơ mi', 'lịch lãm', 'kính', 'đời thường']::text[]),
  ('sp-4403', '4403', 'Chàng trai áo khoác parka', 'https://kevindauto.com/products/sp-4403.webp', 'nam', 'Streetwear', array['nam', 'parka', 'áo khoác', 'streetwear', 'mùa đông']::text[]),
  ('sp-4404', '4404', 'Quý ông vest đen', 'https://kevindauto.com/products/sp-4404.webp', 'nam', 'Công sở', array['nam', 'vest', 'suit', 'công sở', 'doanh nhân', 'lịch lãm']::text[]),
  ('sp-4405', '4405', 'Cầu thủ bóng rổ', 'https://kevindauto.com/products/sp-4405.webp', 'thethao', 'Thể thao', array['thể thao', 'bóng rổ', 'vận động viên', 'jersey', 'năng động']::text[]),
  ('sp-4406', '4406', 'Chàng trai áo khoác đỏ ngồi nghỉ', 'https://kevindauto.com/products/sp-4406.webp', 'nam', 'Đời thường', array['nam', 'áo đỏ', 'ngồi', 'đời thường', 'năng động']::text[]),
  ('sp-4407', '4407', 'Cặp đôi dạo phố', 'https://kevindauto.com/products/sp-4407.webp', 'giadinh', 'Cặp đôi', array['cặp đôi', 'đôi', 'tình nhân', 'hẹn hò', 'nam nữ', 'gia đình', 'hoa']::text[]),
  ('sp-4408', '4408', 'Chàng trai áo polo đỏ', 'https://kevindauto.com/products/sp-4408.webp', 'nam', 'Đời thường', array['nam', 'polo', 'casual', 'đời thường', 'quần short']::text[]),
  ('sp-4409', '4409', 'Phượt thủ ba lô lớn', 'https://kevindauto.com/products/sp-4409.webp', 'nam', 'Du lịch', array['nam', 'phượt', 'du lịch', 'ba lô', 'mũ', 'đi bộ']::text[]),
  ('sp-4410', '4410', 'Cô gái cá tính nóng bỏng', 'https://kevindauto.com/products/sp-4410.webp', 'nu', 'Cá tính', array['nữ', 'bikini', 'gợi cảm', 'biker', 'mũ bảo hiểm', 'boots']::text[]),
  ('sp-4411', '4411', 'Quý cô váy mỏng', 'https://kevindauto.com/products/sp-4411.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'váy', 'tóc vàng', 'cao gót']::text[]),
  ('sp-4412', '4412', 'Quý cô áo măng tô', 'https://kevindauto.com/products/sp-4412.webp', 'nu', 'Thanh lịch', array['nữ', 'măng tô', 'trench coat', 'thanh lịch', 'boots']::text[]),
  ('sp-4413', '4413', 'Cụ ông vest chào', 'https://kevindauto.com/products/sp-4413.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vest', 'ông', 'lịch lãm']::text[]),
  ('sp-4414', '4414', 'Cụ ông tạp dề thợ', 'https://kevindauto.com/products/sp-4414.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'cao tuổi', 'tạp dề', 'thợ', 'đầu bếp', 'ông']::text[]),
  ('sp-4415', '4415', 'Cụ ông túi đeo dạo bước', 'https://kevindauto.com/products/sp-4415.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ông', 'túi', 'đi bộ']::text[]),
  ('sp-4416', '4416', 'Chàng trai ngồi xổm xem điện thoại', 'https://kevindauto.com/products/sp-4416.webp', 'nam', 'Streetwear', array['nam', 'denim', 'ngồi xổm', 'điện thoại', 'streetwear']::text[]),
  ('sp-4417', '4417', 'Bóng đen bí ẩn', 'https://kevindauto.com/products/sp-4417.webp', 'nam', 'Độc đáo', array['nam', 'bí ẩn', 'bóng đen', 'ngồi', 'độc đáo', 'kinh dị']::text[]),
  ('sp-4418', '4418', 'Ông hoàng áo choàng', 'https://kevindauto.com/products/sp-4418.webp', 'nam', 'Độc đáo', array['nam', 'vương miện', 'áo choàng', 'hoàng gia', 'độc đáo', 'quyền lực']::text[]),
  ('sp-4419', '4419', 'Mẫu áo liền quần đỏ', 'https://kevindauto.com/products/sp-4419.webp', 'nam', 'Ấn tượng', array['đỏ', 'áo liền quần', 'money heist', 'trùm đầu', 'ấn tượng', 'unisex']::text[]),
  ('sp-4420', '4420', 'Cụ ông tạp dề xem điện thoại', 'https://kevindauto.com/products/sp-4420.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'cao tuổi', 'tạp dề', 'ông', 'điện thoại']::text[]),
  ('sp-4421', '4421', 'Quý cô áo choàng đen', 'https://kevindauto.com/products/sp-4421.webp', 'nu', 'Cá tính', array['nữ', 'đen', 'áo choàng', 'bí ẩn', 'tóc đen', 'cá tính']::text[]),
  ('sp-4422', '4422', 'Doanh nhân ngồi suy tư', 'https://kevindauto.com/products/sp-4422.webp', 'nam', 'Công sở', array['nam', 'vest', 'doanh nhân', 'ngồi', 'suy tư']::text[]),
  ('sp-4423', '4423', 'Nam sinh áo gile', 'https://kevindauto.com/products/sp-4423.webp', 'nam', 'Học đường', array['nam', 'học sinh', 'sinh viên', 'gile', 'ba lô', 'trẻ']::text[]),
  ('sp-4424', '4424', 'Quý cô nội y đen', 'https://kevindauto.com/products/sp-4424.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'nội y', 'đen', 'ngồi']::text[]),
  ('sp-4425', '4425', 'Tượng thiếu nữ cổ điển', 'https://kevindauto.com/products/sp-4425.webp', 'nu', 'Nghệ thuật', array['nữ', 'tượng', 'nghệ thuật', 'cổ điển', 'trắng', 'điêu khắc']::text[]),
  ('sp-4426', '4426', 'Người ngồi thiền hoodie', 'https://kevindauto.com/products/sp-4426.webp', 'nu', 'Thư giãn', array['thiền', 'hoodie', 'ngồi', 'yoga', 'tĩnh lặng', 'unisex']::text[]),
  ('sp-4427', '4427', 'Cô nàng áo khoác xanh cá tính', 'https://kevindauto.com/products/sp-4427.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'áo khoác xanh', 'jean', 'cá tính', 'kính']::text[]),
  ('sp-4428', '4428', 'Quý cô đầm đỏ', 'https://kevindauto.com/products/sp-4428.webp', 'nu', 'Dạ hội', array['nữ', 'đầm đỏ', 'sang trọng', 'ngồi', 'dạ hội']::text[]),
  ('sp-4429', '4429', 'Nữ mẫu bản xám (chưa sơn)', 'https://kevindauto.com/products/sp-4429.webp', 'nu', 'Prototype', array['nữ', 'xám', 'chưa sơn', 'prototype', 'hút thuốc', 'thuốc lá', 'điếu thuốc']::text[]),
  ('sp-4430', '4430', 'Cô gái tóc vàng', 'https://kevindauto.com/products/sp-4430.webp', 'nu', 'Đời thường', array['nữ', 'tóc vàng', 'đời thường', 'điện thoại']::text[]),
  ('sp-4431', '4431', 'Cô dâu váy cưới', 'https://kevindauto.com/products/sp-4431.webp', 'nu', 'Cưới', array['nữ', 'cô dâu', 'váy cưới', 'cưới', 'voan', 'lãng mạn']::text[]),
  ('sp-4432', '4432', 'Nữ sát thủ kiếm đỏ', 'https://kevindauto.com/products/sp-4432.webp', 'nu', 'Anime', array['nữ', 'kiếm', 'katana', 'đầm đỏ', 'sát thủ', 'anime', 'ấn tượng']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
