-- Lo 034: san pham 4433 den 2822
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-4433', '4433', 'Tượng nữ thần áo choàng', 'https://kevindauto.com/products/sp-4433.webp', 'nu', 'Nghệ thuật', array['nữ', 'tượng', 'nghệ thuật', 'cổ điển', 'nữ thần', 'điêu khắc', 'trắng']::text[]),
  ('sp-4434', '4434', 'Tượng thiếu nữ ngồi', 'https://kevindauto.com/products/sp-4434.webp', 'nu', 'Nghệ thuật', array['nữ', 'tượng', 'nghệ thuật', 'trắng', 'điêu khắc', 'ngồi']::text[]),
  ('sp-4435', '4435', 'Thiên thần có cánh', 'https://kevindauto.com/products/sp-4435.webp', 'nu', 'Fantasy', array['nữ', 'tượng', 'thiên thần', 'cánh', 'nghệ thuật', 'điêu khắc', 'fantasy']::text[]),
  ('sp-4436', '4436', 'Cô gái hoodie thường ngày', 'https://kevindauto.com/products/sp-4436.webp', 'nu', 'Streetwear', array['nữ', 'hoodie', 'đời thường', 'điện thoại', 'streetwear']::text[]),
  ('sp-4437', '4437', 'Cô nàng hoodie mũ lưỡi trai', 'https://kevindauto.com/products/sp-4437.webp', 'nu', 'Streetwear', array['nữ', 'hoodie', 'mũ', 'streetwear', 'năng động']::text[]),
  ('sp-4438', '4438', 'Cô gái áo denim cầm ly', 'https://kevindauto.com/products/sp-4438.webp', 'nu', 'Streetwear', array['nữ', 'denim', 'beanie', 'streetwear', 'đời thường', 'ly nước']::text[]),
  ('sp-4439', '4439', 'Shipper giao hàng', 'https://kevindauto.com/products/sp-4439.webp', 'nam', 'Nghề nghiệp', array['nam', 'shipper', 'giao hàng', 'xe máy', 'mũ bảo hiểm', 'đời thường', 'nghề nghiệp']::text[]),
  ('sp-4440', '4440', 'Gấu Kumamon áo da', 'https://kevindauto.com/products/sp-4440.webp', 'dongvat', 'Chibi', array['gấu', 'kumamon', 'chibi', 'dễ thương', 'mascot', 'đen']::text[]),
  ('sp-4441', '4441', 'Khủng long T-Rex', 'https://kevindauto.com/products/sp-4441.webp', 'dongvat', 'Khủng long', array['khủng long', 't-rex', 'động vật', 'dinosaur', 'mô hình']::text[]),
  ('sp-4442', '4442', 'Gấu bông đeo kính', 'https://kevindauto.com/products/sp-4442.webp', 'dongvat', 'Chibi', array['gấu', 'teddy', 'chibi', 'dễ thương', 'kính', 'đồ chơi']::text[]),
  ('sp-4443', '4443', 'Khủng long hoạt hình xanh', 'https://kevindauto.com/products/sp-4443.webp', 'dongvat', 'Chibi', array['khủng long', 'dinosaur', 'chibi', 'dễ thương', 'xanh', 'hoạt hình']::text[]),
  ('sp-4444', '4444', 'Cậu bé cầm máy ảnh', 'https://kevindauto.com/products/sp-4444.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'máy ảnh', 'ghế xếp', 'gia đình', 'dễ thương']::text[]),
  ('sp-4445', '4445', 'Cầu thủ bóng đá ăn mừng', 'https://kevindauto.com/products/sp-4445.webp', 'thethao', 'Thể thao', array['thể thao', 'bóng đá', 'cầu thủ', 'ăn mừng', 'jersey', 'số 7']::text[]),
  ('sp-4446', '4446', 'Chàng trai đeo kính ngồi ghế', 'https://kevindauto.com/products/sp-4446.webp', 'nam', 'Đời thường', array['nam', 'kính', 'ngồi', 'đời thường', 'ghế']::text[]),
  ('sp-4447', '4447', 'Doanh nhân thuyết trình', 'https://kevindauto.com/products/sp-4447.webp', 'nam', 'Công sở', array['nam', 'doanh nhân', 'ngồi', 'thuyết trình', 'công sở']::text[]),
  ('sp-4448', '4448', 'Quý ông vest ngồi', 'https://kevindauto.com/products/sp-4448.webp', 'nam', 'Công sở', array['nam', 'vest', 'suit', 'ngồi', 'công sở', 'lịch lãm']::text[]),
  ('sp-4449', '4449', 'Thuyền phao gắn máy', 'https://kevindauto.com/products/sp-4449.webp', 'phukien', 'Phụ kiện', array['phụ kiện', 'thuyền', 'thuyền phao', 'ca nô', 'bối cảnh', 'nước']::text[]),
  ('sp-4450', '4450', 'Thuyền phao cứu sinh', 'https://kevindauto.com/products/sp-4450.webp', 'phukien', 'Phụ kiện', array['phụ kiện', 'thuyền', 'phao cứu sinh', 'bối cảnh', 'nước']::text[]),
  ('sp-4451', '4451', 'Cô nàng trà sữa streetwear', 'https://kevindauto.com/products/sp-4451.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'beanie', 'trà sữa', 'đời thường', 'cá tính']::text[]),
  ('sp-4352', '4352', 'Nhân viên văn phòng ngồi nghỉ', 'https://kevindauto.com/products/sp-4352.webp', 'nam', 'Công sở', array['nam', 'công sở', 'sơ mi', 'cà vạt', 'ngồi', 'đời thường']::text[]),
  ('sp-4353', '4353', 'Chàng trai áo khoác cầm ly', 'https://kevindauto.com/products/sp-4353.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'áo khoác', 'ly', 'cá tính']::text[]),
  ('sp-4354', '4354', 'Chàng trai áo khoác da', 'https://kevindauto.com/products/sp-4354.webp', 'nam', 'Streetwear', array['nam', 'áo khoác da', 'streetwear', 'cá tính']::text[]),
  ('sp-4355', '4355', 'Shipper ba lô cam', 'https://kevindauto.com/products/sp-4355.webp', 'nam', 'Nghề nghiệp', array['nam', 'shipper', 'giao hàng', 'ba lô', 'điện thoại', 'nghề nghiệp']::text[]),
  ('sp-4356', '4356', 'Chàng trai áo choàng trắng', 'https://kevindauto.com/products/sp-4356.webp', 'nam', 'Streetwear', array['nam', 'áo choàng', 'trắng', 'streetwear', 'đời thường']::text[]),
  ('sp-4357', '4357', 'Chàng trai selfie', 'https://kevindauto.com/products/sp-4357.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'selfie', 'streetwear', 'đời thường']::text[]),
  ('sp-4358', '4358', 'Cô gái mũ túi dạo phố', 'https://kevindauto.com/products/sp-4358.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'mũ', 'túi', 'đời thường']::text[]),
  ('sp-4359', '4359', 'Cô gái ván trượt', 'https://kevindauto.com/products/sp-4359.webp', 'nu', 'Streetwear', array['nữ', 'ván trượt', 'skateboard', 'thể thao', 'streetwear', 'mũ']::text[]),
  ('sp-4360', '4360', 'Chàng trai sơ mi kẻ', 'https://kevindauto.com/products/sp-4360.webp', 'nam', 'Đời thường', array['nam', 'sơ mi', 'kẻ caro', 'đời thường']::text[]),
  ('sp-4361', '4361', 'Chàng trai ngồi xổm uống nước', 'https://kevindauto.com/products/sp-4361.webp', 'nam', 'Streetwear', array['nam', 'ngồi', 'streetwear', 'mũ', 'uống nước']::text[]),
  ('sp-4362', '4362', 'Chàng trai áo len cargo', 'https://kevindauto.com/products/sp-4362.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'áo len', 'cargo', 'cá tính']::text[]),
  ('sp-4363', '4363', 'Cô gái ngồi váy', 'https://kevindauto.com/products/sp-4363.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'váy', 'đời thường']::text[]),
  ('sp-4364', '4364', 'Chàng trai khoanh tay', 'https://kevindauto.com/products/sp-4364.webp', 'nam', 'Đời thường', array['nam', 'đời thường', 'trắng', 'khoanh tay']::text[]),
  ('sp-4365', '4365', 'Chàng trai denim cầm túi', 'https://kevindauto.com/products/sp-4365.webp', 'nam', 'Streetwear', array['nam', 'denim', 'mua sắm', 'túi', 'đời thường']::text[]),
  ('sp-4366', '4366', 'Chàng trai ngồi áo khoác mở', 'https://kevindauto.com/products/sp-4366.webp', 'nam', 'Streetwear', array['nam', 'ngồi', 'streetwear', 'cá tính']::text[]),
  ('sp-4367', '4367', 'Cô gái phao bơi đỏ', 'https://kevindauto.com/products/sp-4367.webp', 'nu', 'Gợi cảm', array['nữ', 'phao bơi', 'bikini', 'đỏ', 'gợi cảm', 'biển']::text[]),
  ('sp-4368', '4368', 'Cụ ông thợ tạp dề', 'https://kevindauto.com/products/sp-4368.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'cao tuổi', 'tạp dề', 'thợ', 'nghề nghiệp']::text[]),
  ('sp-4369', '4369', 'Chàng trai tạp dề', 'https://kevindauto.com/products/sp-4369.webp', 'nam', 'Nghề nghiệp', array['nam', 'tạp dề', 'đầu bếp', 'phục vụ', 'nghề nghiệp']::text[]),
  ('sp-4370', '4370', 'Quý ông cao tuổi cầm gậy', 'https://kevindauto.com/products/sp-4370.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'quý ông', 'áo khoác', 'gậy', 'mũ', 'lịch lãm']::text[]),
  ('sp-4371', '4371', 'Cô gái phao bơi tươi tắn', 'https://kevindauto.com/products/sp-4371.webp', 'nu', 'Gợi cảm', array['nữ', 'phao bơi', 'bikini', 'đỏ', 'gợi cảm', 'biển']::text[]),
  ('sp-4372', '4372', 'Cô gái mũ túi cá tính', 'https://kevindauto.com/products/sp-4372.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'mũ', 'túi', 'cá tính']::text[]),
  ('sp-4375', '4375', 'Tay đua xe', 'https://kevindauto.com/products/sp-4375.webp', 'thethao', 'Thể thao', array['thể thao', 'đua xe', 'racing', 'mũ bảo hiểm', 'vận động viên']::text[]),
  ('sp-4378', '4378', 'Xe đạp cổ điển', 'https://kevindauto.com/products/sp-4378.webp', 'xe', 'Xe đạp', array['xe đạp', 'phụ kiện', 'bối cảnh', 'xe', 'cổ điển']::text[]),
  ('sp-4379', '4379', 'Hòm thư đỏ', 'https://kevindauto.com/products/sp-4379.webp', 'phukien', 'Phụ kiện', array['phụ kiện', 'hòm thư', 'bưu điện', 'bối cảnh', 'đỏ']::text[]),
  ('sp-4380', '4380', 'Xe tay ga', 'https://kevindauto.com/products/sp-4380.webp', 'xe', 'Xe máy', array['xe máy', 'xe tay ga', 'scooter', 'phụ kiện', 'bối cảnh', 'xe']::text[]),
  ('sp-4381', '4381', 'Shipper xe đạp', 'https://kevindauto.com/products/sp-4381.webp', 'nam', 'Nghề nghiệp', array['nam', 'shipper', 'giao hàng', 'xe đạp', 'nghề nghiệp', 'mũ']::text[]),
  ('sp-4382', '4382', 'Nữ sinh đạp xe', 'https://kevindauto.com/products/sp-4382.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'xe đạp', 'đồng phục', 'học đường']::text[]),
  ('sp-4383', '4383', 'Cầu thủ bóng đá đỏ ăn mừng', 'https://kevindauto.com/products/sp-4383.webp', 'thethao', 'Thể thao', array['thể thao', 'bóng đá', 'cầu thủ', 'ăn mừng', 'đỏ']::text[]),
  ('sp-4384', '4384', 'Cô gái đầm đen thanh lịch', 'https://kevindauto.com/products/sp-4384.webp', 'nu', 'Dạ hội', array['nữ', 'đầm đen', 'đen', 'thanh lịch', 'dạ hội']::text[]),
  ('sp-4391', '4391', 'Chàng trai áo khoác cargo', 'https://kevindauto.com/products/sp-4391.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'cargo', 'streetwear']::text[]),
  ('sp-4392', '4392', 'Chàng trai sơ mi cầm điện thoại', 'https://kevindauto.com/products/sp-4392.webp', 'nam', 'Đời thường', array['nam', 'sơ mi', 'điện thoại', 'mũ', 'đời thường']::text[]),
  ('sp-4393', '4393', 'Cô gái denim khăn quàng', 'https://kevindauto.com/products/sp-4393.webp', 'nu', 'Streetwear', array['nữ', 'denim', 'khăn', 'boots', 'streetwear', 'cá tính']::text[]),
  ('sp-4394', '4394', 'Chàng trai ngồi áo đỏ', 'https://kevindauto.com/products/sp-4394.webp', 'nam', 'Streetwear', array['nam', 'ngồi', 'áo đỏ', 'đỏ', 'jean']::text[]),
  ('sp-4395', '4395', 'Cô gái tóc vàng ngồi', 'https://kevindauto.com/products/sp-4395.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'tóc vàng', 'ngồi', 'short']::text[]),
  ('sp-4396', '4396', 'Nam hút thuốc Nhật Bản', 'https://kevindauto.com/products/sp-4396.webp', 'nam', 'Tao Bao', array['nam', 'bộ đàm', 'kính râm', 'áo khoác', 'du lịch', 'phượt']::text[]),
  ('sp-4397', '4397', 'Chàng trai áo khoác denim', 'https://kevindauto.com/products/sp-4397.webp', 'nam', 'Streetwear', array['nam', 'denim', 'áo khoác', 'streetwear']::text[]),
  ('sp-4398', '4398', 'Chàng trai ngồi thùng gỗ', 'https://kevindauto.com/products/sp-4398.webp', 'nam', 'Streetwear', array['nam', 'ngồi', 'streetwear', 'mũ']::text[]),
  ('sp-4399', '4399', 'Chàng trai bụi bặm denim', 'https://kevindauto.com/products/sp-4399.webp', 'nam', 'Streetwear', array['nam', 'denim', 'streetwear', 'cá tính', 'đỏ']::text[]),
  ('sp-2800', '2800', 'Mèo Thần Tài may mắn', 'https://kevindauto.com/products/sp-2800.webp', 'dongvat', 'Mascot', array['mèo', 'thần tài', 'may mắn', 'mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-2801', '2801', 'Cụ ông áo blouse khoanh tay', 'https://kevindauto.com/products/sp-2801.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'cao tuổi', 'ông', 'áo blouse', 'khoanh tay']::text[]),
  ('sp-2802', '2802', 'Cầu thủ bóng đá kéo áo ăn mừng', 'https://kevindauto.com/products/sp-2802.webp', 'thethao', 'Thể thao', array['thể thao', 'bóng đá', 'cầu thủ', 'ăn mừng', 'áo đỏ', 'số 4']::text[]),
  ('sp-2803', '2803', 'Cầu thủ bóng đá ăn mừng cuồng nhiệt', 'https://kevindauto.com/products/sp-2803.webp', 'thethao', 'Thể thao', array['thể thao', 'bóng đá', 'cầu thủ', 'ăn mừng', 'áo đỏ']::text[]),
  ('sp-2804', '2804', 'Chàng trai hoodie xám tay ôm đầu', 'https://kevindauto.com/products/sp-2804.webp', 'nam', 'Đời thường', array['nam', 'hoodie', 'streetwear', 'đời thường', 'kính']::text[]),
  ('sp-2805', '2805', 'Người áo khoác xanh rêu bí ẩn', 'https://kevindauto.com/products/sp-2805.webp', 'nam', 'Độc đáo', array['nam', 'áo khoác', 'bí ẩn', 'độc đáo', 'xanh rêu']::text[]),
  ('sp-2806', '2806', 'Cô gái tóc bạch kim cầm điện thoại', 'https://kevindauto.com/products/sp-2806.webp', 'nu', 'Đời thường', array['nữ', 'tóc vàng', 'kính', 'điện thoại', 'đời thường']::text[]),
  ('sp-2807', '2807', 'Cô gái áo khoác be dạo phố', 'https://kevindauto.com/products/sp-2807.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'dạo phố', 'đời thường']::text[]),
  ('sp-2808', '2808', 'Người nông dân ôm bó rau', 'https://kevindauto.com/products/sp-2808.webp', 'nam', 'Nghề nghiệp', array['nông dân', 'rau', 'nghề nghiệp', 'lao động']::text[]),
  ('sp-2809', '2809', 'Đầu bếp chế biến món ăn', 'https://kevindauto.com/products/sp-2809.webp', 'nam', 'Nghề nghiệp', array['đầu bếp', 'nghề nghiệp', 'nấu ăn', 'tạp dề']::text[]),
  ('sp-2810', '2810', 'Người áo choàng kẻ sọc trùm đầu', 'https://kevindauto.com/products/sp-2810.webp', 'nam', 'Độc đáo', array['áo choàng', 'bí ẩn', 'độc đáo', 'trùm đầu']::text[]),
  ('sp-2811', '2811', 'Chàng trai áo khoác graffiti cầm ván trượt', 'https://kevindauto.com/products/sp-2811.webp', 'nam', 'Streetwear', array['nam', 'ván trượt', 'skateboard', 'streetwear', 'áo khoác']::text[]),
  ('sp-2812', '2812', 'Chàng trai trượt ván đường phố', 'https://kevindauto.com/products/sp-2812.webp', 'nam', 'Streetwear', array['nam', 'ván trượt', 'skateboard', 'streetwear', 'thể thao', 'mũ']::text[]),
  ('sp-2813', '2813', 'Thành viên đội đua ngồi nghỉ', 'https://kevindauto.com/products/sp-2813.webp', 'thethao', 'Đua xe', array['đua xe', 'racing', 'pit crew', 'ngồi nghỉ', 'thể thao']::text[]),
  ('sp-2814', '2814', 'Cô gái hoodie xám đứng tự nhiên', 'https://kevindauto.com/products/sp-2814.webp', 'nu', 'Đời thường', array['nữ', 'hoodie', 'đời thường']::text[]),
  ('sp-2815', '2815', 'Tay đua ăn mừng chiến thắng', 'https://kevindauto.com/products/sp-2815.webp', 'thethao', 'Đua xe', array['đua xe', 'racing', 'mũ bảo hiểm', 'ăn mừng', 'thể thao']::text[]),
  ('sp-2816', '2816', 'Thợ máy đội đua bên giá lốp', 'https://kevindauto.com/products/sp-2816.webp', 'thethao', 'Đua xe', array['đua xe', 'pit crew', 'lốp xe', 'cơ khí', 'racing']::text[]),
  ('sp-2817', '2817', 'Thợ máy thay lốp xe đua', 'https://kevindauto.com/products/sp-2817.webp', 'thethao', 'Đua xe', array['đua xe', 'pit crew', 'lốp xe', 'thay lốp', 'racing']::text[]),
  ('sp-2818', '2818', 'Chỉ huy đội đua đeo tai nghe', 'https://kevindauto.com/products/sp-2818.webp', 'thethao', 'Đua xe', array['đua xe', 'racing', 'tai nghe', 'chỉ huy', 'pit crew']::text[]),
  ('sp-2819', '2819', 'Thợ máy cúi kiểm tra xe đua', 'https://kevindauto.com/products/sp-2819.webp', 'thethao', 'Đua xe', array['đua xe', 'cơ khí', 'kiểm tra', 'pit crew', 'racing']::text[]),
  ('sp-2820', '2820', 'Thợ máy đổ nhiên liệu pit stop', 'https://kevindauto.com/products/sp-2820.webp', 'thethao', 'Đua xe', array['đua xe', 'pit stop', 'nhiên liệu', 'cơ khí', 'racing']::text[]),
  ('sp-2821', '2821', 'Tay đua bộ đồ đua xanh navy', 'https://kevindauto.com/products/sp-2821.webp', 'thethao', 'Đua xe', array['đua xe', 'racing', 'bộ đồ đua', 'mũ bảo hiểm', 'thể thao']::text[]),
  ('sp-2822', '2822', 'Người cầm cờ về đích', 'https://kevindauto.com/products/sp-2822.webp', 'thethao', 'Đua xe', array['đua xe', 'cờ caro', 'về đích', 'chiến thắng', 'racing']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
