-- Lo 035: san pham 2823 den 51
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-2823', '2823', 'Tay đua nhảy ăn mừng', 'https://kevindauto.com/products/sp-2823.webp', 'thethao', 'Đua xe', array['đua xe', 'ăn mừng', 'mũ bảo hiểm', 'chiến thắng', 'racing']::text[]),
  ('sp-2824', '2824', 'Cô gái cầm cờ đua xe', 'https://kevindauto.com/products/sp-2824.webp', 'nu', 'Đua xe', array['nữ', 'đua xe', 'cờ caro', 'grid girl', 'racing']::text[]),
  ('sp-2825', '2825', 'Cô gái ăn mừng với cờ đua', 'https://kevindauto.com/products/sp-2825.webp', 'nu', 'Đua xe', array['nữ', 'đua xe', 'cờ caro', 'ăn mừng', 'racing']::text[]),
  ('sp-2826', '2826', 'Cô gái áo khoác đỏ dáng dài', 'https://kevindauto.com/products/sp-2826.webp', 'nu', 'Thanh lịch', array['nữ', 'áo khoác', 'đỏ', 'thanh lịch']::text[]),
  ('sp-2827', '2827', 'Cô gái áo khoác đỏ túi đeo vai', 'https://kevindauto.com/products/sp-2827.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác đỏ', 'túi xách', 'đời thường']::text[]),
  ('sp-2828', '2828', 'Chú đeo kính mát áo da ngầu', 'https://kevindauto.com/products/sp-2828.webp', 'nam', 'Streetwear', array['nam', 'kính mát', 'áo da', 'ngầu', 'cá tính', 'streetwear']::text[]),
  ('sp-2829', '2829', 'Chàng trai đeo khẩu trang xem điện thoại', 'https://kevindauto.com/products/sp-2829.webp', 'nam', 'Đời thường', array['nam', 'khẩu trang', 'điện thoại', 'đời thường', 'mũ']::text[]),
  ('sp-2830', '2830', 'Chàng trai mũ lưỡi trai đeo khẩu trang', 'https://kevindauto.com/products/sp-2830.webp', 'nam', 'Streetwear', array['nam', 'khẩu trang', 'mũ lưỡi trai', 'streetwear']::text[]),
  ('sp-2831', '2831', 'Cô gái áo khoác đen cầm điện thoại', 'https://kevindauto.com/products/sp-2831.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác đen', 'điện thoại', 'đời thường']::text[]),
  ('sp-2832', '2832', 'Chàng trai áo phông cargo cầm điện thoại', 'https://kevindauto.com/products/sp-2832.webp', 'nam', 'Streetwear', array['nam', 'cargo', 'mũ lưỡi trai', 'điện thoại', 'streetwear']::text[]),
  ('sp-2833', '2833', 'Chàng trai áo khoác đen dáng thư thái', 'https://kevindauto.com/products/sp-2833.webp', 'nam', 'Đời thường', array['nam', 'áo khoác đen', 'đời thường']::text[]),
  ('sp-2834', '2834', 'Võ sĩ ăn mừng chiến thắng', 'https://kevindauto.com/products/sp-2834.webp', 'thethao', 'Võ thuật', array['thể thao', 'võ thuật', 'ăn mừng', 'cơ bắp']::text[]),
  ('sp-2835', '2835', 'Lực sĩ tạo dáng cơ bắp', 'https://kevindauto.com/products/sp-2835.webp', 'thethao', 'Thể hình', array['thể thao', 'thể hình', 'cơ bắp', 'gymer']::text[]),
  ('sp-2836', '2836', 'Nam mẫu bản trắng (chưa sơn)', 'https://kevindauto.com/products/sp-2836.webp', 'nam', 'Prototype', array['nam', 'chưa sơn', 'prototype', 'trắng']::text[]),
  ('sp-2837', '2837', 'Nam mẫu bản trắng dáng đứng', 'https://kevindauto.com/products/sp-2837.webp', 'nam', 'Prototype', array['nam', 'chưa sơn', 'prototype', 'trắng', 'đứng']::text[]),
  ('sp-2838', '2838', 'Lực sĩ cơ bắp săn chắc', 'https://kevindauto.com/products/sp-2838.webp', 'thethao', 'Thể hình', array['thể thao', 'thể hình', 'cơ bắp', 'gymer']::text[]),
  ('sp-2839', '2839', 'Nữ sinh áo polo chân váy caro', 'https://kevindauto.com/products/sp-2839.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'học đường', 'caro', 'sinh viên']::text[]),
  ('sp-2840', '2840', 'Cô gái mũ bucket phong cách năng động', 'https://kevindauto.com/products/sp-2840.webp', 'nu', 'Streetwear', array['nữ', 'mũ bucket', 'streetwear', 'năng động']::text[]),
  ('sp-2841', '2841', 'Cô nàng hoodie đen cúi nhìn điện thoại', 'https://kevindauto.com/products/sp-2841.webp', 'nu', 'Đời thường', array['nữ', 'hoodie đen', 'điện thoại', 'đời thường']::text[]),
  ('sp-2842', '2842', 'Chuột lang đội sừng tuần lộc', 'https://kevindauto.com/products/sp-2842.webp', 'dongvat', 'Chibi', array['chuột lang', 'hamster', 'sừng', 'giáng sinh', 'dễ thương', 'chibi']::text[]),
  ('sp-2843', '2843', 'Hải ly kính mát cầm ly nước', 'https://kevindauto.com/products/sp-2843.webp', 'dongvat', 'Chibi', array['hải ly', 'kính mát', 'sừng', 'dễ thương', 'ly nước', 'chibi']::text[]),
  ('sp-2844', '2844', 'Cụ ông vest nghe điện thoại', 'https://kevindauto.com/products/sp-2844.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vest', 'điện thoại', 'lịch lãm']::text[]),
  ('sp-2845', '2845', 'Chú bảo vệ áo khoác xanh', 'https://kevindauto.com/products/sp-2845.webp', 'nam', 'Nghề nghiệp', array['bảo vệ', 'nghề nghiệp', 'áo khoác', 'an ninh']::text[]),
  ('sp-2846', '2846', 'Chú công nhân đội nón lá', 'https://kevindauto.com/products/sp-2846.webp', 'nam', 'Nghề nghiệp', array['công nhân', 'nón lá', 'nghề nghiệp', 'việt nam', 'lao động']::text[]),
  ('sp-2847', '2847', 'Cụ ông áo nâu dáng lao động', 'https://kevindauto.com/products/sp-2847.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'lao động', 'áo nâu']::text[]),
  ('sp-2848', '2848', 'Em bé cầm que kem', 'https://kevindauto.com/products/sp-2848.webp', 'treem', 'Trẻ em', array['trẻ em', 'kem', 'dễ thương', 'gia đình', 'bé trai']::text[]),
  ('sp-2849', '2849', 'Cô gái áo thun xám dáng đứng', 'https://kevindauto.com/products/sp-2849.webp', 'nu', 'Đời thường', array['nữ', 'áo xám', 'đời thường']::text[]),
  ('sp-2850', '2850', 'Đôi bạn thân phong cách đường phố', 'https://kevindauto.com/products/sp-2850.webp', 'giadinh', 'Đôi bạn', array['đôi bạn', 'streetwear', 'nhóm bạn', 'cặp đôi', 'nam']::text[]),
  ('sp-2851', '2851', 'Cô gái váy hồng tạo dáng chỉ tay', 'https://kevindauto.com/products/sp-2851.webp', 'nu', 'Đời thường', array['nữ', 'váy', 'dạo phố', 'đời thường']::text[]),
  ('sp-1', '1', 'Người ngồi ghế đẩu tay đan vào nhau', 'https://kevindauto.com/products/sp-1.webp', 'nam', 'Prototype', array['ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-2', '2', 'Người quỳ gối chắp tay', 'https://kevindauto.com/products/sp-2.webp', 'nam', 'Prototype', array['quỳ', 'chắp tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-3', '3', 'Người ngồi vắt chân thư giãn', 'https://kevindauto.com/products/sp-3.webp', 'nam', 'Prototype', array['ngồi', 'thư giãn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-4', '4', 'Người đứng uống nước', 'https://kevindauto.com/products/sp-4.webp', 'nam', 'Prototype', array['đứng', 'uống nước', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-5', '5', 'Người đứng tay chạm cằm suy tư', 'https://kevindauto.com/products/sp-5.webp', 'nam', 'Prototype', array['đứng', 'suy tư', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-6', '6', 'Người đội mũ tay đưa lên miệng', 'https://kevindauto.com/products/sp-6.webp', 'nam', 'Prototype', array['đứng', 'mũ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-7', '7', 'Người đứng khoanh tay', 'https://kevindauto.com/products/sp-7.webp', 'nam', 'Prototype', array['đứng', 'khoanh tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-8', '8', 'Người đứng cầm mũ', 'https://kevindauto.com/products/sp-8.webp', 'nam', 'Prototype', array['đứng', 'mũ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-9', '9', 'Người đứng dáng thư thái', 'https://kevindauto.com/products/sp-9.webp', 'nam', 'Prototype', array['đứng', 'hoodie', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-10', '10', 'Người đứng chỉ tay phía trước', 'https://kevindauto.com/products/sp-10.webp', 'nam', 'Prototype', array['đứng', 'chỉ tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-11', '11', 'Người đứng vẫy tay', 'https://kevindauto.com/products/sp-11.webp', 'nam', 'Prototype', array['đứng', 'vẫy tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-12', '12', 'Người giơ tay ăn mừng', 'https://kevindauto.com/products/sp-12.webp', 'thethao', 'Prototype', array['ăn mừng', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-13', '13', 'Người giơ hai tay ăn mừng chiến thắng', 'https://kevindauto.com/products/sp-13.webp', 'thethao', 'Prototype', array['ăn mừng', 'chiến thắng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-14', '14', 'Người chơi bóng rổ bật nhảy ném bóng', 'https://kevindauto.com/products/sp-14.webp', 'thethao', 'Thể thao', array['bóng rổ', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-15', '15', 'Người tư thế võ thuật', 'https://kevindauto.com/products/sp-15.webp', 'thethao', 'Thể thao', array['võ thuật', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-16', '16', 'Người đứng cầm đàn guitar', 'https://kevindauto.com/products/sp-16.webp', 'nam', 'Nhạc cụ', array['guitar', 'nhạc cụ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-17', '17', 'Người đứng tay chạm cằm', 'https://kevindauto.com/products/sp-17.webp', 'nam', 'Prototype', array['đứng', 'suy tư', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-18', '18', 'Người đứng khoanh tay áo rộng', 'https://kevindauto.com/products/sp-18.webp', 'nam', 'Prototype', array['đứng', 'khoanh tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-19', '19', 'Người đứng tay che mắt nhìn xa', 'https://kevindauto.com/products/sp-19.webp', 'nam', 'Prototype', array['đứng', 'nhìn xa', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-20', '20', 'Người đội mũ khoanh tay', 'https://kevindauto.com/products/sp-20.webp', 'nam', 'Prototype', array['đứng', 'mũ', 'khoanh tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-21', '21', 'Người đứng tay ôm đầu', 'https://kevindauto.com/products/sp-21.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-22', '22', 'Người đeo balo đứng nhìn nghiêng', 'https://kevindauto.com/products/sp-22.webp', 'nam', 'Prototype', array['đứng', 'ba lô', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-23', '23', 'Người áo khoác đội mũ đứng', 'https://kevindauto.com/products/sp-23.webp', 'nam', 'Prototype', array['đứng', 'áo khoác', 'mũ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-24', '24', 'Người đứng quay đầu nhìn lại', 'https://kevindauto.com/products/sp-24.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-25', '25', 'Người tóc dài dáng đứng', 'https://kevindauto.com/products/sp-25.webp', 'nam', 'Prototype', array['đứng', 'tóc dài', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-26', '26', 'Người ném rổ', 'https://kevindauto.com/products/sp-26.webp', 'thethao', 'Thể thao', array['bóng rổ', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-27', '27', 'Cụ ông vẫy tay chào', 'https://kevindauto.com/products/sp-27.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vẫy tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-28', '28', 'Người ngồi chơi đàn guitar', 'https://kevindauto.com/products/sp-28.webp', 'nam', 'Nhạc cụ', array['guitar', 'nhạc cụ', 'ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-29', '29', 'Người áo choàng dang tay', 'https://kevindauto.com/products/sp-29.webp', 'nam', 'Prototype', array['áo choàng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-30', '30', 'Người đứng giơ tay cầm đồ vật', 'https://kevindauto.com/products/sp-30.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-31', '31', 'Người quay phim cầm máy quay', 'https://kevindauto.com/products/sp-31.webp', 'nam', 'Nghề nghiệp', array['máy quay', 'nghề nghiệp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-32', '32', 'Người trùm mũ chắp tay', 'https://kevindauto.com/products/sp-32.webp', 'nam', 'Prototype', array['hoodie', 'chắp tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-33', '33', 'Người đội mũ đứng thư giãn', 'https://kevindauto.com/products/sp-33.webp', 'nam', 'Prototype', array['mũ', 'đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-34', '34', 'Người áo choàng dài', 'https://kevindauto.com/products/sp-34.webp', 'nam', 'Prototype', array['áo choàng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-35', '35', 'Người đứng chào kiểu salute', 'https://kevindauto.com/products/sp-35.webp', 'nam', 'Prototype', array['salute', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-36', '36', 'Người mang túi đồ nghề', 'https://kevindauto.com/products/sp-36.webp', 'nam', 'Nghề nghiệp', array['nghề nghiệp', 'túi đồ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-37', '37', 'Người áo khoác dài đứng', 'https://kevindauto.com/products/sp-37.webp', 'nam', 'Prototype', array['áo khoác', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-38', '38', 'Người đưa tay lên gọi điện', 'https://kevindauto.com/products/sp-38.webp', 'nam', 'Prototype', array['điện thoại', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-39', '39', 'Người giơ tay vẫy chào', 'https://kevindauto.com/products/sp-39.webp', 'nam', 'Prototype', array['vẫy tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-40', '40', 'Quý ông áo vest tay đút túi', 'https://kevindauto.com/products/sp-40.webp', 'nam', 'Công sở', array['vest', 'công sở', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-41', '41', 'Người đứng dáng nghiêng thư thái', 'https://kevindauto.com/products/sp-41.webp', 'nam', 'Prototype', array['áo khoác', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-42', '42', 'Người đứng phong cách bụi', 'https://kevindauto.com/products/sp-42.webp', 'nam', 'Streetwear', array['streetwear', 'mũ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-43', '43', 'Người đứng tay chạm đầu', 'https://kevindauto.com/products/sp-43.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-44', '44', 'Người đội mũ bảo hiểm dáng đứng', 'https://kevindauto.com/products/sp-44.webp', 'nam', 'Prototype', array['mũ bảo hiểm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-45', '45', 'Người giơ nắm đấm', 'https://kevindauto.com/products/sp-45.webp', 'thethao', 'Prototype', array['ăn mừng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-46', '46', 'Người đội mũ chỉ tay', 'https://kevindauto.com/products/sp-46.webp', 'nam', 'Prototype', array['mũ', 'chỉ tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-47', '47', 'Người tóc dài tay đưa ra', 'https://kevindauto.com/products/sp-47.webp', 'nam', 'Prototype', array['tóc dài', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-48', '48', 'Người áo choàng dài truyền thống', 'https://kevindauto.com/products/sp-48.webp', 'nam', 'Độc đáo', array['áo choàng', 'truyền thống', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-49', '49', 'Người lính tư thế canh gác', 'https://kevindauto.com/products/sp-49.webp', 'nam', 'Độc đáo', array['lính', 'quân sự', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-50', '50', 'Lực sĩ cơ bắp khổng lồ', 'https://kevindauto.com/products/sp-50.webp', 'thethao', 'Thể hình', array['thể hình', 'cơ bắp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-51', '51', 'Người mặc tạp dề công việc', 'https://kevindauto.com/products/sp-51.webp', 'nam', 'Nghề nghiệp', array['tạp dề', 'nghề nghiệp', 'chưa sơn', 'prototype', 'bản xám']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
