-- Lo 036: san pham 52 den 131
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-52', '52', 'Người ngồi ghế thư giãn', 'https://kevindauto.com/products/sp-52.webp', 'nam', 'Prototype', array['ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-53', '53', 'Người ngồi tựa lưng thư giãn', 'https://kevindauto.com/products/sp-53.webp', 'nam', 'Prototype', array['ngồi', 'thư giãn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-54', '54', 'Người quỳ cúi người', 'https://kevindauto.com/products/sp-54.webp', 'nam', 'Prototype', array['quỳ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-55', '55', 'Nhà sư ngồi thiền', 'https://kevindauto.com/products/sp-55.webp', 'nam', 'Độc đáo', array['nhà sư', 'thiền', 'áo cà sa', 'tĩnh lặng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-56', '56', 'Người quỳ giơ tay cầu nguyện', 'https://kevindauto.com/products/sp-56.webp', 'nam', 'Độc đáo', array['quỳ', 'cầu nguyện', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-57', '57', 'Người đứng chỉ tay lên trời', 'https://kevindauto.com/products/sp-57.webp', 'thethao', 'Prototype', array['thể thao', 'chỉ tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-58', '58', 'Người đứng dáng thể thao', 'https://kevindauto.com/products/sp-58.webp', 'thethao', 'Thể thao', array['thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-59', '59', 'Người đứng dáng thể thao thoải mái', 'https://kevindauto.com/products/sp-59.webp', 'thethao', 'Thể thao', array['thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-60', '60', 'Người đứng tay chạm miệng', 'https://kevindauto.com/products/sp-60.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-61', '61', 'Người đứng tạo dáng chân gác cao', 'https://kevindauto.com/products/sp-61.webp', 'thethao', 'Thể thao', array['thể thao', 'tạo dáng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-62', '62', 'Người đứng tạo dáng thể thao', 'https://kevindauto.com/products/sp-62.webp', 'thethao', 'Thể thao', array['thể thao', 'cơ bắp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-63', '63', 'Người đứng cầm vật trong tay', 'https://kevindauto.com/products/sp-63.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-64', '64', 'Người áo choàng có mũ trùm', 'https://kevindauto.com/products/sp-64.webp', 'nam', 'Độc đáo', array['áo choàng', 'mũ trùm', 'bí ẩn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-65', '65', 'Người đứng dáng thư thái', 'https://kevindauto.com/products/sp-65.webp', 'thethao', 'Prototype', array['thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-66', '66', 'Người đứng dáng anh hùng cơ bắp', 'https://kevindauto.com/products/sp-66.webp', 'thethao', 'Thể hình', array['thể hình', 'cơ bắp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-67', '67', 'Người đứng áo khoác casual', 'https://kevindauto.com/products/sp-67.webp', 'nam', 'Prototype', array['áo khoác', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-68', '68', 'Người đứng phong cách hiện đại', 'https://kevindauto.com/products/sp-68.webp', 'nam', 'Prototype', array['đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-69', '69', 'Nhân vật fantasy tư thế động', 'https://kevindauto.com/products/sp-69.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-70', '70', 'Nhân vật hành động tư thế bay nhảy', 'https://kevindauto.com/products/sp-70.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-71', '71', 'Người mặc áo dài tay đứng yên', 'https://kevindauto.com/products/sp-71.webp', 'nam', 'Độc đáo', array['áo dài', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-72', '72', 'Người đứng tay đặt trước ngực', 'https://kevindauto.com/products/sp-72.webp', 'nam', 'Nghề nghiệp', array['nghề nghiệp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-73', '73', 'Nhân vật fantasy tinh linh nhỏ', 'https://kevindauto.com/products/sp-73.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'nhân vật nhỏ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-74', '74', 'Tướng quân tư thế uy nghiêm', 'https://kevindauto.com/products/sp-74.webp', 'nam', 'Cổ trang', array['tướng quân', 'cổ trang', 'áo giáp', 'độc đáo', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-75', '75', 'Vua Khỉ cầm gậy như ý', 'https://kevindauto.com/products/sp-75.webp', 'nam', 'Cổ trang', array['fantasy', 'cổ trang', 'độc đáo', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-76', '76', 'Nhân vật hoạt hình thân tròn', 'https://kevindauto.com/products/sp-76.webp', 'nam', 'Fantasy', array['hoạt hình', 'độc đáo', 'fantasy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-77', '77', 'Nhân vật ninja tư thế hành động', 'https://kevindauto.com/products/sp-77.webp', 'nam', 'Fantasy', array['ninja', 'hành động', 'độc đáo', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-78', '78', 'Nhân vật fantasy đội mũ lông', 'https://kevindauto.com/products/sp-78.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'mũ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-79', '79', 'Người ngồi ghế bành thư giãn', 'https://kevindauto.com/products/sp-79.webp', 'nam', 'Prototype', array['ngồi', 'ghế bành', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-80', '80', 'Nhân vật áo giáp tư thế hành động', 'https://kevindauto.com/products/sp-80.webp', 'nam', 'Fantasy', array['fantasy', 'áo giáp', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-81', '81', 'Người bế em bé', 'https://kevindauto.com/products/sp-81.webp', 'treem', 'Trẻ em', array['gia đình', 'bế trẻ', 'ấm áp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-82', '82', 'Nhân vật hoạt hình dáng tròn', 'https://kevindauto.com/products/sp-82.webp', 'nam', 'Fantasy', array['hoạt hình', 'độc đáo', 'fantasy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-83', '83', 'Nhân vật fantasy nữ tinh nghịch', 'https://kevindauto.com/products/sp-83.webp', 'nu', 'Fantasy', array['fantasy', 'nữ', 'độc đáo', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-84', '84', 'Người vác bao tải lớn', 'https://kevindauto.com/products/sp-84.webp', 'nam', 'Nghề nghiệp', array['lao động', 'nghề nghiệp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-85', '85', 'Người ngồi tựa thoải mái', 'https://kevindauto.com/products/sp-85.webp', 'nam', 'Prototype', array['ngồi', 'thư giãn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-86', '86', 'Người nằm thư giãn', 'https://kevindauto.com/products/sp-86.webp', 'nam', 'Prototype', array['nằm', 'thư giãn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-87', '87', 'Người ngồi cúi đầu xem tay', 'https://kevindauto.com/products/sp-87.webp', 'nam', 'Prototype', array['ngồi', 'điện thoại', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-88', '88', 'Người ngồi ăn uống trên ghế cao', 'https://kevindauto.com/products/sp-88.webp', 'nam', 'Prototype', array['ngồi', 'ăn uống', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-89', '89', 'Người ngồi ghế bắt chéo chân', 'https://kevindauto.com/products/sp-89.webp', 'nam', 'Prototype', array['ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-90', '90', 'Người đội mũ lông vũ ngồi xếp bằng', 'https://kevindauto.com/products/sp-90.webp', 'nam', 'Độc đáo', array['mũ lông', 'ngồi', 'truyền thống', 'độc đáo', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-91', '91', 'Người ngồi bàn làm việc', 'https://kevindauto.com/products/sp-91.webp', 'nam', 'Công sở', array['công sở', 'bàn làm việc', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-92', '92', 'Người ngồi xổm tay che mặt', 'https://kevindauto.com/products/sp-92.webp', 'nam', 'Prototype', array['ngồi xổm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-93', '93', 'Người ngồi xổm tay chống gối', 'https://kevindauto.com/products/sp-93.webp', 'nam', 'Prototype', array['ngồi xổm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-94', '94', 'Người ngồi khoanh tay cởi trần', 'https://kevindauto.com/products/sp-94.webp', 'thethao', 'Thể thao', array['ngồi', 'cởi trần', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-95', '95', 'Người ngồi ôm vật tròn', 'https://kevindauto.com/products/sp-95.webp', 'nam', 'Prototype', array['ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-96', '96', 'Người ngồi trầm tư', 'https://kevindauto.com/products/sp-96.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ngồi', 'trầm tư', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-97', '97', 'Người quỳ ăn mừng chiến thắng', 'https://kevindauto.com/products/sp-97.webp', 'thethao', 'Thể thao', array['quỳ', 'ăn mừng', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-98', '98', 'Người ngồi duỗi chân thư giãn', 'https://kevindauto.com/products/sp-98.webp', 'nam', 'Prototype', array['ngồi', 'thư giãn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-99', '99', 'Người đứng gồng cơ tay', 'https://kevindauto.com/products/sp-99.webp', 'thethao', 'Thể hình', array['thể hình', 'cơ bắp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-100', '100', 'Chàng trai cởi trần gồng cơ', 'https://kevindauto.com/products/sp-100.webp', 'nam', 'Prototype', array['nam', 'cởi trần', 'cơ bắp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-101', '101', 'Chàng trai áo phông tạo dáng cá tính', 'https://kevindauto.com/products/sp-101.webp', 'nam', 'Prototype', array['nam', 'áo phông', 'cá tính', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-102', '102', 'Người đàn ông khoanh tay', 'https://kevindauto.com/products/sp-102.webp', 'nam', 'Prototype', array['nam', 'khoanh tay', 'đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-103', '103', 'Chàng trai cúi vuốt ve chó cưng', 'https://kevindauto.com/products/sp-103.webp', 'nam', 'Prototype', array['nam', 'chó', 'thú cưng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-104', '104', 'Chàng trai áo khoác đút túi', 'https://kevindauto.com/products/sp-104.webp', 'nam', 'Prototype', array['nam', 'áo khoác', 'đút túi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-105', '105', 'Chàng trai vẫy tay mời gọi', 'https://kevindauto.com/products/sp-105.webp', 'nam', 'Prototype', array['nam', 'vẫy tay', 'áo rộng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-106', '106', 'Chàng trai hoodie cúi người', 'https://kevindauto.com/products/sp-106.webp', 'nam', 'Prototype', array['nam', 'hoodie', 'cúi người', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-107', '107', 'Chàng trai đeo túi máy ảnh', 'https://kevindauto.com/products/sp-107.webp', 'nam', 'Prototype', array['nam', 'túi máy ảnh', 'đi bộ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-108', '108', 'Chàng trai cúi chụp ảnh', 'https://kevindauto.com/products/sp-108.webp', 'nam', 'Prototype', array['nam', 'chụp ảnh', 'cúi người', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-109', '109', 'Lính đặc nhiệm ngắm bắn', 'https://kevindauto.com/products/sp-109.webp', 'nam', 'Prototype', array['nam', 'lính', 'quân sự', 'súng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-110', '110', 'Lính đặc nhiệm đứng gác', 'https://kevindauto.com/products/sp-110.webp', 'nam', 'Prototype', array['nam', 'lính', 'quân sự', 'mũ bảo hiểm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-111', '111', 'Lính đặc nhiệm cầm súng', 'https://kevindauto.com/products/sp-111.webp', 'nam', 'Prototype', array['nam', 'lính', 'quân sự', 'súng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-112', '112', 'Lính nguỵ trang tư thế phục kích', 'https://kevindauto.com/products/sp-112.webp', 'nam', 'Prototype', array['nam', 'lính', 'quân sự', 'nguỵ trang', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-113', '113', 'Tay súng phong cách hành động', 'https://kevindauto.com/products/sp-113.webp', 'nam', 'Prototype', array['nam', 'súng', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-114', '114', 'Người đàn ông vạm vỡ cầm dụng cụ', 'https://kevindauto.com/products/sp-114.webp', 'nam', 'Prototype', array['nam', 'vạm vỡ', 'dụng cụ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-115', '115', 'Thợ cơ khí áo liền quần', 'https://kevindauto.com/products/sp-115.webp', 'nam', 'Prototype', array['nam', 'thợ', 'cơ khí', 'nghề nghiệp', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-116', '116', 'Chàng trai đội mũ lưỡi trai tạo dáng', 'https://kevindauto.com/products/sp-116.webp', 'nam', 'Prototype', array['nam', 'mũ lưỡi trai', 'cá tính', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-117', '117', 'Quý ông vest tự tin diễn thuyết', 'https://kevindauto.com/products/sp-117.webp', 'nam', 'Prototype', array['nam', 'vest', 'công sở', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-118', '118', 'Chàng trai dắt chó đi dạo', 'https://kevindauto.com/products/sp-118.webp', 'nam', 'Prototype', array['nam', 'chó', 'dắt chó', 'thú cưng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-119', '119', 'Vận động viên đang chạy bộ', 'https://kevindauto.com/products/sp-119.webp', 'thethao', 'Prototype', array['nam', 'chạy bộ', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-120', '120', 'Người đàn ông quỳ suy tư', 'https://kevindauto.com/products/sp-120.webp', 'nam', 'Prototype', array['nam', 'quỳ', 'suy tư', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-121', '121', 'Biker đội mũ bảo hiểm ngồi xổm', 'https://kevindauto.com/products/sp-121.webp', 'nam', 'Prototype', array['nam', 'mũ bảo hiểm', 'ngồi xổm', 'biker', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-122', '122', 'Chàng trai sải bước tự nhiên', 'https://kevindauto.com/products/sp-122.webp', 'nam', 'Prototype', array['nam', 'đi bộ', 'tự nhiên', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-123', '123', 'Chàng trai đứng thoải mái', 'https://kevindauto.com/products/sp-123.webp', 'nam', 'Prototype', array['nam', 'đứng', 'thoải mái', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-124', '124', 'Chàng trai xách túi đi bộ', 'https://kevindauto.com/products/sp-124.webp', 'nam', 'Prototype', array['nam', 'xách túi', 'đi bộ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-125', '125', 'Người lái mô tô phong cách', 'https://kevindauto.com/products/sp-125.webp', 'xe', 'Prototype', array['nam', 'mô tô', 'xe máy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-126', '126', 'Quý ông vest đút túi tự tin', 'https://kevindauto.com/products/sp-126.webp', 'nam', 'Prototype', array['nam', 'vest', 'công sở', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-127', '127', 'Chàng trai tung chân đá', 'https://kevindauto.com/products/sp-127.webp', 'nam', 'Prototype', array['nam', 'đá', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-128', '128', 'Mô hình xe mô tô cổ điển', 'https://kevindauto.com/products/sp-128.webp', 'xe', 'Prototype', array['mô tô', 'xe máy', 'cổ điển', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-129', '129', 'Mascot mèo đội mũ lưỡi trai', 'https://kevindauto.com/products/sp-129.webp', 'dongvat', 'Prototype', array['mèo', 'mascot', 'chibi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-130', '130', 'Mascot thỏ tai dài', 'https://kevindauto.com/products/sp-130.webp', 'dongvat', 'Prototype', array['thỏ', 'mascot', 'chibi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-131', '131', 'Mascot gấu ôm gấu bông', 'https://kevindauto.com/products/sp-131.webp', 'dongvat', 'Prototype', array['gấu', 'mascot', 'chibi', 'chưa sơn', 'prototype', 'bản xám']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
