-- Lo 037: san pham 132 den 914
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-132', '132', 'Mascot thú cưng tai to', 'https://kevindauto.com/products/sp-132.webp', 'dongvat', 'Prototype', array['mascot', 'chibi', 'tai to', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-133', '133', 'Khỉ đột khổng lồ gầm gừ', 'https://kevindauto.com/products/sp-133.webp', 'dongvat', 'Prototype', array['khỉ đột', 'quái thú', 'khổng lồ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-134', '134', 'Khỉ đột khổng lồ đứng oai vệ', 'https://kevindauto.com/products/sp-134.webp', 'dongvat', 'Prototype', array['khỉ đột', 'quái thú', 'khổng lồ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-135', '135', 'Quái thú khủng long gầm thét', 'https://kevindauto.com/products/sp-135.webp', 'dongvat', 'Prototype', array['khủng long', 'quái thú', 'kaiju', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-136', '136', 'Robot chiến giáp tư thế chiến đấu', 'https://kevindauto.com/products/sp-136.webp', 'nam', 'Prototype', array['robot', 'cơ khí', 'chiến giáp', 'fantasy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-137', '137', 'Robot chiến giáp đứng trấn giữ', 'https://kevindauto.com/products/sp-137.webp', 'nam', 'Prototype', array['robot', 'cơ khí', 'chiến giáp', 'fantasy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-138', '138', 'Robot chiến giáp cầm vũ khí hạng nặng', 'https://kevindauto.com/products/sp-138.webp', 'nam', 'Prototype', array['robot', 'cơ khí', 'vũ khí', 'fantasy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-139', '139', 'Mascot búp bê vương miện', 'https://kevindauto.com/products/sp-139.webp', 'dongvat', 'Prototype', array['mascot', 'búp bê', 'vương miện', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-140', '140', 'Mascot mèo nơ đáng yêu', 'https://kevindauto.com/products/sp-140.webp', 'dongvat', 'Prototype', array['mèo', 'mascot', 'nơ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-141', '141', 'Mascot thỏ nơ ngồi', 'https://kevindauto.com/products/sp-141.webp', 'dongvat', 'Prototype', array['thỏ', 'mascot', 'nơ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-142', '142', 'Tượng bán thân nàng tiên cá', 'https://kevindauto.com/products/sp-142.webp', 'nu', 'Prototype', array['nữ', 'tiên cá', 'nghệ thuật', 'điêu khắc', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-143', '143', 'Mascot gấu trúc ngồi khoanh tay', 'https://kevindauto.com/products/sp-143.webp', 'dongvat', 'Prototype', array['gấu trúc', 'mascot', 'ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-144', '144', 'Cặp đôi chàng trai bế bổng bạn gái', 'https://kevindauto.com/products/sp-144.webp', 'giadinh', 'Prototype', array['cặp đôi', 'bế bổng', 'tình nhân', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-145', '145', 'Cặp đôi cõng nhau vui vẻ', 'https://kevindauto.com/products/sp-145.webp', 'giadinh', 'Prototype', array['cặp đôi', 'cõng', 'tình nhân', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-146', '146', 'Cặp đôi vác vai tinh nghịch', 'https://kevindauto.com/products/sp-146.webp', 'giadinh', 'Prototype', array['cặp đôi', 'vác vai', 'tình nhân', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-147', '147', 'Người cha dắt tay con nhỏ', 'https://kevindauto.com/products/sp-147.webp', 'treem', 'Prototype', array['gia đình', 'cha con', 'trẻ em', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-148', '148', 'Cặp đôi ngồi tựa vai âu yếm', 'https://kevindauto.com/products/sp-148.webp', 'giadinh', 'Prototype', array['cặp đôi', 'ngồi', 'âu yếm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-149', '149', 'Bé gái trượt patin tung tăng', 'https://kevindauto.com/products/sp-149.webp', 'treem', 'Prototype', array['trẻ em', 'bé gái', 'trượt patin', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-150', '150', 'Bé trai đứng dạo bước', 'https://kevindauto.com/products/sp-150.webp', 'treem', 'Prototype', array['trẻ em', 'bé trai', 'đi bộ', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-151', '151', 'Đôi bạn thân sánh vai', 'https://kevindauto.com/products/sp-151.webp', 'giadinh', 'Prototype', array['đôi bạn', 'nam', 'sánh vai', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-153', '153', 'Chàng trai đi xe trượt scooter', 'https://kevindauto.com/products/sp-153.webp', 'nam', 'Prototype', array['nam', 'scooter', 'xe trượt', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-154', '154', 'Cặp đôi ôm nhau tình cảm', 'https://kevindauto.com/products/sp-154.webp', 'giadinh', 'Prototype', array['cặp đôi', 'ôm nhau', 'tình nhân', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-157', '157', 'Cô gái chân váy tạo dáng', 'https://kevindauto.com/products/sp-157.webp', 'nu', 'Prototype', array['nữ', 'chân váy', 'cá tính', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-158', '158', 'Tượng thiên thần cánh lớn', 'https://kevindauto.com/products/sp-158.webp', 'nu', 'Prototype', array['nữ', 'thiên thần', 'cánh', 'nghệ thuật', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-159', '159', 'Cô gái áo khoác mở gợi cảm', 'https://kevindauto.com/products/sp-159.webp', 'nu', 'Prototype', array['nữ', 'gợi cảm', 'áo khoác', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-160', '160', 'Cô gái tóc dài tạo dáng tự tin', 'https://kevindauto.com/products/sp-160.webp', 'nu', 'Prototype', array['nữ', 'tóc dài', 'gợi cảm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-161', '161', 'Cô gái chống hông năng động', 'https://kevindauto.com/products/sp-161.webp', 'nu', 'Prototype', array['nữ', 'chống hông', 'năng động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-162', '162', 'Cô gái dáng gợi cảm', 'https://kevindauto.com/products/sp-162.webp', 'nu', 'Prototype', array['nữ', 'gợi cảm', 'body', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-163', '163', 'Cô gái trinh sát ngồi quan sát', 'https://kevindauto.com/products/sp-163.webp', 'nu', 'Prototype', array['nữ', 'trinh sát', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-164', '164', 'Nữ chiến binh cầm vũ khí', 'https://kevindauto.com/products/sp-164.webp', 'nu', 'Prototype', array['nữ', 'chiến binh', 'vũ khí', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-165', '165', 'Cô gái ngồi xổm xem điện thoại', 'https://kevindauto.com/products/sp-165.webp', 'nu', 'Prototype', array['nữ', 'ngồi xổm', 'điện thoại', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-166', '166', 'Cô gái streetwear cá tính', 'https://kevindauto.com/products/sp-166.webp', 'nu', 'Prototype', array['nữ', 'streetwear', 'cá tính', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-167', '167', 'Cô gái tai thỏ ngồi', 'https://kevindauto.com/products/sp-167.webp', 'nu', 'Prototype', array['nữ', 'thỏ', 'gợi cảm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-168', '168', 'Cô gái ngồi đất thư giãn', 'https://kevindauto.com/products/sp-168.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'thư giãn', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-169', '169', 'Cô gái ngồi thanh lịch', 'https://kevindauto.com/products/sp-169.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'thanh lịch', 'giày cao gót', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-170', '170', 'Cô gái ngồi bắt chéo chân', 'https://kevindauto.com/products/sp-170.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'bắt chéo chân', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-171', '171', 'Cô gái giơ tay tạo dáng', 'https://kevindauto.com/products/sp-171.webp', 'nu', 'Prototype', array['nữ', 'tạo dáng', 'cá tính', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-172', '172', 'Cô gái mũ nồi phong cách quân đội', 'https://kevindauto.com/products/sp-172.webp', 'nu', 'Prototype', array['nữ', 'mũ nồi', 'streetwear', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-173', '173', 'Cô gái áo khoác đứng tự nhiên', 'https://kevindauto.com/products/sp-173.webp', 'nu', 'Prototype', array['nữ', 'áo khoác', 'đời thường', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-174', '174', 'Cô gái tạo dáng năng động', 'https://kevindauto.com/products/sp-174.webp', 'nu', 'Prototype', array['nữ', 'năng động', 'tạo dáng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-175', '175', 'Cô gái khoác áo choàng', 'https://kevindauto.com/products/sp-175.webp', 'nu', 'Prototype', array['nữ', 'áo choàng', 'thanh lịch', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-176', '176', 'Cô gái tóc đuôi ngựa mặc đầm', 'https://kevindauto.com/products/sp-176.webp', 'nu', 'Prototype', array['nữ', 'đầm', 'tóc đuôi ngựa', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-177', '177', 'Cô gái đứng tạo dáng giản dị', 'https://kevindauto.com/products/sp-177.webp', 'nu', 'Prototype', array['nữ', 'đứng', 'giản dị', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-178', '178', 'Tượng nghệ thuật nữ dáng ngồi', 'https://kevindauto.com/products/sp-178.webp', 'nu', 'Prototype', array['nữ', 'nghệ thuật', 'điêu khắc', 'dáng ngồi', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-179', '179', 'Cô gái ngồi gác chân sang trọng', 'https://kevindauto.com/products/sp-179.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'giày cao gót', 'sang trọng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-180', '180', 'Cô gái nội y chống hông', 'https://kevindauto.com/products/sp-180.webp', 'nu', 'Prototype', array['nữ', 'nội y', 'gợi cảm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-181', '181', 'Cô gái tóc dài nhìn ra sau', 'https://kevindauto.com/products/sp-181.webp', 'nu', 'Prototype', array['nữ', 'nội y', 'tóc dài', 'gợi cảm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-182', '182', 'Cô gái ngồi chân váy ngắn', 'https://kevindauto.com/products/sp-182.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'chân váy ngắn', 'dễ thương', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-183', '183', 'Cô gái tự sướng với điện thoại', 'https://kevindauto.com/products/sp-183.webp', 'nu', 'Prototype', array['nữ', 'điện thoại', 'tự sướng', 'gợi cảm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-184', '184', 'Cô gái áo khoác rộng vẫy tay', 'https://kevindauto.com/products/sp-184.webp', 'nu', 'Prototype', array['nữ', 'áo khoác', 'vẫy tay', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-185', '185', 'Cô gái ngồi trụ cứu hoả', 'https://kevindauto.com/products/sp-185.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'dễ thương', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-186', '186', 'Chàng trai hoodie xem điện thoại', 'https://kevindauto.com/products/sp-186.webp', 'nam', 'Prototype', array['nam', 'hoodie', 'điện thoại', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-187', '187', 'Tượng nghệ thuật nữ dáng đứng', 'https://kevindauto.com/products/sp-187.webp', 'nu', 'Prototype', array['nữ', 'nghệ thuật', 'điêu khắc', 'dáng đứng', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-188', '188', 'Cô gái quỳ mặc đầm dễ thương', 'https://kevindauto.com/products/sp-188.webp', 'nu', 'Prototype', array['nữ', 'quỳ', 'đầm', 'dễ thương', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-189', '189', 'Cô gái tóc đuôi ngựa đứng đầm', 'https://kevindauto.com/products/sp-189.webp', 'nu', 'Prototype', array['nữ', 'đầm', 'tóc đuôi ngựa', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-190', '190', 'Nữ chiến binh tư thế tấn công', 'https://kevindauto.com/products/sp-190.webp', 'nu', 'Prototype', array['nữ', 'chiến binh', 'vũ khí', 'hành động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-191', '191', 'Cô gái ngồi bàn xem điện thoại', 'https://kevindauto.com/products/sp-191.webp', 'nu', 'Prototype', array['nữ', 'ngồi', 'điện thoại', 'đời thường', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-192', '192', 'Nữ chiến binh trang bị chiến thuật', 'https://kevindauto.com/products/sp-192.webp', 'nu', 'Prototype', array['nữ', 'chiến binh', 'súng', 'trang bị', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-193', '193', 'Mô hình xe đạp đua', 'https://kevindauto.com/products/sp-193.webp', 'xe', 'Prototype', array['xe đạp', 'đua xe', 'thể thao', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-194', '194', 'Cô gái cúi buộc dây giày', 'https://kevindauto.com/products/sp-194.webp', 'nu', 'Prototype', array['nữ', 'cúi người', 'buộc dây giày', 'dễ thương', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-195', '195', 'Nữ sinh chân váy đồng phục', 'https://kevindauto.com/products/sp-195.webp', 'nu', 'Prototype', array['nữ', 'học sinh', 'đồng phục', 'chân váy', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-196', '196', 'Nữ sinh đầm đồng phục', 'https://kevindauto.com/products/sp-196.webp', 'nu', 'Prototype', array['nữ', 'học sinh', 'đồng phục', 'đầm', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-197', '197', 'Cô gái khoanh tay tự tin', 'https://kevindauto.com/products/sp-197.webp', 'nu', 'Prototype', array['nữ', 'khoanh tay', 'tự tin', 'đời thường', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-198', '198', 'Cô gái duỗi chân thể dục', 'https://kevindauto.com/products/sp-198.webp', 'nu', 'Prototype', array['nữ', 'thể dục', 'năng động', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-199', '199', 'Cô gái lau nhà đời thường', 'https://kevindauto.com/products/sp-199.webp', 'nu', 'Prototype', array['nữ', 'lau nhà', 'nghề nghiệp', 'đời thường', 'chưa sơn', 'prototype', 'bản xám']::text[]),
  ('sp-900', '900', 'Mascot robot cổ điển', 'https://kevindauto.com/products/sp-900.webp', 'dongvat', 'Mascot', array['mascot', 'robot', 'chibi', 'dễ thương']::text[]),
  ('sp-901', '901', 'Ghế đẩu tròn', 'https://kevindauto.com/products/sp-901.webp', 'phukien', 'Nội thất', array['ghế đẩu', 'nội thất', 'bối cảnh']::text[]),
  ('sp-902', '902', 'Rùa biển', 'https://kevindauto.com/products/sp-902.webp', 'dongvat', 'Động vật', array['rùa', 'động vật', 'biển']::text[]),
  ('sp-903', '903', 'Bình cứu hỏa', 'https://kevindauto.com/products/sp-903.webp', 'phukien', 'Bối cảnh', array['bình cứu hỏa', 'an toàn', 'bối cảnh']::text[]),
  ('sp-904', '904', 'Xe đẩy bình khí', 'https://kevindauto.com/products/sp-904.webp', 'phukien', 'Bối cảnh', array['bình khí', 'xe đẩy', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-905', '905', 'Quý cô dạ hội tạo dáng', 'https://kevindauto.com/products/sp-905.webp', 'nu', 'Dạ hội', array['nữ', 'dạ hội', 'đầm dài', 'sang trọng']::text[]),
  ('sp-906', '906', 'Quý cô vuốt tóc thanh lịch', 'https://kevindauto.com/products/sp-906.webp', 'nu', 'Dạ hội', array['nữ', 'dạ hội', 'thanh lịch']::text[]),
  ('sp-907', '907', 'Cô gái suy tư', 'https://kevindauto.com/products/sp-907.webp', 'nu', 'Đời thường', array['nữ', 'suy tư', 'đời thường']::text[]),
  ('sp-908', '908', 'Cô gái áo khoác dạo phố', 'https://kevindauto.com/products/sp-908.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách', 'dạo phố']::text[]),
  ('sp-909', '909', 'Cô gái áo khoác đứng', 'https://kevindauto.com/products/sp-909.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đứng']::text[]),
  ('sp-910', '910', 'Cô gái ngồi dáng sang trọng', 'https://kevindauto.com/products/sp-910.webp', 'nu', 'Dạ hội', array['nữ', 'ngồi', 'sang trọng']::text[]),
  ('sp-911', '911', 'Quý cô đầm dạ hội', 'https://kevindauto.com/products/sp-911.webp', 'nu', 'Dạ hội', array['nữ', 'đầm dạ hội', 'sang trọng']::text[]),
  ('sp-912', '912', 'Cô gái phục vụ bưng khay', 'https://kevindauto.com/products/sp-912.webp', 'nu', 'Nghề nghiệp', array['nữ', 'phục vụ', 'nghề nghiệp']::text[]),
  ('sp-913', '913', 'Đôi bạn gái ôm nhau', 'https://kevindauto.com/products/sp-913.webp', 'giadinh', 'Đôi bạn', array['đôi bạn', 'ôm nhau', 'tình bạn']::text[]),
  ('sp-914', '914', 'Cô gái đội mũ tạo dáng', 'https://kevindauto.com/products/sp-914.webp', 'nu', 'Cá tính', array['nữ', 'mũ lưỡi trai', 'cá tính']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
