-- Lo 038: san pham 915 den 995
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-915', '915', 'Cô gái dáng gợi cảm', 'https://kevindauto.com/products/sp-915.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'body']::text[]),
  ('sp-916', '916', 'Cô gái nghe điện thoại', 'https://kevindauto.com/products/sp-916.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'đời thường']::text[]),
  ('sp-917', '917', 'Người đàn ông ngồi trầm tư', 'https://kevindauto.com/products/sp-917.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'trầm tư']::text[]),
  ('sp-918', '918', 'Người đàn ông cởi trần đứng', 'https://kevindauto.com/products/sp-918.webp', 'nam', 'Đời thường', array['nam', 'cởi trần', 'đứng']::text[]),
  ('sp-919', '919', 'Chàng trai hoodie ôm đầu', 'https://kevindauto.com/products/sp-919.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'streetwear']::text[]),
  ('sp-920', '920', 'Người đàn ông cơ bắp đứng', 'https://kevindauto.com/products/sp-920.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'thể hình']::text[]),
  ('sp-921', '921', 'Người đàn ông khoác áo choàng', 'https://kevindauto.com/products/sp-921.webp', 'nam', 'Đời thường', array['nam', 'áo choàng', 'đời thường']::text[]),
  ('sp-922', '922', 'Người đàn ông cầm bảng hiệu', 'https://kevindauto.com/products/sp-922.webp', 'nam', 'Nghề nghiệp', array['nam', 'bảng hiệu', 'chỉ tay', 'quảng cáo']::text[]),
  ('sp-923', '923', 'Tượng thần tài đứng', 'https://kevindauto.com/products/sp-923.webp', 'nam', 'Nghệ thuật', array['tượng', 'thần tài', 'nghệ thuật', 'phong thủy']::text[]),
  ('sp-924', '924', 'Tượng thần tài ngồi ngai', 'https://kevindauto.com/products/sp-924.webp', 'nam', 'Nghệ thuật', array['tượng', 'thần tài', 'nghệ thuật', 'phong thủy']::text[]),
  ('sp-925', '925', 'Tượng sư tử phong thủy', 'https://kevindauto.com/products/sp-925.webp', 'dongvat', 'Phong thủy', array['sư tử', 'phong thủy', 'tượng', 'may mắn']::text[]),
  ('sp-926', '926', 'Mũ giáp chiến binh', 'https://kevindauto.com/products/sp-926.webp', 'nam', 'Fantasy', array['fantasy', 'áo giáp', 'mũ giáp', 'độc đáo']::text[]),
  ('sp-927', '927', 'Xe đạp BMX', 'https://kevindauto.com/products/sp-927.webp', 'xe', 'Xe đạp', array['xe đạp', 'bmx', 'thể thao']::text[]),
  ('sp-928', '928', 'Đầu bếp bưng đĩa', 'https://kevindauto.com/products/sp-928.webp', 'nam', 'Nghề nghiệp', array['nam', 'đầu bếp', 'tạp dề', 'nghề nghiệp']::text[]),
  ('sp-929', '929', 'Doanh nhân cầm cặp', 'https://kevindauto.com/products/sp-929.webp', 'nam', 'Công sở', array['nam', 'doanh nhân', 'cặp táp', 'công sở']::text[]),
  ('sp-930', '930', 'Người đàn ông cơ bắp khoanh tay', 'https://kevindauto.com/products/sp-930.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'khoanh tay', 'thể hình']::text[]),
  ('sp-931', '931', 'Người đàn ông khoanh tay', 'https://kevindauto.com/products/sp-931.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'đứng']::text[]),
  ('sp-932', '932', 'Người đàn ông cầm súng ngắm bắn', 'https://kevindauto.com/products/sp-932.webp', 'nam', 'Hành động', array['nam', 'súng', 'hành động']::text[]),
  ('sp-933', '933', 'Người đàn ông cơ bắp cầm súng', 'https://kevindauto.com/products/sp-933.webp', 'nam', 'Hành động', array['nam', 'cơ bắp', 'súng', 'hành động']::text[]),
  ('sp-934', '934', 'Cô gái chống hông', 'https://kevindauto.com/products/sp-934.webp', 'nu', 'Đời thường', array['nữ', 'chống hông', 'đời thường']::text[]),
  ('sp-935', '935', 'Người đàn ông áo khoác đi bộ', 'https://kevindauto.com/products/sp-935.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đi bộ']::text[]),
  ('sp-936', '936', 'Cô gái khoanh tay', 'https://kevindauto.com/products/sp-936.webp', 'nu', 'Đời thường', array['nữ', 'khoanh tay', 'đứng']::text[]),
  ('sp-937', '937', 'Cô gái áo khoác đứng', 'https://kevindauto.com/products/sp-937.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đứng']::text[]),
  ('sp-938', '938', 'Người đàn ông áo khoác dài', 'https://kevindauto.com/products/sp-938.webp', 'nam', 'Trinh thám', array['nam', 'áo khoác dài', 'trinh thám', 'bí ẩn']::text[]),
  ('sp-939', '939', 'Quý ông vest cổ điển', 'https://kevindauto.com/products/sp-939.webp', 'nam', 'Cổ điển', array['nam', 'vest', 'cổ điển']::text[]),
  ('sp-940', '940', 'Quý ông vest đứng trang trọng', 'https://kevindauto.com/products/sp-940.webp', 'nam', 'Cổ điển', array['nam', 'vest', 'trang trọng', 'cổ điển']::text[]),
  ('sp-941', '941', 'Cô gái áo kimono', 'https://kevindauto.com/products/sp-941.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'cổ trang', 'nhật bản']::text[]),
  ('sp-942', '942', 'Cô gái áo choàng cổ trang cầm quạt', 'https://kevindauto.com/products/sp-942.webp', 'nu', 'Cổ trang', array['nữ', 'cổ trang', 'quạt', 'truyền thống']::text[]),
  ('sp-943', '943', 'Cô gái kimono cầm ô', 'https://kevindauto.com/products/sp-943.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'ô', 'nhật bản']::text[]),
  ('sp-944', '944', 'Cô gái áo choàng cổ trang', 'https://kevindauto.com/products/sp-944.webp', 'nu', 'Cổ trang', array['nữ', 'áo choàng', 'cổ trang']::text[]),
  ('sp-945', '945', 'Cô gái đầm cổ điển đội mũ', 'https://kevindauto.com/products/sp-945.webp', 'nu', 'Vintage', array['nữ', 'vintage', 'đầm', 'mũ']::text[]),
  ('sp-946', '946', 'Cô gái đầm pinup', 'https://kevindauto.com/products/sp-946.webp', 'nu', 'Vintage', array['nữ', 'vintage', 'pinup', 'đầm']::text[]),
  ('sp-947', '947', 'Tượng nghệ thuật dáng động', 'https://kevindauto.com/products/sp-947.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'điêu khắc', 'dáng động']::text[]),
  ('sp-948', '948', 'Tượng nghệ thuật dáng cúi', 'https://kevindauto.com/products/sp-948.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'điêu khắc', 'dáng cúi']::text[]),
  ('sp-949', '949', 'Tượng nghệ thuật dáng ngồi xổm', 'https://kevindauto.com/products/sp-949.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'điêu khắc', 'dáng động']::text[]),
  ('sp-950', '950', 'Cô gái đội mũ ngồi', 'https://kevindauto.com/products/sp-950.webp', 'nu', 'Đời thường', array['nữ', 'mũ lưỡi trai', 'ngồi']::text[]),
  ('sp-951', '951', 'Người đàn ông áo choàng khăn quàng', 'https://kevindauto.com/products/sp-951.webp', 'nam', 'Trinh thám', array['nam', 'áo choàng', 'khăn quàng', 'trinh thám']::text[]),
  ('sp-952', '952', 'Tượng nghệ thuật nữ đứng', 'https://kevindauto.com/products/sp-952.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'điêu khắc', 'dáng đứng']::text[]),
  ('sp-953', '953', 'Chó Bulldog Pháp', 'https://kevindauto.com/products/sp-953.webp', 'dongvat', 'Thú cưng', array['chó', 'bulldog', 'thú cưng']::text[]),
  ('sp-954', '954', 'Chó Bulldog Anh', 'https://kevindauto.com/products/sp-954.webp', 'dongvat', 'Thú cưng', array['chó', 'bulldog', 'thú cưng']::text[]),
  ('sp-955', '955', 'Chó Becgie ngồi', 'https://kevindauto.com/products/sp-955.webp', 'dongvat', 'Thú cưng', array['chó', 'becgie', 'thú cưng']::text[]),
  ('sp-956', '956', 'Chó sói đứng', 'https://kevindauto.com/products/sp-956.webp', 'dongvat', 'Thú cưng', array['chó', 'sói', 'husky', 'thú cưng']::text[]),
  ('sp-957', '957', 'Chó Becgie đứng', 'https://kevindauto.com/products/sp-957.webp', 'dongvat', 'Thú cưng', array['chó', 'becgie', 'thú cưng']::text[]),
  ('sp-958', '958', 'Chó Becgie ngồi chi tiết', 'https://kevindauto.com/products/sp-958.webp', 'dongvat', 'Thú cưng', array['chó', 'becgie', 'thú cưng']::text[]),
  ('sp-959', '959', 'Mascot phi hành gia', 'https://kevindauto.com/products/sp-959.webp', 'dongvat', 'Mascot', array['mascot', 'phi hành gia', 'chibi', 'dễ thương']::text[]),
  ('sp-960', '960', 'Pallet gỗ', 'https://kevindauto.com/products/sp-960.webp', 'phukien', 'Bối cảnh', array['pallet', 'gỗ', 'bối cảnh', 'kho hàng']::text[]),
  ('sp-961', '961', 'Ghế đua xe', 'https://kevindauto.com/products/sp-961.webp', 'phukien', 'Bối cảnh', array['ghế đua xe', 'nội thất xe', 'bối cảnh']::text[]),
  ('sp-962', '962', 'Bình cứu hỏa kèm giá', 'https://kevindauto.com/products/sp-962.webp', 'phukien', 'Bối cảnh', array['bình cứu hỏa', 'giá đỡ', 'an toàn']::text[]),
  ('sp-963', '963', 'Thang nhỏ', 'https://kevindauto.com/products/sp-963.webp', 'phukien', 'Bối cảnh', array['thang', 'dụng cụ', 'bối cảnh']::text[]),
  ('sp-964', '964', 'Hàng rào sắt', 'https://kevindauto.com/products/sp-964.webp', 'phukien', 'Bối cảnh', array['hàng rào', 'sắt', 'bối cảnh']::text[]),
  ('sp-965', '965', 'Cô gái đầm trễ vai', 'https://kevindauto.com/products/sp-965.webp', 'nu', 'Cá tính', array['nữ', 'đầm trễ vai', 'cá tính']::text[]),
  ('sp-966', '966', 'Cô gái chống hông đứng', 'https://kevindauto.com/products/sp-966.webp', 'nu', 'Đời thường', array['nữ', 'chống hông', 'đứng']::text[]),
  ('sp-967', '967', 'Nhân vật trùm khăn bí ẩn', 'https://kevindauto.com/products/sp-967.webp', 'nam', 'Fantasy', array['fantasy', 'trùm khăn', 'bí ẩn', 'độc đáo']::text[]),
  ('sp-968', '968', 'Người đàn ông giơ nắm đấm', 'https://kevindauto.com/products/sp-968.webp', 'nam', 'Hành động', array['nam', 'nắm đấm', 'hành động']::text[]),
  ('sp-970', '970', 'Nữ sinh cầm sách', 'https://kevindauto.com/products/sp-970.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'sách', 'học đường']::text[]),
  ('sp-971', '971', 'Người đàn ông ngồi thoải mái', 'https://kevindauto.com/products/sp-971.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thoải mái']::text[]),
  ('sp-972', '972', 'Chàng trai hoodie đứng', 'https://kevindauto.com/products/sp-972.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'streetwear']::text[]),
  ('sp-973', '973', 'Người đàn ông nghe điện thoại', 'https://kevindauto.com/products/sp-973.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đời thường']::text[]),
  ('sp-974', '974', 'Nhân vật tóc trắng phong cách anime', 'https://kevindauto.com/products/sp-974.webp', 'nam', 'Anime', array['anime', 'tóc trắng', 'độc đáo', 'fantasy']::text[]),
  ('sp-975', '975', 'Pháp sư tóc trắng phong cách anime', 'https://kevindauto.com/products/sp-975.webp', 'nam', 'Anime', array['anime', 'tóc trắng', 'pháp sư', 'fantasy']::text[]),
  ('sp-976', '976', 'Ninja tóc cam cầm cuộn giấy', 'https://kevindauto.com/products/sp-976.webp', 'nam', 'Anime', array['anime', 'ninja', 'độc đáo', 'fantasy']::text[]),
  ('sp-977', '977', 'Thùng rác', 'https://kevindauto.com/products/sp-977.webp', 'phukien', 'Bối cảnh', array['thùng rác', 'bối cảnh', 'đường phố']::text[]),
  ('sp-978', '978', 'Chim cánh cụt', 'https://kevindauto.com/products/sp-978.webp', 'dongvat', 'Động vật', array['chim cánh cụt', 'động vật', 'dễ thương']::text[]),
  ('sp-979', '979', 'Xô nhựa', 'https://kevindauto.com/products/sp-979.webp', 'phukien', 'Bối cảnh', array['xô', 'dụng cụ', 'bối cảnh']::text[]),
  ('sp-980', '980', 'Thùng rác có bánh xe', 'https://kevindauto.com/products/sp-980.webp', 'phukien', 'Bối cảnh', array['thùng rác', 'bánh xe', 'bối cảnh']::text[]),
  ('sp-981', '981', 'Thùng rác hình trụ', 'https://kevindauto.com/products/sp-981.webp', 'phukien', 'Bối cảnh', array['thùng rác', 'bối cảnh']::text[]),
  ('sp-982', '982', 'Thùng rác cổ điển', 'https://kevindauto.com/products/sp-982.webp', 'phukien', 'Bối cảnh', array['thùng rác', 'cổ điển', 'bối cảnh']::text[]),
  ('sp-983', '983', 'Hòm thư', 'https://kevindauto.com/products/sp-983.webp', 'phukien', 'Bối cảnh', array['hòm thư', 'bưu điện', 'bối cảnh']::text[]),
  ('sp-984', '984', 'Thùng rác lớn công nghiệp', 'https://kevindauto.com/products/sp-984.webp', 'phukien', 'Bối cảnh', array['thùng rác', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-985', '985', 'Tủ điện', 'https://kevindauto.com/products/sp-985.webp', 'phukien', 'Bối cảnh', array['tủ điện', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-986', '986', 'Cục nóng điều hòa', 'https://kevindauto.com/products/sp-986.webp', 'phukien', 'Bối cảnh', array['điều hòa', 'bối cảnh', 'nhà phố']::text[]),
  ('sp-987', '987', 'Bàn tròn', 'https://kevindauto.com/products/sp-987.webp', 'phukien', 'Nội thất', array['bàn', 'nội thất', 'bối cảnh']::text[]),
  ('sp-988', '988', 'Ghế đẩu tròn chân cao', 'https://kevindauto.com/products/sp-988.webp', 'phukien', 'Nội thất', array['ghế đẩu', 'nội thất', 'bối cảnh']::text[]),
  ('sp-989', '989', 'Tủ bình cứu hỏa', 'https://kevindauto.com/products/sp-989.webp', 'phukien', 'Bối cảnh', array['bình cứu hỏa', 'tủ', 'an toàn']::text[]),
  ('sp-990', '990', 'Ghế xếp chồng', 'https://kevindauto.com/products/sp-990.webp', 'phukien', 'Nội thất', array['ghế xếp', 'nội thất', 'bối cảnh']::text[]),
  ('sp-991', '991', 'Cột trang trí', 'https://kevindauto.com/products/sp-991.webp', 'phukien', 'Bối cảnh', array['cột', 'trang trí', 'bối cảnh']::text[]),
  ('sp-992', '992', 'Cột dây chắn', 'https://kevindauto.com/products/sp-992.webp', 'phukien', 'Bối cảnh', array['cột chắn', 'dây chắn', 'bối cảnh']::text[]),
  ('sp-993', '993', 'Quầy kiosk', 'https://kevindauto.com/products/sp-993.webp', 'phukien', 'Bối cảnh', array['kiosk', 'quầy', 'bối cảnh']::text[]),
  ('sp-994', '994', 'Ghế bành cổ điển', 'https://kevindauto.com/products/sp-994.webp', 'phukien', 'Nội thất', array['ghế bành', 'cổ điển', 'nội thất']::text[]),
  ('sp-995', '995', 'Chậu cây tròn', 'https://kevindauto.com/products/sp-995.webp', 'phukien', 'Bối cảnh', array['chậu cây', 'cây cảnh', 'bối cảnh']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
