-- Lo 039: san pham 996 den 1075
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-996', '996', 'Bình gốm cao', 'https://kevindauto.com/products/sp-996.webp', 'phukien', 'Bối cảnh', array['bình gốm', 'trang trí', 'bối cảnh']::text[]),
  ('sp-997', '997', 'Quạt đứng', 'https://kevindauto.com/products/sp-997.webp', 'phukien', 'Nội thất', array['quạt', 'nội thất', 'bối cảnh']::text[]),
  ('sp-998', '998', 'Cục nóng điều hòa công nghiệp', 'https://kevindauto.com/products/sp-998.webp', 'phukien', 'Bối cảnh', array['điều hòa', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-999', '999', 'Ghế hiện đại', 'https://kevindauto.com/products/sp-999.webp', 'phukien', 'Nội thất', array['ghế', 'hiện đại', 'nội thất']::text[]),
  ('sp-1000', '1000', 'Quạt thông gió', 'https://kevindauto.com/products/sp-1000.webp', 'phukien', 'Bối cảnh', array['quạt thông gió', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-1001', '1001', 'Bộ bàn ghế xếp', 'https://kevindauto.com/products/sp-1001.webp', 'phukien', 'Nội thất', array['bàn ghế xếp', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1002', '1002', 'Ghế xếp', 'https://kevindauto.com/products/sp-1002.webp', 'phukien', 'Nội thất', array['ghế xếp', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1003', '1003', 'Bàn nhỏ', 'https://kevindauto.com/products/sp-1003.webp', 'phukien', 'Nội thất', array['bàn', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1004', '1004', 'Tủ locker', 'https://kevindauto.com/products/sp-1004.webp', 'phukien', 'Nội thất', array['tủ locker', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1005', '1005', 'Tủ locker đơn', 'https://kevindauto.com/products/sp-1005.webp', 'phukien', 'Nội thất', array['tủ locker', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1006', '1006', 'Chó Golden Retriever', 'https://kevindauto.com/products/sp-1006.webp', 'dongvat', 'Thú cưng', array['chó', 'golden retriever', 'thú cưng']::text[]),
  ('sp-1007', '1007', 'Bộ dụng cụ vệ sinh', 'https://kevindauto.com/products/sp-1007.webp', 'phukien', 'Bối cảnh', array['dụng cụ vệ sinh', 'xô', 'bối cảnh']::text[]),
  ('sp-1008', '1008', 'Chổi xẻng dọn dẹp', 'https://kevindauto.com/products/sp-1008.webp', 'phukien', 'Bối cảnh', array['chổi', 'xẻng', 'dụng cụ', 'bối cảnh']::text[]),
  ('sp-1009', '1009', 'Tủ điện công nghiệp', 'https://kevindauto.com/products/sp-1009.webp', 'phukien', 'Bối cảnh', array['tủ điện', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-1010', '1010', 'Đường ray', 'https://kevindauto.com/products/sp-1010.webp', 'phukien', 'Bối cảnh', array['đường ray', 'tàu hỏa', 'bối cảnh']::text[]),
  ('sp-1011', '1011', 'Chậu cây cảnh', 'https://kevindauto.com/products/sp-1011.webp', 'phukien', 'Bối cảnh', array['chậu cây', 'cây cảnh', 'bối cảnh']::text[]),
  ('sp-1012', '1012', 'Cổng lưới rào', 'https://kevindauto.com/products/sp-1012.webp', 'phukien', 'Bối cảnh', array['cổng', 'hàng rào', 'bối cảnh']::text[]),
  ('sp-1013', '1013', 'Mảng gạch lát', 'https://kevindauto.com/products/sp-1013.webp', 'phukien', 'Bối cảnh', array['gạch lát', 'nền', 'bối cảnh']::text[]),
  ('sp-1014', '1014', 'Tháp giàn khung', 'https://kevindauto.com/products/sp-1014.webp', 'phukien', 'Bối cảnh', array['tháp', 'giàn khung', 'công nghiệp']::text[]),
  ('sp-1015', '1015', 'Bồn công nghiệp', 'https://kevindauto.com/products/sp-1015.webp', 'phukien', 'Bối cảnh', array['bồn', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-1016', '1016', 'Lan can trang trí', 'https://kevindauto.com/products/sp-1016.webp', 'phukien', 'Bối cảnh', array['lan can', 'trang trí', 'bối cảnh']::text[]),
  ('sp-1017', '1017', 'Lan can trang trí kiểu 2', 'https://kevindauto.com/products/sp-1017.webp', 'phukien', 'Bối cảnh', array['lan can', 'trang trí', 'bối cảnh']::text[]),
  ('sp-1018', '1018', 'Cửa sắt song', 'https://kevindauto.com/products/sp-1018.webp', 'phukien', 'Bối cảnh', array['cửa sắt', 'song sắt', 'bối cảnh']::text[]),
  ('sp-1019', '1019', 'Máy bán hàng tự động', 'https://kevindauto.com/products/sp-1019.webp', 'phukien', 'Bối cảnh', array['máy bán hàng', 'bối cảnh', 'đường phố']::text[]),
  ('sp-1020', '1020', 'Quạt thông gió mái', 'https://kevindauto.com/products/sp-1020.webp', 'phukien', 'Bối cảnh', array['quạt thông gió', 'mái nhà', 'công nghiệp']::text[]),
  ('sp-1021', '1021', 'Biển hiệu kem', 'https://kevindauto.com/products/sp-1021.webp', 'phukien', 'Bối cảnh', array['biển hiệu', 'kem', 'cửa hàng']::text[]),
  ('sp-1022', '1022', 'Rào chắn bê tông', 'https://kevindauto.com/products/sp-1022.webp', 'phukien', 'Bối cảnh', array['rào chắn', 'bê tông', 'giao thông']::text[]),
  ('sp-1023', '1023', 'Rào chắn bê tông kiểu 2', 'https://kevindauto.com/products/sp-1023.webp', 'phukien', 'Bối cảnh', array['rào chắn', 'bê tông', 'giao thông']::text[]),
  ('sp-1024', '1024', 'Dù che nắng', 'https://kevindauto.com/products/sp-1024.webp', 'phukien', 'Bối cảnh', array['dù', 'che nắng', 'bối cảnh']::text[]),
  ('sp-1025', '1025', 'Cô gái áo choàng bước đi', 'https://kevindauto.com/products/sp-1025.webp', 'nu', 'Đời thường', array['nữ', 'áo choàng', 'bước đi']::text[]),
  ('sp-1026', '1026', 'Người đàn ông áo thawb cầm ly', 'https://kevindauto.com/products/sp-1026.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1027', '1027', 'Người đàn ông áo thawb đứng', 'https://kevindauto.com/products/sp-1027.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1028', '1028', 'Người đàn ông áo thawb', 'https://kevindauto.com/products/sp-1028.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1029', '1029', 'Người đàn ông áo thawb cầm túi', 'https://kevindauto.com/products/sp-1029.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'túi xách']::text[]),
  ('sp-1030', '1030', 'Người đàn ông áo thawb dáng thẳng', 'https://kevindauto.com/products/sp-1030.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1031', '1031', 'Người đàn ông áo thawb tay xuôi', 'https://kevindauto.com/products/sp-1031.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1032', '1032', 'Người đàn ông áo thawb trang trọng', 'https://kevindauto.com/products/sp-1032.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1033', '1033', 'Người đàn ông áo thawb giản dị', 'https://kevindauto.com/products/sp-1033.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1034', '1034', 'Người đàn ông áo thawb khoác vải', 'https://kevindauto.com/products/sp-1034.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'trang phục truyền thống']::text[]),
  ('sp-1035', '1035', 'Người đàn ông áo thawb cầm sách', 'https://kevindauto.com/products/sp-1035.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'sách']::text[]),
  ('sp-1036', '1036', 'Người đàn ông áo thawb nghe điện thoại', 'https://kevindauto.com/products/sp-1036.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'điện thoại']::text[]),
  ('sp-1037', '1037', 'Người đàn ông áo thawb cầm điện thoại', 'https://kevindauto.com/products/sp-1037.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'điện thoại']::text[]),
  ('sp-1038', '1038', 'Người đàn ông áo thawb xách túi', 'https://kevindauto.com/products/sp-1038.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'túi xách', 'đi bộ']::text[]),
  ('sp-1039', '1039', 'Người đàn ông áo thawb bước đi', 'https://kevindauto.com/products/sp-1039.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'đi bộ']::text[]),
  ('sp-1040', '1040', 'Người đàn ông áo thawb ngồi', 'https://kevindauto.com/products/sp-1040.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'ngồi']::text[]),
  ('sp-1041', '1041', 'Người đàn ông áo thawb ngồi ghế', 'https://kevindauto.com/products/sp-1041.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'ngồi']::text[]),
  ('sp-1042', '1042', 'Người đàn ông áo thawb ngồi thư giãn', 'https://kevindauto.com/products/sp-1042.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'ngồi', 'thư giãn']::text[]),
  ('sp-1043', '1043', 'Người đàn ông áo thawb ngồi xem điện thoại', 'https://kevindauto.com/products/sp-1043.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'ngồi', 'điện thoại']::text[]),
  ('sp-1044', '1044', 'Người đàn ông áo thawb ngồi trò chuyện', 'https://kevindauto.com/products/sp-1044.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'ngồi']::text[]),
  ('sp-1045', '1045', 'Cô gái áo abaya khoanh tay', 'https://kevindauto.com/products/sp-1045.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo abaya', 'trang phục truyền thống']::text[]),
  ('sp-1046', '1046', 'Cô gái áo abaya cầm túi', 'https://kevindauto.com/products/sp-1046.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo abaya', 'túi xách']::text[]),
  ('sp-1047', '1047', 'Người đàn ông áo thawb khoanh tay', 'https://kevindauto.com/products/sp-1047.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'khoanh tay']::text[]),
  ('sp-1048', '1048', 'Người đàn ông áo thawb khoanh tay cầm túi', 'https://kevindauto.com/products/sp-1048.webp', 'nam', 'Trang phục truyền thống', array['nam', 'áo thawb', 'khoanh tay', 'túi xách']::text[]),
  ('sp-1049', '1049', 'Cô gái áo abaya xách túi', 'https://kevindauto.com/products/sp-1049.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo abaya', 'túi xách']::text[]),
  ('sp-1050', '1050', 'Cô gái áo abaya nghe điện thoại', 'https://kevindauto.com/products/sp-1050.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo abaya', 'điện thoại']::text[]),
  ('sp-1051', '1051', 'Cô gái áo abaya bước đi', 'https://kevindauto.com/products/sp-1051.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo abaya', 'đi bộ']::text[]),
  ('sp-1052', '1052', 'Cô gái áo choàng che mặt', 'https://kevindauto.com/products/sp-1052.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo choàng', 'trang phục truyền thống']::text[]),
  ('sp-1053', '1053', 'Cô gái áo choàng che mặt cầm túi', 'https://kevindauto.com/products/sp-1053.webp', 'nu', 'Trang phục truyền thống', array['nữ', 'áo choàng', 'túi xách']::text[]),
  ('sp-1054', '1054', 'Cô gái áo khoác thời trang', 'https://kevindauto.com/products/sp-1054.webp', 'nu', 'Thời trang', array['nữ', 'áo khoác', 'thời trang']::text[]),
  ('sp-1055', '1055', 'Cô gái cầm điện thoại', 'https://kevindauto.com/products/sp-1055.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'đời thường']::text[]),
  ('sp-1056', '1056', 'Nhân vật fantasy cầm ly rượu', 'https://kevindauto.com/products/sp-1056.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'độc đáo', 'cổ trang']::text[]),
  ('sp-1057', '1057', 'Nữ chiến binh fantasy có cánh', 'https://kevindauto.com/products/sp-1057.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'fantasy', 'vũ khí']::text[]),
  ('sp-1058', '1058', 'Cô gái tóc đuôi ngựa dài phong cách anime', 'https://kevindauto.com/products/sp-1058.webp', 'nu', 'Anime', array['nữ', 'anime', 'tóc dài', 'độc đáo']::text[]),
  ('sp-1059', '1059', 'Nhân vật đầu dê trượt ván', 'https://kevindauto.com/products/sp-1059.webp', 'dongvat', 'Fantasy', array['fantasy', 'độc đáo', 'trượt ván', 'nhân vật']::text[]),
  ('sp-1060', '1060', 'Cao bồi cầm súng', 'https://kevindauto.com/products/sp-1060.webp', 'nam', 'Viễn Tây', array['nam', 'cao bồi', 'súng', 'viễn tây']::text[]),
  ('sp-1061', '1061', 'Cao bồi đội mũ', 'https://kevindauto.com/products/sp-1061.webp', 'nam', 'Viễn Tây', array['nam', 'cao bồi', 'mũ', 'viễn tây']::text[]),
  ('sp-1062', '1062', 'Người đàn ông ngồi xếp bằng', 'https://kevindauto.com/products/sp-1062.webp', 'nam', 'Đời thường', array['nam', 'ngồi xếp bằng', 'đời thường']::text[]),
  ('sp-1063', '1063', 'Người đàn ông ngồi thư giãn', 'https://kevindauto.com/products/sp-1063.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thư giãn']::text[]),
  ('sp-1064', '1064', 'Ngựa tung vó', 'https://kevindauto.com/products/sp-1064.webp', 'dongvat', 'Động vật', array['ngựa', 'động vật', 'hành động']::text[]),
  ('sp-1065', '1065', 'Người đàn ông đeo balo', 'https://kevindauto.com/products/sp-1065.webp', 'nam', 'Du lịch', array['nam', 'balo', 'du lịch']::text[]),
  ('sp-1066', '1066', 'Xe máy cổ điển', 'https://kevindauto.com/products/sp-1066.webp', 'xe', 'Xe máy', array['xe máy', 'scooter', 'cổ điển']::text[]),
  ('sp-1067', '1067', 'Xe đạp', 'https://kevindauto.com/products/sp-1067.webp', 'xe', 'Xe đạp', array['xe đạp', 'phương tiện']::text[]),
  ('sp-1068', '1068', 'Mascot mèo cầm cờ lê', 'https://kevindauto.com/products/sp-1068.webp', 'dongvat', 'Mascot', array['mèo', 'mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1069', '1069', 'Cụ ông đọc báo', 'https://kevindauto.com/products/sp-1069.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đọc báo', 'ngồi']::text[]),
  ('sp-1070', '1070', 'Cô gái đạp xe', 'https://kevindauto.com/products/sp-1070.webp', 'xe', 'Xe đạp', array['nữ', 'xe đạp', 'đạp xe']::text[]),
  ('sp-1071', '1071', 'Cô gái xách túi đi bộ', 'https://kevindauto.com/products/sp-1071.webp', 'nu', 'Đời thường', array['nữ', 'túi xách', 'đi bộ']::text[]),
  ('sp-1072', '1072', 'Cô gái mặc đầm xách túi', 'https://kevindauto.com/products/sp-1072.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'túi xách']::text[]),
  ('sp-1073', '1073', 'Cô gái đội mũ đi bộ', 'https://kevindauto.com/products/sp-1073.webp', 'nu', 'Đời thường', array['nữ', 'mũ', 'đi bộ']::text[]),
  ('sp-1074', '1074', 'Cô gái đội mũ nghe điện thoại', 'https://kevindauto.com/products/sp-1074.webp', 'nu', 'Đời thường', array['nữ', 'mũ', 'điện thoại']::text[]),
  ('sp-1075', '1075', 'Cô gái áo khoác quần cargo', 'https://kevindauto.com/products/sp-1075.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'quần cargo', 'streetwear']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
