-- Lo 040: san pham 1076 den 1155
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1076', '1076', 'Cô gái tạo dáng gợi cảm', 'https://kevindauto.com/products/sp-1076.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'tạo dáng']::text[]),
  ('sp-1077', '1077', 'Người đàn ông ngồi đeo balo', 'https://kevindauto.com/products/sp-1077.webp', 'nam', 'Du lịch', array['nam', 'balo', 'ngồi', 'du lịch']::text[]),
  ('sp-1078', '1078', 'Cô gái khoanh tay đứng', 'https://kevindauto.com/products/sp-1078.webp', 'nu', 'Đời thường', array['nữ', 'khoanh tay', 'đứng']::text[]),
  ('sp-1079', '1079', 'Cô gái kimono cầm ô và kiếm', 'https://kevindauto.com/products/sp-1079.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'ô', 'kiếm', 'cổ trang']::text[]),
  ('sp-1080', '1080', 'Nữ chiến binh fantasy đội mão', 'https://kevindauto.com/products/sp-1080.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'fantasy', 'vũ khí']::text[]),
  ('sp-1081', '1081', 'Người đàn ông đeo kính ngồi', 'https://kevindauto.com/products/sp-1081.webp', 'nam', 'Đời thường', array['nam', 'kính', 'ngồi']::text[]),
  ('sp-1082', '1082', 'Cô gái quàng khăn đi bộ', 'https://kevindauto.com/products/sp-1082.webp', 'nu', 'Đời thường', array['nữ', 'khăn quàng', 'đi bộ']::text[]),
  ('sp-1083', '1083', 'Xe đua mini', 'https://kevindauto.com/products/sp-1083.webp', 'xe', 'Đua xe', array['xe đua', 'mini', 'thể thao']::text[]),
  ('sp-1084', '1084', 'Cô gái quàng khăn dạo phố', 'https://kevindauto.com/products/sp-1084.webp', 'nu', 'Đời thường', array['nữ', 'khăn quàng', 'dạo phố']::text[]),
  ('sp-1085', '1085', 'Chàng trai trùm khăn streetwear', 'https://kevindauto.com/products/sp-1085.webp', 'nam', 'Streetwear', array['nam', 'khăn trùm', 'streetwear']::text[]),
  ('sp-1086', '1086', 'Người đàn ông mặc đồng phục', 'https://kevindauto.com/products/sp-1086.webp', 'nam', 'Nghề nghiệp', array['nam', 'đồng phục', 'nghề nghiệp']::text[]),
  ('sp-1087', '1087', 'Người múa lân', 'https://kevindauto.com/products/sp-1087.webp', 'nam', 'Văn hoá', array['nam', 'múa lân', 'văn hoá', 'lễ hội']::text[]),
  ('sp-1088', '1088', 'Chàng trai cầm loa streetwear', 'https://kevindauto.com/products/sp-1088.webp', 'nam', 'Streetwear', array['nam', 'loa', 'streetwear', 'âm nhạc']::text[]),
  ('sp-1089', '1089', 'Người đàn ông vẫy tay đội mũ', 'https://kevindauto.com/products/sp-1089.webp', 'nam', 'Đời thường', array['nam', 'vẫy tay', 'mũ', 'đời thường']::text[]),
  ('sp-1090', '1090', 'Cô gái đi bộ xem điện thoại', 'https://kevindauto.com/products/sp-1090.webp', 'nu', 'Đời thường', array['nữ', 'đi bộ', 'điện thoại']::text[]),
  ('sp-1091', '1091', 'Nhiếp ảnh gia cúi chụp ảnh', 'https://kevindauto.com/products/sp-1091.webp', 'nam', 'Nghề nghiệp', array['nam', 'nhiếp ảnh', 'chụp ảnh', 'balo']::text[]),
  ('sp-1092', '1092', 'Người đàn ông ngồi đất thư giãn', 'https://kevindauto.com/products/sp-1092.webp', 'nam', 'Đời thường', array['nam', 'ngồi đất', 'thư giãn']::text[]),
  ('sp-1093', '1093', 'Người đàn ông ngồi uống nước', 'https://kevindauto.com/products/sp-1093.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'uống nước']::text[]),
  ('sp-1094', '1094', 'Nam sinh cầm điện thoại', 'https://kevindauto.com/products/sp-1094.webp', 'nam', 'Học đường', array['nam', 'học sinh', 'điện thoại', 'học đường']::text[]),
  ('sp-1095', '1095', 'Ghế bành cổ điển kiểu 2', 'https://kevindauto.com/products/sp-1095.webp', 'phukien', 'Nội thất', array['ghế bành', 'cổ điển', 'nội thất']::text[]),
  ('sp-1096', '1096', 'Chàng trai hoodie đeo balo', 'https://kevindauto.com/products/sp-1096.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'balo', 'streetwear']::text[]),
  ('sp-1097', '1097', 'Người đàn ông đeo balo xem điện thoại', 'https://kevindauto.com/products/sp-1097.webp', 'nam', 'Đời thường', array['nam', 'balo', 'điện thoại']::text[]),
  ('sp-1098', '1098', 'Người đàn ông áo khoác đi bộ', 'https://kevindauto.com/products/sp-1098.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đi bộ']::text[]),
  ('sp-1099', '1099', 'Người đàn ông đi bộ', 'https://kevindauto.com/products/sp-1099.webp', 'nam', 'Đời thường', array['nam', 'đi bộ', 'đời thường']::text[]),
  ('sp-1100', '1100', 'Người đàn ông xách túi mua sắm', 'https://kevindauto.com/products/sp-1100.webp', 'nam', 'Đời thường', array['nam', 'túi mua sắm', 'đời thường']::text[]),
  ('sp-1101', '1101', 'Người đàn ông cúi nhìn xuống', 'https://kevindauto.com/products/sp-1101.webp', 'nam', 'Đời thường', array['nam', 'cúi người', 'đời thường']::text[]),
  ('sp-1102', '1102', 'Người đàn ông khoác áo casual', 'https://kevindauto.com/products/sp-1102.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đời thường']::text[]),
  ('sp-1103', '1103', 'Người đàn ông kéo vali du lịch', 'https://kevindauto.com/products/sp-1103.webp', 'nam', 'Du lịch', array['nam', 'vali', 'du lịch']::text[]),
  ('sp-1104', '1104', 'Người đàn ông đeo balo đứng', 'https://kevindauto.com/products/sp-1104.webp', 'nam', 'Du lịch', array['nam', 'balo', 'du lịch']::text[]),
  ('sp-1105', '1105', 'Người đàn ông đội mũ bucket', 'https://kevindauto.com/products/sp-1105.webp', 'nam', 'Đời thường', array['nam', 'mũ bucket', 'đời thường']::text[]),
  ('sp-1106', '1106', 'Người đàn ông đứng casual', 'https://kevindauto.com/products/sp-1106.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'đời thường']::text[]),
  ('sp-1107', '1107', 'Chàng trai áo phông đứng', 'https://kevindauto.com/products/sp-1107.webp', 'nam', 'Đời thường', array['nam', 'áo phông', 'đời thường']::text[]),
  ('sp-1108', '1108', 'Người đàn ông tay chạm cằm', 'https://kevindauto.com/products/sp-1108.webp', 'nam', 'Đời thường', array['nam', 'suy tư', 'đời thường']::text[]),
  ('sp-1109', '1109', 'Chàng trai hoodie chắp tay', 'https://kevindauto.com/products/sp-1109.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'streetwear']::text[]),
  ('sp-1110', '1110', 'Tượng nghệ thuật áo choàng cổ điển', 'https://kevindauto.com/products/sp-1110.webp', 'nam', 'Nghệ thuật', array['nam', 'áo choàng', 'nghệ thuật', 'cổ điển']::text[]),
  ('sp-1111', '1111', 'Tượng cụ già áo choàng vẫy tay', 'https://kevindauto.com/products/sp-1111.webp', 'caotuoi', 'Nghệ thuật', array['người già', 'áo choàng', 'nghệ thuật', 'vẫy tay']::text[]),
  ('sp-1112', '1112', 'Giày sneaker mô hình', 'https://kevindauto.com/products/sp-1112.webp', 'phukien', 'Phụ kiện', array['giày', 'sneaker', 'phụ kiện']::text[]),
  ('sp-1113', '1113', 'Nhân vật hậu tận thế áo rách', 'https://kevindauto.com/products/sp-1113.webp', 'nam', 'Fantasy', array['fantasy', 'hành động', 'độc đáo']::text[]),
  ('sp-1114', '1114', 'Cụ bà xách túi đứng', 'https://kevindauto.com/products/sp-1114.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'túi xách']::text[]),
  ('sp-1115', '1115', 'Cầu thủ bóng rổ cầm bóng', 'https://kevindauto.com/products/sp-1115.webp', 'thethao', 'Bóng rổ', array['nam', 'bóng rổ', 'thể thao']::text[]),
  ('sp-1116', '1116', 'Cầu thủ bóng rổ đứng cầm bóng', 'https://kevindauto.com/products/sp-1116.webp', 'thethao', 'Bóng rổ', array['nam', 'bóng rổ', 'thể thao']::text[]),
  ('sp-1117', '1117', 'Chiến binh fantasy đeo kiếm', 'https://kevindauto.com/products/sp-1117.webp', 'nam', 'Fantasy', array['fantasy', 'kiếm', 'độc đáo']::text[]),
  ('sp-1118', '1118', 'Chiến binh áo giáp cầm khiên', 'https://kevindauto.com/products/sp-1118.webp', 'nam', 'Fantasy', array['fantasy', 'áo giáp', 'khiên', 'vũ khí']::text[]),
  ('sp-1119', '1119', 'Chiến binh viễn Tây khoác áo choàng', 'https://kevindauto.com/products/sp-1119.webp', 'nam', 'Fantasy', array['fantasy', 'viễn tây', 'áo choàng', 'vũ khí']::text[]),
  ('sp-1120', '1120', 'Nhân vật đội mũ lông vũ bí ẩn', 'https://kevindauto.com/products/sp-1120.webp', 'nam', 'Fantasy', array['fantasy', 'mũ lông vũ', 'độc đáo']::text[]),
  ('sp-1121', '1121', 'Cô gái sửa động cơ tên lửa', 'https://kevindauto.com/products/sp-1121.webp', 'nu', 'Cơ khí', array['nữ', 'cơ khí', 'động cơ', 'độc đáo']::text[]),
  ('sp-1122', '1122', 'Chàng trai streetwear khoanh tay', 'https://kevindauto.com/products/sp-1122.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'khoanh tay']::text[]),
  ('sp-1123', '1123', 'Chàng trai streetwear đứng', 'https://kevindauto.com/products/sp-1123.webp', 'nam', 'Streetwear', array['nam', 'streetwear']::text[]),
  ('sp-1124', '1124', 'Cô gái áo choàng cổ trang Á Đông', 'https://kevindauto.com/products/sp-1124.webp', 'nu', 'Cổ trang', array['nữ', 'áo choàng', 'cổ trang']::text[]),
  ('sp-1125', '1125', 'Người đàn ông khoác áo choàng vẫy tay', 'https://kevindauto.com/products/sp-1125.webp', 'nam', 'Đời thường', array['nam', 'áo choàng', 'vẫy tay']::text[]),
  ('sp-1126', '1126', 'Chiến sĩ bị thương chống nạng', 'https://kevindauto.com/products/sp-1126.webp', 'nam', 'Quân sự', array['nam', 'lính', 'quân sự', 'nạng']::text[]),
  ('sp-1127', '1127', 'Cô gái cầm ly đồ uống', 'https://kevindauto.com/products/sp-1127.webp', 'nu', 'Đời thường', array['nữ', 'ly nước', 'đời thường']::text[]),
  ('sp-1128', '1128', 'Cô gái áo choàng cầm quạt xoè', 'https://kevindauto.com/products/sp-1128.webp', 'nu', 'Cổ trang', array['nữ', 'áo choàng', 'quạt', 'cổ trang']::text[]),
  ('sp-1129', '1129', 'Chàng trai hoodie tay chạm cằm', 'https://kevindauto.com/products/sp-1129.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'streetwear']::text[]),
  ('sp-1130', '1130', 'Người đàn ông cơ bắp cầm điện thoại', 'https://kevindauto.com/products/sp-1130.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'điện thoại']::text[]),
  ('sp-1131', '1131', 'Người đàn ông đội mũ đi bộ', 'https://kevindauto.com/products/sp-1131.webp', 'nam', 'Đời thường', array['nam', 'mũ lưỡi trai', 'đi bộ']::text[]),
  ('sp-1132', '1132', 'Nhân vật đầu tivi độc đáo', 'https://kevindauto.com/products/sp-1132.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'nghệ thuật']::text[]),
  ('sp-1133', '1133', 'Mô hình xe mô tô thể thao', 'https://kevindauto.com/products/sp-1133.webp', 'xe', 'Xe máy', array['xe máy', 'mô tô', 'thể thao']::text[]),
  ('sp-1134', '1134', 'Chàng trai streetwear tự tin', 'https://kevindauto.com/products/sp-1134.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'tự tin']::text[]),
  ('sp-1135', '1135', 'Người đàn ông áo khoác đứng', 'https://kevindauto.com/products/sp-1135.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-1136', '1136', 'Nhân vật cầm đại đao hành động', 'https://kevindauto.com/products/sp-1136.webp', 'nam', 'Fantasy', array['fantasy', 'vũ khí', 'hành động']::text[]),
  ('sp-1137', '1137', 'Người đàn ông ngồi xổm uống nước', 'https://kevindauto.com/products/sp-1137.webp', 'nam', 'Đời thường', array['nam', 'ngồi xổm', 'uống nước']::text[]),
  ('sp-1138', '1138', 'Robot đầu tròn đứng', 'https://kevindauto.com/products/sp-1138.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-1139', '1139', 'Nữ chiến binh kiếm cổ trang', 'https://kevindauto.com/products/sp-1139.webp', 'nu', 'Fantasy', array['nữ', 'kiếm', 'cổ trang', 'fantasy']::text[]),
  ('sp-1140', '1140', 'Cô gái pha chế công nghiệp', 'https://kevindauto.com/products/sp-1140.webp', 'nu', 'Nghề nghiệp', array['nữ', 'công nghiệp', 'nghề nghiệp']::text[]),
  ('sp-1141', '1141', 'Quý ông vest đứng', 'https://kevindauto.com/products/sp-1141.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1142', '1142', 'Người đàn ông cơ bắp khoanh tay', 'https://kevindauto.com/products/sp-1142.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'khoanh tay']::text[]),
  ('sp-1143', '1143', 'Cụ ông khoanh tay đứng', 'https://kevindauto.com/products/sp-1143.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'khoanh tay']::text[]),
  ('sp-1144', '1144', 'Quý ông vest đứng nghiêm', 'https://kevindauto.com/products/sp-1144.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1145', '1145', 'Cô gái mặc jumpsuit thể thao', 'https://kevindauto.com/products/sp-1145.webp', 'nu', 'Thể thao', array['nữ', 'jumpsuit', 'thể thao']::text[]),
  ('sp-1146', '1146', 'Nhân vật mặc đồ bảo hộ cầm vũ khí', 'https://kevindauto.com/products/sp-1146.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'vũ khí', 'hành động']::text[]),
  ('sp-1147', '1147', 'Nhân vật mặc đồ bảo hộ đứng', 'https://kevindauto.com/products/sp-1147.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'hành động']::text[]),
  ('sp-1148', '1148', 'Nữ chiến binh trang bị chiến thuật', 'https://kevindauto.com/products/sp-1148.webp', 'nu', 'Hành động', array['nữ', 'chiến binh', 'vũ khí', 'hành động']::text[]),
  ('sp-1149', '1149', 'Nữ đặc nhiệm ngồi trang bị', 'https://kevindauto.com/products/sp-1149.webp', 'nu', 'Hành động', array['nữ', 'đặc nhiệm', 'vũ khí', 'hành động']::text[]),
  ('sp-1150', '1150', 'Chiến sĩ cầm súng trường', 'https://kevindauto.com/products/sp-1150.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1151', '1151', 'Nữ quân nhân cầm súng trường', 'https://kevindauto.com/products/sp-1151.webp', 'nu', 'Quân sự', array['nữ', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1152', '1152', 'Quý ông vest khoanh tay', 'https://kevindauto.com/products/sp-1152.webp', 'nam', 'Công sở', array['nam', 'vest', 'khoanh tay']::text[]),
  ('sp-1153', '1153', 'Nữ đặc nhiệm chỉ súng hành động', 'https://kevindauto.com/products/sp-1153.webp', 'nu', 'Hành động', array['nữ', 'đặc nhiệm', 'súng', 'hành động']::text[]),
  ('sp-1154', '1154', 'Người đàn ông cầm đũa gỗ', 'https://kevindauto.com/products/sp-1154.webp', 'nam', 'Đời thường', array['nam', 'đũa gỗ', 'đời thường']::text[]),
  ('sp-1155', '1155', 'Người đàn ông quỳ chắp tay cầu nguyện', 'https://kevindauto.com/products/sp-1155.webp', 'nam', 'Đời thường', array['nam', 'quỳ', 'cầu nguyện']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
