-- Lo 041: san pham 1156 den 1236
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1156', '1156', 'Quý ông vest chắp tay', 'https://kevindauto.com/products/sp-1156.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1157', '1157', 'Người đàn ông chào kiểu salute', 'https://kevindauto.com/products/sp-1157.webp', 'nam', 'Đời thường', array['nam', 'chào', 'salute']::text[]),
  ('sp-1158', '1158', 'Chàng trai chào kiểu salute', 'https://kevindauto.com/products/sp-1158.webp', 'nam', 'Đời thường', array['nam', 'chào', 'salute']::text[]),
  ('sp-1159', '1159', 'Cô gái chào kiểu salute', 'https://kevindauto.com/products/sp-1159.webp', 'nu', 'Đời thường', array['nữ', 'chào', 'salute']::text[]),
  ('sp-1160', '1160', 'Nữ sinh chào kiểu salute', 'https://kevindauto.com/products/sp-1160.webp', 'treem', 'Học đường', array['trẻ em', 'học sinh', 'chào']::text[]),
  ('sp-1161', '1161', 'Bé gái chào kiểu salute', 'https://kevindauto.com/products/sp-1161.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'chào']::text[]),
  ('sp-1162', '1162', 'Quái vật người sói', 'https://kevindauto.com/products/sp-1162.webp', 'dongvat', 'Quái thú', array['quái thú', 'người sói', 'fantasy']::text[]),
  ('sp-1163', '1163', 'Chim bồ câu', 'https://kevindauto.com/products/sp-1163.webp', 'dongvat', 'Động vật', array['chim', 'bồ câu', 'động vật']::text[]),
  ('sp-1164', '1164', 'Mèo ngồi đuôi cong', 'https://kevindauto.com/products/sp-1164.webp', 'dongvat', 'Thú cưng', array['mèo', 'thú cưng', 'động vật']::text[]),
  ('sp-1165', '1165', 'Chiến binh tóc dựng phong cách anime', 'https://kevindauto.com/products/sp-1165.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'hành động']::text[]),
  ('sp-1166', '1166', 'Cọc chóp nón giao thông', 'https://kevindauto.com/products/sp-1166.webp', 'phukien', 'Bối cảnh', array['cọc chóp nón', 'giao thông', 'bối cảnh']::text[]),
  ('sp-1167', '1167', 'Mascot mèo chụp ảnh', 'https://kevindauto.com/products/sp-1167.webp', 'dongvat', 'Mascot', array['mèo', 'mascot', 'máy ảnh', 'chibi']::text[]),
  ('sp-1168', '1168', 'Chó đứng đánh hơi', 'https://kevindauto.com/products/sp-1168.webp', 'dongvat', 'Thú cưng', array['chó', 'thú cưng', 'động vật']::text[]),
  ('sp-1169', '1169', 'Người đàn ông ngồi xổm casual', 'https://kevindauto.com/products/sp-1169.webp', 'nam', 'Đời thường', array['nam', 'ngồi xổm', 'đời thường']::text[]),
  ('sp-1170', '1170', 'Người đàn ông ngồi thư giãn', 'https://kevindauto.com/products/sp-1170.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thư giãn']::text[]),
  ('sp-1171', '1171', 'Người đàn ông đứng đút túi', 'https://kevindauto.com/products/sp-1171.webp', 'nam', 'Đời thường', array['nam', 'đút túi', 'đứng']::text[]),
  ('sp-1172', '1172', 'Chàng trai hoodie đút túi', 'https://kevindauto.com/products/sp-1172.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'đút túi']::text[]),
  ('sp-1173', '1173', 'Người đàn ông hút thuốc casual', 'https://kevindauto.com/products/sp-1173.webp', 'nam', 'Đời thường', array['nam', 'hút thuốc', 'thuốc lá', 'đời thường']::text[]),
  ('sp-1174', '1174', 'Người đàn ông đứng ra hiệu', 'https://kevindauto.com/products/sp-1174.webp', 'nam', 'Đời thường', array['nam', 'ra hiệu', 'đứng']::text[]),
  ('sp-1175', '1175', 'Cụ ông đứng ra hiệu', 'https://kevindauto.com/products/sp-1175.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ra hiệu']::text[]),
  ('sp-1176', '1176', 'Người đàn ông ngồi tập dưỡng sinh', 'https://kevindauto.com/products/sp-1176.webp', 'nam', 'Thể thao', array['nam', 'dưỡng sinh', 'thể thao']::text[]),
  ('sp-1177', '1177', 'Người đàn ông tập võ thuật', 'https://kevindauto.com/products/sp-1177.webp', 'nam', 'Thể thao', array['nam', 'võ thuật', 'thể thao']::text[]),
  ('sp-1178', '1178', 'Quái thú nhỏ đuôi dài', 'https://kevindauto.com/products/sp-1178.webp', 'dongvat', 'Quái thú', array['quái thú', 'fantasy', 'độc đáo']::text[]),
  ('sp-1179', '1179', 'Mascot khủng long béo tròn', 'https://kevindauto.com/products/sp-1179.webp', 'dongvat', 'Mascot', array['khủng long', 'mascot', 'dễ thương', 'chibi']::text[]),
  ('sp-1180', '1180', 'Mascot khủng long há miệng', 'https://kevindauto.com/products/sp-1180.webp', 'dongvat', 'Mascot', array['khủng long', 'mascot', 'chibi']::text[]),
  ('sp-1181', '1181', 'Mô hình súng máy giá ba chân', 'https://kevindauto.com/products/sp-1181.webp', 'phukien', 'Bối cảnh', array['súng máy', 'vũ khí', 'bối cảnh']::text[]),
  ('sp-1182', '1182', 'Người đàn ông khoanh tay đứng', 'https://kevindauto.com/products/sp-1182.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'đứng']::text[]),
  ('sp-1183', '1183', 'Cô gái áo khoác dài tạo dáng', 'https://kevindauto.com/products/sp-1183.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác dài', 'tạo dáng']::text[]),
  ('sp-1184', '1184', 'Người đàn ông xách túi đứng', 'https://kevindauto.com/products/sp-1184.webp', 'nam', 'Đời thường', array['nam', 'túi xách', 'đứng']::text[]),
  ('sp-1185', '1185', 'Mascot rồng nhỏ ngồi', 'https://kevindauto.com/products/sp-1185.webp', 'dongvat', 'Mascot', array['rồng', 'mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1186', '1186', 'Mascot rồng nhỏ đứng', 'https://kevindauto.com/products/sp-1186.webp', 'dongvat', 'Mascot', array['rồng', 'mascot', 'chibi']::text[]),
  ('sp-1187', '1187', 'Chiến binh siêu nhân cầm kiếm', 'https://kevindauto.com/products/sp-1187.webp', 'nam', 'Anime', array['anime', 'siêu nhân', 'kiếm', 'hành động']::text[]),
  ('sp-1188', '1188', 'Mô hình xe tăng mini', 'https://kevindauto.com/products/sp-1188.webp', 'xe', 'Xe quân sự', array['xe tăng', 'quân sự', 'mô hình']::text[]),
  ('sp-1189', '1189', 'Nhân vật cá sấu đi bộ', 'https://kevindauto.com/products/sp-1189.webp', 'dongvat', 'Fantasy', array['cá sấu', 'fantasy', 'độc đáo']::text[]),
  ('sp-1190', '1190', 'Nhân vật cá sấu ngồi', 'https://kevindauto.com/products/sp-1190.webp', 'dongvat', 'Fantasy', array['cá sấu', 'fantasy', 'độc đáo']::text[]),
  ('sp-1191', '1191', 'Cô gái chống hông tóc dài', 'https://kevindauto.com/products/sp-1191.webp', 'nu', 'Đời thường', array['nữ', 'chống hông', 'tóc dài']::text[]),
  ('sp-1192', '1192', 'Chiến binh siêu nhân cơ bắp', 'https://kevindauto.com/products/sp-1192.webp', 'nam', 'Anime', array['anime', 'siêu nhân', 'cơ bắp']::text[]),
  ('sp-1193', '1193', 'Mascot mèo máy màu xanh', 'https://kevindauto.com/products/sp-1193.webp', 'dongvat', 'Mascot', array['mascot', 'mèo máy', 'chibi', 'dễ thương']::text[]),
  ('sp-1194', '1194', 'Mascot mèo máy màu xanh cười', 'https://kevindauto.com/products/sp-1194.webp', 'dongvat', 'Mascot', array['mascot', 'mèo máy', 'chibi', 'dễ thương']::text[]),
  ('sp-1195', '1195', 'Mascot mèo máy màu xanh ngồi', 'https://kevindauto.com/products/sp-1195.webp', 'dongvat', 'Mascot', array['mascot', 'mèo máy', 'chibi', 'dễ thương']::text[]),
  ('sp-1196', '1196', 'Mascot bé gái tóc ngắn', 'https://kevindauto.com/products/sp-1196.webp', 'dongvat', 'Mascot', array['mascot', 'bé gái', 'chibi']::text[]),
  ('sp-1197', '1197', 'Mascot bé trai giơ nắm đấm', 'https://kevindauto.com/products/sp-1197.webp', 'dongvat', 'Mascot', array['mascot', 'bé trai', 'chibi']::text[]),
  ('sp-1198', '1198', 'Mascot bé trai mập cười', 'https://kevindauto.com/products/sp-1198.webp', 'dongvat', 'Mascot', array['mascot', 'bé trai', 'chibi']::text[]),
  ('sp-1199', '1199', 'Mascot bé trai đứng', 'https://kevindauto.com/products/sp-1199.webp', 'dongvat', 'Mascot', array['mascot', 'bé trai', 'chibi']::text[]),
  ('sp-1200', '1200', 'Mascot bé trai ngồi tựa', 'https://kevindauto.com/products/sp-1200.webp', 'dongvat', 'Mascot', array['mascot', 'bé trai', 'chibi']::text[]),
  ('sp-1202', '1202', 'Mascot bé trai đội mũ giơ tay', 'https://kevindauto.com/products/sp-1202.webp', 'dongvat', 'Mascot', array['mascot', 'bé trai', 'chibi', 'mũ']::text[]),
  ('sp-1203', '1203', 'Mascot nhân vật tròn trịa', 'https://kevindauto.com/products/sp-1203.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1204', '1204', 'Mascot robot đèn bàn nhỏ', 'https://kevindauto.com/products/sp-1204.webp', 'dongvat', 'Mascot', array['mascot', 'robot', 'chibi']::text[]),
  ('sp-1205', '1205', 'Chàng trai streetwear tay chạm cằm', 'https://kevindauto.com/products/sp-1205.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'suy tư']::text[]),
  ('sp-1206', '1206', 'Cô gái áo khoác xách túi đi bộ', 'https://kevindauto.com/products/sp-1206.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách', 'đi bộ']::text[]),
  ('sp-1207', '1207', 'Cô gái chân váy xách túi', 'https://kevindauto.com/products/sp-1207.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'túi xách']::text[]),
  ('sp-1208', '1208', 'Cô gái chân váy đội mũ', 'https://kevindauto.com/products/sp-1208.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'mũ']::text[]),
  ('sp-1209', '1209', 'Cô gái áo khoác quần cargo đứng', 'https://kevindauto.com/products/sp-1209.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'quần cargo', 'streetwear']::text[]),
  ('sp-1210', '1210', 'Cô gái chân váy áo khoác đứng', 'https://kevindauto.com/products/sp-1210.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'áo khoác']::text[]),
  ('sp-1211', '1211', 'Nhân vật trùm khăn khoanh tay', 'https://kevindauto.com/products/sp-1211.webp', 'nam', 'Fantasy', array['fantasy', 'trùm khăn', 'khoanh tay']::text[]),
  ('sp-1212', '1212', 'Cô gái cầm ly đồ uống đứng', 'https://kevindauto.com/products/sp-1212.webp', 'nu', 'Đời thường', array['nữ', 'ly nước', 'đồ uống']::text[]),
  ('sp-1213', '1213', 'Cô gái áo khoác xách túi đứng', 'https://kevindauto.com/products/sp-1213.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách']::text[]),
  ('sp-1214', '1214', 'Người đàn ông đeo dây chuyền casual', 'https://kevindauto.com/products/sp-1214.webp', 'nam', 'Streetwear', array['nam', 'dây chuyền', 'streetwear']::text[]),
  ('sp-1215', '1215', 'Cô gái đầm dáng gợi cảm', 'https://kevindauto.com/products/sp-1215.webp', 'nu', 'Gợi cảm', array['nữ', 'đầm', 'gợi cảm']::text[]),
  ('sp-1216', '1216', 'Người đàn ông quần short casual', 'https://kevindauto.com/products/sp-1216.webp', 'nam', 'Đời thường', array['nam', 'quần short', 'đời thường']::text[]),
  ('sp-1217', '1217', 'Người cha ôm hai con nhỏ', 'https://kevindauto.com/products/sp-1217.webp', 'treem', 'Gia đình', array['gia đình', 'cha con', 'trẻ em', 'ấm áp']::text[]),
  ('sp-1218', '1218', 'Quý ông vest đứng lịch lãm', 'https://kevindauto.com/products/sp-1218.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1219', '1219', 'Cụ bà đứng casual', 'https://kevindauto.com/products/sp-1219.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi']::text[]),
  ('sp-1220', '1220', 'Người đàn ông áo phông đứng', 'https://kevindauto.com/products/sp-1220.webp', 'nam', 'Đời thường', array['nam', 'áo phông', 'đứng']::text[]),
  ('sp-1221', '1221', 'Người mẹ bế con ngồi', 'https://kevindauto.com/products/sp-1221.webp', 'treem', 'Gia đình', array['gia đình', 'mẹ con', 'trẻ em', 'ấm áp']::text[]),
  ('sp-1222', '1222', 'Người đàn ông áo khoác đứng casual', 'https://kevindauto.com/products/sp-1222.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-1223', '1223', 'Người đàn ông áo khoác xách túi', 'https://kevindauto.com/products/sp-1223.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'túi xách']::text[]),
  ('sp-1224', '1224', 'Người đàn ông chống hông casual', 'https://kevindauto.com/products/sp-1224.webp', 'nam', 'Đời thường', array['nam', 'chống hông', 'đứng']::text[]),
  ('sp-1225', '1225', 'Người mẹ bế con đứng', 'https://kevindauto.com/products/sp-1225.webp', 'treem', 'Gia đình', array['gia đình', 'mẹ con', 'trẻ em', 'ấm áp']::text[]),
  ('sp-1226', '1226', 'Người đàn ông hút thuốc đời thường', 'https://kevindauto.com/products/sp-1226.webp', 'nam', 'Đời thường', array['nam', 'hút thuốc', 'thuốc lá', 'đời thường']::text[]),
  ('sp-1227', '1227', 'Người đàn ông ngồi tựa casual', 'https://kevindauto.com/products/sp-1227.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'tựa']::text[]),
  ('sp-1228', '1228', 'Người đàn ông vest cầm gậy', 'https://kevindauto.com/products/sp-1228.webp', 'nam', 'Công sở', array['nam', 'vest', 'gậy']::text[]),
  ('sp-1229', '1229', 'Mascot cao bồi đồ chơi', 'https://kevindauto.com/products/sp-1229.webp', 'dongvat', 'Mascot', array['mascot', 'cao bồi', 'chibi', 'đồ chơi']::text[]),
  ('sp-1230', '1230', 'Mascot chuột tai tròn vẫy tay', 'https://kevindauto.com/products/sp-1230.webp', 'dongvat', 'Mascot', array['mascot', 'chuột', 'chibi', 'dễ thương']::text[]),
  ('sp-1231', '1231', 'Mascot chó corgi đội mũ', 'https://kevindauto.com/products/sp-1231.webp', 'dongvat', 'Mascot', array['mascot', 'chó', 'chibi', 'mũ']::text[]),
  ('sp-1232', '1232', 'Tượng tướng quân trên bệ đá', 'https://kevindauto.com/products/sp-1232.webp', 'nam', 'Nghệ thuật', array['tượng', 'tướng quân', 'nghệ thuật', 'áo giáp']::text[]),
  ('sp-1233', '1233', 'Mascot sao biển mỉm cười', 'https://kevindauto.com/products/sp-1233.webp', 'dongvat', 'Mascot', array['mascot', 'sao biển', 'chibi', 'dễ thương']::text[]),
  ('sp-1234', '1234', 'Mascot miếng bọt biển vuông', 'https://kevindauto.com/products/sp-1234.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1235', '1235', 'Mascot khỉ cưỡi mây', 'https://kevindauto.com/products/sp-1235.webp', 'dongvat', 'Mascot', array['mascot', 'khỉ', 'chibi', 'anime']::text[]),
  ('sp-1236', '1236', 'Mascot phi hành gia tròn', 'https://kevindauto.com/products/sp-1236.webp', 'dongvat', 'Mascot', array['mascot', 'phi hành gia', 'chibi']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
