-- Lo 042: san pham 1237 den 1316
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1237', '1237', 'Người mặc đồ bảo hộ đứng', 'https://kevindauto.com/products/sp-1237.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'đứng']::text[]),
  ('sp-1238', '1238', 'Người mặc đồ bảo hộ đứng thẳng', 'https://kevindauto.com/products/sp-1238.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'đứng']::text[]),
  ('sp-1239', '1239', 'Người mặc đồ bảo hộ ngồi xổm', 'https://kevindauto.com/products/sp-1239.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'ngồi xổm']::text[]),
  ('sp-1240', '1240', 'Mascot bé gái búi tóc đôi', 'https://kevindauto.com/products/sp-1240.webp', 'dongvat', 'Mascot', array['mascot', 'bé gái', 'chibi', 'tóc']::text[]),
  ('sp-1241', '1241', 'Mascot mèo samurai cầm kiếm', 'https://kevindauto.com/products/sp-1241.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'samurai', 'kiếm']::text[]),
  ('sp-1242', '1242', 'Mascot cá chép cuộn tròn', 'https://kevindauto.com/products/sp-1242.webp', 'dongvat', 'Mascot', array['mascot', 'cá chép', 'chibi']::text[]),
  ('sp-1243', '1243', 'Mascot chó bulldog đứng', 'https://kevindauto.com/products/sp-1243.webp', 'dongvat', 'Mascot', array['mascot', 'chó', 'bulldog', 'chibi']::text[]),
  ('sp-1244', '1244', 'Thước đo mô hình', 'https://kevindauto.com/products/sp-1244.webp', 'phukien', 'Bối cảnh', array['thước đo', 'dụng cụ', 'bối cảnh']::text[]),
  ('sp-1245', '1245', 'Lợn rừng', 'https://kevindauto.com/products/sp-1245.webp', 'dongvat', 'Động vật', array['lợn rừng', 'động vật']::text[]),
  ('sp-1246', '1246', 'Mascot robot dọn dẹp', 'https://kevindauto.com/products/sp-1246.webp', 'dongvat', 'Mascot', array['mascot', 'robot', 'chibi']::text[]),
  ('sp-1247', '1247', 'Mèo thần tài vẫy tay', 'https://kevindauto.com/products/sp-1247.webp', 'dongvat', 'Phong thủy', array['mèo', 'thần tài', 'may mắn', 'phong thủy']::text[]),
  ('sp-1248', '1248', 'Mascot vịt đội mũ', 'https://kevindauto.com/products/sp-1248.webp', 'dongvat', 'Mascot', array['mascot', 'vịt', 'chibi', 'mũ']::text[]),
  ('sp-1249', '1249', 'Mèo thần tài kiểu khác', 'https://kevindauto.com/products/sp-1249.webp', 'dongvat', 'Phong thủy', array['mèo', 'thần tài', 'may mắn', 'phong thủy']::text[]),
  ('sp-1250', '1250', 'Mascot bé gái quàng khăn', 'https://kevindauto.com/products/sp-1250.webp', 'dongvat', 'Mascot', array['mascot', 'bé gái', 'chibi', 'khăn quàng']::text[]),
  ('sp-1251', '1251', 'Mascot mèo mắt sáng huyền bí', 'https://kevindauto.com/products/sp-1251.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'chibi', 'huyền bí']::text[]),
  ('sp-1252', '1252', 'Phụ kiện khớp nối ống chữ thập', 'https://kevindauto.com/products/sp-1252.webp', 'phukien', 'Bối cảnh', array['ống nối', 'công nghiệp', 'bối cảnh']::text[]),
  ('sp-1253', '1253', 'Người đàn ông bật nhảy đeo balo', 'https://kevindauto.com/products/sp-1253.webp', 'nam', 'Hành động', array['nam', 'balo', 'hành động', 'nhảy']::text[]),
  ('sp-1254', '1254', 'Người đàn ông đạp xe địa hình', 'https://kevindauto.com/products/sp-1254.webp', 'xe', 'Xe đạp', array['nam', 'xe đạp', 'địa hình', 'thể thao']::text[]),
  ('sp-1255', '1255', 'Tay đua cầm mũ bảo hiểm', 'https://kevindauto.com/products/sp-1255.webp', 'thethao', 'Đua xe', array['nam', 'đua xe', 'mũ bảo hiểm', 'thể thao']::text[]),
  ('sp-1256', '1256', 'Cô gái áo khoác cầm hoa', 'https://kevindauto.com/products/sp-1256.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'hoa']::text[]),
  ('sp-1257', '1257', 'Chiến binh bò tường tư thế hành động', 'https://kevindauto.com/products/sp-1257.webp', 'nam', 'Anime', array['anime', 'hành động', 'độc đáo']::text[]),
  ('sp-1258', '1258', 'Quái nhân cơ bắp cầm cưa máy', 'https://kevindauto.com/products/sp-1258.webp', 'nam', 'Fantasy', array['fantasy', 'quái nhân', 'vũ khí', 'hành động']::text[]),
  ('sp-1259', '1259', 'Robot chiến giáp khổng lồ', 'https://kevindauto.com/products/sp-1259.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy', 'khổng lồ']::text[]),
  ('sp-1260', '1260', 'Người áo phông rộng tay ôm đầu', 'https://kevindauto.com/products/sp-1260.webp', 'nu', 'Streetwear', array['nữ', 'áo phông rộng', 'streetwear']::text[]),
  ('sp-1261', '1261', 'Nhân vật áo choàng cầm bình cổ', 'https://kevindauto.com/products/sp-1261.webp', 'nam', 'Cổ trang', array['nam', 'áo choàng', 'bình cổ', 'cổ trang']::text[]),
  ('sp-1262', '1262', 'Người đàn ông áo choàng đứng trang trọng', 'https://kevindauto.com/products/sp-1262.webp', 'nam', 'Cổ trang', array['nam', 'áo choàng', 'cổ trang']::text[]),
  ('sp-1263', '1263', 'Khối hộp chữ nhật mô hình', 'https://kevindauto.com/products/sp-1263.webp', 'phukien', 'Bối cảnh', array['khối hộp', 'bối cảnh']::text[]),
  ('sp-1264', '1264', 'Ngựa có cánh và kỵ sĩ', 'https://kevindauto.com/products/sp-1264.webp', 'dongvat', 'Fantasy', array['ngựa', 'cánh', 'fantasy', 'kỵ sĩ']::text[]),
  ('sp-1265', '1265', 'Cụ ông ra hiệu đi bộ', 'https://kevindauto.com/products/sp-1265.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ra hiệu']::text[]),
  ('sp-1266', '1266', 'Quý ông vest ra hiệu đi bộ', 'https://kevindauto.com/products/sp-1266.webp', 'nam', 'Công sở', array['nam', 'vest', 'đi bộ']::text[]),
  ('sp-1267', '1267', 'Quý ông vest ra hiệu đứng', 'https://kevindauto.com/products/sp-1267.webp', 'nam', 'Công sở', array['nam', 'vest', 'ra hiệu']::text[]),
  ('sp-1268', '1268', 'Cụ ông giơ nắm đấm', 'https://kevindauto.com/products/sp-1268.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'nắm đấm']::text[]),
  ('sp-1269', '1269', 'Yêu tinh fantasy ngồi', 'https://kevindauto.com/products/sp-1269.webp', 'dongvat', 'Fantasy', array['fantasy', 'yêu tinh', 'độc đáo']::text[]),
  ('sp-1270', '1270', 'Người đàn ông tập võ tư thế tấn công', 'https://kevindauto.com/products/sp-1270.webp', 'nam', 'Thể thao', array['nam', 'võ thuật', 'thể thao']::text[]),
  ('sp-1271', '1271', 'Người đàn ông áo da cầm súng', 'https://kevindauto.com/products/sp-1271.webp', 'nam', 'Hành động', array['nam', 'áo da', 'súng', 'hành động']::text[]),
  ('sp-1272', '1272', 'Người đàn ông khoanh tay streetwear', 'https://kevindauto.com/products/sp-1272.webp', 'nam', 'Streetwear', array['nam', 'khoanh tay', 'streetwear']::text[]),
  ('sp-1273', '1273', 'Hiệp sĩ cầm giáo áo giáp', 'https://kevindauto.com/products/sp-1273.webp', 'nam', 'Fantasy', array['fantasy', 'hiệp sĩ', 'giáo', 'áo giáp']::text[]),
  ('sp-1274', '1274', 'Cô gái kimono giữ tay áo', 'https://kevindauto.com/products/sp-1274.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'cổ trang']::text[]),
  ('sp-1275', '1275', 'Cô gái gợi cảm cầm mũ', 'https://kevindauto.com/products/sp-1275.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'mũ']::text[]),
  ('sp-1276', '1276', 'Cô gái gợi cảm dáng đứng', 'https://kevindauto.com/products/sp-1276.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1277', '1277', 'Mascot gấu mập lông xù', 'https://kevindauto.com/products/sp-1277.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'chibi', 'lông xù']::text[]),
  ('sp-1278', '1278', 'Mascot thú lông xù cuộn tròn', 'https://kevindauto.com/products/sp-1278.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'lông xù']::text[]),
  ('sp-1279', '1279', 'Mascot gấu khoác áo choàng', 'https://kevindauto.com/products/sp-1279.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'áo choàng', 'chibi']::text[]),
  ('sp-1280', '1280', 'Mô hình cá thon dài', 'https://kevindauto.com/products/sp-1280.webp', 'dongvat', 'Động vật', array['cá', 'động vật']::text[]),
  ('sp-1281', '1281', 'Chó nghiệp vụ đứng đeo đai', 'https://kevindauto.com/products/sp-1281.webp', 'dongvat', 'Thú cưng', array['chó', 'nghiệp vụ', 'thú cưng']::text[]),
  ('sp-1282', '1282', 'Chó nghiệp vụ ngồi đeo đai', 'https://kevindauto.com/products/sp-1282.webp', 'dongvat', 'Thú cưng', array['chó', 'nghiệp vụ', 'thú cưng']::text[]),
  ('sp-1283', '1283', 'Quái thú lông trắng khổng lồ', 'https://kevindauto.com/products/sp-1283.webp', 'dongvat', 'Quái thú', array['quái thú', 'fantasy', 'độc đáo']::text[]),
  ('sp-1284', '1284', 'Tượng nghệ thuật hiện đại cầm gậy', 'https://kevindauto.com/products/sp-1284.webp', 'nam', 'Nghệ thuật', array['tượng', 'nghệ thuật', 'hiện đại', 'độc đáo']::text[]),
  ('sp-1285', '1285', 'Cá mập', 'https://kevindauto.com/products/sp-1285.webp', 'dongvat', 'Động vật', array['cá mập', 'động vật']::text[]),
  ('sp-1286', '1286', 'Mascot mèo mập cau có', 'https://kevindauto.com/products/sp-1286.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'chibi', 'dễ thương']::text[]),
  ('sp-1287', '1287', 'Mascot mèo mập cau có kiểu 2', 'https://kevindauto.com/products/sp-1287.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'chibi', 'dễ thương']::text[]),
  ('sp-1288', '1288', 'Mèo cau có nằm', 'https://kevindauto.com/products/sp-1288.webp', 'dongvat', 'Thú cưng', array['mèo', 'thú cưng', 'dễ thương']::text[]),
  ('sp-1289', '1289', 'Người đàn ông đứng giản dị', 'https://kevindauto.com/products/sp-1289.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'giản dị']::text[]),
  ('sp-1290', '1290', 'Người đàn ông tay sau lưng', 'https://kevindauto.com/products/sp-1290.webp', 'nam', 'Đời thường', array['nam', 'tay sau lưng', 'đứng']::text[]),
  ('sp-1291', '1291', 'Người đàn ông áo choàng đội mũ trinh thám', 'https://kevindauto.com/products/sp-1291.webp', 'nam', 'Trinh thám', array['nam', 'áo choàng', 'mũ', 'trinh thám']::text[]),
  ('sp-1292', '1292', 'Cụ ông râu dài ngồi ra hiệu', 'https://kevindauto.com/products/sp-1292.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'râu dài']::text[]),
  ('sp-1293', '1293', 'Mascot gấu trên bệ nhỏ', 'https://kevindauto.com/products/sp-1293.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'chibi']::text[]),
  ('sp-1294', '1294', 'Mascot voi rót nước', 'https://kevindauto.com/products/sp-1294.webp', 'dongvat', 'Mascot', array['mascot', 'voi', 'chibi']::text[]),
  ('sp-1295', '1295', 'Mèo đi bộ', 'https://kevindauto.com/products/sp-1295.webp', 'dongvat', 'Thú cưng', array['mèo', 'thú cưng']::text[]),
  ('sp-1296', '1296', 'Mascot quái thú lông xù tròn', 'https://kevindauto.com/products/sp-1296.webp', 'dongvat', 'Mascot', array['mascot', 'quái thú', 'lông xù', 'chibi']::text[]),
  ('sp-1297', '1297', 'Người đàn ông đứng cầm điện thoại', 'https://kevindauto.com/products/sp-1297.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng']::text[]),
  ('sp-1298', '1298', 'Người đàn ông cơ bắp đeo phao bơi', 'https://kevindauto.com/products/sp-1298.webp', 'nam', 'Thể thao', array['nam', 'cơ bắp', 'phao bơi', 'biển']::text[]),
  ('sp-1299', '1299', 'Người đàn ông đội mũ cao bồi đeo balo', 'https://kevindauto.com/products/sp-1299.webp', 'nam', 'Du lịch', array['nam', 'mũ cao bồi', 'balo', 'du lịch']::text[]),
  ('sp-1300', '1300', 'Võ sĩ tư thế tấn công', 'https://kevindauto.com/products/sp-1300.webp', 'nam', 'Anime', array['anime', 'võ sĩ', 'hành động']::text[]),
  ('sp-1301', '1301', 'Cảnh sát cầm dùi cui', 'https://kevindauto.com/products/sp-1301.webp', 'nam', 'Nghề nghiệp', array['nam', 'cảnh sát', 'đồng phục', 'nghề nghiệp']::text[]),
  ('sp-1302', '1302', 'Nhân vật áo choàng bay phong cách kịch tính', 'https://kevindauto.com/products/sp-1302.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'độc đáo']::text[]),
  ('sp-1303', '1303', 'Chiến binh tóc dựng ra dấu chiến thắng', 'https://kevindauto.com/products/sp-1303.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'hành động']::text[]),
  ('sp-1304', '1304', 'Cầu trượt sân chơi', 'https://kevindauto.com/products/sp-1304.webp', 'phukien', 'Bối cảnh', array['cầu trượt', 'sân chơi', 'bối cảnh']::text[]),
  ('sp-1305', '1305', 'Xích đu sân chơi', 'https://kevindauto.com/products/sp-1305.webp', 'phukien', 'Bối cảnh', array['xích đu', 'sân chơi', 'bối cảnh']::text[]),
  ('sp-1306', '1306', 'Mascot mèo tinh nghịch', 'https://kevindauto.com/products/sp-1306.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'chibi', 'dễ thương']::text[]),
  ('sp-1307', '1307', 'Chó lông xù đứng', 'https://kevindauto.com/products/sp-1307.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1308', '1308', 'Chó lông xù đứng nhìn nghiêng', 'https://kevindauto.com/products/sp-1308.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1309', '1309', 'Chó lông xù ngồi', 'https://kevindauto.com/products/sp-1309.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1310', '1310', 'Chó lông xù nằm chơi đùa', 'https://kevindauto.com/products/sp-1310.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1311', '1311', 'Chó lông xù ngồi nhìn thẳng', 'https://kevindauto.com/products/sp-1311.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1312', '1312', 'Đôi chó lông xù bên nhau', 'https://kevindauto.com/products/sp-1312.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1313', '1313', 'Cô gái áo khoác đứng tự nhiên', 'https://kevindauto.com/products/sp-1313.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đứng']::text[]),
  ('sp-1314', '1314', 'Cô gái xách túi bước đi', 'https://kevindauto.com/products/sp-1314.webp', 'nu', 'Đời thường', array['nữ', 'túi xách', 'đi bộ']::text[]),
  ('sp-1315', '1315', 'Cô gái áo khoác streetwear', 'https://kevindauto.com/products/sp-1315.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'streetwear']::text[]),
  ('sp-1316', '1316', 'Cô gái vuốt tóc chỉnh trang', 'https://kevindauto.com/products/sp-1316.webp', 'nu', 'Đời thường', array['nữ', 'vuốt tóc', 'đời thường']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
