-- Lo 043: san pham 1317 den 1397
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1317', '1317', 'Người đàn ông ngồi đội mũ', 'https://kevindauto.com/products/sp-1317.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'mũ']::text[]),
  ('sp-1318', '1318', 'Cô gái ngồi đất thư giãn', 'https://kevindauto.com/products/sp-1318.webp', 'nu', 'Đời thường', array['nữ', 'ngồi đất', 'thư giãn']::text[]),
  ('sp-1319', '1319', 'Cô gái vẫy tay khoác áo', 'https://kevindauto.com/products/sp-1319.webp', 'nu', 'Đời thường', array['nữ', 'vẫy tay', 'áo khoác']::text[]),
  ('sp-1320', '1320', 'Cô gái áo crop top đứng', 'https://kevindauto.com/products/sp-1320.webp', 'nu', 'Cá tính', array['nữ', 'crop top', 'cá tính']::text[]),
  ('sp-1321', '1321', 'Cô gái hoodie tai thú xách túi', 'https://kevindauto.com/products/sp-1321.webp', 'nu', 'Cá tính', array['nữ', 'hoodie', 'tai thú', 'cá tính']::text[]),
  ('sp-1322', '1322', 'Cô gái cầm điện thoại đứng', 'https://kevindauto.com/products/sp-1322.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'đứng']::text[]),
  ('sp-1323', '1323', 'Cô gái cầm điện thoại đứng kiểu 2', 'https://kevindauto.com/products/sp-1323.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'đứng']::text[]),
  ('sp-1324', '1324', 'Cô gái chống hông đứng thời trang', 'https://kevindauto.com/products/sp-1324.webp', 'nu', 'Thời trang', array['nữ', 'chống hông', 'thời trang']::text[]),
  ('sp-1325', '1325', 'Cô gái ngồi xổm xách túi', 'https://kevindauto.com/products/sp-1325.webp', 'nu', 'Cá tính', array['nữ', 'ngồi xổm', 'túi xách']::text[]),
  ('sp-1326', '1326', 'Tượng nghệ thuật nữ cầm bình gốm', 'https://kevindauto.com/products/sp-1326.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'bình gốm', 'điêu khắc']::text[]),
  ('sp-1327', '1327', 'Tượng nghệ thuật nữ cầm bình gốm kiểu 2', 'https://kevindauto.com/products/sp-1327.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'bình gốm', 'điêu khắc']::text[]),
  ('sp-1328', '1328', 'Nữ chiến binh anime cầm kiếm', 'https://kevindauto.com/products/sp-1328.webp', 'nu', 'Anime', array['nữ', 'anime', 'kiếm', 'fantasy']::text[]),
  ('sp-1329', '1329', 'Cô gái cosplay tai thỏ', 'https://kevindauto.com/products/sp-1329.webp', 'nu', 'Gợi cảm', array['nữ', 'tai thỏ', 'cosplay', 'gợi cảm']::text[]),
  ('sp-1330', '1330', 'Tượng nghệ thuật tiên nữ', 'https://kevindauto.com/products/sp-1330.webp', 'nu', 'Nghệ thuật', array['nữ', 'tiên nữ', 'nghệ thuật', 'fantasy']::text[]),
  ('sp-1331', '1331', 'Nữ chiến binh anime váy ngắn', 'https://kevindauto.com/products/sp-1331.webp', 'nu', 'Anime', array['nữ', 'anime', 'fantasy']::text[]),
  ('sp-1332', '1332', 'Tượng nghệ thuật nữ chiến binh boot cao', 'https://kevindauto.com/products/sp-1332.webp', 'nu', 'Fantasy', array['nữ', 'nghệ thuật', 'fantasy', 'boot']::text[]),
  ('sp-1333', '1333', 'Cô gái gợi cảm giày cao gót', 'https://kevindauto.com/products/sp-1333.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'giày cao gót']::text[]),
  ('sp-1334', '1334', 'Nữ chiến binh ngồi cầm thương', 'https://kevindauto.com/products/sp-1334.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'thương', 'fantasy']::text[]),
  ('sp-1335', '1335', 'Tượng nghệ thuật nữ áo choàng bay', 'https://kevindauto.com/products/sp-1335.webp', 'nu', 'Nghệ thuật', array['nữ', 'nghệ thuật', 'áo choàng', 'fantasy']::text[]),
  ('sp-1336', '1336', 'Cô gái đầm dài đội mũ', 'https://kevindauto.com/products/sp-1336.webp', 'nu', 'Thời trang', array['nữ', 'đầm dài', 'mũ', 'thời trang']::text[]),
  ('sp-1337', '1337', 'Người đàn ông khoanh tay quần âu', 'https://kevindauto.com/products/sp-1337.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'quần âu']::text[]),
  ('sp-1338', '1338', 'Người đàn ông phong cách bụi bặm', 'https://kevindauto.com/products/sp-1338.webp', 'nam', 'Đời thường', array['nam', 'bụi bặm', 'đời thường']::text[]),
  ('sp-1339', '1339', 'Chàng trai đội mũ khoanh tay', 'https://kevindauto.com/products/sp-1339.webp', 'nam', 'Đời thường', array['nam', 'mũ', 'khoanh tay']::text[]),
  ('sp-1340', '1340', 'Người đàn ông đút túi casual', 'https://kevindauto.com/products/sp-1340.webp', 'nam', 'Đời thường', array['nam', 'đút túi', 'đứng']::text[]),
  ('sp-1341', '1341', 'Người đàn ông cầm gậy bóng chày', 'https://kevindauto.com/products/sp-1341.webp', 'nam', 'Thể thao', array['nam', 'bóng chày', 'gậy', 'thể thao']::text[]),
  ('sp-1342', '1342', 'Cô gái khoanh tay đời thường', 'https://kevindauto.com/products/sp-1342.webp', 'nu', 'Đời thường', array['nữ', 'khoanh tay', 'đời thường']::text[]),
  ('sp-1343', '1343', 'Cô gái đầm bay trong gió', 'https://kevindauto.com/products/sp-1343.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'gió']::text[]),
  ('sp-1344', '1344', 'Người đàn ông dang tay thoải mái', 'https://kevindauto.com/products/sp-1344.webp', 'nam', 'Đời thường', array['nam', 'dang tay', 'đời thường']::text[]),
  ('sp-1345', '1345', 'Người đàn ông đội mũ chóp vui nhộn', 'https://kevindauto.com/products/sp-1345.webp', 'nam', 'Hài hước', array['nam', 'mũ chóp', 'hài hước']::text[]),
  ('sp-1346', '1346', 'Người đàn ông đội mũ đứng casual', 'https://kevindauto.com/products/sp-1346.webp', 'nam', 'Đời thường', array['nam', 'mũ', 'đứng']::text[]),
  ('sp-1347', '1347', 'Người đàn ông áo ba lỗ tay chạm cằm', 'https://kevindauto.com/products/sp-1347.webp', 'nam', 'Đời thường', array['nam', 'áo ba lỗ', 'suy tư']::text[]),
  ('sp-1348', '1348', 'Người đàn ông áo khoác đứng thẳng', 'https://kevindauto.com/products/sp-1348.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-1349', '1349', 'Người đàn ông cơ bắp chống hông', 'https://kevindauto.com/products/sp-1349.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'chống hông']::text[]),
  ('sp-1350', '1350', 'Cụ ông mặc đồng phục đứng', 'https://kevindauto.com/products/sp-1350.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đồng phục']::text[]),
  ('sp-1351', '1351', 'Người đàn ông cầm quả cầu', 'https://kevindauto.com/products/sp-1351.webp', 'nam', 'Đời thường', array['nam', 'quả cầu', 'đời thường']::text[]),
  ('sp-1352', '1352', 'Người đàn ông đút túi đứng thẳng', 'https://kevindauto.com/products/sp-1352.webp', 'nam', 'Đời thường', array['nam', 'đút túi', 'đứng']::text[]),
  ('sp-1353', '1353', 'Người đàn ông ngồi chơi đàn guitar', 'https://kevindauto.com/products/sp-1353.webp', 'nam', 'Nhạc cụ', array['nam', 'guitar', 'nhạc cụ', 'ngồi']::text[]),
  ('sp-1354', '1354', 'Người đàn ông ngồi đất casual', 'https://kevindauto.com/products/sp-1354.webp', 'nam', 'Đời thường', array['nam', 'ngồi đất', 'đời thường']::text[]),
  ('sp-1355', '1355', 'Cụ ông ngồi ghế đẩu đọc sách', 'https://kevindauto.com/products/sp-1355.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đọc sách', 'ngồi']::text[]),
  ('sp-1356', '1356', 'Người đàn ông đội mũ ngồi chơi nhạc cụ', 'https://kevindauto.com/products/sp-1356.webp', 'nam', 'Nhạc cụ', array['nam', 'nhạc cụ', 'mũ', 'ngồi']::text[]),
  ('sp-1357', '1357', 'Người đàn ông ngồi thoải mái casual', 'https://kevindauto.com/products/sp-1357.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thoải mái']::text[]),
  ('sp-1358', '1358', 'Người đàn ông ngồi ghế cao', 'https://kevindauto.com/products/sp-1358.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'ghế cao']::text[]),
  ('sp-1359', '1359', 'Chàng trai hoodie ngồi xổm', 'https://kevindauto.com/products/sp-1359.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'ngồi xổm', 'streetwear']::text[]),
  ('sp-1360', '1360', 'Người đàn ông ngồi tay ôm đầu', 'https://kevindauto.com/products/sp-1360.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'ôm đầu']::text[]),
  ('sp-1361', '1361', 'Cụ bà đứng cầm gậy', 'https://kevindauto.com/products/sp-1361.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'gậy']::text[]),
  ('sp-1362', '1362', 'Nhân vật to béo phong cách anime', 'https://kevindauto.com/products/sp-1362.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'fantasy']::text[]),
  ('sp-1363', '1363', 'Chiến binh cơ bắp cầm vũ khí anime', 'https://kevindauto.com/products/sp-1363.webp', 'nam', 'Anime', array['anime', 'chiến binh', 'vũ khí', 'hành động']::text[]),
  ('sp-1364', '1364', 'Chiến binh tóc vàng phong cách anime', 'https://kevindauto.com/products/sp-1364.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'hành động']::text[]),
  ('sp-1365', '1365', 'Chiến binh da xanh áo choàng', 'https://kevindauto.com/products/sp-1365.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'áo choàng']::text[]),
  ('sp-1366', '1366', 'Hiệp sĩ áo choàng cầm kiếm', 'https://kevindauto.com/products/sp-1366.webp', 'nam', 'Fantasy', array['fantasy', 'hiệp sĩ', 'kiếm', 'áo choàng']::text[]),
  ('sp-1367', '1367', 'Võ sĩ tóc đen phong cách anime', 'https://kevindauto.com/products/sp-1367.webp', 'nam', 'Anime', array['anime', 'võ sĩ', 'độc đáo']::text[]),
  ('sp-1368', '1368', 'Cô gái lái mô tô tương lai', 'https://kevindauto.com/products/sp-1368.webp', 'xe', 'Mô tô', array['nữ', 'mô tô', 'tương lai', 'độc đáo']::text[]),
  ('sp-1369', '1369', 'Robot chiến giáp lớn đứng', 'https://kevindauto.com/products/sp-1369.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-1370', '1370', 'Cô gái tóc dài quay lưng', 'https://kevindauto.com/products/sp-1370.webp', 'nu', 'Đời thường', array['nữ', 'tóc dài', 'quay lưng']::text[]),
  ('sp-1371', '1371', 'Nhân vật tóc dài bò ra từ màn hình', 'https://kevindauto.com/products/sp-1371.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'kinh dị']::text[]),
  ('sp-1372', '1372', 'Nhân vật tóc dài bò ra từ giếng', 'https://kevindauto.com/products/sp-1372.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo', 'kinh dị']::text[]),
  ('sp-1373', '1373', 'Thợ rèn cầm búa bên đe', 'https://kevindauto.com/products/sp-1373.webp', 'nam', 'Nghề nghiệp', array['nam', 'thợ rèn', 'búa', 'nghề nghiệp']::text[]),
  ('sp-1374', '1374', 'Mascot rồng kỳ lân', 'https://kevindauto.com/products/sp-1374.webp', 'dongvat', 'Mascot', array['mascot', 'rồng', 'kỳ lân', 'chibi']::text[]),
  ('sp-1375', '1375', 'Hoa hướng dương mô hình', 'https://kevindauto.com/products/sp-1375.webp', 'phukien', 'Bối cảnh', array['hoa', 'hướng dương', 'bối cảnh']::text[]),
  ('sp-1376', '1376', 'Bình gốm rồng trang trí', 'https://kevindauto.com/products/sp-1376.webp', 'phukien', 'Bối cảnh', array['bình gốm', 'rồng', 'trang trí']::text[]),
  ('sp-1378', '1378', 'Cụ ông xách túi đi bộ', 'https://kevindauto.com/products/sp-1378.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'túi xách', 'đi bộ']::text[]),
  ('sp-1379', '1379', 'Người mặc đồ bảo hộ ngồi', 'https://kevindauto.com/products/sp-1379.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'ngồi']::text[]),
  ('sp-1380', '1380', 'Bé gái đứng chỉ tay', 'https://kevindauto.com/products/sp-1380.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'chỉ tay']::text[]),
  ('sp-1381', '1381', 'Bé gái mặc áo khoác đứng', 'https://kevindauto.com/products/sp-1381.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'áo khoác']::text[]),
  ('sp-1382', '1382', 'Bé gái ngồi casual', 'https://kevindauto.com/products/sp-1382.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'ngồi']::text[]),
  ('sp-1383', '1383', 'Bé gái mặc đầm đứng', 'https://kevindauto.com/products/sp-1383.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đầm']::text[]),
  ('sp-1384', '1384', 'Bé gái cầm đồ chơi', 'https://kevindauto.com/products/sp-1384.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đồ chơi']::text[]),
  ('sp-1385', '1385', 'Người đàn ông vest đút túi', 'https://kevindauto.com/products/sp-1385.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1386', '1386', 'Người đàn ông vest đứng casual', 'https://kevindauto.com/products/sp-1386.webp', 'nam', 'Công sở', array['nam', 'vest', 'đứng']::text[]),
  ('sp-1387', '1387', 'Đôi bạn nhỏ đứng cùng nhau', 'https://kevindauto.com/products/sp-1387.webp', 'treem', 'Trẻ em', array['trẻ em', 'đôi bạn', 'tình bạn']::text[]),
  ('sp-1388', '1388', 'Bối cảnh thu nhỏ nhiều chi tiết', 'https://kevindauto.com/products/sp-1388.webp', 'phukien', 'Bối cảnh', array['bối cảnh', 'diorama', 'chi tiết']::text[]),
  ('sp-1389', '1389', 'Người đàn ông đồng phục chào salute', 'https://kevindauto.com/products/sp-1389.webp', 'nam', 'Nghề nghiệp', array['nam', 'đồng phục', 'chào', 'nghề nghiệp']::text[]),
  ('sp-1390', '1390', 'Người đàn ông vest thân hình đầy đặn', 'https://kevindauto.com/products/sp-1390.webp', 'nam', 'Công sở', array['nam', 'vest', 'đầy đặn']::text[]),
  ('sp-1391', '1391', 'Robot chiến giáp toàn thân', 'https://kevindauto.com/products/sp-1391.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-1392', '1392', 'Người đàn ông vest đứng casual 2', 'https://kevindauto.com/products/sp-1392.webp', 'nam', 'Công sở', array['nam', 'vest', 'đứng']::text[]),
  ('sp-1393', '1393', 'Người đàn ông áo phông đứng casual', 'https://kevindauto.com/products/sp-1393.webp', 'nam', 'Đời thường', array['nam', 'áo phông', 'đứng']::text[]),
  ('sp-1394', '1394', 'Người đàn ông hoodie đứng casual', 'https://kevindauto.com/products/sp-1394.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'đứng']::text[]),
  ('sp-1395', '1395', 'Người đàn ông hoodie đứng casual 2', 'https://kevindauto.com/products/sp-1395.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'đứng']::text[]),
  ('sp-1396', '1396', 'Người đàn ông áo choàng dài thanh lịch', 'https://kevindauto.com/products/sp-1396.webp', 'nam', 'Thời trang', array['nam', 'áo choàng dài', 'thời trang']::text[]),
  ('sp-1397', '1397', 'Đường đua mô hình', 'https://kevindauto.com/products/sp-1397.webp', 'phukien', 'Bối cảnh', array['đường đua', 'thể thao', 'bối cảnh']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
