-- Lo 044: san pham 1398 den 1478
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1398', '1398', 'Bộ đồ ăn uống mô hình', 'https://kevindauto.com/products/sp-1398.webp', 'phukien', 'Bối cảnh', array['đồ ăn', 'đồ uống', 'bối cảnh']::text[]),
  ('sp-1399', '1399', 'Tượng tháp cổ trang trí', 'https://kevindauto.com/products/sp-1399.webp', 'phukien', 'Bối cảnh', array['tháp', 'trang trí', 'cổ trang', 'bối cảnh']::text[]),
  ('sp-1400', '1400', 'Đôi người vô gia cư đứng cùng nhau', 'https://kevindauto.com/products/sp-1400.webp', 'nam', 'Đời thường', array['nam', 'vô gia cư', 'đời thường']::text[]),
  ('sp-1401', '1401', 'Người đàn ông vest dang tay', 'https://kevindauto.com/products/sp-1401.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1402', '1402', 'Robot chiến giáp kim loại', 'https://kevindauto.com/products/sp-1402.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-1403', '1403', 'Người đàn ông ngồi xổm casual', 'https://kevindauto.com/products/sp-1403.webp', 'nam', 'Đời thường', array['nam', 'ngồi xổm', 'đời thường']::text[]),
  ('sp-1404', '1404', 'Bàn phủ khăn trải', 'https://kevindauto.com/products/sp-1404.webp', 'phukien', 'Nội thất', array['bàn', 'khăn trải', 'nội thất']::text[]),
  ('sp-1405', '1405', 'Mâm trái cây trang trí', 'https://kevindauto.com/products/sp-1405.webp', 'phukien', 'Bối cảnh', array['trái cây', 'trang trí', 'bối cảnh']::text[]),
  ('sp-1406', '1406', 'Hai người đàn ông đứng cùng nhau', 'https://kevindauto.com/products/sp-1406.webp', 'nam', 'Đôi bạn', array['đôi bạn', 'nam', 'tình bạn']::text[]),
  ('sp-1407', '1407', 'Cụ ông đứng ra hiệu', 'https://kevindauto.com/products/sp-1407.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ra hiệu']::text[]),
  ('sp-1408', '1408', 'Hai người đàn ông đeo balo', 'https://kevindauto.com/products/sp-1408.webp', 'nam', 'Đôi bạn', array['đôi bạn', 'balo', 'du lịch']::text[]),
  ('sp-1409', '1409', 'Bé trai áo rách đứng', 'https://kevindauto.com/products/sp-1409.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'đời thường']::text[]),
  ('sp-1410', '1410', 'Bé trai đứng casual', 'https://kevindauto.com/products/sp-1410.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'đời thường']::text[]),
  ('sp-1411', '1411', 'Bé trai áo rách đứng casual', 'https://kevindauto.com/products/sp-1411.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'đời thường']::text[]),
  ('sp-1412', '1412', 'Bé trai ngồi bó gối', 'https://kevindauto.com/products/sp-1412.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'ngồi']::text[]),
  ('sp-1413', '1413', 'Bé gái đội mũ xách túi', 'https://kevindauto.com/products/sp-1413.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'mũ', 'túi xách']::text[]),
  ('sp-1414', '1414', 'Bé trai vẫy tay chào', 'https://kevindauto.com/products/sp-1414.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'vẫy tay']::text[]),
  ('sp-1415', '1415', 'Bé trai đeo balo vẫy tay', 'https://kevindauto.com/products/sp-1415.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'balo', 'vẫy tay']::text[]),
  ('sp-1416', '1416', 'Bé gái cưỡi xe scooter đồ chơi', 'https://kevindauto.com/products/sp-1416.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'xe đồ chơi']::text[]),
  ('sp-1417', '1417', 'Bé gái giữ tà váy', 'https://kevindauto.com/products/sp-1417.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'váy']::text[]),
  ('sp-1418', '1418', 'Bé trai ngồi xếp bằng', 'https://kevindauto.com/products/sp-1418.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'ngồi']::text[]),
  ('sp-1419', '1419', 'Bé trai đứng casual 2', 'https://kevindauto.com/products/sp-1419.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'đứng']::text[]),
  ('sp-1420', '1420', 'Em bé ngồi', 'https://kevindauto.com/products/sp-1420.webp', 'treem', 'Trẻ em', array['trẻ em', 'em bé', 'ngồi']::text[]),
  ('sp-1421', '1421', 'Người đàn ông giơ tay ăn mừng', 'https://kevindauto.com/products/sp-1421.webp', 'nam', 'Hành động', array['nam', 'ăn mừng', 'hành động']::text[]),
  ('sp-1422', '1422', 'Chiến sĩ ngắm bắn súng trường', 'https://kevindauto.com/products/sp-1422.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1423', '1423', 'Người đàn ông cầm ống nhòm', 'https://kevindauto.com/products/sp-1423.webp', 'nam', 'Đời thường', array['nam', 'ống nhòm', 'quan sát']::text[]),
  ('sp-1424', '1424', 'Cô gái đạp xe đạp', 'https://kevindauto.com/products/sp-1424.webp', 'xe', 'Xe đạp', array['nữ', 'xe đạp', 'đạp xe']::text[]),
  ('sp-1425', '1425', 'Quái thú chân nhện nhỏ', 'https://kevindauto.com/products/sp-1425.webp', 'dongvat', 'Quái thú', array['quái thú', 'fantasy', 'độc đáo']::text[]),
  ('sp-1426', '1426', 'Tượng thiên thần nhỏ cầu nguyện', 'https://kevindauto.com/products/sp-1426.webp', 'nu', 'Nghệ thuật', array['nữ', 'thiên thần', 'nghệ thuật', 'cầu nguyện']::text[]),
  ('sp-1427', '1427', 'Chó bulldog đứng', 'https://kevindauto.com/products/sp-1427.webp', 'dongvat', 'Thú cưng', array['chó', 'bulldog', 'thú cưng']::text[]),
  ('sp-1428', '1428', 'Tượng mannequin nam nghệ thuật', 'https://kevindauto.com/products/sp-1428.webp', 'nam', 'Nghệ thuật', array['nam', 'mannequin', 'nghệ thuật']::text[]),
  ('sp-1429', '1429', 'Người trượt tuyết vác ván', 'https://kevindauto.com/products/sp-1429.webp', 'nam', 'Thể thao', array['nam', 'trượt tuyết', 'thể thao']::text[]),
  ('sp-1430', '1430', 'Người trượt tuyết đứng vác ván', 'https://kevindauto.com/products/sp-1430.webp', 'nam', 'Thể thao', array['nam', 'trượt tuyết', 'thể thao']::text[]),
  ('sp-1431', '1431', 'Người trượt ván cúi hành động', 'https://kevindauto.com/products/sp-1431.webp', 'nam', 'Thể thao', array['nam', 'trượt ván', 'thể thao']::text[]),
  ('sp-1432', '1432', 'Người đàn ông cơ bắp khoanh tay áo choàng', 'https://kevindauto.com/products/sp-1432.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'khoanh tay']::text[]),
  ('sp-1433', '1433', 'Cô gái chân váy tay chạm ngực', 'https://kevindauto.com/products/sp-1433.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'đời thường']::text[]),
  ('sp-1434', '1434', 'Người ngồi đọc sách áo choàng', 'https://kevindauto.com/products/sp-1434.webp', 'nam', 'Đời thường', array['nam', 'đọc sách', 'áo choàng']::text[]),
  ('sp-1435', '1435', 'Người áo choàng dáng đứng tĩnh lặng', 'https://kevindauto.com/products/sp-1435.webp', 'nu', 'Đời thường', array['nữ', 'áo choàng', 'tĩnh lặng']::text[]),
  ('sp-1436', '1436', 'Người áo khoác trùm đầu mùa đông', 'https://kevindauto.com/products/sp-1436.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'mùa đông']::text[]),
  ('sp-1437', '1437', 'Cô gái áo khoác cầm ly', 'https://kevindauto.com/products/sp-1437.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'ly nước']::text[]),
  ('sp-1438', '1438', 'Người đàn ông áo khoác mùa đông đứng', 'https://kevindauto.com/products/sp-1438.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'mùa đông']::text[]),
  ('sp-1439', '1439', 'Cụ ông đội mũ đứng', 'https://kevindauto.com/products/sp-1439.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'mũ']::text[]),
  ('sp-1440', '1440', 'Cụ ông tay chạm đầu', 'https://kevindauto.com/products/sp-1440.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi']::text[]),
  ('sp-1441', '1441', 'Người đàn ông áo khoác đứng casual', 'https://kevindauto.com/products/sp-1441.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-1442', '1442', 'Người đàn ông đút túi đứng', 'https://kevindauto.com/products/sp-1442.webp', 'nam', 'Đời thường', array['nam', 'đút túi', 'đứng']::text[]),
  ('sp-1443', '1443', 'Người đàn ông đút túi đứng 2', 'https://kevindauto.com/products/sp-1443.webp', 'nam', 'Đời thường', array['nam', 'đút túi', 'đứng']::text[]),
  ('sp-1444', '1444', 'Người mặc giáp mũ chiến thuật', 'https://kevindauto.com/products/sp-1444.webp', 'nam', 'Hành động', array['nam', 'áo giáp', 'mũ', 'hành động']::text[]),
  ('sp-1445', '1445', 'Ghế lười hạt xốp', 'https://kevindauto.com/products/sp-1445.webp', 'phukien', 'Nội thất', array['ghế lười', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1446', '1446', 'Người đàn ông đồng phục suy tư', 'https://kevindauto.com/products/sp-1446.webp', 'nam', 'Nghề nghiệp', array['nam', 'đồng phục', 'suy tư']::text[]),
  ('sp-1447', '1447', 'Người đàn ông đồng phục ra hiệu', 'https://kevindauto.com/products/sp-1447.webp', 'nam', 'Nghề nghiệp', array['nam', 'đồng phục', 'ra hiệu']::text[]),
  ('sp-1448', '1448', 'Cô gái áo khoác xách túi đi bộ', 'https://kevindauto.com/products/sp-1448.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách']::text[]),
  ('sp-1449', '1449', 'Tượng cá chép hóa rồng', 'https://kevindauto.com/products/sp-1449.webp', 'dongvat', 'Nghệ thuật', array['cá chép', 'rồng', 'nghệ thuật', 'phong thủy']::text[]),
  ('sp-1450', '1450', 'Tượng sư tử đá trên bệ', 'https://kevindauto.com/products/sp-1450.webp', 'dongvat', 'Phong thủy', array['sư tử', 'phong thủy', 'tượng']::text[]),
  ('sp-1451', '1451', 'Tượng sư tử đá trên bệ kiểu 2', 'https://kevindauto.com/products/sp-1451.webp', 'dongvat', 'Phong thủy', array['sư tử', 'phong thủy', 'tượng']::text[]),
  ('sp-1452', '1452', 'Ghế xếp có tay vịn', 'https://kevindauto.com/products/sp-1452.webp', 'phukien', 'Nội thất', array['ghế xếp', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1453', '1453', 'Mô hình xe mô tô cổ điển kiểu 2', 'https://kevindauto.com/products/sp-1453.webp', 'xe', 'Xe máy', array['mô tô', 'xe máy', 'cổ điển']::text[]),
  ('sp-1454', '1454', 'Robot chiến giáp kiểu đầu tròn', 'https://kevindauto.com/products/sp-1454.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-1455', '1455', 'Robot chiến giáp cầm khiên', 'https://kevindauto.com/products/sp-1455.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'khiên', 'fantasy']::text[]),
  ('sp-1456', '1456', 'Robot chiến giáp cầm kiếm', 'https://kevindauto.com/products/sp-1456.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'kiếm', 'fantasy']::text[]),
  ('sp-1457', '1457', 'Chiến sĩ trang bị chiến thuật đứng', 'https://kevindauto.com/products/sp-1457.webp', 'nam', 'Quân sự', array['nam', 'lính', 'quân sự']::text[]),
  ('sp-1458', '1458', 'Người đàn ông vest chỉ tay', 'https://kevindauto.com/products/sp-1458.webp', 'nam', 'Công sở', array['nam', 'vest', 'chỉ tay']::text[]),
  ('sp-1459', '1459', 'Cụ ông áo khoác chống gậy', 'https://kevindauto.com/products/sp-1459.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'gậy']::text[]),
  ('sp-1460', '1460', 'Cô gái trang phục hoa lá cổ trang', 'https://kevindauto.com/products/sp-1460.webp', 'nu', 'Cổ trang', array['nữ', 'cổ trang', 'hoa lá', 'fantasy']::text[]),
  ('sp-1461', '1461', 'Người đàn ông cơ bắp khoanh tay cởi trần', 'https://kevindauto.com/products/sp-1461.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'khoanh tay']::text[]),
  ('sp-1462', '1462', 'Người đàn ông quần short đứng', 'https://kevindauto.com/products/sp-1462.webp', 'nam', 'Đời thường', array['nam', 'quần short', 'đứng']::text[]),
  ('sp-1463', '1463', 'Người đàn ông đứng xem điện thoại', 'https://kevindauto.com/products/sp-1463.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng']::text[]),
  ('sp-1464', '1464', 'Người đàn ông đứng thoải mái', 'https://kevindauto.com/products/sp-1464.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'thoải mái']::text[]),
  ('sp-1465', '1465', 'Người đàn ông tung chân đá', 'https://kevindauto.com/products/sp-1465.webp', 'nam', 'Hành động', array['nam', 'đá', 'hành động']::text[]),
  ('sp-1466', '1466', 'Chàng trai hoodie tư thế thủ', 'https://kevindauto.com/products/sp-1466.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'streetwear']::text[]),
  ('sp-1467', '1467', 'Chiến binh bò tường kiểu 2', 'https://kevindauto.com/products/sp-1467.webp', 'nam', 'Anime', array['anime', 'hành động', 'độc đáo']::text[]),
  ('sp-1468', '1468', 'Người nhào lộn trên không', 'https://kevindauto.com/products/sp-1468.webp', 'nam', 'Thể thao', array['nam', 'nhào lộn', 'thể thao']::text[]),
  ('sp-1469', '1469', 'Người đàn ông giơ cao vải trên đầu', 'https://kevindauto.com/products/sp-1469.webp', 'nam', 'Hành động', array['nam', 'vải', 'hành động']::text[]),
  ('sp-1470', '1470', 'Người đàn ông cầm ván trượt', 'https://kevindauto.com/products/sp-1470.webp', 'nam', 'Thể thao', array['nam', 'ván trượt', 'thể thao']::text[]),
  ('sp-1471', '1471', 'Người đàn ông breakdance xoay người', 'https://kevindauto.com/products/sp-1471.webp', 'nam', 'Thể thao', array['nam', 'breakdance', 'thể thao']::text[]),
  ('sp-1472', '1472', 'Người đàn ông nhảy múa năng động', 'https://kevindauto.com/products/sp-1472.webp', 'nam', 'Hành động', array['nam', 'nhảy múa', 'năng động']::text[]),
  ('sp-1473', '1473', 'Người đàn ông áo choàng dài bí ẩn', 'https://kevindauto.com/products/sp-1473.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'bí ẩn']::text[]),
  ('sp-1474', '1474', 'Người đàn ông cầm bóng rổ đứng', 'https://kevindauto.com/products/sp-1474.webp', 'thethao', 'Bóng rổ', array['nam', 'bóng rổ', 'thể thao']::text[]),
  ('sp-1476', '1476', 'Bé gái mặc váy đội mũ', 'https://kevindauto.com/products/sp-1476.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'váy', 'mũ']::text[]),
  ('sp-1477', '1477', 'Cụ ông đứng cầm mũ', 'https://kevindauto.com/products/sp-1477.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'mũ']::text[]),
  ('sp-1478', '1478', 'Người cha và con trai đứng cùng nhau', 'https://kevindauto.com/products/sp-1478.webp', 'treem', 'Gia đình', array['gia đình', 'cha con', 'trẻ em']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
