-- Lo 045: san pham 1479 den 1559
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1479', '1479', 'Võ sĩ sumo tạo dáng', 'https://kevindauto.com/products/sp-1479.webp', 'nam', 'Thể thao', array['nam', 'sumo', 'thể thao']::text[]),
  ('sp-1480', '1480', 'Tay đua đội mũ bảo hiểm giơ ngón cái', 'https://kevindauto.com/products/sp-1480.webp', 'nam', 'Đua xe', array['nam', 'đua xe', 'mũ bảo hiểm']::text[]),
  ('sp-1481', '1481', 'Ghế tựa gỗ', 'https://kevindauto.com/products/sp-1481.webp', 'phukien', 'Nội thất', array['ghế', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1482', '1482', 'Bàn tròn chân trụ', 'https://kevindauto.com/products/sp-1482.webp', 'phukien', 'Nội thất', array['bàn', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1483', '1483', 'Ghế băng dài', 'https://kevindauto.com/products/sp-1483.webp', 'phukien', 'Nội thất', array['ghế băng', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1484', '1484', 'Bối cảnh tiền và két sắt', 'https://kevindauto.com/products/sp-1484.webp', 'phukien', 'Bối cảnh', array['tiền', 'két sắt', 'bối cảnh']::text[]),
  ('sp-1485', '1485', 'Xe máy mini', 'https://kevindauto.com/products/sp-1485.webp', 'xe', 'Xe máy', array['xe máy', 'mini']::text[]),
  ('sp-1486', '1486', 'Chồng gạch xây dựng', 'https://kevindauto.com/products/sp-1486.webp', 'phukien', 'Bối cảnh', array['gạch', 'xây dựng', 'bối cảnh']::text[]),
  ('sp-1487', '1487', 'Người dắt ngựa', 'https://kevindauto.com/products/sp-1487.webp', 'dongvat', 'Động vật', array['ngựa', 'cưỡi ngựa', 'động vật']::text[]),
  ('sp-1488', '1488', 'Linh dương', 'https://kevindauto.com/products/sp-1488.webp', 'dongvat', 'Động vật', array['linh dương', 'động vật']::text[]),
  ('sp-1490', '1490', 'Khung cầu thang kim loại', 'https://kevindauto.com/products/sp-1490.webp', 'phukien', 'Bối cảnh', array['cầu thang', 'kim loại', 'bối cảnh']::text[]),
  ('sp-1491', '1491', 'Thang kho hàng có bánh xe', 'https://kevindauto.com/products/sp-1491.webp', 'phukien', 'Bối cảnh', array['thang', 'kho hàng', 'bối cảnh']::text[]),
  ('sp-1492', '1492', 'Xe đẩy siêu thị', 'https://kevindauto.com/products/sp-1492.webp', 'phukien', 'Bối cảnh', array['xe đẩy', 'siêu thị', 'bối cảnh']::text[]),
  ('sp-1493', '1493', 'Người đàn ông tay chạm đầu casual', 'https://kevindauto.com/products/sp-1493.webp', 'nam', 'Đời thường', array['nam', 'tay chạm đầu', 'đời thường']::text[]),
  ('sp-1494', '1494', 'Người đàn ông tay chạm đầu casual 2', 'https://kevindauto.com/products/sp-1494.webp', 'nam', 'Đời thường', array['nam', 'tay chạm đầu', 'đời thường']::text[]),
  ('sp-1495', '1495', 'Người đàn ông đeo kính đứng', 'https://kevindauto.com/products/sp-1495.webp', 'nam', 'Đời thường', array['nam', 'kính', 'đứng']::text[]),
  ('sp-1496', '1496', 'Người đàn ông đội mũ đứng casual', 'https://kevindauto.com/products/sp-1496.webp', 'nam', 'Đời thường', array['nam', 'mũ', 'đứng']::text[]),
  ('sp-1497', '1497', 'Người giao hàng cầm hộp', 'https://kevindauto.com/products/sp-1497.webp', 'nam', 'Nghề nghiệp', array['nam', 'giao hàng', 'hộp', 'nghề nghiệp']::text[]),
  ('sp-1498', '1498', 'Người đàn ông đi bộ casual', 'https://kevindauto.com/products/sp-1498.webp', 'nam', 'Đời thường', array['nam', 'đi bộ', 'đời thường']::text[]),
  ('sp-1499', '1499', 'Người mặc đồ bảo hộ đeo mặt nạ', 'https://kevindauto.com/products/sp-1499.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'mặt nạ', 'hành động']::text[]),
  ('sp-1500', '1500', 'Người đàn ông ngồi nghe điện thoại', 'https://kevindauto.com/products/sp-1500.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'điện thoại']::text[]),
  ('sp-1501', '1501', 'Người đàn ông ngồi khoác áo', 'https://kevindauto.com/products/sp-1501.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'áo khoác']::text[]),
  ('sp-1502', '1502', 'Người đàn ông cởi trần cầm ly', 'https://kevindauto.com/products/sp-1502.webp', 'nam', 'Đời thường', array['nam', 'cởi trần', 'ly nước']::text[]),
  ('sp-1503', '1503', 'Người đàn ông quần short đứng casual', 'https://kevindauto.com/products/sp-1503.webp', 'nam', 'Đời thường', array['nam', 'quần short', 'đứng']::text[]),
  ('sp-1504', '1504', 'Người đàn ông cơ bắp giơ nắm đấm', 'https://kevindauto.com/products/sp-1504.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'nắm đấm']::text[]),
  ('sp-1505', '1505', 'Người đàn ông ngồi duỗi người', 'https://kevindauto.com/products/sp-1505.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'duỗi người']::text[]),
  ('sp-1506', '1506', 'Cô gái ngồi ôm mèo cưng', 'https://kevindauto.com/products/sp-1506.webp', 'nu', 'Thú cưng', array['nữ', 'mèo', 'thú cưng', 'ngồi']::text[]),
  ('sp-1507', '1507', 'Cô gái dáng gợi cảm đi boot', 'https://kevindauto.com/products/sp-1507.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'boot']::text[]),
  ('sp-1508', '1508', 'Bé gái cầm dù đen', 'https://kevindauto.com/products/sp-1508.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'dù']::text[]),
  ('sp-1509', '1509', 'Cô gái áo khoác streetwear đứng', 'https://kevindauto.com/products/sp-1509.webp', 'nu', 'Streetwear', array['nữ', 'áo khoác', 'streetwear']::text[]),
  ('sp-1510', '1510', 'Cô gái áo khoác xem điện thoại', 'https://kevindauto.com/products/sp-1510.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'điện thoại']::text[]),
  ('sp-1511', '1511', 'Cô gái đứng casual', 'https://kevindauto.com/products/sp-1511.webp', 'nu', 'Đời thường', array['nữ', 'đứng', 'đời thường']::text[]),
  ('sp-1512', '1512', 'Người đàn ông đứng xem điện thoại casual', 'https://kevindauto.com/products/sp-1512.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng']::text[]),
  ('sp-1513', '1513', 'Cô gái quần short đứng', 'https://kevindauto.com/products/sp-1513.webp', 'nu', 'Đời thường', array['nữ', 'quần short', 'đứng']::text[]),
  ('sp-1514', '1514', 'Cô gái chân váy chỉ tay', 'https://kevindauto.com/products/sp-1514.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'chỉ tay']::text[]),
  ('sp-1515', '1515', 'Cô gái ngồi mặc đầm', 'https://kevindauto.com/products/sp-1515.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'đầm']::text[]),
  ('sp-1516', '1516', 'Cô gái ngồi cầm ly casual', 'https://kevindauto.com/products/sp-1516.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'ly nước']::text[]),
  ('sp-1517', '1517', 'Cô gái ngồi giơ tay lên tóc', 'https://kevindauto.com/products/sp-1517.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'tóc']::text[]),
  ('sp-1518', '1518', 'Cô gái ngồi casual thư giãn', 'https://kevindauto.com/products/sp-1518.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'thư giãn']::text[]),
  ('sp-1519', '1519', 'Cô gái ngồi tự chụp ảnh', 'https://kevindauto.com/products/sp-1519.webp', 'nu', 'Đời thường', array['nữ', 'tự chụp ảnh', 'điện thoại']::text[]),
  ('sp-1520', '1520', 'Cô gái quỳ tự chụp ảnh', 'https://kevindauto.com/products/sp-1520.webp', 'nu', 'Đời thường', array['nữ', 'tự chụp ảnh', 'quỳ']::text[]),
  ('sp-1521', '1521', 'Cô gái quỳ tự chụp ảnh đeo balo', 'https://kevindauto.com/products/sp-1521.webp', 'nu', 'Đời thường', array['nữ', 'tự chụp ảnh', 'balo']::text[]),
  ('sp-1522', '1522', 'Cặp đôi ngồi âu yếm', 'https://kevindauto.com/products/sp-1522.webp', 'giadinh', 'Cặp đôi', array['cặp đôi', 'ngồi', 'tình nhân']::text[]),
  ('sp-1523', '1523', 'Cô gái ngồi trong hộp gỗ', 'https://kevindauto.com/products/sp-1523.webp', 'nu', 'Cá tính', array['nữ', 'hộp gỗ', 'cá tính']::text[]),
  ('sp-1524', '1524', 'Người đàn ông cầm máy quay phim', 'https://kevindauto.com/products/sp-1524.webp', 'nam', 'Nghề nghiệp', array['nam', 'máy quay', 'nghề nghiệp']::text[]),
  ('sp-1525', '1525', 'Robot ngồi xem điện thoại', 'https://kevindauto.com/products/sp-1525.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'điện thoại']::text[]),
  ('sp-1526', '1526', 'Tượng mannequin nam đứng', 'https://kevindauto.com/products/sp-1526.webp', 'nam', 'Nghệ thuật', array['nam', 'mannequin', 'nghệ thuật']::text[]),
  ('sp-1527', '1527', 'Robot phi hành phong cách đồ chơi', 'https://kevindauto.com/products/sp-1527.webp', 'nam', 'Robot', array['robot', 'phi hành', 'đồ chơi']::text[]),
  ('sp-1528', '1528', 'Cô gái gợi cảm dáng chuẩn', 'https://kevindauto.com/products/sp-1528.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1529', '1529', 'Người đàn ông đứng xem điện thoại 2', 'https://kevindauto.com/products/sp-1529.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng']::text[]),
  ('sp-1530', '1530', 'Người đàn ông ngồi cùng chó cưng', 'https://kevindauto.com/products/sp-1530.webp', 'nam', 'Thú cưng', array['nam', 'chó', 'thú cưng', 'ngồi']::text[]),
  ('sp-1531', '1531', 'Đầu bếp cầm chảo', 'https://kevindauto.com/products/sp-1531.webp', 'nam', 'Nghề nghiệp', array['nam', 'đầu bếp', 'chảo', 'nghề nghiệp']::text[]),
  ('sp-1532', '1532', 'Mascot người kẹo dẻo', 'https://kevindauto.com/products/sp-1532.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1533', '1533', 'Người đàn ông áo khoác xách túi đứng', 'https://kevindauto.com/products/sp-1533.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'túi xách']::text[]),
  ('sp-1534', '1534', 'Người đàn ông đi bộ casual 2', 'https://kevindauto.com/products/sp-1534.webp', 'nam', 'Đời thường', array['nam', 'đi bộ', 'đời thường']::text[]),
  ('sp-1535', '1535', 'Người đàn ông cơ bắp cởi trần đứng', 'https://kevindauto.com/products/sp-1535.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'cởi trần']::text[]),
  ('sp-1536', '1536', 'Người đàn ông tập tạ đẩy ngực', 'https://kevindauto.com/products/sp-1536.webp', 'thethao', 'Gym', array['nam', 'gym', 'tập tạ', 'thể thao']::text[]),
  ('sp-1537', '1537', 'Bác sĩ đứng cầm dụng cụ', 'https://kevindauto.com/products/sp-1537.webp', 'nam', 'Nghề nghiệp', array['nam', 'bác sĩ', 'nghề nghiệp']::text[]),
  ('sp-1538', '1538', 'Đầu bếp dang tay', 'https://kevindauto.com/products/sp-1538.webp', 'nam', 'Nghề nghiệp', array['nam', 'đầu bếp', 'nghề nghiệp']::text[]),
  ('sp-1539', '1539', 'Chiến binh fantasy cầm kiếm giáp nhẹ', 'https://kevindauto.com/products/sp-1539.webp', 'nam', 'Fantasy', array['fantasy', 'kiếm', 'áo giáp']::text[]),
  ('sp-1540', '1540', 'Tượng chiến binh cầm gậy trên bệ', 'https://kevindauto.com/products/sp-1540.webp', 'nam', 'Nghệ thuật', array['tượng', 'chiến binh', 'nghệ thuật', 'fantasy']::text[]),
  ('sp-1541', '1541', 'Người đàn ông hoodie ngồi xếp bằng', 'https://kevindauto.com/products/sp-1541.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'ngồi']::text[]),
  ('sp-1542', '1542', 'Người đàn ông ngồi đưa tay ra', 'https://kevindauto.com/products/sp-1542.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'đưa tay']::text[]),
  ('sp-1543', '1543', 'Người đàn ông ngồi co chân', 'https://kevindauto.com/products/sp-1543.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'co chân']::text[]),
  ('sp-1544', '1544', 'Người đàn ông ngồi xem điện thoại casual', 'https://kevindauto.com/products/sp-1544.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'điện thoại']::text[]),
  ('sp-1545', '1545', 'Người đàn ông ngồi xem điện thoại casual 2', 'https://kevindauto.com/products/sp-1545.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'điện thoại']::text[]),
  ('sp-1546', '1546', 'Người đàn ông ngồi xổm casual 2', 'https://kevindauto.com/products/sp-1546.webp', 'nam', 'Đời thường', array['nam', 'ngồi xổm', 'đời thường']::text[]),
  ('sp-1547', '1547', 'Người đàn ông ngồi chỉ tay', 'https://kevindauto.com/products/sp-1547.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'chỉ tay']::text[]),
  ('sp-1548', '1548', 'Người đàn ông ngồi thư giãn casual', 'https://kevindauto.com/products/sp-1548.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thư giãn']::text[]),
  ('sp-1549', '1549', 'Người đàn ông ngồi thư giãn casual 2', 'https://kevindauto.com/products/sp-1549.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thư giãn']::text[]),
  ('sp-1550', '1550', 'Người đàn ông cởi trần ngồi thư giãn', 'https://kevindauto.com/products/sp-1550.webp', 'nam', 'Đời thường', array['nam', 'cởi trần', 'ngồi']::text[]),
  ('sp-1551', '1551', 'Người đàn ông cởi trần ngồi thư giãn 2', 'https://kevindauto.com/products/sp-1551.webp', 'nam', 'Đời thường', array['nam', 'cởi trần', 'ngồi']::text[]),
  ('sp-1552', '1552', 'Người đàn ông khoanh tay đời thường', 'https://kevindauto.com/products/sp-1552.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'đứng']::text[]),
  ('sp-1553', '1553', 'Người đàn ông vest ngồi ghế', 'https://kevindauto.com/products/sp-1553.webp', 'nam', 'Công sở', array['nam', 'vest', 'ngồi']::text[]),
  ('sp-1554', '1554', 'Cụ ông đứng casual', 'https://kevindauto.com/products/sp-1554.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đứng']::text[]),
  ('sp-1555', '1555', 'Người đàn ông áo len đứng', 'https://kevindauto.com/products/sp-1555.webp', 'nam', 'Đời thường', array['nam', 'áo len', 'đứng']::text[]),
  ('sp-1556', '1556', 'Người đàn ông cầm áo khoác đứng', 'https://kevindauto.com/products/sp-1556.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-1557', '1557', 'Người đàn ông khoác áo choàng đứng', 'https://kevindauto.com/products/sp-1557.webp', 'nam', 'Đời thường', array['nam', 'áo choàng', 'đứng']::text[]),
  ('sp-1558', '1558', 'Người đàn ông cầm mũ bảo hiểm đứng', 'https://kevindauto.com/products/sp-1558.webp', 'nam', 'Đời thường', array['nam', 'mũ bảo hiểm', 'đứng']::text[]),
  ('sp-1559', '1559', 'Người đàn ông quỳ chụp ảnh', 'https://kevindauto.com/products/sp-1559.webp', 'nam', 'Nghề nghiệp', array['nam', 'quỳ', 'chụp ảnh']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
