-- Lo 046: san pham 1560 den 1639
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1560', '1560', 'Cụ ông vest cầm súng', 'https://kevindauto.com/products/sp-1560.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vest']::text[]),
  ('sp-1561', '1561', 'Người đàn ông đồng phục cổ điển đứng', 'https://kevindauto.com/products/sp-1561.webp', 'nam', 'Cổ điển', array['nam', 'đồng phục', 'cổ điển']::text[]),
  ('sp-1562', '1562', 'Người đàn ông vest đứng casual 3', 'https://kevindauto.com/products/sp-1562.webp', 'nam', 'Công sở', array['nam', 'vest', 'đứng']::text[]),
  ('sp-1563', '1563', 'Người đàn ông hoodie cầm nến', 'https://kevindauto.com/products/sp-1563.webp', 'nam', 'Đời thường', array['nam', 'hoodie', 'nến']::text[]),
  ('sp-1564', '1564', 'Người đàn ông cởi trần chống hông', 'https://kevindauto.com/products/sp-1564.webp', 'nam', 'Thể hình', array['nam', 'cởi trần', 'chống hông']::text[]),
  ('sp-1565', '1565', 'Cô gái hoạ sĩ ngồi vẽ tranh', 'https://kevindauto.com/products/sp-1565.webp', 'nu', 'Nghề nghiệp', array['nữ', 'hoạ sĩ', 'vẽ tranh', 'nghề nghiệp']::text[]),
  ('sp-1566', '1566', 'Tượng thiên thần nhỏ có cánh', 'https://kevindauto.com/products/sp-1566.webp', 'nu', 'Nghệ thuật', array['nữ', 'thiên thần', 'cánh', 'nghệ thuật']::text[]),
  ('sp-1567', '1567', 'Nhân vật áo choàng bí ẩn che mặt', 'https://kevindauto.com/products/sp-1567.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'bí ẩn']::text[]),
  ('sp-1568', '1568', 'Ninja tóc vàng áo choàng giơ tay', 'https://kevindauto.com/products/sp-1568.webp', 'nam', 'Fantasy', array['fantasy', 'ninja', 'áo choàng']::text[]),
  ('sp-1569', '1569', 'Chiến binh có cánh áo choàng dang tay', 'https://kevindauto.com/products/sp-1569.webp', 'nam', 'Fantasy', array['fantasy', 'cánh', 'áo choàng']::text[]),
  ('sp-1570', '1570', 'Nhân vật áo choàng đứng tự nhiên', 'https://kevindauto.com/products/sp-1570.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng']::text[]),
  ('sp-1571', '1571', 'Nhân vật cầm roi áo choàng', 'https://kevindauto.com/products/sp-1571.webp', 'nam', 'Fantasy', array['fantasy', 'roi', 'áo choàng']::text[]),
  ('sp-1572', '1572', 'Nhân vật áo choàng trùm đầu đứng', 'https://kevindauto.com/products/sp-1572.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'trùm đầu']::text[]),
  ('sp-1573', '1573', 'Nhân vật áo choàng giơ nắm đấm', 'https://kevindauto.com/products/sp-1573.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'nắm đấm']::text[]),
  ('sp-1574', '1574', 'Nhân vật áo choàng băng trán tạo dáng', 'https://kevindauto.com/products/sp-1574.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'băng trán']::text[]),
  ('sp-1575', '1575', 'Nhân vật tóc trắng bù xù áo choàng', 'https://kevindauto.com/products/sp-1575.webp', 'nam', 'Fantasy', array['fantasy', 'tóc trắng', 'áo choàng']::text[]),
  ('sp-1576', '1576', 'Nhân vật áo choàng cầm quạt', 'https://kevindauto.com/products/sp-1576.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'quạt']::text[]),
  ('sp-1577', '1577', 'Nữ chiến binh fantasy cầm dao găm', 'https://kevindauto.com/products/sp-1577.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'dao găm']::text[]),
  ('sp-1578', '1578', 'Cô gái áo khoác dáng gợi cảm', 'https://kevindauto.com/products/sp-1578.webp', 'nu', 'Gợi cảm', array['nữ', 'áo khoác', 'gợi cảm']::text[]),
  ('sp-1579', '1579', 'Hổ', 'https://kevindauto.com/products/sp-1579.webp', 'dongvat', 'Động vật', array['hổ', 'động vật']::text[]),
  ('sp-1580', '1580', 'Cô gái nội y dáng gợi cảm', 'https://kevindauto.com/products/sp-1580.webp', 'nu', 'Gợi cảm', array['nữ', 'nội y', 'gợi cảm']::text[]),
  ('sp-1581', '1581', 'Cụ ông vest ra hiệu nói chuyện', 'https://kevindauto.com/products/sp-1581.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vest']::text[]),
  ('sp-1582', '1582', 'Mascot bé gái tóc buộc', 'https://kevindauto.com/products/sp-1582.webp', 'dongvat', 'Mascot', array['mascot', 'bé gái', 'chibi']::text[]),
  ('sp-1583', '1583', 'Mascot gấu đứng vẫy tay', 'https://kevindauto.com/products/sp-1583.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'chibi']::text[]),
  ('sp-1584', '1584', 'Cụ ông đứng casual 2', 'https://kevindauto.com/products/sp-1584.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đứng']::text[]),
  ('sp-1585', '1585', 'Nhân vật tóc trắng ngồi xổm', 'https://kevindauto.com/products/sp-1585.webp', 'nam', 'Anime', array['anime', 'tóc trắng', 'ngồi xổm']::text[]),
  ('sp-1586', '1586', 'Cô gái dáng gợi cảm đứng thẳng', 'https://kevindauto.com/products/sp-1586.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đứng']::text[]),
  ('sp-1587', '1587', 'Mascot ếch ngồi', 'https://kevindauto.com/products/sp-1587.webp', 'dongvat', 'Mascot', array['mascot', 'ếch', 'chibi']::text[]),
  ('sp-1588', '1588', 'Nhân vật fantasy dáng mảnh khảnh', 'https://kevindauto.com/products/sp-1588.webp', 'nam', 'Fantasy', array['fantasy', 'độc đáo']::text[]),
  ('sp-1589', '1589', 'Nhân vật khoác lông thú cổ trang', 'https://kevindauto.com/products/sp-1589.webp', 'nam', 'Cổ trang', array['nam', 'lông thú', 'cổ trang']::text[]),
  ('sp-1590', '1590', 'Samurai cầm kiếm tư thế chiến đấu', 'https://kevindauto.com/products/sp-1590.webp', 'nam', 'Cổ trang', array['nam', 'samurai', 'kiếm', 'cổ trang']::text[]),
  ('sp-1591', '1591', 'Samurai đứng cầm kiếm', 'https://kevindauto.com/products/sp-1591.webp', 'nam', 'Cổ trang', array['nam', 'samurai', 'kiếm', 'cổ trang']::text[]),
  ('sp-1592', '1592', 'Xe đạp mô hình', 'https://kevindauto.com/products/sp-1592.webp', 'xe', 'Xe đạp', array['xe đạp']::text[]),
  ('sp-1593', '1593', 'Thùng phuy dầu', 'https://kevindauto.com/products/sp-1593.webp', 'phukien', 'Bối cảnh', array['thùng phuy', 'dầu', 'bối cảnh']::text[]),
  ('sp-1594', '1594', 'Trụ cứu hoả', 'https://kevindauto.com/products/sp-1594.webp', 'phukien', 'Bối cảnh', array['trụ cứu hỏa', 'bối cảnh']::text[]),
  ('sp-1595', '1595', 'Lính đánh thuê trang bị balo', 'https://kevindauto.com/products/sp-1595.webp', 'nam', 'Quân sự', array['nam', 'lính', 'balo', 'quân sự']::text[]),
  ('sp-1596', '1596', 'Người đàn ông cơ bắp tóc dựng cởi trần', 'https://kevindauto.com/products/sp-1596.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'cởi trần']::text[]),
  ('sp-1597', '1597', 'Lạc đà', 'https://kevindauto.com/products/sp-1597.webp', 'dongvat', 'Động vật', array['lạc đà', 'động vật']::text[]),
  ('sp-1598', '1598', 'Cô gái gợi cảm ôm quả cầu', 'https://kevindauto.com/products/sp-1598.webp', 'nu', 'Fantasy', array['nữ', 'gợi cảm', 'quả cầu', 'fantasy']::text[]),
  ('sp-1599', '1599', 'Tượng học giả cổ trang Á Đông', 'https://kevindauto.com/products/sp-1599.webp', 'nam', 'Nghệ thuật', array['tượng', 'học giả', 'cổ trang', 'nghệ thuật']::text[]),
  ('sp-1600', '1600', 'Tượng học giả áo choàng cổ trang', 'https://kevindauto.com/products/sp-1600.webp', 'caotuoi', 'Nghệ thuật', array['người già', 'học giả', 'cổ trang', 'nghệ thuật']::text[]),
  ('sp-1601', '1601', 'Người đàn ông đội mũ vest cổ điển', 'https://kevindauto.com/products/sp-1601.webp', 'nam', 'Cổ điển', array['nam', 'mũ', 'vest', 'cổ điển']::text[]),
  ('sp-1602', '1602', 'Cô gái áo khoác đội mũ vintage', 'https://kevindauto.com/products/sp-1602.webp', 'nu', 'Vintage', array['nữ', 'áo khoác', 'mũ', 'vintage']::text[]),
  ('sp-1603', '1603', 'Người đàn ông vest đội mũ đứng', 'https://kevindauto.com/products/sp-1603.webp', 'nam', 'Cổ điển', array['nam', 'vest', 'mũ', 'cổ điển']::text[]),
  ('sp-1604', '1604', 'Mascot gấu đội mũ cầm máy ảnh', 'https://kevindauto.com/products/sp-1604.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'máy ảnh', 'chibi']::text[]),
  ('sp-1605', '1605', 'Mascot gấu khoác áo choàng quàng khăn', 'https://kevindauto.com/products/sp-1605.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'khăn quàng', 'chibi']::text[]),
  ('sp-1606', '1606', 'Mascot cáo cầm máy ảnh vest', 'https://kevindauto.com/products/sp-1606.webp', 'dongvat', 'Mascot', array['mascot', 'cáo', 'máy ảnh', 'chibi']::text[]),
  ('sp-1607', '1607', 'Mascot chim cánh cụt đứng', 'https://kevindauto.com/products/sp-1607.webp', 'dongvat', 'Mascot', array['mascot', 'chim cánh cụt', 'chibi']::text[]),
  ('sp-1608', '1608', 'Mascot chim cánh cụt đứng cao', 'https://kevindauto.com/products/sp-1608.webp', 'dongvat', 'Mascot', array['mascot', 'chim cánh cụt', 'chibi']::text[]),
  ('sp-1609', '1609', 'Mascot trứng chim dễ thương', 'https://kevindauto.com/products/sp-1609.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1610', '1610', 'Mascot chim cánh cụt đứng kiểu 2', 'https://kevindauto.com/products/sp-1610.webp', 'dongvat', 'Mascot', array['mascot', 'chim cánh cụt', 'chibi']::text[]),
  ('sp-1611', '1611', 'Mascot chim cánh cụt mặc đồng phục', 'https://kevindauto.com/products/sp-1611.webp', 'dongvat', 'Mascot', array['mascot', 'chim cánh cụt', 'đồng phục', 'chibi']::text[]),
  ('sp-1612', '1612', 'Mascot chim cánh cụt khoác áo choàng', 'https://kevindauto.com/products/sp-1612.webp', 'dongvat', 'Mascot', array['mascot', 'chim cánh cụt', 'áo choàng', 'chibi']::text[]),
  ('sp-1613', '1613', 'Cô gái anime cầm kiếm nhỏ', 'https://kevindauto.com/products/sp-1613.webp', 'nu', 'Anime', array['nữ', 'anime', 'kiếm']::text[]),
  ('sp-1614', '1614', 'Cô gái gợi cảm dáng chuẩn 2', 'https://kevindauto.com/products/sp-1614.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1615', '1615', 'Cô gái fantasy áo choàng mở', 'https://kevindauto.com/products/sp-1615.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'áo choàng']::text[]),
  ('sp-1616', '1616', 'Cô gái đội mũ cầm bát', 'https://kevindauto.com/products/sp-1616.webp', 'nu', 'Đời thường', array['nữ', 'mũ', 'bát']::text[]),
  ('sp-1617', '1617', 'Cô gái phiêu lưu áo choàng túi xách', 'https://kevindauto.com/products/sp-1617.webp', 'nu', 'Du lịch', array['nữ', 'áo choàng', 'túi xách', 'du lịch']::text[]),
  ('sp-1618', '1618', 'Cô gái cầm loa cổ vũ', 'https://kevindauto.com/products/sp-1618.webp', 'nu', 'Đời thường', array['nữ', 'loa', 'cổ vũ']::text[]),
  ('sp-1619', '1619', 'Cô gái ăn mừng tạp dề', 'https://kevindauto.com/products/sp-1619.webp', 'nu', 'Đời thường', array['nữ', 'ăn mừng', 'tạp dề']::text[]),
  ('sp-1620', '1620', 'Cô gái áo khoác cầm đồ uống', 'https://kevindauto.com/products/sp-1620.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đồ uống']::text[]),
  ('sp-1621', '1621', 'Tượng nhỏ lướt sóng mini', 'https://kevindauto.com/products/sp-1621.webp', 'nu', 'Nghệ thuật', array['nữ', 'lướt sóng', 'nghệ thuật', 'tỉ lệ nhỏ']::text[]),
  ('sp-1622', '1622', 'Nữ chiến binh fantasy cầm thương', 'https://kevindauto.com/products/sp-1622.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'thương', 'fantasy']::text[]),
  ('sp-1623', '1623', 'Nữ chiến binh fantasy áo choàng', 'https://kevindauto.com/products/sp-1623.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'áo choàng', 'fantasy']::text[]),
  ('sp-1624', '1624', 'Cô gái chân váy dạo phố', 'https://kevindauto.com/products/sp-1624.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'dạo phố']::text[]),
  ('sp-1625', '1625', 'Cô gái fantasy đội mũ áo choàng', 'https://kevindauto.com/products/sp-1625.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'mũ', 'áo choàng']::text[]),
  ('sp-1626', '1626', 'Cô gái ngồi áo choàng trùm đầu', 'https://kevindauto.com/products/sp-1626.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'áo choàng']::text[]),
  ('sp-1627', '1627', 'Nữ đặc nhiệm cầm súng đứng', 'https://kevindauto.com/products/sp-1627.webp', 'nu', 'Hành động', array['nữ', 'đặc nhiệm', 'súng', 'hành động']::text[]),
  ('sp-1628', '1628', 'Nữ xạ thủ cầm súng bắn tỉa', 'https://kevindauto.com/products/sp-1628.webp', 'nu', 'Hành động', array['nữ', 'súng bắn tỉa', 'hành động']::text[]),
  ('sp-1629', '1629', 'Cô gái gợi cảm cầm quạt', 'https://kevindauto.com/products/sp-1629.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'quạt']::text[]),
  ('sp-1630', '1630', 'Tượng tiên cá trên bệ', 'https://kevindauto.com/products/sp-1630.webp', 'nu', 'Nghệ thuật', array['nữ', 'tiên cá', 'nghệ thuật', 'fantasy']::text[]),
  ('sp-1631', '1631', 'Cô gái lái xe máy địa hình cầm súng', 'https://kevindauto.com/products/sp-1631.webp', 'xe', 'Xe máy', array['nữ', 'xe máy', 'địa hình', 'súng']::text[]),
  ('sp-1632', '1632', 'Cô gái ngồi trên mô tô', 'https://kevindauto.com/products/sp-1632.webp', 'xe', 'Mô tô', array['nữ', 'mô tô']::text[]),
  ('sp-1633', '1633', 'Tượng thiên thần dang tay', 'https://kevindauto.com/products/sp-1633.webp', 'nu', 'Nghệ thuật', array['nữ', 'thiên thần', 'nghệ thuật']::text[]),
  ('sp-1634', '1634', 'Cô gái áo khoác cầm ly đứng', 'https://kevindauto.com/products/sp-1634.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'ly nước']::text[]),
  ('sp-1635', '1635', 'Cô gái áo choàng dài trang trọng', 'https://kevindauto.com/products/sp-1635.webp', 'nu', 'Cổ trang', array['nữ', 'áo choàng', 'trang trọng']::text[]),
  ('sp-1636', '1636', 'Tượng rồng nghệ thuật cuộn mình', 'https://kevindauto.com/products/sp-1636.webp', 'dongvat', 'Nghệ thuật', array['rồng', 'nghệ thuật', 'fantasy']::text[]),
  ('sp-1637', '1637', 'Em bé bò trên sàn', 'https://kevindauto.com/products/sp-1637.webp', 'treem', 'Trẻ em', array['trẻ em', 'em bé', 'bò']::text[]),
  ('sp-1638', '1638', 'Vật phẩm trang trí thủ công', 'https://kevindauto.com/products/sp-1638.webp', 'phukien', 'Bối cảnh', array['trang trí', 'bối cảnh']::text[]),
  ('sp-1639', '1639', 'Bó hoa hồng trang trí', 'https://kevindauto.com/products/sp-1639.webp', 'phukien', 'Bối cảnh', array['hoa hồng', 'trang trí', 'bối cảnh']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
