-- Lo 047: san pham 1640 den 1721
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1640', '1640', 'Mascot tai to màu xanh', 'https://kevindauto.com/products/sp-1640.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1641', '1641', 'Mascot chuột điện vàng', 'https://kevindauto.com/products/sp-1641.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1642', '1642', 'Mascot lợn rừng chiến binh cầm vũ khí', 'https://kevindauto.com/products/sp-1642.webp', 'dongvat', 'Mascot', array['mascot', 'lợn rừng', 'vũ khí', 'chibi']::text[]),
  ('sp-1643', '1643', 'Mascot mập đội mũ phi hành', 'https://kevindauto.com/products/sp-1643.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'mũ']::text[]),
  ('sp-1644', '1644', 'Mascot mập đội mũ cứng', 'https://kevindauto.com/products/sp-1644.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'mũ']::text[]),
  ('sp-1645', '1645', 'Mascot mập mặc vest', 'https://kevindauto.com/products/sp-1645.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'vest']::text[]),
  ('sp-1646', '1646', 'Mascot mập đội mũ tai thỏ', 'https://kevindauto.com/products/sp-1646.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'tai thỏ']::text[]),
  ('sp-1647', '1647', 'Mascot mập đội mũ robot', 'https://kevindauto.com/products/sp-1647.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'robot']::text[]),
  ('sp-1648', '1648', 'Mascot mập ngồi trên sofa', 'https://kevindauto.com/products/sp-1648.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'sofa']::text[]),
  ('sp-1649', '1649', 'Người đàn ông cơ bắp khoác áo khoanh tay', 'https://kevindauto.com/products/sp-1649.webp', 'nam', 'Đời thường', array['nam', 'cơ bắp', 'khoanh tay']::text[]),
  ('sp-1650', '1650', 'Người đàn ông vest tóc ngắn đứng', 'https://kevindauto.com/products/sp-1650.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[]),
  ('sp-1651', '1651', 'Người đàn ông áo khoác cầm súng đứng', 'https://kevindauto.com/products/sp-1651.webp', 'nam', 'Hành động', array['nam', 'áo khoác', 'súng', 'hành động']::text[]),
  ('sp-1652', '1652', 'Người đàn ông cởi trần đi bộ', 'https://kevindauto.com/products/sp-1652.webp', 'nam', 'Đời thường', array['nam', 'cởi trần', 'đi bộ']::text[]),
  ('sp-1653', '1653', 'Cụ ông đội mũ đi bộ', 'https://kevindauto.com/products/sp-1653.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'mũ', 'đi bộ']::text[]),
  ('sp-1654', '1654', 'Ghế lười hạt xốp cùng loa', 'https://kevindauto.com/products/sp-1654.webp', 'phukien', 'Nội thất', array['ghế lười', 'loa', 'nội thất']::text[]),
  ('sp-1655', '1655', 'Người đàn ông vô gia cư ngồi bó gối', 'https://kevindauto.com/products/sp-1655.webp', 'nam', 'Đời thường', array['nam', 'vô gia cư', 'ngồi']::text[]),
  ('sp-1656', '1656', 'Người đàn ông đội mũ bảo hiểm dắt xe', 'https://kevindauto.com/products/sp-1656.webp', 'nam', 'Xe cộ', array['nam', 'mũ bảo hiểm', 'xe máy']::text[]),
  ('sp-1657', '1657', 'Người đàn ông vác ván lướt sóng', 'https://kevindauto.com/products/sp-1657.webp', 'nam', 'Thể thao', array['nam', 'lướt sóng', 'thể thao']::text[]),
  ('sp-1658', '1658', 'Người đàn ông đi bộ vung tay', 'https://kevindauto.com/products/sp-1658.webp', 'nam', 'Đời thường', array['nam', 'đi bộ', 'đời thường']::text[]),
  ('sp-1659', '1659', 'Người đàn ông cơ bắp đứng casual', 'https://kevindauto.com/products/sp-1659.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'đứng']::text[]),
  ('sp-1660', '1660', 'Người đàn ông áo khoác đứng casual 2', 'https://kevindauto.com/products/sp-1660.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-1661', '1661', 'Cô gái gợi cảm nhấc chân', 'https://kevindauto.com/products/sp-1661.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1662', '1662', 'Cô gái gợi cảm quỳ gối', 'https://kevindauto.com/products/sp-1662.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'quỳ']::text[]),
  ('sp-1663', '1663', 'Cô gái áo choàng streetwear hành động', 'https://kevindauto.com/products/sp-1663.webp', 'nu', 'Streetwear', array['nữ', 'áo choàng', 'hành động']::text[]),
  ('sp-1664', '1664', 'Cô gái gợi cảm nhấc chân cao', 'https://kevindauto.com/products/sp-1664.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1665', '1665', 'Nữ chiến binh fantasy cầm kiếm gợi cảm', 'https://kevindauto.com/products/sp-1665.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'kiếm', 'gợi cảm']::text[]),
  ('sp-1666', '1666', 'Nữ đặc nhiệm quỳ cầm súng gợi cảm', 'https://kevindauto.com/products/sp-1666.webp', 'nu', 'Fantasy', array['nữ', 'súng', 'gợi cảm']::text[]),
  ('sp-1667', '1667', 'Cô gái gợi cảm đứng cầm sách', 'https://kevindauto.com/products/sp-1667.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'sách']::text[]),
  ('sp-1668', '1668', 'Cô gái gợi cảm quỳ thư giãn', 'https://kevindauto.com/products/sp-1668.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'quỳ']::text[]),
  ('sp-1669', '1669', 'Tượng fantasy nữ trên bệ vũ khí', 'https://kevindauto.com/products/sp-1669.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'nghệ thuật']::text[]),
  ('sp-1670', '1670', 'Cô gái ngồi bàn trang điểm', 'https://kevindauto.com/products/sp-1670.webp', 'nu', 'Đời thường', array['nữ', 'bàn trang điểm', 'ngồi']::text[]),
  ('sp-1671', '1671', 'Cụ bà đứng quay lưng áo choàng', 'https://kevindauto.com/products/sp-1671.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'áo choàng']::text[]),
  ('sp-1672', '1672', 'Cô gái gợi cảm ngồi xổm xách túi', 'https://kevindauto.com/products/sp-1672.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'túi xách']::text[]),
  ('sp-1673', '1673', 'Chiến binh tóc dựng phong cách anime nắm đấm', 'https://kevindauto.com/products/sp-1673.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'hành động']::text[]),
  ('sp-1674', '1674', 'Chiến binh cầm kiếm lớn phong cách anime', 'https://kevindauto.com/products/sp-1674.webp', 'nam', 'Anime', array['anime', 'kiếm', 'hành động']::text[]),
  ('sp-1675', '1675', 'Chiến binh tóc dựng ném đấm', 'https://kevindauto.com/products/sp-1675.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'hành động']::text[]),
  ('sp-1676', '1676', 'Chiến binh nhí tóc dựng phong cách anime', 'https://kevindauto.com/products/sp-1676.webp', 'treem', 'Anime', array['trẻ em', 'anime', 'độc đáo']::text[]),
  ('sp-1677', '1677', 'Chiến binh tóc dựng áo rách đứng', 'https://kevindauto.com/products/sp-1677.webp', 'nam', 'Anime', array['anime', 'độc đáo', 'hành động']::text[]),
  ('sp-1678', '1678', 'Chiến binh tóc dựng phong cách anime kiểu 2', 'https://kevindauto.com/products/sp-1678.webp', 'nam', 'Anime', array['anime', 'độc đáo']::text[]),
  ('sp-1679', '1679', 'Mascot sao biển chỉ tay', 'https://kevindauto.com/products/sp-1679.webp', 'dongvat', 'Mascot', array['mascot', 'sao biển', 'chibi']::text[]),
  ('sp-1680', '1680', 'Mascot sao biển chắp tay', 'https://kevindauto.com/products/sp-1680.webp', 'dongvat', 'Mascot', array['mascot', 'sao biển', 'chibi']::text[]),
  ('sp-1681', '1681', 'Lợn', 'https://kevindauto.com/products/sp-1681.webp', 'dongvat', 'Động vật', array['lợn', 'động vật']::text[]),
  ('sp-1682', '1682', 'Xe pod tương lai', 'https://kevindauto.com/products/sp-1682.webp', 'xe', 'Xe cộ', array['xe cộ', 'tương lai', 'độc đáo']::text[]),
  ('sp-1683', '1683', 'Cô gái lái xe pod tương lai', 'https://kevindauto.com/products/sp-1683.webp', 'xe', 'Xe cộ', array['nữ', 'xe cộ', 'tương lai']::text[]),
  ('sp-1684', '1684', 'Bé trai hoodie cầm súng đồ chơi', 'https://kevindauto.com/products/sp-1684.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'hoodie', 'súng']::text[]),
  ('sp-1685', '1685', 'Chiến binh đội đen cầm rìu', 'https://kevindauto.com/products/sp-1685.webp', 'nam', 'Fantasy', array['fantasy', 'chiến binh', 'rìu', 'hành động']::text[]),
  ('sp-1686', '1686', 'Chiến binh đội xanh cầm thương', 'https://kevindauto.com/products/sp-1686.webp', 'nam', 'Fantasy', array['fantasy', 'chiến binh', 'thương', 'hành động']::text[]),
  ('sp-1687', '1687', 'Chiến binh đội xanh lá cầm kiếm', 'https://kevindauto.com/products/sp-1687.webp', 'nam', 'Fantasy', array['fantasy', 'chiến binh', 'kiếm', 'hành động']::text[]),
  ('sp-1688', '1688', 'Nữ chiến binh đội hồng cầm kiếm', 'https://kevindauto.com/products/sp-1688.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'kiếm', 'hành động']::text[]),
  ('sp-1689', '1689', 'Chiến binh đội đỏ cầm vũ khí', 'https://kevindauto.com/products/sp-1689.webp', 'nam', 'Fantasy', array['fantasy', 'chiến binh', 'vũ khí', 'hành động']::text[]),
  ('sp-1690', '1690', 'Nữ chiến binh đội vàng', 'https://kevindauto.com/products/sp-1690.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'hành động']::text[]),
  ('sp-1691', '1691', 'Chiến binh đội trắng tư thế chiến đấu', 'https://kevindauto.com/products/sp-1691.webp', 'nam', 'Fantasy', array['fantasy', 'chiến binh', 'hành động']::text[]),
  ('sp-1692', '1692', 'Nhà khoa học điên cầm vũ khí', 'https://kevindauto.com/products/sp-1692.webp', 'nam', 'Fantasy', array['fantasy', 'nhà khoa học', 'vũ khí']::text[]),
  ('sp-1693', '1693', 'Cảnh sát đứng cầm súng ngắn', 'https://kevindauto.com/products/sp-1693.webp', 'nam', 'Nghề nghiệp', array['nam', 'cảnh sát', 'súng', 'nghề nghiệp']::text[]),
  ('sp-1694', '1694', 'Hổ trắng', 'https://kevindauto.com/products/sp-1694.webp', 'dongvat', 'Động vật', array['hổ trắng', 'động vật']::text[]),
  ('sp-1695', '1695', 'Võ sĩ cơ bắp quần cargo', 'https://kevindauto.com/products/sp-1695.webp', 'nam', 'Thể thao', array['nam', 'võ sĩ', 'cơ bắp', 'thể thao']::text[]),
  ('sp-1696', '1696', 'Cô gái gợi cảm bikini đứng', 'https://kevindauto.com/products/sp-1696.webp', 'nu', 'Gợi cảm', array['nữ', 'bikini', 'gợi cảm']::text[]),
  ('sp-1697', '1697', 'Cột điện đường phố', 'https://kevindauto.com/products/sp-1697.webp', 'phukien', 'Bối cảnh', array['cột điện', 'bối cảnh', 'đường phố']::text[]),
  ('sp-1698', '1698', 'Giàn giáo khung sắt', 'https://kevindauto.com/products/sp-1698.webp', 'phukien', 'Bối cảnh', array['giàn giáo', 'xây dựng', 'bối cảnh']::text[]),
  ('sp-1699', '1699', 'Máy biến áp điện', 'https://kevindauto.com/products/sp-1699.webp', 'phukien', 'Bối cảnh', array['máy biến áp', 'điện', 'bối cảnh']::text[]),
  ('sp-1700', '1700', 'Cửa sổ kính khung nhôm', 'https://kevindauto.com/products/sp-1700.webp', 'phukien', 'Bối cảnh', array['cửa sổ', 'bối cảnh']::text[]),
  ('sp-1701', '1701', 'Cửa gỗ có ô kính', 'https://kevindauto.com/products/sp-1701.webp', 'phukien', 'Bối cảnh', array['cửa', 'bối cảnh']::text[]),
  ('sp-1702', '1702', 'Tủ điện có ô kính', 'https://kevindauto.com/products/sp-1702.webp', 'phukien', 'Bối cảnh', array['tủ điện', 'bối cảnh']::text[]),
  ('sp-1703', '1703', 'Cửa cuốn nhà kho', 'https://kevindauto.com/products/sp-1703.webp', 'phukien', 'Bối cảnh', array['cửa cuốn', 'bối cảnh']::text[]),
  ('sp-1704', '1704', 'Cột ăng-ten cao', 'https://kevindauto.com/products/sp-1704.webp', 'phukien', 'Bối cảnh', array['cột ăng-ten', 'bối cảnh']::text[]),
  ('sp-1705', '1705', 'Cột thẳng đứng mảnh', 'https://kevindauto.com/products/sp-1705.webp', 'phukien', 'Bối cảnh', array['cột', 'bối cảnh']::text[]),
  ('sp-1706', '1706', 'Rào chắn tam giác có gai', 'https://kevindauto.com/products/sp-1706.webp', 'phukien', 'Bối cảnh', array['rào chắn', 'bối cảnh']::text[]),
  ('sp-1707', '1707', 'Trụ bơm xăng', 'https://kevindauto.com/products/sp-1707.webp', 'phukien', 'Bối cảnh', array['trụ bơm xăng', 'bối cảnh']::text[]),
  ('sp-1708', '1708', 'Xe jeep quân sự', 'https://kevindauto.com/products/sp-1708.webp', 'xe', 'Xe cộ', array['xe jeep', 'quân sự']::text[]),
  ('sp-1709', '1709', 'Mascot mập đội mũ chóp', 'https://kevindauto.com/products/sp-1709.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'mũ chóp']::text[]),
  ('sp-1710', '1710', 'Dê', 'https://kevindauto.com/products/sp-1710.webp', 'dongvat', 'Động vật', array['dê', 'động vật']::text[]),
  ('sp-1713', '1713', 'Nữ y tá đứng', 'https://kevindauto.com/products/sp-1713.webp', 'nu', 'Nghề nghiệp', array['nữ', 'y tá', 'nghề nghiệp']::text[]),
  ('sp-1714', '1714', 'Bò', 'https://kevindauto.com/products/sp-1714.webp', 'dongvat', 'Động vật', array['bò', 'động vật']::text[]),
  ('sp-1715', '1715', 'Cô gái gợi cảm ngồi bàn', 'https://kevindauto.com/products/sp-1715.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'ngồi']::text[]),
  ('sp-1716', '1716', 'Chiến binh nhảy cầm kiếm hành động', 'https://kevindauto.com/products/sp-1716.webp', 'nam', 'Anime', array['anime', 'kiếm', 'hành động']::text[]),
  ('sp-1717', '1717', 'Người đàn ông cầm bình xịt sơn', 'https://kevindauto.com/products/sp-1717.webp', 'nam', 'Đời thường', array['nam', 'bình xịt sơn', 'graffiti']::text[]),
  ('sp-1718', '1718', 'Chiến sĩ trang bị nặng đứng', 'https://kevindauto.com/products/sp-1718.webp', 'nam', 'Quân sự', array['nam', 'lính', 'quân sự']::text[]),
  ('sp-1719', '1719', 'Chiến sĩ cầm súng trường đứng', 'https://kevindauto.com/products/sp-1719.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1720', '1720', 'Chiến sĩ ngắm bắn súng trường 2', 'https://kevindauto.com/products/sp-1720.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1721', '1721', 'Người đàn ông vest chống chân lên hòm', 'https://kevindauto.com/products/sp-1721.webp', 'nam', 'Đời thường', array['nam', 'vest', 'hòm']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
