-- Lo 048: san pham 1722 den 1801
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1722', '1722', 'Cô gái gợi cảm quấn vải fantasy', 'https://kevindauto.com/products/sp-1722.webp', 'nu', 'Fantasy', array['nữ', 'gợi cảm', 'fantasy']::text[]),
  ('sp-1723', '1723', 'Cô gái gợi cảm đứng thẳng 2', 'https://kevindauto.com/products/sp-1723.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1724', '1724', 'Cô gái gợi cảm mặc đầm dài', 'https://kevindauto.com/products/sp-1724.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm']::text[]),
  ('sp-1725', '1725', 'Cô gái gợi cảm cầm kiếm đứng', 'https://kevindauto.com/products/sp-1725.webp', 'nu', 'Fantasy', array['nữ', 'gợi cảm', 'kiếm']::text[]),
  ('sp-1726', '1726', 'Nữ pháp sư đội mũ phù thuỷ', 'https://kevindauto.com/products/sp-1726.webp', 'nu', 'Fantasy', array['nữ', 'phù thuỷ', 'fantasy']::text[]),
  ('sp-1727', '1727', 'Cô gái áo choàng ngắn tạo dáng', 'https://kevindauto.com/products/sp-1727.webp', 'nu', 'Đời thường', array['nữ', 'áo choàng', 'tạo dáng']::text[]),
  ('sp-1728', '1728', 'Cô gái áo choàng dài tạo dáng', 'https://kevindauto.com/products/sp-1728.webp', 'nu', 'Đời thường', array['nữ', 'áo choàng', 'tạo dáng']::text[]),
  ('sp-1729', '1729', 'Cô gái gợi cảm ngồi thư giãn', 'https://kevindauto.com/products/sp-1729.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'ngồi']::text[]),
  ('sp-1730', '1730', 'Cô gái gợi cảm đứng tạo dáng', 'https://kevindauto.com/products/sp-1730.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1731', '1731', 'Đầu bếp mập mạp cầm dụng cụ', 'https://kevindauto.com/products/sp-1731.webp', 'nam', 'Nghề nghiệp', array['nam', 'đầu bếp', 'nghề nghiệp']::text[]),
  ('sp-1732', '1732', 'Cô gái gợi cảm chào salute', 'https://kevindauto.com/products/sp-1732.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'chào']::text[]),
  ('sp-1733', '1733', 'Cô gái fantasy áo choàng dài kịch tính', 'https://kevindauto.com/products/sp-1733.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'áo choàng']::text[]),
  ('sp-1734', '1734', 'Người đội mũ mặt nạ thú', 'https://kevindauto.com/products/sp-1734.webp', 'nam', 'Fantasy', array['fantasy', 'mặt nạ', 'độc đáo']::text[]),
  ('sp-1735', '1735', 'Cô gái gợi cảm đứng tự nhiên', 'https://kevindauto.com/products/sp-1735.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1736', '1736', 'Cô gái gợi cảm đứng trên bệ', 'https://kevindauto.com/products/sp-1736.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1737', '1737', 'Nữ chiến binh fantasy áo giáp ngắn', 'https://kevindauto.com/products/sp-1737.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'áo giáp', 'fantasy']::text[]),
  ('sp-1738', '1738', 'Chiến binh tóc dựng ngồi trên mây', 'https://kevindauto.com/products/sp-1738.webp', 'nam', 'Anime', array['anime', 'độc đáo']::text[]),
  ('sp-1739', '1739', 'Cô gái gợi cảm cầm roi dài', 'https://kevindauto.com/products/sp-1739.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'roi']::text[]),
  ('sp-1740', '1740', 'Cô gái gợi cảm ngồi giày boot', 'https://kevindauto.com/products/sp-1740.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'boot']::text[]),
  ('sp-1741', '1741', 'Máy tập gym ngoài trời ghế nằm', 'https://kevindauto.com/products/sp-1741.webp', 'phukien', 'Bối cảnh', array['gym', 'ngoài trời', 'bối cảnh']::text[]),
  ('sp-1742', '1742', 'Máy tập gym ngoài trời đạp chân', 'https://kevindauto.com/products/sp-1742.webp', 'phukien', 'Bối cảnh', array['gym', 'ngoài trời', 'bối cảnh']::text[]),
  ('sp-1743', '1743', 'Máy tập gym ngoài trời xoay eo', 'https://kevindauto.com/products/sp-1743.webp', 'phukien', 'Bối cảnh', array['gym', 'ngoài trời', 'bối cảnh']::text[]),
  ('sp-1744', '1744', 'Máy tập gym ngoài trời kéo tay', 'https://kevindauto.com/products/sp-1744.webp', 'phukien', 'Bối cảnh', array['gym', 'ngoài trời', 'bối cảnh']::text[]),
  ('sp-1745', '1745', 'Robot quái vật cơ khí', 'https://kevindauto.com/products/sp-1745.webp', 'nam', 'Robot', array['robot', 'quái vật', 'cơ khí', 'fantasy']::text[]),
  ('sp-1746', '1746', 'Quái vật cơ bắp đen bóng', 'https://kevindauto.com/products/sp-1746.webp', 'nam', 'Fantasy', array['fantasy', 'quái vật', 'cơ bắp']::text[]),
  ('sp-1747', '1747', 'Tượng mannequin nam ngồi', 'https://kevindauto.com/products/sp-1747.webp', 'nam', 'Nghệ thuật', array['nam', 'mannequin', 'nghệ thuật']::text[]),
  ('sp-1748', '1748', 'Người đàn ông vest cầm súng ngắn', 'https://kevindauto.com/products/sp-1748.webp', 'nam', 'Hành động', array['nam', 'vest', 'súng', 'hành động']::text[]),
  ('sp-1749', '1749', 'Người đàn ông ngồi ghế cầm ly', 'https://kevindauto.com/products/sp-1749.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'ly nước']::text[]),
  ('sp-1750', '1750', 'Mascot đầu tròn dễ thương', 'https://kevindauto.com/products/sp-1750.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-1751', '1751', 'Nữ chiến binh anime áo giáp đứng', 'https://kevindauto.com/products/sp-1751.webp', 'nu', 'Anime', array['nữ', 'anime', 'áo giáp']::text[]),
  ('sp-1752', '1752', 'Nữ chiến binh anime cầm kiếm đứng', 'https://kevindauto.com/products/sp-1752.webp', 'nu', 'Anime', array['nữ', 'anime', 'kiếm']::text[]),
  ('sp-1753', '1753', 'Cô gái gợi cảm mặc đầm ngắn', 'https://kevindauto.com/products/sp-1753.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm']::text[]),
  ('sp-1754', '1754', 'Cô gái gợi cảm nhảy múa', 'https://kevindauto.com/products/sp-1754.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'nhảy múa']::text[]),
  ('sp-1755', '1755', 'Quái vật cơ bắp đứng', 'https://kevindauto.com/products/sp-1755.webp', 'nam', 'Fantasy', array['fantasy', 'quái vật', 'cơ bắp']::text[]),
  ('sp-1756', '1756', 'Người đàn ông cơ bắp quần short đứng', 'https://kevindauto.com/products/sp-1756.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'quần short']::text[]),
  ('sp-1757', '1757', 'Cầu thủ bóng rổ xoay bóng đội tai nghe', 'https://kevindauto.com/products/sp-1757.webp', 'thethao', 'Bóng rổ', array['nam', 'bóng rổ', 'thể thao']::text[]),
  ('sp-1758', '1758', 'Cô gái quần short đứng casual', 'https://kevindauto.com/products/sp-1758.webp', 'nu', 'Đời thường', array['nữ', 'quần short', 'đứng']::text[]),
  ('sp-1759', '1759', 'Samurai áo choàng đeo kiếm đứng', 'https://kevindauto.com/products/sp-1759.webp', 'nam', 'Cổ trang', array['nam', 'samurai', 'kiếm', 'cổ trang']::text[]),
  ('sp-1760', '1760', 'Người đàn ông hoodie đứng casual 3', 'https://kevindauto.com/products/sp-1760.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'đứng']::text[]),
  ('sp-1761', '1761', 'Tượng nhỏ tỉ lệ mini đứng', 'https://kevindauto.com/products/sp-1761.webp', 'nam', 'Nghệ thuật', array['nam', 'tỉ lệ nhỏ', 'nghệ thuật']::text[]),
  ('sp-1762', '1762', 'Người đàn ông trùm mũ đeo mặt nạ', 'https://kevindauto.com/products/sp-1762.webp', 'nam', 'Hành động', array['nam', 'mũ trùm', 'mặt nạ', 'hành động']::text[]),
  ('sp-1763', '1763', 'Người đàn ông áo polo đứng', 'https://kevindauto.com/products/sp-1763.webp', 'nam', 'Đời thường', array['nam', 'áo polo', 'đứng']::text[]),
  ('sp-1764', '1764', 'Người đàn ông chào salute casual', 'https://kevindauto.com/products/sp-1764.webp', 'nam', 'Đời thường', array['nam', 'chào', 'salute']::text[]),
  ('sp-1765', '1765', 'Sinh vật ngoài hành tinh đứng', 'https://kevindauto.com/products/sp-1765.webp', 'nam', 'Fantasy', array['fantasy', 'sinh vật', 'độc đáo']::text[]),
  ('sp-1766', '1766', 'Chiến sĩ trang bị súng trường đứng', 'https://kevindauto.com/products/sp-1766.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1767', '1767', 'Cô gái chống hông áo khoác', 'https://kevindauto.com/products/sp-1767.webp', 'nu', 'Đời thường', array['nữ', 'chống hông', 'áo khoác']::text[]),
  ('sp-1768', '1768', 'Cô gái gợi cảm quần short đứng', 'https://kevindauto.com/products/sp-1768.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'quần short']::text[]),
  ('sp-1769', '1769', 'Hộp bánh trung thu trang trí', 'https://kevindauto.com/products/sp-1769.webp', 'phukien', 'Bối cảnh', array['bánh', 'hộp quà', 'bối cảnh']::text[]),
  ('sp-1770', '1770', 'Khay bánh kẹo trang trí', 'https://kevindauto.com/products/sp-1770.webp', 'phukien', 'Bối cảnh', array['bánh kẹo', 'khay', 'bối cảnh']::text[]),
  ('sp-1771', '1771', 'Hộp quà bánh kẹo trang trí', 'https://kevindauto.com/products/sp-1771.webp', 'phukien', 'Bối cảnh', array['quà tặng', 'bánh kẹo', 'bối cảnh']::text[]),
  ('sp-1772', '1772', 'Xe nâng tay hàng hoá', 'https://kevindauto.com/products/sp-1772.webp', 'phukien', 'Bối cảnh', array['xe nâng tay', 'kho hàng', 'bối cảnh']::text[]),
  ('sp-1773', '1773', 'Mặt nạ phòng độc', 'https://kevindauto.com/products/sp-1773.webp', 'phukien', 'Bối cảnh', array['mặt nạ phòng độc', 'bối cảnh']::text[]),
  ('sp-1774', '1774', 'Bình gas propane', 'https://kevindauto.com/products/sp-1774.webp', 'phukien', 'Bối cảnh', array['bình gas', 'bối cảnh']::text[]),
  ('sp-1775', '1775', 'Dép sandal', 'https://kevindauto.com/products/sp-1775.webp', 'phukien', 'Phụ kiện', array['dép', 'giày dép', 'phụ kiện']::text[]),
  ('sp-1776', '1776', 'Balo đeo vai', 'https://kevindauto.com/products/sp-1776.webp', 'phukien', 'Phụ kiện', array['balo', 'phụ kiện']::text[]),
  ('sp-1777', '1777', 'Đèn đứng trang trí', 'https://kevindauto.com/products/sp-1777.webp', 'phukien', 'Bối cảnh', array['đèn', 'trang trí', 'bối cảnh']::text[]),
  ('sp-1778', '1778', 'Giày sneaker cổ thấp', 'https://kevindauto.com/products/sp-1778.webp', 'phukien', 'Phụ kiện', array['giày', 'sneaker', 'phụ kiện']::text[]),
  ('sp-1779', '1779', 'Giày boot cổ cao', 'https://kevindauto.com/products/sp-1779.webp', 'phukien', 'Phụ kiện', array['giày boot', 'phụ kiện']::text[]),
  ('sp-1780', '1780', 'Võ sĩ Kung Fu tư thế tấn công', 'https://kevindauto.com/products/sp-1780.webp', 'nam', 'Thể thao', array['nam', 'võ thuật', 'kung fu', 'thể thao']::text[]),
  ('sp-1781', '1781', 'Chiến sĩ thời chiến cầm súng đứng', 'https://kevindauto.com/products/sp-1781.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1782', '1782', 'Chiến sĩ hành quân cầm súng', 'https://kevindauto.com/products/sp-1782.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1783', '1783', 'Chiến sĩ ngắm bắn súng', 'https://kevindauto.com/products/sp-1783.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1784', '1784', 'Chiến sĩ hành quân cầm súng 2', 'https://kevindauto.com/products/sp-1784.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1785', '1785', 'Chiến sĩ cúi người cầm súng', 'https://kevindauto.com/products/sp-1785.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1786', '1786', 'Chiến sĩ hành quân cầm súng 3', 'https://kevindauto.com/products/sp-1786.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1787', '1787', 'Chiến sĩ ngắm bắn trang bị đầy đủ', 'https://kevindauto.com/products/sp-1787.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1788', '1788', 'Chiến sĩ đứng ngắm bắn', 'https://kevindauto.com/products/sp-1788.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1789', '1789', 'Chiến sĩ hành quân trang bị đầy đủ', 'https://kevindauto.com/products/sp-1789.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1790', '1790', 'Chiến sĩ cúi người cầm súng 2', 'https://kevindauto.com/products/sp-1790.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1791', '1791', 'Chiến sĩ quỳ ngắm bắn', 'https://kevindauto.com/products/sp-1791.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1792', '1792', 'Chiến sĩ cúi người hành quân', 'https://kevindauto.com/products/sp-1792.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-1793', '1793', 'Bé gái ngồi trong xe đẩy siêu thị', 'https://kevindauto.com/products/sp-1793.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'xe đẩy']::text[]),
  ('sp-1794', '1794', 'Cô gái chân váy chỉ tay xách túi', 'https://kevindauto.com/products/sp-1794.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'chỉ tay']::text[]),
  ('sp-1795', '1795', 'Cô gái đứng cầm đồ uống casual', 'https://kevindauto.com/products/sp-1795.webp', 'nu', 'Đời thường', array['nữ', 'đồ uống', 'đứng']::text[]),
  ('sp-1796', '1796', 'Cô gái dắt chó đi dạo', 'https://kevindauto.com/products/sp-1796.webp', 'nu', 'Thú cưng', array['nữ', 'chó', 'thú cưng', 'dạo phố']::text[]),
  ('sp-1797', '1797', 'Cô gái áo khoác đứng thanh lịch', 'https://kevindauto.com/products/sp-1797.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'thanh lịch']::text[]),
  ('sp-1798', '1798', 'Cô gái mặc đầm xách túi đứng', 'https://kevindauto.com/products/sp-1798.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'túi xách']::text[]),
  ('sp-1799', '1799', 'Cô gái ngồi trên thùng phuy', 'https://kevindauto.com/products/sp-1799.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'thùng phuy']::text[]),
  ('sp-1800', '1800', 'Cô gái streetwear tai mèo cầm đồ uống', 'https://kevindauto.com/products/sp-1800.webp', 'nu', 'Streetwear', array['nữ', 'tai mèo', 'streetwear', 'cá tính']::text[]),
  ('sp-1801', '1801', 'Người đàn ông vest đứng lịch lãm', 'https://kevindauto.com/products/sp-1801.webp', 'nam', 'Công sở', array['nam', 'vest', 'công sở']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
