-- Lo 049: san pham 1802 den 1881
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1802', '1802', 'Cụ ông ngồi ghế văn phòng', 'https://kevindauto.com/products/sp-1802.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ngồi']::text[]),
  ('sp-1803', '1803', 'Nữ sinh chân váy đồng phục đứng', 'https://kevindauto.com/products/sp-1803.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'đồng phục']::text[]),
  ('sp-1804', '1804', 'Ô dù cầm tay', 'https://kevindauto.com/products/sp-1804.webp', 'phukien', 'Phụ kiện', array['ô dù', 'phụ kiện']::text[]),
  ('sp-1805', '1805', 'Cô gái gợi cảm mặc đầm đứng 2', 'https://kevindauto.com/products/sp-1805.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm']::text[]),
  ('sp-1806', '1806', 'Cô gái gợi cảm mặc chân váy đứng', 'https://kevindauto.com/products/sp-1806.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'chân váy']::text[]),
  ('sp-1807', '1807', 'Nhân vật lướt ván bạc bay lượn', 'https://kevindauto.com/products/sp-1807.webp', 'nam', 'Fantasy', array['fantasy', 'lướt ván', 'độc đáo']::text[]),
  ('sp-1808', '1808', 'Người đàn ông streetwear ôm chim cú', 'https://kevindauto.com/products/sp-1808.webp', 'dongvat', 'Thú cưng', array['nam', 'chim cú', 'thú cưng', 'streetwear']::text[]),
  ('sp-1809', '1809', 'Máy lọc nước nóng lạnh', 'https://kevindauto.com/products/sp-1809.webp', 'phukien', 'Nội thất', array['máy lọc nước', 'nội thất']::text[]),
  ('sp-1810', '1810', 'Tai nghe chụp tai', 'https://kevindauto.com/products/sp-1810.webp', 'phukien', 'Phụ kiện', array['tai nghe', 'phụ kiện']::text[]),
  ('sp-1811', '1811', 'Người đàn ông đứng cầm đồ vật', 'https://kevindauto.com/products/sp-1811.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'đời thường']::text[]),
  ('sp-1812', '1812', 'Người đàn ông áo khoác đứng streetwear', 'https://kevindauto.com/products/sp-1812.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'streetwear']::text[]),
  ('sp-1813', '1813', 'Túi ngủ cắm trại', 'https://kevindauto.com/products/sp-1813.webp', 'phukien', 'Bối cảnh', array['túi ngủ', 'cắm trại', 'bối cảnh']::text[]),
  ('sp-1814', '1814', 'Giá đựng gậy golf', 'https://kevindauto.com/products/sp-1814.webp', 'phukien', 'Bối cảnh', array['golf', 'thể thao', 'bối cảnh']::text[]),
  ('sp-1815', '1815', 'Cô gái gợi cảm streetwear đứng', 'https://kevindauto.com/products/sp-1815.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'streetwear']::text[]),
  ('sp-1816', '1816', 'Cô gái đứng đi bộ casual', 'https://kevindauto.com/products/sp-1816.webp', 'nu', 'Đời thường', array['nữ', 'đi bộ', 'đời thường']::text[]),
  ('sp-1817', '1817', 'Người mặc đồ bảo hộ đeo kính đứng', 'https://kevindauto.com/products/sp-1817.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ', 'kính']::text[]),
  ('sp-1818', '1818', 'Người mặc đồ bảo hộ cầm đồ vật', 'https://kevindauto.com/products/sp-1818.webp', 'nam', 'Hành động', array['nam', 'đồ bảo hộ']::text[]),
  ('sp-1819', '1819', 'Cô gái gợi cảm đội mũ cao bồi', 'https://kevindauto.com/products/sp-1819.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'mũ cao bồi']::text[]),
  ('sp-1820', '1820', 'Người đàn ông ăn bằng đũa đứng', 'https://kevindauto.com/products/sp-1820.webp', 'nam', 'Đời thường', array['nam', 'đũa', 'ăn uống']::text[]),
  ('sp-1821', '1821', 'Người đàn ông ngồi ghế đẩu hút thuốc', 'https://kevindauto.com/products/sp-1821.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'hút thuốc']::text[]),
  ('sp-1822', '1822', 'Cô gái gợi cảm tạo dáng năng động', 'https://kevindauto.com/products/sp-1822.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'năng động']::text[]),
  ('sp-1823', '1823', 'Thùng phuy có nhãn', 'https://kevindauto.com/products/sp-1823.webp', 'phukien', 'Bối cảnh', array['thùng phuy', 'bối cảnh']::text[]),
  ('sp-1824', '1824', 'Mascot bé gái búi tóc đôi đứng', 'https://kevindauto.com/products/sp-1824.webp', 'dongvat', 'Mascot', array['mascot', 'bé gái', 'chibi']::text[]),
  ('sp-1825', '1825', 'Cô gái streetwear quần cargo đứng', 'https://kevindauto.com/products/sp-1825.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'quần cargo']::text[]),
  ('sp-1826', '1826', 'Nữ chiến binh fantasy áo choàng gợi cảm', 'https://kevindauto.com/products/sp-1826.webp', 'nu', 'Fantasy', array['nữ', 'chiến binh', 'gợi cảm', 'fantasy']::text[]),
  ('sp-1827', '1827', 'Người đàn ông vest cầm ly casual', 'https://kevindauto.com/products/sp-1827.webp', 'nam', 'Công sở', array['nam', 'vest', 'ly nước']::text[]),
  ('sp-1828', '1828', 'Cô gái gợi cảm cầm quạt xoè', 'https://kevindauto.com/products/sp-1828.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'quạt']::text[]),
  ('sp-1829', '1829', 'Nữ samurai đứng cầm kiếm anime', 'https://kevindauto.com/products/sp-1829.webp', 'nu', 'Anime', array['nữ', 'samurai', 'kiếm', 'anime']::text[]),
  ('sp-1830', '1830', 'Ninja nhí tóc vàng phong cách anime', 'https://kevindauto.com/products/sp-1830.webp', 'treem', 'Anime', array['trẻ em', 'ninja', 'anime']::text[]),
  ('sp-1831', '1831', 'Nhân vật áo choàng dài súng dramatique', 'https://kevindauto.com/products/sp-1831.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng', 'súng']::text[]),
  ('sp-1832', '1832', 'Nữ chiến binh anime áo giáp vũ khí', 'https://kevindauto.com/products/sp-1832.webp', 'nu', 'Anime', array['nữ', 'anime', 'áo giáp', 'vũ khí']::text[]),
  ('sp-1833', '1833', 'Người đàn ông vest đứng trang trọng 2', 'https://kevindauto.com/products/sp-1833.webp', 'nam', 'Công sở', array['nam', 'vest', 'trang trọng']::text[]),
  ('sp-1834', '1834', 'Người đàn ông đội mũ cầm súng dramatique', 'https://kevindauto.com/products/sp-1834.webp', 'nam', 'Hành động', array['nam', 'mũ', 'súng', 'hành động']::text[]),
  ('sp-1835', '1835', 'Cô gái cầm kiếm streetwear', 'https://kevindauto.com/products/sp-1835.webp', 'nu', 'Fantasy', array['nữ', 'kiếm', 'streetwear']::text[]),
  ('sp-1836', '1836', 'Cô gái áo khoác đứng casual 2', 'https://kevindauto.com/products/sp-1836.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đứng']::text[]),
  ('sp-1837', '1837', 'Nhà sư áo choàng đứng', 'https://kevindauto.com/products/sp-1837.webp', 'nam', 'Cổ trang', array['nam', 'nhà sư', 'áo choàng', 'cổ trang']::text[]),
  ('sp-1838', '1838', 'Tượng nữ thần áo choàng hoa lá', 'https://kevindauto.com/products/sp-1838.webp', 'nu', 'Nghệ thuật', array['nữ', 'áo choàng', 'hoa lá', 'nghệ thuật']::text[]),
  ('sp-1839', '1839', 'Người đàn ông streetwear đứng chống hông', 'https://kevindauto.com/products/sp-1839.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'chống hông']::text[]),
  ('sp-1840', '1840', 'Cô gái streetwear đứng chống chân', 'https://kevindauto.com/products/sp-1840.webp', 'nu', 'Streetwear', array['nữ', 'streetwear']::text[]),
  ('sp-1841', '1841', 'Người đàn ông ngồi cầm cờ cười tươi', 'https://kevindauto.com/products/sp-1841.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'cờ']::text[]),
  ('sp-1842', '1842', 'Người đàn ông đứng chỉ súng ngón tay', 'https://kevindauto.com/products/sp-1842.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'cử chỉ']::text[]),
  ('sp-1843', '1843', 'Cụ ông đeo kính đứng casual', 'https://kevindauto.com/products/sp-1843.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'kính']::text[]),
  ('sp-1844', '1844', 'Người đàn ông đứng tay chạm đầu casual', 'https://kevindauto.com/products/sp-1844.webp', 'nam', 'Đời thường', array['nam', 'tay chạm đầu', 'đứng']::text[]),
  ('sp-1845', '1845', 'Samurai đứng cầm kiếm dài', 'https://kevindauto.com/products/sp-1845.webp', 'nam', 'Cổ trang', array['nam', 'samurai', 'kiếm', 'cổ trang']::text[]),
  ('sp-1846', '1846', 'Người đàn ông áo choàng đứng dramatique', 'https://kevindauto.com/products/sp-1846.webp', 'nam', 'Fantasy', array['fantasy', 'áo choàng']::text[]),
  ('sp-1847', '1847', 'Cô gái gợi cảm mặc đầm cầm ly', 'https://kevindauto.com/products/sp-1847.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm', 'ly nước']::text[]),
  ('sp-1848', '1848', 'Cô gái gợi cảm mặc áo choàng cổ điển', 'https://kevindauto.com/products/sp-1848.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'áo choàng']::text[]),
  ('sp-1849', '1849', 'Cô gái gợi cảm cúi người tạo dáng', 'https://kevindauto.com/products/sp-1849.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-1850', '1850', 'Cô gái mặc đầm đứng thanh lịch', 'https://kevindauto.com/products/sp-1850.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'thanh lịch']::text[]),
  ('sp-1851', '1851', 'Người mặc giáp trang bị quỳ', 'https://kevindauto.com/products/sp-1851.webp', 'nam', 'Hành động', array['nam', 'áo giáp', 'quỳ', 'hành động']::text[]),
  ('sp-1852', '1852', 'Cô gái áp điện thoại chân váy', 'https://kevindauto.com/products/sp-1852.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'chân váy']::text[]),
  ('sp-1853', '1853', 'Cô gái áo khoác dài đứng', 'https://kevindauto.com/products/sp-1853.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác dài', 'đứng']::text[]),
  ('sp-1854', '1854', 'Cô gái đứng cầm sách hoặc bảng', 'https://kevindauto.com/products/sp-1854.webp', 'nu', 'Đời thường', array['nữ', 'sách', 'đứng']::text[]),
  ('sp-1855', '1855', 'Cô gái đứng ra hiệu gesture', 'https://kevindauto.com/products/sp-1855.webp', 'nu', 'Đời thường', array['nữ', 'ra hiệu']::text[]),
  ('sp-1856', '1856', 'Cô gái áo khoác cầm ly đồ uống', 'https://kevindauto.com/products/sp-1856.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'ly nước']::text[]),
  ('sp-1857', '1857', 'Cô gái quần short đứng casual 2', 'https://kevindauto.com/products/sp-1857.webp', 'nu', 'Đời thường', array['nữ', 'quần short', 'đứng']::text[]),
  ('sp-1858', '1858', 'Cô gái ngồi kimono cổ trang', 'https://kevindauto.com/products/sp-1858.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'cổ trang']::text[]),
  ('sp-1859', '1859', 'Cô gái quỳ đội tai thỏ gợi cảm', 'https://kevindauto.com/products/sp-1859.webp', 'nu', 'Gợi cảm', array['nữ', 'tai thỏ', 'gợi cảm']::text[]),
  ('sp-1860', '1860', 'Cụ ông ngồi quấn chăn', 'https://kevindauto.com/products/sp-1860.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ngồi']::text[]),
  ('sp-1861', '1861', 'Người đàn ông streetwear đứng casual', 'https://kevindauto.com/products/sp-1861.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1862', '1862', 'Cô gái áo khoác cầm túi đứng', 'https://kevindauto.com/products/sp-1862.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách']::text[]),
  ('sp-1863', '1863', 'Cô gái áo khoác đứng casual 3', 'https://kevindauto.com/products/sp-1863.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đứng']::text[]),
  ('sp-1864', '1864', 'Người đàn ông đứng ra hiệu casual', 'https://kevindauto.com/products/sp-1864.webp', 'nam', 'Đời thường', array['nam', 'ra hiệu', 'đứng']::text[]),
  ('sp-1865', '1865', 'Người đàn ông đồng phục chỉ tay', 'https://kevindauto.com/products/sp-1865.webp', 'nam', 'Nghề nghiệp', array['nam', 'đồng phục', 'chỉ tay']::text[]),
  ('sp-1866', '1866', 'Người đàn ông đội mũ cao bồi đứng', 'https://kevindauto.com/products/sp-1866.webp', 'nam', 'Đời thường', array['nam', 'mũ cao bồi', 'đứng']::text[]),
  ('sp-1867', '1867', 'Người đàn ông streetwear đứng casual 2', 'https://kevindauto.com/products/sp-1867.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1868', '1868', 'Chiến binh fantasy áo giáp có cánh', 'https://kevindauto.com/products/sp-1868.webp', 'nam', 'Fantasy', array['fantasy', 'áo giáp', 'cánh', 'vũ khí']::text[]),
  ('sp-1869', '1869', 'Tay đua giơ nắm đấm ăn mừng', 'https://kevindauto.com/products/sp-1869.webp', 'nam', 'Đua xe', array['nam', 'đua xe', 'mũ bảo hiểm']::text[]),
  ('sp-1870', '1870', 'Tay đua đứng đội mũ bảo hiểm', 'https://kevindauto.com/products/sp-1870.webp', 'nam', 'Đua xe', array['nam', 'đua xe', 'mũ bảo hiểm']::text[]),
  ('sp-1871', '1871', 'Người đàn ông trùm mũ đứng casual', 'https://kevindauto.com/products/sp-1871.webp', 'nam', 'Đời thường', array['nam', 'mũ trùm', 'đứng']::text[]),
  ('sp-1872', '1872', 'Người đàn ông đút túi đứng casual 3', 'https://kevindauto.com/products/sp-1872.webp', 'nam', 'Đời thường', array['nam', 'đút túi', 'đứng']::text[]),
  ('sp-1873', '1873', 'Người đàn ông tay chạm cằm đứng', 'https://kevindauto.com/products/sp-1873.webp', 'nam', 'Đời thường', array['nam', 'suy tư', 'đứng']::text[]),
  ('sp-1874', '1874', 'Người đàn ông mập đứng casual', 'https://kevindauto.com/products/sp-1874.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'đời thường']::text[]),
  ('sp-1875', '1875', 'Người đàn ông đồng phục đứng casual', 'https://kevindauto.com/products/sp-1875.webp', 'nam', 'Nghề nghiệp', array['nam', 'đồng phục', 'đứng']::text[]),
  ('sp-1876', '1876', 'Người đàn ông mập cầm bóng đứng', 'https://kevindauto.com/products/sp-1876.webp', 'nam', 'Đời thường', array['nam', 'bóng', 'đứng']::text[]),
  ('sp-1877', '1877', 'Người đàn ông áo choàng truyền thống đứng', 'https://kevindauto.com/products/sp-1877.webp', 'nam', 'Cổ trang', array['nam', 'áo choàng', 'cổ trang']::text[]),
  ('sp-1878', '1878', 'Cô gái gợi cảm đội mũ cao bồi 2', 'https://kevindauto.com/products/sp-1878.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'mũ cao bồi']::text[]),
  ('sp-1879', '1879', 'Người đàn ông run rẩy lạnh casual', 'https://kevindauto.com/products/sp-1879.webp', 'nam', 'Đời thường', array['nam', 'đời thường']::text[]),
  ('sp-1880', '1880', 'Nữ sinh chân váy đồng phục đứng 2', 'https://kevindauto.com/products/sp-1880.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'đồng phục']::text[]),
  ('sp-1881', '1881', 'Pháp sư fantasy đội mũ cầm gậy', 'https://kevindauto.com/products/sp-1881.webp', 'nam', 'Fantasy', array['fantasy', 'pháp sư', 'gậy phép']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
