-- Lo 050: san pham 1882 den 1961
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1882', '1882', 'Nữ sinh chân váy khoanh tay', 'https://kevindauto.com/products/sp-1882.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'khoanh tay']::text[]),
  ('sp-1883', '1883', 'Robot chiến giáp kiểu Gundam', 'https://kevindauto.com/products/sp-1883.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-1884', '1884', 'Mascot mèo đeo kính vẫy tay', 'https://kevindauto.com/products/sp-1884.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'chibi']::text[]),
  ('sp-1885', '1885', 'Mascot mèo mập ngậm cá', 'https://kevindauto.com/products/sp-1885.webp', 'dongvat', 'Mascot', array['mascot', 'mèo', 'chibi']::text[]),
  ('sp-1886', '1886', 'Chó corgi đứng', 'https://kevindauto.com/products/sp-1886.webp', 'dongvat', 'Thú cưng', array['chó', 'corgi', 'thú cưng']::text[]),
  ('sp-1887', '1887', 'Chó lông xù đứng chibi', 'https://kevindauto.com/products/sp-1887.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-1888', '1888', 'Nữ sinh chân váy đồng phục xách túi', 'https://kevindauto.com/products/sp-1888.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'đồng phục', 'túi xách']::text[]),
  ('sp-1889', '1889', 'Người đàn ông streetwear đứng casual 3', 'https://kevindauto.com/products/sp-1889.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1890', '1890', 'Người đàn ông quỳ ăn mừng giơ tay', 'https://kevindauto.com/products/sp-1890.webp', 'nam', 'Hành động', array['nam', 'ăn mừng', 'quỳ']::text[]),
  ('sp-1891', '1891', 'Tượng mannequin nam đứng thẳng', 'https://kevindauto.com/products/sp-1891.webp', 'nam', 'Nghệ thuật', array['nam', 'mannequin', 'nghệ thuật']::text[]),
  ('sp-1892', '1892', 'Cụ ông áo khoác đứng casual', 'https://kevindauto.com/products/sp-1892.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'áo khoác']::text[]),
  ('sp-1893', '1893', 'Người đàn ông vest đứng casual 4', 'https://kevindauto.com/products/sp-1893.webp', 'nam', 'Công sở', array['nam', 'vest', 'đứng']::text[]),
  ('sp-1894', '1894', 'Người đàn ông mập đứng casual 2', 'https://kevindauto.com/products/sp-1894.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'đời thường']::text[]),
  ('sp-1895', '1895', 'Người đàn ông đồ đua giơ nắm đấm', 'https://kevindauto.com/products/sp-1895.webp', 'nam', 'Đua xe', array['nam', 'đua xe', 'mũ bảo hiểm']::text[]),
  ('sp-1896', '1896', 'Mascot bé trai trùm mũ đứng', 'https://kevindauto.com/products/sp-1896.webp', 'dongvat', 'Mascot', array['mascot', 'bé trai', 'chibi']::text[]),
  ('sp-1897', '1897', 'Xe đạp gấp mini', 'https://kevindauto.com/products/sp-1897.webp', 'xe', 'Xe đạp', array['xe đạp', 'gấp', 'mini']::text[]),
  ('sp-1898', '1898', 'Cô gái mặc đầm xách túi đứng 2', 'https://kevindauto.com/products/sp-1898.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'túi xách']::text[]),
  ('sp-1899', '1899', 'Mascot gấu trúc mập nằm', 'https://kevindauto.com/products/sp-1899.webp', 'dongvat', 'Mascot', array['mascot', 'gấu trúc', 'chibi']::text[]),
  ('sp-1900', '1900', 'Mascot gấu mập ngồi', 'https://kevindauto.com/products/sp-1900.webp', 'dongvat', 'Mascot', array['mascot', 'gấu', 'chibi']::text[]),
  ('sp-1901', '1901', 'Cô gái ngồi chơi đàn guitar', 'https://kevindauto.com/products/sp-1901.webp', 'nu', 'Nhạc cụ', array['nữ', 'guitar', 'nhạc cụ']::text[]),
  ('sp-1902', '1902', 'Mô tô cổ điển', 'https://kevindauto.com/products/sp-1902.webp', 'xe', 'Mô tô', array['mô tô', 'cổ điển']::text[]),
  ('sp-1903', '1903', 'Xe tay ga cổ điển', 'https://kevindauto.com/products/sp-1903.webp', 'xe', 'Xe máy', array['xe tay ga', 'cổ điển']::text[]),
  ('sp-1904', '1904', 'Người đàn ông đội mũ bảo hiểm cúi người', 'https://kevindauto.com/products/sp-1904.webp', 'nam', 'Đua xe', array['nam', 'mũ bảo hiểm', 'đua xe']::text[]),
  ('sp-1905', '1905', 'Cô gái áo dài nón lá', 'https://kevindauto.com/products/sp-1905.webp', 'nu', 'Áo dài', array['nữ', 'áo dài', 'nón lá', 'việt nam']::text[]),
  ('sp-1906', '1906', 'Cô gái áo dài cầm hoa', 'https://kevindauto.com/products/sp-1906.webp', 'nu', 'Áo dài', array['nữ', 'áo dài', 'hoa', 'việt nam']::text[]),
  ('sp-1907', '1907', 'Cụ ông ngồi hút thuốc', 'https://kevindauto.com/products/sp-1907.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'hút thuốc']::text[]),
  ('sp-1908', '1908', 'Cô gái áo dài đứng', 'https://kevindauto.com/products/sp-1908.webp', 'nu', 'Áo dài', array['nữ', 'áo dài', 'việt nam']::text[]),
  ('sp-1909', '1909', 'Cô gái áo dài cầm hoa đứng', 'https://kevindauto.com/products/sp-1909.webp', 'nu', 'Áo dài', array['nữ', 'áo dài', 'hoa', 'việt nam']::text[]),
  ('sp-1910', '1910', 'Tô phở Việt Nam', 'https://kevindauto.com/products/sp-1910.webp', 'phukien', 'Bối cảnh', array['phở', 'ẩm thực', 'bối cảnh']::text[]),
  ('sp-1911', '1911', 'Người đàn ông ngồi xổm bán hàng rong', 'https://kevindauto.com/products/sp-1911.webp', 'nam', 'Nghề nghiệp', array['nam', 'bán hàng rong', 'nghề nghiệp']::text[]),
  ('sp-1912', '1912', 'Cụ ông ngồi ghế ăn uống', 'https://kevindauto.com/products/sp-1912.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ăn uống']::text[]),
  ('sp-1913', '1913', 'Bó rau hành lá', 'https://kevindauto.com/products/sp-1913.webp', 'phukien', 'Bối cảnh', array['rau củ', 'thực phẩm', 'bối cảnh']::text[]),
  ('sp-1914', '1914', 'Rổ trái cây', 'https://kevindauto.com/products/sp-1914.webp', 'phukien', 'Bối cảnh', array['trái cây', 'thực phẩm', 'bối cảnh']::text[]),
  ('sp-1915', '1915', 'Bình gas dân dụng', 'https://kevindauto.com/products/sp-1915.webp', 'phukien', 'Bối cảnh', array['bình gas', 'bối cảnh']::text[]),
  ('sp-1916', '1916', 'Người đàn ông đội mũ gà trống', 'https://kevindauto.com/products/sp-1916.webp', 'nam', 'Đời thường', array['nam', 'mũ', 'đời thường']::text[]),
  ('sp-1917', '1917', 'Người đàn ông áo khoác dài để râu', 'https://kevindauto.com/products/sp-1917.webp', 'nam', 'Đời thường', array['nam', 'áo khoác dài', 'râu']::text[]),
  ('sp-1918', '1918', 'Người đàn ông áo mưa đứng', 'https://kevindauto.com/products/sp-1918.webp', 'nam', 'Đời thường', array['nam', 'áo mưa', 'đứng']::text[]),
  ('sp-1919', '1919', 'Cụ ông cởi trần tay chạm cằm', 'https://kevindauto.com/products/sp-1919.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'cởi trần']::text[]),
  ('sp-1920', '1920', 'Kệ để đồ nhiều tầng', 'https://kevindauto.com/products/sp-1920.webp', 'phukien', 'Nội thất', array['kệ', 'nội thất', 'bối cảnh']::text[]),
  ('sp-1921', '1921', 'Cây lá đỏ trong chậu', 'https://kevindauto.com/products/sp-1921.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1922', '1922', 'Cây lá xanh trong chậu', 'https://kevindauto.com/products/sp-1922.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1923', '1923', 'Cây xương rồng nhỏ', 'https://kevindauto.com/products/sp-1923.webp', 'phukien', 'Bối cảnh', array['xương rồng', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1924', '1924', 'Cây thông nhỏ trong chậu', 'https://kevindauto.com/products/sp-1924.webp', 'phukien', 'Bối cảnh', array['cây thông', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1925', '1925', 'Cây leo trong chậu', 'https://kevindauto.com/products/sp-1925.webp', 'phukien', 'Bối cảnh', array['cây leo', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1926', '1926', 'Cây lá to trong chậu', 'https://kevindauto.com/products/sp-1926.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1927', '1927', 'Cây hoa trắng trong chậu', 'https://kevindauto.com/products/sp-1927.webp', 'phukien', 'Bối cảnh', array['cây hoa', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1928', '1928', 'Cây lá xanh chậu tròn', 'https://kevindauto.com/products/sp-1928.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1929', '1929', 'Cây lá to chậu vuông', 'https://kevindauto.com/products/sp-1929.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1930', '1930', 'Robot hình nón nhỏ', 'https://kevindauto.com/products/sp-1930.webp', 'dongvat', 'Mascot', array['mascot', 'robot', 'chibi']::text[]),
  ('sp-1931', '1931', 'Bàn làm việc kèm đèn', 'https://kevindauto.com/products/sp-1931.webp', 'phukien', 'Nội thất', array['bàn làm việc', 'đèn', 'nội thất']::text[]),
  ('sp-1932', '1932', 'Người đàn ông ngồi ghế xoay ra hiệu', 'https://kevindauto.com/products/sp-1932.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'ghế xoay']::text[]),
  ('sp-1933', '1933', 'Người đàn ông đeo kính ngồi xổm', 'https://kevindauto.com/products/sp-1933.webp', 'nam', 'Đời thường', array['nam', 'kính', 'ngồi xổm']::text[]),
  ('sp-1934', '1934', 'Thùng đá giữ lạnh', 'https://kevindauto.com/products/sp-1934.webp', 'phukien', 'Bối cảnh', array['thùng đá', 'bối cảnh']::text[]),
  ('sp-1935', '1935', 'Xe đẩy hàng có bánh', 'https://kevindauto.com/products/sp-1935.webp', 'phukien', 'Bối cảnh', array['xe đẩy', 'bối cảnh']::text[]),
  ('sp-1936', '1936', 'Xô đựng cây lau nhà', 'https://kevindauto.com/products/sp-1936.webp', 'phukien', 'Bối cảnh', array['xô', 'dụng cụ vệ sinh', 'bối cảnh']::text[]),
  ('sp-1937', '1937', 'Người đàn ông streetwear đứng casual 4', 'https://kevindauto.com/products/sp-1937.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1938', '1938', 'Người đàn ông streetwear đứng casual 5', 'https://kevindauto.com/products/sp-1938.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1939', '1939', 'Người đàn ông quỳ cầm đồ vật', 'https://kevindauto.com/products/sp-1939.webp', 'nam', 'Đời thường', array['nam', 'quỳ', 'đời thường']::text[]),
  ('sp-1940', '1940', 'Cụ bà áo khoác đứng casual', 'https://kevindauto.com/products/sp-1940.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'áo khoác']::text[]),
  ('sp-1941', '1941', 'Cô gái đứng xem điện thoại casual', 'https://kevindauto.com/products/sp-1941.webp', 'nu', 'Đời thường', array['nữ', 'điện thoại', 'đứng']::text[]),
  ('sp-1942', '1942', 'Cây hoa lys trong chậu', 'https://kevindauto.com/products/sp-1942.webp', 'phukien', 'Bối cảnh', array['cây hoa', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1943', '1943', 'Cây hoa trắng chậu tròn', 'https://kevindauto.com/products/sp-1943.webp', 'phukien', 'Bối cảnh', array['cây hoa', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1944', '1944', 'Cây cọ nhỏ trong chậu', 'https://kevindauto.com/products/sp-1944.webp', 'phukien', 'Bối cảnh', array['cây cọ', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1945', '1945', 'Cây dương xỉ trong chậu', 'https://kevindauto.com/products/sp-1945.webp', 'phukien', 'Bối cảnh', array['cây dương xỉ', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1946', '1946', 'Cây lá dài trong chậu', 'https://kevindauto.com/products/sp-1946.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1947', '1947', 'Cây hoa nở rộ chậu lớn', 'https://kevindauto.com/products/sp-1947.webp', 'phukien', 'Bối cảnh', array['cây hoa', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1948', '1948', 'Cây mọng nước trong chậu', 'https://kevindauto.com/products/sp-1948.webp', 'phukien', 'Bối cảnh', array['cây mọng nước', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1949', '1949', 'Người đàn ông streetwear đứng casual 6', 'https://kevindauto.com/products/sp-1949.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1950', '1950', 'Người đàn ông đeo kính streetwear đứng', 'https://kevindauto.com/products/sp-1950.webp', 'nam', 'Streetwear', array['nam', 'kính', 'streetwear']::text[]),
  ('sp-1951', '1951', 'Người cha bế con trai', 'https://kevindauto.com/products/sp-1951.webp', 'treem', 'Gia đình', array['gia đình', 'cha con', 'trẻ em']::text[]),
  ('sp-1952', '1952', 'Cô gái mặc đầm đứng casual', 'https://kevindauto.com/products/sp-1952.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'đứng']::text[]),
  ('sp-1953', '1953', 'Cụ bà ngồi casual', 'https://kevindauto.com/products/sp-1953.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ngồi']::text[]),
  ('sp-1954', '1954', 'Tượng đầu chó bulldog đeo vòng cổ', 'https://kevindauto.com/products/sp-1954.webp', 'dongvat', 'Nghệ thuật', array['chó', 'bulldog', 'nghệ thuật']::text[]),
  ('sp-1955', '1955', 'Cây lá kim trong chậu', 'https://kevindauto.com/products/sp-1955.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1956', '1956', 'Cây lá tròn trong chậu', 'https://kevindauto.com/products/sp-1956.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1957', '1957', 'Cây cọ cảnh cao', 'https://kevindauto.com/products/sp-1957.webp', 'phukien', 'Bối cảnh', array['cây cọ', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1958', '1958', 'Cây tre nhỏ trong chậu', 'https://kevindauto.com/products/sp-1958.webp', 'phukien', 'Bối cảnh', array['cây tre', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1959', '1959', 'Cây thông cảnh trong chậu', 'https://kevindauto.com/products/sp-1959.webp', 'phukien', 'Bối cảnh', array['cây thông', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1960', '1960', 'Bình hoa cùng tượng thỏ nhỏ', 'https://kevindauto.com/products/sp-1960.webp', 'phukien', 'Bối cảnh', array['bình hoa', 'trang trí', 'bối cảnh']::text[]),
  ('sp-1961', '1961', 'Cô gái hoodie đứng casual', 'https://kevindauto.com/products/sp-1961.webp', 'nu', 'Streetwear', array['nữ', 'hoodie', 'đứng']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
