-- Lo 051: san pham 1962 den 2041
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-1962', '1962', 'Cô gái ngồi xổm ra hiệu', 'https://kevindauto.com/products/sp-1962.webp', 'nu', 'Đời thường', array['nữ', 'ngồi xổm', 'ra hiệu']::text[]),
  ('sp-1963', '1963', 'Người đàn ông đứng casual streetwear', 'https://kevindauto.com/products/sp-1963.webp', 'nam', 'Streetwear', array['nam', 'đứng', 'streetwear']::text[]),
  ('sp-1964', '1964', 'Người đàn ông áo khoác đứng streetwear 2', 'https://kevindauto.com/products/sp-1964.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'streetwear']::text[]),
  ('sp-1965', '1965', 'Cô gái đứng tay chạm chân casual', 'https://kevindauto.com/products/sp-1965.webp', 'nu', 'Đời thường', array['nữ', 'đứng', 'đời thường']::text[]),
  ('sp-1966', '1966', 'Người nằm sấp tư thế bơi', 'https://kevindauto.com/products/sp-1966.webp', 'nam', 'Thể thao', array['nam', 'bơi lội', 'thể thao']::text[]),
  ('sp-1967', '1967', 'Bình hoa hồng trang trí', 'https://kevindauto.com/products/sp-1967.webp', 'phukien', 'Bối cảnh', array['bình hoa', 'hoa hồng', 'bối cảnh']::text[]),
  ('sp-1968', '1968', 'Chậu hoa lily trang trí', 'https://kevindauto.com/products/sp-1968.webp', 'phukien', 'Bối cảnh', array['chậu hoa', 'hoa lily', 'bối cảnh']::text[]),
  ('sp-1969', '1969', 'Chậu hoa mộc lan trang trí', 'https://kevindauto.com/products/sp-1969.webp', 'phukien', 'Bối cảnh', array['chậu hoa', 'mộc lan', 'bối cảnh']::text[]),
  ('sp-1970', '1970', 'Chậu cây hoa nhỏ', 'https://kevindauto.com/products/sp-1970.webp', 'phukien', 'Bối cảnh', array['chậu hoa', 'cây cảnh', 'bối cảnh']::text[]),
  ('sp-1971', '1971', 'Chậu cây ăn thịt nhỏ', 'https://kevindauto.com/products/sp-1971.webp', 'phukien', 'Bối cảnh', array['cây cảnh', 'chậu cây', 'bối cảnh']::text[]),
  ('sp-1972', '1972', 'Người đàn ông đứng thể thao casual', 'https://kevindauto.com/products/sp-1972.webp', 'nam', 'Thể thao', array['nam', 'đứng', 'thể thao']::text[]),
  ('sp-1973', '1973', 'Bé gái mặc đầm đứng', 'https://kevindauto.com/products/sp-1973.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đầm']::text[]),
  ('sp-1974', '1974', 'Người đàn ông xách túi đứng casual', 'https://kevindauto.com/products/sp-1974.webp', 'nam', 'Đời thường', array['nam', 'túi xách', 'đứng']::text[]),
  ('sp-1975', '1975', 'Người đàn ông ngồi thư giãn casual 3', 'https://kevindauto.com/products/sp-1975.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thư giãn']::text[]),
  ('sp-1976', '1976', 'Cô gái áo khoác chỉ tay', 'https://kevindauto.com/products/sp-1976.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'chỉ tay']::text[]),
  ('sp-1977', '1977', 'Người đàn ông đạp xe đạp', 'https://kevindauto.com/products/sp-1977.webp', 'xe', 'Xe đạp', array['nam', 'xe đạp', 'đạp xe']::text[]),
  ('sp-1978', '1978', 'Cô gái ôm giỏ hoa', 'https://kevindauto.com/products/sp-1978.webp', 'nu', 'Đời thường', array['nữ', 'giỏ hoa', 'đời thường']::text[]),
  ('sp-1979', '1979', 'Nồi vỡ prop', 'https://kevindauto.com/products/sp-1979.webp', 'phukien', 'Bối cảnh', array['nồi', 'bối cảnh']::text[]),
  ('sp-1980', '1980', 'Bé gái ngồi xổm cầm que', 'https://kevindauto.com/products/sp-1980.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'ngồi xổm']::text[]),
  ('sp-1981', '1981', 'Công nhân đội mũ bảo hộ đứng', 'https://kevindauto.com/products/sp-1981.webp', 'nam', 'Nghề nghiệp', array['nam', 'công nhân', 'mũ bảo hộ', 'nghề nghiệp']::text[]),
  ('sp-1982', '1982', 'Công nhân đội mũ bảo hộ đứng 2', 'https://kevindauto.com/products/sp-1982.webp', 'nam', 'Nghề nghiệp', array['nam', 'công nhân', 'mũ bảo hộ', 'nghề nghiệp']::text[]),
  ('sp-1983', '1983', 'Tượng thần tài cầm quả cầu', 'https://kevindauto.com/products/sp-1983.webp', 'nam', 'Nghệ thuật', array['tượng', 'thần tài', 'nghệ thuật', 'phong thủy']::text[]),
  ('sp-1984', '1984', 'Người đàn ông múa côn thể thao', 'https://kevindauto.com/products/sp-1984.webp', 'nam', 'Thể thao', array['nam', 'côn', 'võ thuật', 'thể thao']::text[]),
  ('sp-1985', '1985', 'Người đàn ông áo choàng dài đứng', 'https://kevindauto.com/products/sp-1985.webp', 'nam', 'Đời thường', array['nam', 'áo choàng dài', 'đứng']::text[]),
  ('sp-1986', '1986', 'Người đàn ông áo choàng dài đứng 2', 'https://kevindauto.com/products/sp-1986.webp', 'nam', 'Đời thường', array['nam', 'áo choàng dài', 'đứng']::text[]),
  ('sp-1987', '1987', 'Người đàn ông streetwear đứng casual 7', 'https://kevindauto.com/products/sp-1987.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-1988', '1988', 'Người đàn ông streetwear ngồi casual', 'https://kevindauto.com/products/sp-1988.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'ngồi']::text[]),
  ('sp-1989', '1989', 'Người đàn ông đứng xem điện thoại casual 2', 'https://kevindauto.com/products/sp-1989.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng']::text[]),
  ('sp-1990', '1990', 'Cô gái đứng cầm đồ vật casual', 'https://kevindauto.com/products/sp-1990.webp', 'nu', 'Đời thường', array['nữ', 'đứng', 'đời thường']::text[]),
  ('sp-1991', '1991', 'Cô gái áo khoác tay chạm đầu', 'https://kevindauto.com/products/sp-1991.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'tay chạm đầu']::text[]),
  ('sp-1992', '1992', 'Cô gái ngồi ghế băng casual', 'https://kevindauto.com/products/sp-1992.webp', 'nu', 'Đời thường', array['nữ', 'ngồi', 'ghế băng']::text[]),
  ('sp-1993', '1993', 'Người đàn ông đứng cầm đồ uống casual', 'https://kevindauto.com/products/sp-1993.webp', 'nam', 'Đời thường', array['nam', 'đồ uống', 'đứng']::text[]),
  ('sp-1994', '1994', 'Cụ ông cầm cá lớn', 'https://kevindauto.com/products/sp-1994.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'cá']::text[]),
  ('sp-1995', '1995', 'Mascot thỏ bay lượn', 'https://kevindauto.com/products/sp-1995.webp', 'dongvat', 'Mascot', array['mascot', 'thỏ', 'chibi']::text[]),
  ('sp-1996', '1996', 'Mascot người mập chơi đàn ukulele', 'https://kevindauto.com/products/sp-1996.webp', 'dongvat', 'Mascot', array['mascot', 'nhạc cụ', 'chibi']::text[]),
  ('sp-1997', '1997', 'Gà trống', 'https://kevindauto.com/products/sp-1997.webp', 'dongvat', 'Động vật', array['gà trống', 'động vật']::text[]),
  ('sp-1998', '1998', 'Chậu hoa tròn rực rỡ', 'https://kevindauto.com/products/sp-1998.webp', 'phukien', 'Bối cảnh', array['chậu hoa', 'bối cảnh']::text[]),
  ('sp-1999', '1999', 'Xe tay ga mini', 'https://kevindauto.com/products/sp-1999.webp', 'xe', 'Xe máy', array['xe tay ga', 'mini']::text[]),
  ('sp-2000', '2000', 'Người đàn ông đứng casual đời thường', 'https://kevindauto.com/products/sp-2000.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'đời thường']::text[]),
  ('sp-2001', '2001', 'Cô gái streetwear đứng chân váy', 'https://kevindauto.com/products/sp-2001.webp', 'nu', 'Streetwear', array['nữ', 'chân váy', 'streetwear']::text[]),
  ('sp-2002', '2002', 'Người đàn ông mập ngồi bồn cầu hài hước', 'https://kevindauto.com/products/sp-2002.webp', 'nam', 'Hài hước', array['nam', 'hài hước', 'đời thường']::text[]),
  ('sp-2003', '2003', 'Cụ ông đứng trang phục truyền thống', 'https://kevindauto.com/products/sp-2003.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'truyền thống']::text[]),
  ('sp-2004', '2004', 'Nhân vật áo choàng anime cá tính', 'https://kevindauto.com/products/sp-2004.webp', 'nam', 'Anime', array['anime', 'áo choàng', 'độc đáo']::text[]),
  ('sp-2005', '2005', 'Cô gái áo dài cầm quạt xoè', 'https://kevindauto.com/products/sp-2005.webp', 'nu', 'Áo dài', array['nữ', 'áo dài', 'quạt', 'việt nam']::text[]),
  ('sp-2006', '2006', 'Nữ sinh cười tươi ra dấu chiến thắng', 'https://kevindauto.com/products/sp-2006.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'học đường']::text[]),
  ('sp-2007', '2007', 'Bé gái mặc chân váy đứng', 'https://kevindauto.com/products/sp-2007.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'chân váy']::text[]),
  ('sp-2008', '2008', 'Người mập mạp đứng vẫy tay', 'https://kevindauto.com/products/sp-2008.webp', 'nam', 'Hài hước', array['nam', 'hài hước', 'vẫy tay']::text[]),
  ('sp-2009', '2009', 'Người đàn ông đeo kính đứng ra hiệu', 'https://kevindauto.com/products/sp-2009.webp', 'nam', 'Đời thường', array['nam', 'kính', 'ra hiệu']::text[]),
  ('sp-2010', '2010', 'Cô gái nông dân đội mũ xách giỏ', 'https://kevindauto.com/products/sp-2010.webp', 'nu', 'Nghề nghiệp', array['nữ', 'nông dân', 'giỏ', 'nghề nghiệp']::text[]),
  ('sp-2011', '2011', 'Cụ bà ngồi đội nón lá', 'https://kevindauto.com/products/sp-2011.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'nón lá', 'việt nam']::text[]),
  ('sp-2012', '2012', 'Người đàn ông ngồi xổm chơi ván trượt', 'https://kevindauto.com/products/sp-2012.webp', 'nam', 'Thể thao', array['nam', 'ván trượt', 'ngồi xổm', 'thể thao']::text[]),
  ('sp-2013', '2013', 'Cô gái gợi cảm nhấc chân tinh tế', 'https://kevindauto.com/products/sp-2013.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm']::text[]),
  ('sp-2014', '2014', 'Cô gái streetwear đứng quần rộng', 'https://kevindauto.com/products/sp-2014.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'quần rộng']::text[]),
  ('sp-2015', '2015', 'Cô gái streetwear chống hông', 'https://kevindauto.com/products/sp-2015.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'chống hông']::text[]),
  ('sp-2016', '2016', 'Nhà sư ngồi thiền xếp bằng', 'https://kevindauto.com/products/sp-2016.webp', 'nam', 'Cổ trang', array['nam', 'nhà sư', 'thiền', 'cổ trang']::text[]),
  ('sp-2017', '2017', 'Cụ ông đạp xe đạp trẻ em', 'https://kevindauto.com/products/sp-2017.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'xe đạp']::text[]),
  ('sp-2018', '2018', 'Cụ ông ngồi thư giãn casual', 'https://kevindauto.com/products/sp-2018.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ngồi']::text[]),
  ('sp-2019', '2019', 'Nông dân đội nón lá ngồi xổm', 'https://kevindauto.com/products/sp-2019.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'nông dân', 'nón lá', 'nghề nghiệp']::text[]),
  ('sp-2020', '2020', 'Tượng ông Phúc cười tươi', 'https://kevindauto.com/products/sp-2020.webp', 'nam', 'Nghệ thuật', array['tượng', 'phong thủy', 'nghệ thuật']::text[]),
  ('sp-2021', '2021', 'Chiến binh áo choàng đeo kiếm sau lưng', 'https://kevindauto.com/products/sp-2021.webp', 'nam', 'Cổ trang', array['nam', 'kiếm', 'áo choàng', 'cổ trang']::text[]),
  ('sp-2022', '2022', 'Người đàn ông streetwear đứng tự nhiên', 'https://kevindauto.com/products/sp-2022.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-2023', '2023', 'Nông dân đội nón lá ngồi ghế đẩu', 'https://kevindauto.com/products/sp-2023.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'nông dân', 'nón lá', 'nghề nghiệp']::text[]),
  ('sp-2024', '2024', 'Rổ trái cây tròn', 'https://kevindauto.com/products/sp-2024.webp', 'phukien', 'Bối cảnh', array['trái cây', 'rổ', 'bối cảnh']::text[]),
  ('sp-2025', '2025', 'Rổ trái cây tròn kiểu 2', 'https://kevindauto.com/products/sp-2025.webp', 'phukien', 'Bối cảnh', array['trái cây', 'rổ', 'bối cảnh']::text[]),
  ('sp-2026', '2026', 'Bé gái mặc đầm đứng đơn giản', 'https://kevindauto.com/products/sp-2026.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đầm']::text[]),
  ('sp-2027', '2027', 'Cụ ông nông dân đứng đội mũ', 'https://kevindauto.com/products/sp-2027.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'nông dân', 'mũ', 'nghề nghiệp']::text[]),
  ('sp-2028', '2028', 'Võ sĩ tư thế tấn công cầm côn', 'https://kevindauto.com/products/sp-2028.webp', 'nam', 'Thể thao', array['nam', 'võ thuật', 'côn', 'thể thao']::text[]),
  ('sp-2029', '2029', 'Trống lớn truyền thống', 'https://kevindauto.com/products/sp-2029.webp', 'phukien', 'Bối cảnh', array['trống', 'truyền thống', 'bối cảnh']::text[]),
  ('sp-2030', '2030', 'Nhà sư tư thế võ thuật cầm quạt', 'https://kevindauto.com/products/sp-2030.webp', 'nam', 'Thể thao', array['nam', 'nhà sư', 'võ thuật', 'thể thao']::text[]),
  ('sp-2031', '2031', 'Nông dân đứng áo truyền thống', 'https://kevindauto.com/products/sp-2031.webp', 'nam', 'Nghề nghiệp', array['nam', 'nông dân', 'truyền thống', 'nghề nghiệp']::text[]),
  ('sp-2032', '2032', 'Người nhảy cao tư thế võ thuật', 'https://kevindauto.com/products/sp-2032.webp', 'nam', 'Thể thao', array['nam', 'võ thuật', 'nhảy cao', 'thể thao']::text[]),
  ('sp-2033', '2033', 'Cụ ông ngồi cùng hòm đồ nghề', 'https://kevindauto.com/products/sp-2033.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'cao tuổi', 'hòm đồ nghề', 'nghề nghiệp']::text[]),
  ('sp-2034', '2034', 'Cụ bà ngồi bán hàng rổ', 'https://kevindauto.com/products/sp-2034.webp', 'caotuoi', 'Nghề nghiệp', array['người già', 'cao tuổi', 'bán hàng', 'nghề nghiệp']::text[]),
  ('sp-2035', '2035', 'Bé trai đứng casual đơn giản', 'https://kevindauto.com/products/sp-2035.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'đứng']::text[]),
  ('sp-2036', '2036', 'Bé trai đội mũ bảo hiểm đứng', 'https://kevindauto.com/products/sp-2036.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'mũ bảo hiểm']::text[]),
  ('sp-2037', '2037', 'Hai bé trai nắm tay nhau', 'https://kevindauto.com/products/sp-2037.webp', 'treem', 'Trẻ em', array['trẻ em', 'đôi bạn', 'tình bạn']::text[]),
  ('sp-2038', '2038', 'Em bé ngồi ôm giỏ', 'https://kevindauto.com/products/sp-2038.webp', 'treem', 'Trẻ em', array['trẻ em', 'em bé', 'giỏ']::text[]),
  ('sp-2039', '2039', 'Cảnh sát giao thông chỉ đường đội mũ', 'https://kevindauto.com/products/sp-2039.webp', 'nam', 'Nghề nghiệp', array['nam', 'cảnh sát giao thông', 'nghề nghiệp']::text[]),
  ('sp-2040', '2040', 'Cảnh sát đứng cầm còi', 'https://kevindauto.com/products/sp-2040.webp', 'nam', 'Nghề nghiệp', array['nam', 'cảnh sát', 'còi', 'nghề nghiệp']::text[]),
  ('sp-2041', '2041', 'Cảnh sát giao thông chỉ đường', 'https://kevindauto.com/products/sp-2041.webp', 'nam', 'Nghề nghiệp', array['nam', 'cảnh sát giao thông', 'nghề nghiệp']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
