-- Lo 052: san pham 2042 den 2121
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-2042', '2042', 'Nam sinh áo khoác đứng', 'https://kevindauto.com/products/sp-2042.webp', 'nam', 'Học đường', array['nam', 'học sinh', 'học đường']::text[]),
  ('sp-2043', '2043', 'Nữ sinh quần short đứng', 'https://kevindauto.com/products/sp-2043.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'học đường']::text[]),
  ('sp-2044', '2044', 'Nữ sinh hoodie chân váy đứng', 'https://kevindauto.com/products/sp-2044.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'hoodie', 'học đường']::text[]),
  ('sp-2045', '2045', 'Nam sinh hoodie đứng đút túi', 'https://kevindauto.com/products/sp-2045.webp', 'nam', 'Học đường', array['nam', 'học sinh', 'hoodie', 'học đường']::text[]),
  ('sp-2046', '2046', 'Nam sinh đứng casual đơn giản', 'https://kevindauto.com/products/sp-2046.webp', 'nam', 'Học đường', array['nam', 'học sinh', 'học đường']::text[]),
  ('sp-2047', '2047', 'Nam sinh xách túi đứng', 'https://kevindauto.com/products/sp-2047.webp', 'nam', 'Học đường', array['nam', 'học sinh', 'túi xách', 'học đường']::text[]),
  ('sp-2048', '2048', 'Nữ sinh chân váy xách túi đứng', 'https://kevindauto.com/products/sp-2048.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'chân váy', 'học đường']::text[]),
  ('sp-2049', '2049', 'Tượng nhà sư ngồi thiền cởi trần', 'https://kevindauto.com/products/sp-2049.webp', 'nam', 'Nghệ thuật', array['nam', 'nhà sư', 'thiền', 'nghệ thuật']::text[]),
  ('sp-2050', '2050', 'Cụ ông ngồi ghế đẩu đọc sách', 'https://kevindauto.com/products/sp-2050.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đọc sách']::text[]),
  ('sp-2051', '2051', 'Bé gái nhảy múa cầm quạt', 'https://kevindauto.com/products/sp-2051.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'quạt', 'nhảy múa']::text[]),
  ('sp-2052', '2052', 'Người đàn ông kimono áo choàng đứng', 'https://kevindauto.com/products/sp-2052.webp', 'nam', 'Cổ trang', array['nam', 'kimono', 'áo choàng', 'cổ trang']::text[]),
  ('sp-2053', '2053', 'Mèo ngồi bên chậu hoa trên ghế', 'https://kevindauto.com/products/sp-2053.webp', 'dongvat', 'Thú cưng', array['mèo', 'chậu hoa', 'thú cưng']::text[]),
  ('sp-2054', '2054', 'Ngỗng', 'https://kevindauto.com/products/sp-2054.webp', 'dongvat', 'Động vật', array['ngỗng', 'động vật']::text[]),
  ('sp-2055', '2055', 'Cụ ông kimono cầm kiếm đứng', 'https://kevindauto.com/products/sp-2055.webp', 'caotuoi', 'Cổ trang', array['người già', 'cao tuổi', 'kimono', 'kiếm', 'cổ trang']::text[]),
  ('sp-2056', '2056', 'Quý cô đầm vintage sang trọng', 'https://kevindauto.com/products/sp-2056.webp', 'nu', 'Vintage', array['nữ', 'đầm', 'vintage', 'sang trọng']::text[]),
  ('sp-2057', '2057', 'Bé gái mặc quần short đứng', 'https://kevindauto.com/products/sp-2057.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'quần short']::text[]),
  ('sp-2058', '2058', 'Cô gái streetwear đứng casual', 'https://kevindauto.com/products/sp-2058.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'đứng']::text[]),
  ('sp-2059', '2059', 'Cô gái mặc đầm xách túi đứng', 'https://kevindauto.com/products/sp-2059.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'túi xách']::text[]),
  ('sp-2060', '2060', 'Cô gái tạp dề ôm chậu cây', 'https://kevindauto.com/products/sp-2060.webp', 'nu', 'Nghề nghiệp', array['nữ', 'tạp dề', 'chậu cây', 'nghề nghiệp']::text[]),
  ('sp-2061', '2061', 'Cô gái cầm ván trượt đứng', 'https://kevindauto.com/products/sp-2061.webp', 'nu', 'Thể thao', array['nữ', 'ván trượt', 'thể thao']::text[]),
  ('sp-2062', '2062', 'Cô gái streetwear giơ tay', 'https://kevindauto.com/products/sp-2062.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'giơ tay']::text[]),
  ('sp-2063', '2063', 'Người kimono áo choàng đứng trang trọng', 'https://kevindauto.com/products/sp-2063.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'áo choàng', 'cổ trang']::text[]),
  ('sp-2064', '2064', 'Nữ fantasy áo choàng lộng lẫy', 'https://kevindauto.com/products/sp-2064.webp', 'nu', 'Fantasy', array['nữ', 'fantasy', 'áo choàng']::text[]),
  ('sp-2065', '2065', 'Chiến sĩ đội mũ bảo hiểm chống hông', 'https://kevindauto.com/products/sp-2065.webp', 'nam', 'Quân sự', array['nam', 'lính', 'mũ bảo hiểm', 'quân sự']::text[]),
  ('sp-2066', '2066', 'Cụ ông ngồi trên hòm đội mũ', 'https://kevindauto.com/products/sp-2066.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'mũ']::text[]),
  ('sp-2067', '2067', 'Người đàn ông đang nhảy múa', 'https://kevindauto.com/products/sp-2067.webp', 'nam', 'Hành động', array['nam', 'nhảy múa', 'hành động']::text[]),
  ('sp-2068', '2068', 'Bé trai hoodie chỉ tay', 'https://kevindauto.com/products/sp-2068.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'hoodie', 'chỉ tay']::text[]),
  ('sp-2069', '2069', 'Người đàn ông đứng khoanh tay casual', 'https://kevindauto.com/products/sp-2069.webp', 'nam', 'Đời thường', array['nam', 'khoanh tay', 'đứng']::text[]),
  ('sp-2070', '2070', 'Người đàn ông cơ bắp cởi trần đứng casual', 'https://kevindauto.com/products/sp-2070.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'cởi trần']::text[]),
  ('sp-2071', '2071', 'Người đàn ông hoodie đội mũ đứng', 'https://kevindauto.com/products/sp-2071.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'mũ', 'streetwear']::text[]),
  ('sp-2072', '2072', 'Người đàn ông vác xe đạp trên vai', 'https://kevindauto.com/products/sp-2072.webp', 'xe', 'Xe đạp', array['nam', 'xe đạp']::text[]),
  ('sp-2073', '2073', 'Chiến sĩ đeo túi đứng', 'https://kevindauto.com/products/sp-2073.webp', 'nam', 'Quân sự', array['nam', 'lính', 'túi', 'quân sự']::text[]),
  ('sp-2074', '2074', 'Cụ ông xách túi đứng truyền thống', 'https://kevindauto.com/products/sp-2074.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'túi xách', 'truyền thống']::text[]),
  ('sp-2075', '2075', 'Chiến sĩ trang bị đầy đủ balo súng', 'https://kevindauto.com/products/sp-2075.webp', 'nam', 'Quân sự', array['nam', 'lính', 'balo', 'súng', 'quân sự']::text[]),
  ('sp-2076', '2076', 'Võ sĩ khoanh tay tự tin', 'https://kevindauto.com/products/sp-2076.webp', 'nam', 'Thể thao', array['nam', 'võ sĩ', 'khoanh tay', 'thể thao']::text[]),
  ('sp-2077', '2077', 'Võ sĩ đeo băng trán tư thế thủ', 'https://kevindauto.com/products/sp-2077.webp', 'nam', 'Thể thao', array['nam', 'võ sĩ', 'băng trán', 'thể thao']::text[]),
  ('sp-2078', '2078', 'Người đàn ông hoodie đứng tay đút túi', 'https://kevindauto.com/products/sp-2078.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'đứng']::text[]),
  ('sp-2079', '2079', 'Người đàn ông áo khoác xách túi đứng casual', 'https://kevindauto.com/products/sp-2079.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'túi xách']::text[]),
  ('sp-2080', '2080', 'Cô gái áo khoác đội mũ len đứng', 'https://kevindauto.com/products/sp-2080.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'mũ len']::text[]),
  ('sp-2081', '2081', 'Người đàn ông hoodie đứng casual 3', 'https://kevindauto.com/products/sp-2081.webp', 'nam', 'Streetwear', array['nam', 'hoodie', 'đứng']::text[]),
  ('sp-2082', '2082', 'Cô gái áo khoác xách túi đứng casual', 'https://kevindauto.com/products/sp-2082.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách']::text[]),
  ('sp-2083', '2083', 'Cụ ông vest đứng đút túi', 'https://kevindauto.com/products/sp-2083.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vest']::text[]),
  ('sp-2084', '2084', 'Cụ ông vest đứng trang trọng', 'https://kevindauto.com/products/sp-2084.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'vest']::text[]),
  ('sp-2085', '2085', 'Cụ ông đứng ra hiệu tay lên miệng', 'https://kevindauto.com/products/sp-2085.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ra hiệu']::text[]),
  ('sp-2086', '2086', 'Chiến sĩ ngồi xổm cầm đồ vật', 'https://kevindauto.com/products/sp-2086.webp', 'nam', 'Quân sự', array['nam', 'lính', 'ngồi xổm', 'quân sự']::text[]),
  ('sp-2087', '2087', 'Cụ ông ngồi thư giãn tay chạm cằm', 'https://kevindauto.com/products/sp-2087.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'ngồi']::text[]),
  ('sp-2088', '2088', 'Bàn nhỏ chân xếp', 'https://kevindauto.com/products/sp-2088.webp', 'phukien', 'Nội thất', array['bàn', 'nội thất', 'bối cảnh']::text[]),
  ('sp-2089', '2089', 'Cụ ông đồng phục thân hình đầy đặn', 'https://kevindauto.com/products/sp-2089.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đồng phục']::text[]),
  ('sp-2090', '2090', 'Người đàn ông đứng xem điện thoại casual 3', 'https://kevindauto.com/products/sp-2090.webp', 'nam', 'Đời thường', array['nam', 'điện thoại', 'đứng']::text[]),
  ('sp-2091', '2091', 'Bé trai đội nón lá xách giỏ', 'https://kevindauto.com/products/sp-2091.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'nón lá', 'việt nam']::text[]),
  ('sp-2092', '2092', 'Cô gái kimono đứng truyền thống', 'https://kevindauto.com/products/sp-2092.webp', 'nu', 'Cổ trang', array['nữ', 'kimono', 'cổ trang']::text[]),
  ('sp-2093', '2093', 'Cô gái gợi cảm cầm mũ bảo hiểm', 'https://kevindauto.com/products/sp-2093.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'mũ bảo hiểm']::text[]),
  ('sp-2094', '2094', 'Cô gái streetwear tai thỏ cầm mũ bảo hiểm', 'https://kevindauto.com/products/sp-2094.webp', 'nu', 'Streetwear', array['nữ', 'tai thỏ', 'mũ bảo hiểm', 'streetwear']::text[]),
  ('sp-2095', '2095', 'Người đàn ông vác gậy bóng chày đe doạ', 'https://kevindauto.com/products/sp-2095.webp', 'nam', 'Hành động', array['nam', 'gậy bóng chày', 'hành động']::text[]),
  ('sp-2096', '2096', 'Cô gái mặc đầm xách giỏ đứng', 'https://kevindauto.com/products/sp-2096.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'giỏ']::text[]),
  ('sp-2097', '2097', 'Cô gái cầm mũ bảo hiểm áo crop', 'https://kevindauto.com/products/sp-2097.webp', 'nu', 'Đời thường', array['nữ', 'mũ bảo hiểm', 'crop top']::text[]),
  ('sp-2098', '2098', 'Cô gái mặc đầm cầm mũ bảo hiểm', 'https://kevindauto.com/products/sp-2098.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'mũ bảo hiểm']::text[]),
  ('sp-2099', '2099', 'Cụ ông râu dài áo choàng đứng', 'https://kevindauto.com/products/sp-2099.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'râu dài', 'áo choàng']::text[]),
  ('sp-2100', '2100', 'Bé gái đồng phục cầm ly xách túi', 'https://kevindauto.com/products/sp-2100.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đồng phục', 'túi xách']::text[]),
  ('sp-2101', '2101', 'Nữ sinh cầm đồ vật đứng', 'https://kevindauto.com/products/sp-2101.webp', 'nu', 'Học đường', array['nữ', 'học sinh', 'học đường']::text[]),
  ('sp-2102', '2102', 'Người đàn ông áo khoác đứng casual 3', 'https://kevindauto.com/products/sp-2102.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-2103', '2103', 'Cô gái chân váy nghe điện thoại xách túi', 'https://kevindauto.com/products/sp-2103.webp', 'nu', 'Đời thường', array['nữ', 'chân váy', 'điện thoại']::text[]),
  ('sp-2104', '2104', 'Cụ ông đứng xách túi casual', 'https://kevindauto.com/products/sp-2104.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'túi xách']::text[]),
  ('sp-2105', '2105', 'Người đàn ông trượt ván cởi trần', 'https://kevindauto.com/products/sp-2105.webp', 'nam', 'Thể thao', array['nam', 'trượt ván', 'thể thao']::text[]),
  ('sp-2106', '2106', 'Cụ ông đứng khoác áo chống hông', 'https://kevindauto.com/products/sp-2106.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'áo khoác']::text[]),
  ('sp-2107', '2107', 'Cô gái ôm hoa xách túi đứng', 'https://kevindauto.com/products/sp-2107.webp', 'nu', 'Đời thường', array['nữ', 'hoa', 'túi xách']::text[]),
  ('sp-2108', '2108', 'Chiến sĩ đứng cầm súng trường', 'https://kevindauto.com/products/sp-2108.webp', 'nam', 'Quân sự', array['nam', 'lính', 'súng', 'quân sự']::text[]),
  ('sp-2109', '2109', 'Người đàn ông tóc dài áo khoác đứng', 'https://kevindauto.com/products/sp-2109.webp', 'nam', 'Đời thường', array['nam', 'tóc dài', 'áo khoác']::text[]),
  ('sp-2110', '2110', 'Bé trai cởi trần uống nước', 'https://kevindauto.com/products/sp-2110.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'uống nước']::text[]),
  ('sp-2111', '2111', 'Bé gái xách túi bước đi', 'https://kevindauto.com/products/sp-2111.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'túi xách', 'đi bộ']::text[]),
  ('sp-2112', '2112', 'Bé gái xách túi cầm đồ vật đi bộ', 'https://kevindauto.com/products/sp-2112.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'túi xách', 'đi bộ']::text[]),
  ('sp-2113', '2113', 'Bé gái đồng phục xách túi đứng', 'https://kevindauto.com/products/sp-2113.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đồng phục', 'túi xách']::text[]),
  ('sp-2114', '2114', 'Bé trai đội mũ ngồi xổm', 'https://kevindauto.com/products/sp-2114.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé trai', 'mũ', 'ngồi xổm']::text[]),
  ('sp-2115', '2115', 'Băng ca cứu thương', 'https://kevindauto.com/products/sp-2115.webp', 'phukien', 'Bối cảnh', array['băng ca', 'y tế', 'bối cảnh']::text[]),
  ('sp-2116', '2116', 'Người đàn ông đội mũ giơ nắm đấm', 'https://kevindauto.com/products/sp-2116.webp', 'nam', 'Hành động', array['nam', 'mũ', 'nắm đấm']::text[]),
  ('sp-2117', '2117', 'Bé gái cầm búa đồ chơi', 'https://kevindauto.com/products/sp-2117.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đồ chơi']::text[]),
  ('sp-2118', '2118', 'Chiến sĩ nhảy hành động đội mũ bảo hiểm', 'https://kevindauto.com/products/sp-2118.webp', 'nam', 'Quân sự', array['nam', 'lính', 'mũ bảo hiểm', 'quân sự']::text[]),
  ('sp-2119', '2119', 'Chiến sĩ giơ nắm đấm đội mũ bảo hiểm', 'https://kevindauto.com/products/sp-2119.webp', 'nam', 'Quân sự', array['nam', 'lính', 'mũ bảo hiểm', 'quân sự']::text[]),
  ('sp-2120', '2120', 'Người đội mũ bảo hộ tư thế hành động', 'https://kevindauto.com/products/sp-2120.webp', 'nam', 'Nghề nghiệp', array['nam', 'mũ bảo hộ', 'hành động', 'nghề nghiệp']::text[]),
  ('sp-2121', '2121', 'Cụ ông đứng casual đơn giản', 'https://kevindauto.com/products/sp-2121.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'đứng']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
