-- Lo 053: san pham 2122 den 2199
insert into public.product_image_embeddings (
  product_id, code, name, image_url, category, series, tags
)
values
  ('sp-2122', '2122', 'Người cha vác con trai trên vai', 'https://kevindauto.com/products/sp-2122.webp', 'treem', 'Gia đình', array['gia đình', 'cha con', 'trẻ em']::text[]),
  ('sp-2123', '2123', 'Người đàn ông đứng tư thế hành động casual', 'https://kevindauto.com/products/sp-2123.webp', 'nam', 'Hành động', array['nam', 'hành động', 'đứng']::text[]),
  ('sp-2124', '2124', 'Người đàn ông ngồi đọc đồ vật', 'https://kevindauto.com/products/sp-2124.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'đọc']::text[]),
  ('sp-2125', '2125', 'Cô gái đội mũ chỉ tay đứng', 'https://kevindauto.com/products/sp-2125.webp', 'nu', 'Đời thường', array['nữ', 'mũ', 'chỉ tay']::text[]),
  ('sp-2126', '2126', 'Người đàn ông ngồi thoải mái casual 3', 'https://kevindauto.com/products/sp-2126.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'thoải mái']::text[]),
  ('sp-2127', '2127', 'Người đàn ông áo khoác đứng casual 4', 'https://kevindauto.com/products/sp-2127.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-2128', '2128', 'Cô gái gợi cảm đầm tay giơ cao', 'https://kevindauto.com/products/sp-2128.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm']::text[]),
  ('sp-2129', '2129', 'Cô gái gợi cảm cầm bóng bay trái tim', 'https://kevindauto.com/products/sp-2129.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'bóng bay']::text[]),
  ('sp-2130', '2130', 'Bé gái đồng phục cầm điện thoại', 'https://kevindauto.com/products/sp-2130.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đồng phục', 'điện thoại']::text[]),
  ('sp-2131', '2131', 'Cô gái streetwear khoanh tay đứng 2', 'https://kevindauto.com/products/sp-2131.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'khoanh tay']::text[]),
  ('sp-2132', '2132', 'Cô gái streetwear quần rộng đứng', 'https://kevindauto.com/products/sp-2132.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'quần rộng']::text[]),
  ('sp-2133', '2133', 'Người đàn ông streetwear đứng hành động', 'https://kevindauto.com/products/sp-2133.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'hành động']::text[]),
  ('sp-2134', '2134', 'Người đàn ông áo khoác streetwear đứng', 'https://kevindauto.com/products/sp-2134.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'streetwear']::text[]),
  ('sp-2135', '2135', 'Robot chiến giáp cơ khí đứng', 'https://kevindauto.com/products/sp-2135.webp', 'nam', 'Robot', array['robot', 'cơ khí', 'fantasy']::text[]),
  ('sp-2136', '2136', 'Mô tô cổ điển đứng', 'https://kevindauto.com/products/sp-2136.webp', 'xe', 'Mô tô', array['mô tô', 'cổ điển']::text[]),
  ('sp-2137', '2137', 'Mô tô cổ điển kiểu 2', 'https://kevindauto.com/products/sp-2137.webp', 'xe', 'Mô tô', array['mô tô', 'cổ điển']::text[]),
  ('sp-2138', '2138', 'Người đội mũ bảo hiểm ngồi trên mô tô', 'https://kevindauto.com/products/sp-2138.webp', 'xe', 'Mô tô', array['nam', 'mô tô', 'mũ bảo hiểm']::text[]),
  ('sp-2139', '2139', 'Người ngồi trên phao bơi ra dấu chiến thắng', 'https://kevindauto.com/products/sp-2139.webp', 'nam', 'Thể thao', array['nam', 'phao bơi', 'thể thao']::text[]),
  ('sp-2140', '2140', 'Cô gái hoodie tay chạm đầu đứng', 'https://kevindauto.com/products/sp-2140.webp', 'nu', 'Streetwear', array['nữ', 'hoodie', 'đứng']::text[]),
  ('sp-2141', '2141', 'Cô gái streetwear ra dấu chiến thắng', 'https://kevindauto.com/products/sp-2141.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'chiến thắng']::text[]),
  ('sp-2142', '2142', 'Người đàn ông áo khoác streetwear đứng 2', 'https://kevindauto.com/products/sp-2142.webp', 'nam', 'Streetwear', array['nam', 'áo khoác', 'streetwear']::text[]),
  ('sp-2143', '2143', 'Người đàn ông áo khoác đứng casual 5', 'https://kevindauto.com/products/sp-2143.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-2144', '2144', 'Mascot mập vẫy tay chào', 'https://kevindauto.com/products/sp-2144.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-2145', '2145', 'Người đàn ông streetwear oversize đứng', 'https://kevindauto.com/products/sp-2145.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'oversize']::text[]),
  ('sp-2146', '2146', 'Cô gái streetwear khoác vải tay chạm đầu', 'https://kevindauto.com/products/sp-2146.webp', 'nu', 'Streetwear', array['nữ', 'streetwear']::text[]),
  ('sp-2147', '2147', 'Người đàn ông áo phao đứng tay che mặt', 'https://kevindauto.com/products/sp-2147.webp', 'nam', 'Đời thường', array['nam', 'áo phao', 'đứng']::text[]),
  ('sp-2148', '2148', 'Người đàn ông mập mặc áo phao đứng', 'https://kevindauto.com/products/sp-2148.webp', 'nam', 'Đời thường', array['nam', 'áo phao', 'đứng']::text[]),
  ('sp-2149', '2149', 'Người đàn ông áo khoác cầm đồ vật đứng', 'https://kevindauto.com/products/sp-2149.webp', 'nam', 'Đời thường', array['nam', 'áo khoác', 'đứng']::text[]),
  ('sp-2150', '2150', 'Người đàn ông đứng cầm đồ vật casual 2', 'https://kevindauto.com/products/sp-2150.webp', 'nam', 'Đời thường', array['nam', 'đứng', 'đời thường']::text[]),
  ('sp-2151', '2151', 'Kệ thang gỗ nhỏ', 'https://kevindauto.com/products/sp-2151.webp', 'phukien', 'Bối cảnh', array['kệ', 'thang', 'bối cảnh']::text[]),
  ('sp-2152', '2152', 'Quý cô đầm dài thanh lịch cài trâm', 'https://kevindauto.com/products/sp-2152.webp', 'nu', 'Thời trang', array['nữ', 'đầm dài', 'thanh lịch']::text[]),
  ('sp-2153', '2153', 'Người đàn ông streetwear vác túi vai', 'https://kevindauto.com/products/sp-2153.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'túi xách']::text[]),
  ('sp-2154', '2154', 'Người đàn ông vest quần rộng đeo kính', 'https://kevindauto.com/products/sp-2154.webp', 'nam', 'Thời trang', array['nam', 'vest', 'kính', 'thời trang']::text[]),
  ('sp-2155', '2155', 'Người đàn ông suit đứng casual', 'https://kevindauto.com/products/sp-2155.webp', 'nam', 'Công sở', array['nam', 'suit', 'công sở']::text[]),
  ('sp-2156', '2156', 'Người đàn ông cơ bắp khoanh tay suit', 'https://kevindauto.com/products/sp-2156.webp', 'nam', 'Thể hình', array['nam', 'cơ bắp', 'khoanh tay']::text[]),
  ('sp-2157', '2157', 'Nhân vật áo choàng che mặt bí ẩn', 'https://kevindauto.com/products/sp-2157.webp', 'nu', 'Fantasy', array['nữ', 'áo choàng', 'bí ẩn', 'fantasy']::text[]),
  ('sp-2158', '2158', 'Nhân vật áo choàng che mặt dramatique', 'https://kevindauto.com/products/sp-2158.webp', 'nu', 'Fantasy', array['nữ', 'áo choàng', 'bí ẩn', 'fantasy']::text[]),
  ('sp-2159', '2159', 'Nhân vật áo choàng che mặt đứng thẳng', 'https://kevindauto.com/products/sp-2159.webp', 'nu', 'Fantasy', array['nữ', 'áo choàng', 'bí ẩn', 'fantasy']::text[]),
  ('sp-2160', '2160', 'Nhân vật áo choàng che mặt quay lưng', 'https://kevindauto.com/products/sp-2160.webp', 'nu', 'Fantasy', array['nữ', 'áo choàng', 'bí ẩn', 'fantasy']::text[]),
  ('sp-2161', '2161', 'Người đàn ông nhảy hành động casual', 'https://kevindauto.com/products/sp-2161.webp', 'nam', 'Hành động', array['nam', 'nhảy', 'hành động']::text[]),
  ('sp-2162', '2162', 'Người đàn ông đội mũ đứng casual 3', 'https://kevindauto.com/products/sp-2162.webp', 'nam', 'Đời thường', array['nam', 'mũ', 'đứng']::text[]),
  ('sp-2163', '2163', 'Cô gái áo khoác đứng casual 4', 'https://kevindauto.com/products/sp-2163.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'đứng']::text[]),
  ('sp-2164', '2164', 'Cô gái đi bộ casual', 'https://kevindauto.com/products/sp-2164.webp', 'nu', 'Đời thường', array['nữ', 'đi bộ', 'đời thường']::text[]),
  ('sp-2165', '2165', 'Cụ ông áo khoác truyền thống đứng', 'https://kevindauto.com/products/sp-2165.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'áo khoác']::text[]),
  ('sp-2166', '2166', 'Bé gái mặc đầm tay chạm đầu', 'https://kevindauto.com/products/sp-2166.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đầm']::text[]),
  ('sp-2167', '2167', 'Cô gái áo khoác xách túi đứng casual 2', 'https://kevindauto.com/products/sp-2167.webp', 'nu', 'Đời thường', array['nữ', 'áo khoác', 'túi xách']::text[]),
  ('sp-2168', '2168', 'Người đàn ông ngồi uống nước xách túi', 'https://kevindauto.com/products/sp-2168.webp', 'nam', 'Đời thường', array['nam', 'uống nước', 'ngồi']::text[]),
  ('sp-2169', '2169', 'Cô gái gợi cảm bikini boot đứng', 'https://kevindauto.com/products/sp-2169.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'bikini', 'boot']::text[]),
  ('sp-2171', '2171', 'Cô gái gợi cảm mặc đầm đứng 3', 'https://kevindauto.com/products/sp-2171.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm']::text[]),
  ('sp-2172', '2172', 'Cụ ông đứng chỉ tay gesture', 'https://kevindauto.com/products/sp-2172.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'chỉ tay']::text[]),
  ('sp-2173', '2173', 'Hoa hướng dương đứng', 'https://kevindauto.com/products/sp-2173.webp', 'phukien', 'Bối cảnh', array['hoa hướng dương', 'bối cảnh']::text[]),
  ('sp-2174', '2174', 'Người áo choàng dài đứng thanh lịch', 'https://kevindauto.com/products/sp-2174.webp', 'nu', 'Đời thường', array['nữ', 'áo choàng dài', 'thanh lịch']::text[]),
  ('sp-2175', '2175', 'Cô gái gợi cảm mặc đầm dài thanh lịch', 'https://kevindauto.com/products/sp-2175.webp', 'nu', 'Gợi cảm', array['nữ', 'gợi cảm', 'đầm dài']::text[]),
  ('sp-2176', '2176', 'Người đàn ông đeo túi messenger đứng', 'https://kevindauto.com/products/sp-2176.webp', 'nam', 'Nghề nghiệp', array['nam', 'túi', 'nghề nghiệp']::text[]),
  ('sp-2177', '2177', 'Tượng nhân vật cổ trang khoác áo choàng cúi', 'https://kevindauto.com/products/sp-2177.webp', 'caotuoi', 'Nghệ thuật', array['người già', 'áo choàng', 'cổ trang', 'nghệ thuật']::text[]),
  ('sp-2178', '2178', 'Bé gái cầm xẻng đồ chơi', 'https://kevindauto.com/products/sp-2178.webp', 'treem', 'Trẻ em', array['trẻ em', 'bé gái', 'đồ chơi']::text[]),
  ('sp-2179', '2179', 'Cô gái hoodie quần short đứng', 'https://kevindauto.com/products/sp-2179.webp', 'nu', 'Streetwear', array['nữ', 'hoodie', 'quần short']::text[]),
  ('sp-2180', '2180', 'Cô gái mặc đầm dắt thú cưng', 'https://kevindauto.com/products/sp-2180.webp', 'nu', 'Thú cưng', array['nữ', 'đầm', 'thú cưng']::text[]),
  ('sp-2181', '2181', 'Cô gái mặc đầm nhảy múa', 'https://kevindauto.com/products/sp-2181.webp', 'nu', 'Đời thường', array['nữ', 'đầm', 'nhảy múa']::text[]),
  ('sp-2182', '2182', 'Cụ ông đứng cầm bảng', 'https://kevindauto.com/products/sp-2182.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'bảng']::text[]),
  ('sp-2183', '2183', 'Người đàn ông streetwear cầm điện thoại', 'https://kevindauto.com/products/sp-2183.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'điện thoại']::text[]),
  ('sp-2184', '2184', 'Người đàn ông streetwear đứng uống nước', 'https://kevindauto.com/products/sp-2184.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'uống nước']::text[]),
  ('sp-2185', '2185', 'Chó bulldog đứng 2', 'https://kevindauto.com/products/sp-2185.webp', 'dongvat', 'Thú cưng', array['chó', 'bulldog', 'thú cưng']::text[]),
  ('sp-2186', '2186', 'Người đàn ông ngồi ghế đẩu casual', 'https://kevindauto.com/products/sp-2186.webp', 'nam', 'Đời thường', array['nam', 'ngồi', 'ghế đẩu']::text[]),
  ('sp-2187', '2187', 'Mascot heo phong thủy ngồi', 'https://kevindauto.com/products/sp-2187.webp', 'dongvat', 'Phong thủy', array['heo', 'phong thủy', 'mascot', 'may mắn']::text[]),
  ('sp-2188', '2188', 'Mascot heo bế heo con', 'https://kevindauto.com/products/sp-2188.webp', 'dongvat', 'Mascot', array['heo', 'mascot', 'chibi']::text[]),
  ('sp-2189', '2189', 'Người đàn ông cúi người hành động', 'https://kevindauto.com/products/sp-2189.webp', 'nam', 'Hành động', array['nam', 'cúi người', 'hành động']::text[]),
  ('sp-2190', '2190', 'Chó lông xù đứng 2', 'https://kevindauto.com/products/sp-2190.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-2191', '2191', 'Mascot mập ngồi cầm chai', 'https://kevindauto.com/products/sp-2191.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-2192', '2192', 'Mascot chó trên bệ lò xo', 'https://kevindauto.com/products/sp-2192.webp', 'dongvat', 'Mascot', array['mascot', 'chó', 'chibi']::text[]),
  ('sp-2193', '2193', 'Người đàn ông streetwear đứng casual 4', 'https://kevindauto.com/products/sp-2193.webp', 'nam', 'Streetwear', array['nam', 'streetwear', 'đứng']::text[]),
  ('sp-2194', '2194', 'Người đàn ông ngồi ghế lười thư giãn', 'https://kevindauto.com/products/sp-2194.webp', 'nam', 'Đời thường', array['nam', 'ghế lười', 'ngồi']::text[]),
  ('sp-2195', '2195', 'Chó lông xù ngồi 2', 'https://kevindauto.com/products/sp-2195.webp', 'dongvat', 'Thú cưng', array['chó', 'lông xù', 'thú cưng']::text[]),
  ('sp-2196', '2196', 'Cụ ông cởi trần ngồi ghế đẩu', 'https://kevindauto.com/products/sp-2196.webp', 'caotuoi', 'Người cao tuổi', array['người già', 'cao tuổi', 'cởi trần', 'ngồi']::text[]),
  ('sp-2197', '2197', 'Người đàn ông ngồi chơi sáo', 'https://kevindauto.com/products/sp-2197.webp', 'nam', 'Nhạc cụ', array['nam', 'sáo', 'nhạc cụ', 'ngồi']::text[]),
  ('sp-2198', '2198', 'Mascot hình gối dễ thương', 'https://kevindauto.com/products/sp-2198.webp', 'dongvat', 'Mascot', array['mascot', 'chibi', 'dễ thương']::text[]),
  ('sp-2199', '2199', 'Cô gái streetwear áo khoác đứng', 'https://kevindauto.com/products/sp-2199.webp', 'nu', 'Streetwear', array['nữ', 'streetwear', 'áo khoác']::text[])
on conflict (product_id) do update set
  code = excluded.code,
  name = excluded.name,
  image_url = excluded.image_url,
  category = excluded.category,
  series = excluded.series,
  tags = excluded.tags,
  updated_at = now();
